### ISSUE TITLE
"Deployed instances" header missing in SCMU empty state

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#1010]
"Deployed instances" header should show in SCMU empty state, currently missing:

<img width="711" alt="2017-09-26 at 09 54" src="https://user-images.githubusercontent.com/493451/30848863-c12a65aa-a2a0-11e7-9ab1-f54cd1b58f52.png">

**Comment by mikeminutillo** [comment]
This was deliberately removed when the UI for listed instances changed. #962 

@sergioc If you can confirm this wasn't intended, it's pretty easy to fix.

Should it be upper cased? i.e. DEPLOYED INSTANCES

**Comment by sergioc** [comment]
@mikeminutillo it should still be there to identify what will show below. All upper case.
