### ISSUE TITLE
ServiceControl does not write license files to the correct location

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1013]
When installing a license via the ServiceControl UI, ServiceControl writes the license file to the registry. The registry is not available for .NET Core applications meaning that any applications running .NET Core will not be able to read the license installed via ServiceControl.

**Comment by WilliamBZA** [comment]
Fixed via https://github.com/Particular/ServiceControl/pull/998

**Comment by mikeminutillo** [comment]
@WilliamBZA is there doco to be updated for this? Where does the license go now?

**Comment by WilliamBZA** [comment]
No documentation changes from SC side, this is for core V7 upwards which is already written https://docs.particular.net/nservicebus/licensing/?version=core_7

**Comment by WilliamBZA** [comment]
> Where does the license go now?

Registry and the user file location

**Comment by WilliamBZA** [comment]
Typing that out makes me think it's a mistake. It should be Registry and application wide file location surely?

**Comment by mikeminutillo** [comment]
Why are customers using SCMU to install a license and then assuming that they can use that same license from their own endpoints?

I mean, it works, but those things are more or less orthogonal

**Comment by WilliamBZA** [comment]
Here are the scenarios as I see it:

* Dev machine where user wants SC + SI + SP for development purposes - Should install user location license
* Prod machine where everything resides on one machine - Should install machine location license (but this seems wrong, isn't each license supposed to be specific to an endpoint?)

One would hope that users aren't installing SC just to install license files for endpoints...

**Comment by WilliamBZA** [comment]
As per our sync, the correct location is to write the license to the machine wide location
