### ISSUE TITLE
Queue peek delay

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/ServiceControl#1028]
Hi,
is the queue peek delay that ServiceControl uses configurable? Are there other ways to limit ServiceControl's load on the queue-database?

Thanks!
Tobias

**Comment by SzymonPobiega** [comment]
Hi

No, there is no setting in SQL Server transport for that. The default in SQL transport 2.x is 1 second (for each queue) when idle. This is a trade-off between load on the database and latency. Is that causing you problems?

**Comment by Tobias-Gr** [comment]
No, we just thought if we optimized the value if it was configurable. Thanks!
