### ISSUE TITLE
Possible MemoryLeak due to caching of UniqueId

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1030]
[`ProcessedMessage`](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/MessageAuditing/ProcessedMessage.cs#L16) calls into `UniqueId()` which calls into [`DeterministicGuidBuilder`](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/TransportMessageExtensions.cs#L49) which by default has cache flag set to `true` which means we will try to cache all unique has combinations of `MessageId` and `ProcessingEndpointName`

**Comment by mikeminutillo** [comment]
Good catch. Looking at when the cache was introduced I wonder if it shouldn't default to false or be pulled out altogether into a different component targeting failure group id generation.

**Comment by danielmarbach** [comment]
I agree the default value should be false

**Comment by WilliamBZA** [comment]
The parameter is only used in one place. I vote we :fire: the caching completely.

**Comment by danielmarbach** [comment]
that is even better since each component can cache the GUID on their own if required

**Comment by SzymonPobiega** [comment]
I propose a fix https://github.com/Particular/ServiceControl/pull/1041

**Comment by danielmarbach** [comment]
Contained in https://github.com/Particular/ServiceControl/releases/tag/1.43.3 Closing
