### ISSUE TITLE
Why did ServiceControl 1.43.1 release an exe with a blank LegacySemVerPadded?

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#1037]
After merging, the build on `master` resulted in a file called `Particular.ServiceControl-.exe`:

https://builds.particular.net/viewLog.html?buildId=255634&buildTypeId=ServiceControl_NewBuil&tab=artifacts#!yaozir

This file is missing the `$(GfvLegacySemVerPadded)` part of the filename, as specified in the setup project: 

https://github.com/Particular/ServiceControl/blob/master/src/Setup/Setup.csproj#L81

As a result the file in the Release notes (and other downloads) does not include the version component:

https://github.com/Particular/ServiceControl/releases/tag/1.43.1

The `GitVersion.LegacySemVerPadded` value was populated with `1.43.1` on the build:

https://builds.particular.net/viewLog.html?buildId=255634&buildTypeId=ServiceControl_NewBuil&tab=buildParameters

And previous releases included the version in the file name. Why did it fail this time?

**Comment by SzymonPobiega** [comment]
Not sure I understand?

**Comment by boblangley** [comment]
@SzymonPobiega I updated the description.

**Comment by mikeminutillo** [comment]
It failed for 1.43.0 as well. We downloaded the file, changed the filename and re-uploaded it after smoke testing.

**Comment by mikeminutillo** [comment]
`$(GfvLegacySemVerPadded)` is a v2 GVT property. It was renamed in V3 to `GitVersion_LegacySemVerPadded`

I think this was missed here: https://github.com/Particular/ServiceControl/commit/010f0e92a130308eb204ea846999da4f860d8af5#diff-aad3fa372a374d3f588affa938923b58
