### ISSUE TITLE
PowerShell Command New-ServiceControlInstance does not work due to error: A positional parameter cannot be found that accepts argument 'False'

### ISSUE THREAD

**Issue by w0l0** [Particular/ServiceControl#1063]
I cannot pass a value for the following New-ServiceControlInstance parameters:
-ForwardAuditMessages
-ForwardErrorMessages

When I use following PowerShell command:

New-ServiceControlInstance -Name Company.MessageBus.ServiceControl -Description "A ServiceControl Instance - MessageBus" -InstallPath "C:\Program Files (x86)\Particular Software\Company.MessageBus.ServiceControl" -DBPath "C:\ProgramData\Particular\ServiceControl\Company.MessageBus.ServiceControl\DB" -LogPath "C:\ProgramData\Particular\ServiceControl\Company.MessageBus.ServiceControl\Logs" -Port 33335 -ErrorQueue error -AuditQueue audit -ErrorLogQueue errorlog -AuditLogQueue auditlog -Transport SQLServer -ForwardAuditMessages $false -ForwardErrorMessages $false -AuditRetentionPeriod (New-TimeSpan -Days 30) -ErrorRetentionPeriod (New-TimeSpan -Days 15) -ConnectionString "secretConnectionString"

I get the following error:
A positional parameter cannot be found that accepts argument 'False'

**Comment by mikeminutillo** [comment]
Hi @w0l0,

The syntax to set switch parameters in Powershell is a little bit different. Try the following:

```powershell
New-ServiceControlInstance -Name Company.MessageBus.ServiceControl -Description "A ServiceControl Instance - MessageBus" -InstallPath "C:\Program Files (x86)\Particular Software\Company.MessageBus.ServiceControl" -DBPath "C:\ProgramData\Particular\ServiceControl\Company.MessageBus.ServiceControl\DB" -LogPath "C:\ProgramData\Particular\ServiceControl\Company.MessageBus.ServiceControl\Logs" -Port 33335 -ErrorQueue error -AuditQueue audit -ErrorLogQueue errorlog -AuditLogQueue auditlog -Transport SQLServer -ForwardAuditMessages:$false -ForwardErrorMessages:$false -AuditRetentionPeriod (New-TimeSpan -Days 30) -ErrorRetentionPeriod (New-TimeSpan -Days 15) -ConnectionString "secretConnectionString"
```

**Comment by w0l0** [comment]
Great it works.
Thank You. 
I think that example on the page: 
https://docs.particular.net/servicecontrol/installation-powershell#servicecontrol-instance-cmdlets-and-aliases-upgrading-an-instance
should be corrected to include the colon?

**Comment by mikeminutillo** [comment]
Good point. I have updated that example. Thanks @w0l0
