### ISSUE TITLE
New-MonitoringInstance powershell cmdlet does not support AmazonSQS

### ISSUE THREAD

**Issue by imonthercks** [Particular/ServiceControl#1107]
We are attempting to use the the ServiceControl powershell cmdlets to automate creation of a Monitoring instance in ServiceControl, however the AmazonSQS transport has not been added as a valid parameter to the Transport parameter for the New-MonitoringInstance cmdlet.

[NewMonitoringInstance.cs](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControlInstaller.PowerShell/Cmdlets/MonitoringInstances/NewMonitoringInstance.cs)

```
[Parameter(Mandatory = true, HelpMessage = "Specify the NServiceBus Transport to use")]
        [ValidateSet("AzureServiceBus", "AzureStorageQueue", "MSMQ", "SQLServer", "RabbitMQ")]
        public string Transport { get; set; }
```

**Comment by WilliamBZA** [comment]
Thanks @imonthercks, I have a PR in progress to fix this. I'll let you know as soon as it's ready to go

**Comment by imonthercks** [comment]
@WilliamBZA Thanks for the quick response!

**Comment by WilliamBZA** [comment]
[PR merged](https://github.com/Particular/ServiceControl/pull/1108). Just waiting for a release. Should be within the next day or so in version `1.47.1`.

**Comment by WilliamBZA** [comment]
1.47.1 has been released! 🎉
