### ISSUE TITLE
Dodgy drop down alignment

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#1117]
![image](https://user-images.githubusercontent.com/122666/38284180-47865004-37fd-11e8-9fb8-1d29f5f7502d.png)
![image](https://user-images.githubusercontent.com/122666/38284182-4e0ac3e2-37fd-11e8-83ba-e33f20be0949.png)

**Comment by mikeminutillo** [comment]
@SimonCropp which version of the installer is that? I cannot replicate it with 1.47.2. 

Do you have a multi-monitor setup? If so, can you describe the setup?

**Comment by SimonCropp** [comment]
yep 1.47.2.

and i have dual monitors running through an RDP session
