### ISSUE TITLE
Conflicting logic of the existence of SendingEndpoint information in the message headers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#1120]
the assumption in the logic of `EndpointDetailsParser.SendingEndpoint` implies that `SendingEndpoint` can be null.

https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Operations/EndpointDetailsParser.cs#L33

This then propogates into the message metadata. https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/EndpointControl/DetectNewEndpointsFromImportsEnricher.cs#L33

This "implied can be null" conlicts with the "implied must exist logic" of `GetErrorById.Map`
https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/MessageFailures/Api/GetErrorById.cs#L60

note the same bug exists for ReceivingEndpoint

**Comment by tmasternak** [comment]
Solved by #1125
