### ISSUE TITLE
ServiceControl data storage makes the Platform unstable

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1129]
<sup>*Moved from https://github.com/Particular/PlatformDevelopment/issues/1908 opened by @SzymonPobiega on [06 Apr 2018 09:12 UTC](https://github.com/Particular/PlatformDevelopment/issues/1908)*</sup>
ServiceControl data storage has serious issues which make the whole platform unstable. There are three categories of issues we managed to identify, ordered from least to most critical.

### Users are unable to use the Platform due to index corruption

Indexes get corrupted in RavenDB. This results in users seeing stale data. Dropping the indexes might help to restore the correct behavior of SC.

### Users are unable to use the Platform due to eventually consistent nature of the storage

Frequently, not only under heavy load, RavenDB indexing process can't deal with the data ingress resulting in indexes being permanently stale. This means that information users see in SP and SI is not updated and they can't conduct any actions. These problems can't be easily resolved by restating the SC because being offline for a hile puts even higher pressure on RavenDB indexing.

### Users are unable to use the Platform due to permanent corruption of RavenDB log/data files

In this case RavenDB leave the log and/or data files permanently corrupted and there is no way to recover other than deleting all the data. This means message loss if there were failed messages stored in the database.

**Comment by WilliamBZA** [comment]
<sup>*@WilliamBZA commented on <a id="issuecomment-379206027" href="1129#user-content-issuecomment-379206027">06 Apr 2018 09:52 UTC</a>*</sup>
Related issue with more details here: https://github.com/Particular/PlatformDevelopment/issues/1268

---
<sup>*@WilliamBZA commented on <a id="issuecomment-379206381" href="1129#user-content-issuecomment-379206381">06 Apr 2018 09:54 UTC</a>*</sup>
Some of my cases related to raven data storage problems. Of note are the last 2 where corruption resulted in the customer deleting their entire database. Complete message loss of all failed messages.

| Case Link                                             | Summary                                                                       | Category      |
|-------------------------------------------------------|-------------------------------------------------------------------------------|---------------|
| https://c.eu1.visual.force.com/apex/Case?num=00022608 | RavenDB seemingly grows too large for the number of messages it is processing | Database Size |
| https://c.eu1.visual.force.com/apex/Case?num=00024541 | RavenDB has to be compacted before archive operation completes                | Indexes       |
| https://c.eu1.visual.force.com/apex/Case?num=00025458 | Have to export and reimport Raven data because of stale indexes               | Indexes       |
| https://c.eu1.visual.force.com/apex/Case?num=00028774 | Had to split audits and errors to separate instances                          | Capacity      |
| https://c.eu1.visual.force.com/apex/Case?num=00028854 | Stale indexes caused retry operation failure                                  | Indexes       |
| https://c.eu1.visual.force.com/apex/Case?num=00030742 | Stale indexes                                                                 | Indexes       |
| https://c.eu1.visual.force.com/apex/Case?num=00031451 | RavenDB grows too much and doesn't cope with the volume                       | Capacity      |
| https://c.eu1.visual.force.com/apex/Case?num=00035339 | RavenDB log file corruption required deleting entire database                 | Corruption    |
| https://c.eu1.visual.force.com/apex/Case?num=00034648 | Database corruption resulting in losing entire database                       | Corruption    |

---
<sup>*@SzymonPobiega commented on <a id="issuecomment-379207199" href="1129#user-content-issuecomment-379207199">06 Apr 2018 09:57 UTC</a>*</sup>
@mikeminutillo @danielmarbach @tmasternak @boblangley this is the thing we want to talk about with Udi on Wednesday. Please help us refine it further. I think the more precise we are, the better. 

---
<sup>*@danielmarbach commented on <a id="issuecomment-379297859" href="1129#user-content-issuecomment-379297859">06 Apr 2018 15:57 UTC</a>*</sup>
@SzymonPobiega I looked at it and based on my knowledge it is descriptive enough but I might not be the right person to give that feedback

---
<sup>*@WojcikMike commented on <a id="issuecomment-379677108" href="1129#user-content-issuecomment-379677108">09 Apr 2018 08:36 UTC</a>*</sup>
@SzymonPobiega I was not asked but one angle that I would express is that keeping this known problem covers some other issues that we have in the code. When the similar kind of issues is reported we believe it has to be Raven but it doesn't have to be. So by keeping this data storage, we are more inclined to dismiss certain types of errors as related to that.

An example would be this patch: https://github.com/Particular/PlatformDevelopment/issues/1876
We found some support cases that were raised, and in some cases we dismiss it saying: it's Raven

---
<sup>*@mikeminutillo commented on <a id="issuecomment-379687886" href="1129#user-content-issuecomment-379687886">09 Apr 2018 09:15 UTC</a>*</sup>
I think you nailed the problem but it's still tied into the solution. 

The problem is that SC in unreliable. Our theory is that Raven (specifically 2.5) is the greatest contributor to that lack of reliability. As supporting evidence we have a list of support cases where Raven corruption/instability seems to be the root cause. 

We also discussed (last week) how we would know if we fixed it (or made it better/worse). It's really hard to say "version X is more stable than version Y". At the moment, stability is measured in support cases over months. We need some kind of test that can tell us if we made it better (or worse) in a shorter feedback cycle (and with less risk).

---
<sup>*@tmasternak commented on <a id="issuecomment-380003378" href="1129#user-content-issuecomment-380003378">10 Apr 2018 07:33 UTC</a>*</sup>
> I think you nailed the problem but it's still tied into the solution.

Would it be more problem focused if we said that "ServiceControl is unreliable from the clients perspective"? The arguments outlined by @SzymonPobiega  and cases found by @WilliamBZA are supporting that IMHO. 

Putting myself in the client's shoes I'm in a situation in which I can't be sure that ServiceControl
  * Won't loose all my data (Data Corruption),
  * Will allow me to perform business operation (Archive, Retry, blocked business processes)
  * Is reflecting current state of my production system (Stale indexes and capacity)


---
<sup>*@tmasternak commented on <a id="issuecomment-380003541" href="1129#user-content-issuecomment-380003541">10 Apr 2018 07:33 UTC</a>*</sup>
> We need some kind of test that can tell us if we made it better (or worse) in a shorter feedback cycle (and with less risk).

@mikeminutillo I think that should be the first step in whatever plan we come-up with.

---
<sup>*@WilliamBZA commented on <a id="issuecomment-380004046" href="1129#user-content-issuecomment-380004046">10 Apr 2018 07:35 UTC</a>*</sup>
> and with less risk

_isolation is a great way of reducing risk_

**Comment by danielmarbach** [comment]
Addressed by #1144 . Closing
