### ISSUE TITLE
We don't have a long-running test environment

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1130]
ServiceControl is an application that should run continuously in an environment. This is critical to us ensuring stability and performance improvements over time.

I suggest creating an azure (or AWS) environment that ingests a set number of audit messages, and error messages in such a way that the audit cleanup process will run during the ingestion and some retries of error groups can be triggered automatically to simulate a very busy environment.

We can then use this environment to see if we get the same raven stability issues and if we do - we can use the environment as a way to improve on that.

If we don't get the stability problems, we can at least use the environment as a performance benchmark to ensure the future stability work we do does not impact performance negatively.

**Comment by danielmarbach** [comment]
During the test phase we created Azure Ressources with 4000 IOPS (D8_V3) and 16000 (E8-4S_V3) IOPS. In order to achieve that many IOPS we created multiple managed disks and stripped them together. 

The following query was used to query for stale indexes during the database upgrade

```
$staleIndexes = 1
do
{
    $j = Invoke-WebRequest 'http://localhost:33333/storage/stats' | ConvertFrom-Json
    $staleIndexes = $j.StaleIndexes.Count
    $information = @(

        [pscustomobject]@{

        Time = $(Get-Date -format 's')

        StaleIndexes  = $staleIndexes

        Data  = $j.StaleIndexes | ConvertTo-Json

        }

    )
    $information | Export-Csv -Path  C:\stats.csv -Append -NoTypeInformation
    Write-Host $information
    sleep 60
}
while($true)
```

```
and this script to create the disks

clear
 
# RM stands for resource manager, and is the new way of managing things in Azure
 
# you need to login the first time using this command
# Login-AzureRmAccount
 
$vm = Get-AzureRmVM -ResourceGroupName "ravenmigrations" -Name "ravenfast"
 
# adds 8 disks
for($i=1; $i -le 32; $i++) {
    $name = "ravenfast-disk{0:00}" -f $i
    $lun = $i - 1
 
    $diskConfig = New-AzureRmDiskConfig `
    -Location "westeurope" `
    -CreateOption Empty `
    -DiskSizeGB 512
    $dataDisk = New-AzureRmDisk `
    -ResourceGroupName "ravenmigrations" `
    -DiskName $name `
    -Disk $diskConfig
 
    $vm = Add-AzureRmVMDataDisk `
    -VM $vm `
    -Name $name `
    -CreateOption Attach `
    -ManagedDiskId $dataDisk.Id `
    -Lun $lun
}
 
$vm.DataDiskNames
 
# uncomment when you are ready, this updates the VM on azure!
Update-AzureRmVM -ResourceGroupName "ravenmigrations" -VM $vm
```
