### ISSUE TITLE
Network location for license.xml

### ISSUE THREAD

**Issue by anetteha** [Particular/ServiceControl#1132]
All our hosts use a hidden file share where IT operations maintains the license files. ITOps want a “one-stop” solution to NServiceBus license maintenance. Therefore, we want to configure a network path to the license file in stead of adding it to the registry.

**Comment by WilliamBZA** [comment]
Hi @anetteha 

Any reason why a mapped folder wouldn't work? There shouldn't be any problems with using a network share to host the license file.

**Comment by ramonsmits** [comment]
@anetteha I've synced with @WilliamBZA about this and it seems that although the UI doesn't provide a way to configure this it can be done manually by adding the `NServiceBus/LicensePath` application setting to the `ServiceControl.exe.config` configuration file.

```xml
<add key="NServiceBus/LicensePath" value="\\alwaysonserver\superhidden$\NServiceBus\License\License.xml" />
```
https://docs.particular.net/nservicebus/licensing/?version=core_5#license-management-using-app-config-appsettings

**Comment by awright18** [comment]
Looks like this has been resolved.
