### ISSUE TITLE
Add option to not consume audit and error queues

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#1142]
Consider the scenario where a user of NSB wants to keep the audit queue (for historical records) and the error queue (so they can optionally retry/interrogate errors in other tooling) and they are using SC. to achieve this they need to use queue forwarding https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior

However in a high throughput system there can be significant load placed upon the error and audit queues, as every message gets sent to one of those. when using SC queue forwarding this results in an effective doubling of that load as well as extra infrastructure to keep track of. Also, when people move to the cloud, and are paying per read/write + throughput, this could equate to significant $$.

So, instead of queue forwarding, Sc should have an option to "not consume" those queues. It should instead keep track of where in the queue it has processed.

**Comment by WilliamBZA** [comment]
You can change the config and set the error or audit queue to `!disable` and the audit/error ingestion pipeline won't be run within SC.  It does mean that ingestion isn't happening though, which won't really work in the scenario you're describing.

I expect an index to keep track of where it last ingested in the queue might be more applicable to some transports than others (e.g. kafka would be a natural fit, whilst MSMQ would be problematic).

**Comment by SimonCropp** [comment]
>  index to keep track of where it last ingested in the queue might be more applicable to some transports than others

yep that would work in the sql transport as well

**Comment by SzymonPobiega** [comment]
@SimonCropp keeping track of last consumed message is not a workable solution in SQL Server. In a high-throughput scenario you would have to add either `NO LOCK` or `READ PAST` hints in order for the query to return any rows. In the first case you would might see stuff that data that is not going to be committed. In the second case you can skip over some rows that will be inserted later. When you store the pointer to the last-processed row you would never come back to these rows.

Alternatively you can store a "I processed this" mark for each processed row but this would be more-or-less the same as moving stuff from one queue to the other.
