### ISSUE TITLE
Cannot disable error and audit queue together via SCMU

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1174]
When setting the error AND audit queue value to `!disable`, the ServiceControl Management Utility validation prevents saving the instance due to the duplicated value.

![image](https://user-images.githubusercontent.com/124014/41211545-a530ac20-6d6a-11e8-8c45-052db4e8fb0a.png)

**Comment by WilliamBZA** [comment]
I had to think for a second about the use case for disabling both audit and error queues. Is this something we want to explicitly document as a drain-stop technique?

**Comment by mikeminutillo** [comment]
@WilliamBZA we recommend doing just that https://docs.particular.net/servicecontrol/upgrades/1to2#overview-side-by-side-upgrade-process
