### ISSUE TITLE
Single ServiceControl instance for multi catalog (single instance) transport

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/ServiceControl#1181]
Hi,
we are using SQL Transport in multi catalog configuration (single instance) and want to use a single ServiceControl instance to manage all endpoints (in all catalogs). Do I need ServiceControl Transport Adapter for this setup or is it possible to configure endpoints across catalogs to use error and audit queues in a single catalog (e. g. endpoints A and B use catalog 1, endpoints C and D use catalog 2, all endpoints use catalog "shared" for error/audit)?

Thanks!
Tobias

**Comment by SzymonPobiega** [comment]
@Tobias-Gr with the latest version of ServiceControl that uses NServiceBus 7 you can use multi-catalog SQL Server topology with SC without the adapter. You need to configure the endpoints to use audit/error/particular.servicecontrol queues in the SC's catalog. SC will be able to retry failed messages to their respective catalogs because it now understands the multi-catalog addressing schema.

Note that it would only work with SQL multi-catalog. It won't work with the legacy multi-instance mode.

**Comment by Tobias-Gr** [comment]
Sounds good, thanks for the information!
Is this topic already in the docs (I didn't find anything)?
Do ServicePulse and ServiceInsight separate the messages from the different catalogs in a nice way?

**Comment by SzymonPobiega** [comment]
@Tobias-Gr no, SP and SI are not aware of the separation. You can only filter/browse messages by endpoint. What would be the scenario where you want to browse/filter them by catalog? Do you use catalogs to group related endpoints?

**Comment by Tobias-Gr** [comment]
We have different tenants and each tenant has its own catalog (and its own set of endpoints; so yes in this regard we use catalogs to group related endpoints).

**Comment by Tobias-Gr** [comment]
Yes, correct. Browsing by catalog (like it's possible for endpoints) would be nice.

**Comment by SzymonPobiega** [comment]
@Tobias-Gr I've raised internal issue to track the support of multi-tenant systems in SI/SP. Let me close this one now. If you have any questions regarding the multi-catalog and the new version of SC, ping us.

**Comment by Tobias-Gr** [comment]
@SzymonPobiega Sorry for replying on this closed issue. Any updates regarding filtering in SI/SP based on catalogs?

**Comment by WilliamBZA** [comment]
@Tobias-Gr We have a longer-term plan in place to make this a better story, but it's unlikely to be helpful for you in the short-term.

To get you something at least useful in the short-term, can you clarify if this would be helpful: We can make a ServiceControl release that will allow you to group failed messages within ServicePulse by catalog. Would that be helpful for now?

![image](https://user-images.githubusercontent.com/1060960/76398516-aea3ec00-6385-11ea-80bc-f16734b3d178.png)

ServiceInsight will be substantially harder to implement filtering.

**Comment by Tobias-Gr** [comment]
@WilliamBZA Thanks for your suggestion. But at least for us it makes more sense to stay with separated ServiceControl instances until the whole filtering story (including ServiceInsight) is available.
