### ISSUE TITLE
Review Async Code

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1226]
A major change was made to switch ServiceControl over to async code. A thorough review of the async code is required to make sure it is valid, and to suggest further refactorings that can be made to improve the performance (e.g. fanout in places)

**Comment by timbussmann** [comment]
the change to async doesn't seem to have intended the usage of `ConfigureAwait(false)`, was that done on purpose or do we have to retrofit that? @WilliamBZA

**Comment by WilliamBZA** [comment]
Seems like all the `ConfigureAwait`s have been added?

**Comment by timbussmann** [comment]
I've had a conversation with @danielmarbach and we decided to add the missing ConfigureAwaits to the SC project. I forgot to update this info on this issue.

**Comment by timbussmann** [comment]
* the particular code rules package has been added to ensure we're not missing any awaits or similar.
* ConfigureAwaits have been added to align with the general best-practice for our packages

I think there's not much more to actively pursue as part of this issue. I'm going to close this. If you feel there is a specific part of the code which needs additional review, please comment or create a new issue.
