### ISSUE TITLE
Align develop with new coding standards

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1250]
- Take latest https://github.com/Particular/RepoStandards
- Update dotSettings and potentially ignore files where necessary
- Fix code inspections
- Reformat all the code to use the newest code style as one dedicated commit
- Where possible and needed use latest csharp feature (optional)

## POA

* [x] Project ServiceControl
  * [x] ServiceControl\CompositeViews @timbussmann
  * [x] ServiceControl\Contracts @timbussmann
  * [x] ServiceControl\CustomChecks @timbussmann
  * [x] ServiceControl\DbMigrations @danielmarbach
  * [x] ServiceControl\ExternalIntegrations @danielmarbach
  * [x] ServiceControl\EventLog @danielmarbach
  * [x] ServiceControl\Hosting @danielmarbach
  * [x] ServiceControl\HeartbeatMonitoring @timbussmann
  * [x] ServiceControl\Infrastructure @timbussmann
  * [x] ServiceControl\Licensing @timbussmann
  * [x] ServiceControl\MessageAuditing @timbussmann
  * [x] ServiceControl\MessageFailures @timbussmann
  * [x] ServiceControl\Monitoring @timbussmann
  * [x] ServiceControl\Operations @weralabaj
  * [x] ServiceControl\Recoverability @weralabaj
  * [x] ServiceControl\SagaAudit @weralabaj
  * [x] ServiceControl\Upgrade @weralabaj

* [x] Project ServiceControl.AcceptanceTests
  * [x] ServiceControl.AcceptanceTests\Audit @timbussmann
  * [x] ServiceControl.AcceptanceTests\CustomChecks @timbussmann
  * [x] ServiceControl.AcceptanceTests\EndpointTemplates @timbussmann
  * [x] ServiceControl.AcceptanceTests\ExternalIntegrations @timbussmann
  * [x] ServiceControl.AcceptanceTests\HeartbeatMonitoring @timbussmann
  * [x] ServiceControl.AcceptanceTests\MessageFailures @timbussmann
  * [x] ServiceControl.AcceptanceTests\MessageRedirects @timbussmann
  * [x] ServiceControl.AcceptanceTests\MultiInstance @timbussmann
  * [x] ServiceControl.AcceptanceTests\Recoverability @weralabaj
  * [x] ServiceControl.AcceptanceTests\SagaAudit @weralabaj
  * [x] ServiceControl.AcceptanceTests @weralabaj

* [x] Project ServiceControl.Config   @danielmarbach
* [x] Project ServiceControl.UnitTests @timbussmann
* [x] Project ServiceControlInstaller.CustomActions @timbussmann
* [x] Project ServiceControlInstaller.Engine @timbussmann
* [x] Project ServiceControlInstaller.Engine.UnitTests @timbussmann
* [x] Project ServiceControlInstaller.PowerShell @timbussmann

* [x] Investigate and fix ` When_a_message_fails_to_import.It_can_be_reimported ` @danielmarbach

**Comment by danielmarbach** [comment]
Once develop is green again we can close this. All outstanding PoA items have been addressed. Well done @weralabaj @timbussmann

**Comment by timbussmann** [comment]
develop is green. Closing this issue.
