### ISSUE TITLE
Create sensible default configuration for ASB Endpoint Oriented Topology

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1308]
- Check transport for settings that are suitable for concurrent processing of messages that potentially take a few seconds to process
  - Background information: 
    - Audit Ingestion is done with a concurrency of 10, Error Ingestion as well and there is the main input queue of ServiceControl that has a concurrency limit of 10 as well
    - There is also a ReturnToSenderDequeuer that is used when messages are returned to the input queue they came from. More information about that process can be found https://github.com/Particular/ServiceControl/blob/master/docs/bulk-retries-design.md
  - For example, message prefetch should be done cautiously to avoid lock losts or messages getting visible again which can lead to unnecessary dead lettering depending on the transport
  - Other examples are VisibilityTimeout, PeekLock duration...
  - Check what was possible in the v5 version of the transport to influence the transport by providing configuration sections in the App.config, for example ASB had [AzureServiceBusQueueConfig ](https://docs.particular.net/transports/azure-service-bus/configuration/azureservicebusqueueconfig) that allowed to overload the runtime behavior. The idea is that tweaks like that should no longer be needed
- Apply sensible default transport settings in `ServiceControl.Transports.ASB` assembly both for NSB.Raw and the main input queue
- Determine the best suitable transaction mode for the transport and apply
- If no changes need to be applied please close this issue with a short explanation why the settings are well suited for ServiceControl

**Comment by yvesgoeleven** [comment]
These are safe defaults for operations that can take a few seconds each:

PrefetchCount: 0
NumberOfMessagingFactoriesPerNamespace: 2
NumberOfClientsPerEntity: NumberOfCores or concurrencylimit, whatever is less
LockDuration: 5 minutes

**Comment by WilliamBZA** [comment]
Would these default remain the same regardless of the topology? In other words: are these settings applicable for both Endpoint oriented as well as Forwarding topology?

**Comment by yvesgoeleven** [comment]
@WilliamBZA yes, receive is the same on both

**Comment by WilliamBZA** [comment]
PR approved, closing
