### ISSUE TITLE
Create sensible default configuration for RabbitMQ Conventional Topology

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1310]
- Check transport for settings that are suitable for concurrent processing of messages that potentially take a few seconds to process
  - Background information: 
    - Audit Ingestion is done with a concurrency of 10, Error Ingestion as well and there is the main input queue of ServiceControl that has a concurrency limit of 10 as well
    - There is also a ReturnToSenderDequeuer that is used when messages are returned to the input queue they came from. More information about that process can be found https://github.com/Particular/ServiceControl/blob/master/docs/bulk-retries-design.md
  - For example, message prefetch should be done cautiously to avoid lock losts or messages getting visible again which can lead to unnecessary dead lettering depending on the transport
  - Other examples are VisibilityTimeout, PeekLock duration...
  - Check what was possible in the v5 version of the transport to influence the transport by providing configuration sections in the App.config, for example ASB had [AzureServiceBusQueueConfig ](https://docs.particular.net/transports/azure-service-bus/configuration/azureservicebusqueueconfig) that allowed to overload the runtime behavior. The idea is that tweaks like that should no longer be needed
- Apply sensible default transport settings in `ServiceControl.Transports.RabbitMQ` assembly both for NSB.Raw and the main input queue
- Determine the best suitable transaction mode for the transport and apply
- If no changes need to be applied please close this issue with a short explanation why the settings are well suited for ServiceControl

**Comment by bording** [comment]
What sort of configuration settings are you thinking about here?

**Comment by bording** [comment]
Based on what @danielmarbach has added since I asked my question, I believe that there is nothing that we need to alter for the RabbitMQ transport.
