### ISSUE TITLE
Installer: Deprecate usages of AzureServiceBusConfig

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1316]
The v5 version of AzureServiceBus has the possibility to define config sections in the app.config of type AzureServiceBusConfig. Customers are using that to tweak the behavior of the transport. When #1308 is introduced we need to deprecate those settings during the upgrade process of an existing instance. 

The `AzureServiceBusConfig` ConfigSection will no longer be supported, and has to be replaced by #1308. As part of this replacement, ServiceControl should log a WARN at startup if it detects that the app.config file contains a ConfigSection for Azure Service Bus to let users know that they should not be using that anymore. This could probably take the shape of a StartupTask that does a simple text search within the app.config file.

**Comment by WilliamBZA** [comment]
Closing as this has been done
