### ISSUE TITLE
Installer: Deprecate usages of AzureStorageQueueConfig

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1317]
The v5 version of AzureStorageQueue has the possibility to define config sections in the app.config of type AzureStorageQueueConfig. Customers are using that to tweak the behavior of the transport. When #1309 is introduced we need to deprecate those settings during the upgrade process of an existing instance.

**Comment by WilliamBZA** [comment]
I have gone back and forth on whether or not an installer change or a warn in the log file is more appropriate. I'm currently leaning towards log file because someone can add the settings after an upgrade because of some internal documentation they might have.
