### ISSUE TITLE
Make LoadTest generator work with multiple transports

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1322]
As a preparation step for testing SC 3.0 we need to augment the load test generator to support multiple transports.

- [x] Setup Load testing environment with D4S_v3 machines. One generator machine, one for SC and another one for the brokers if required. IOPS Data disk with 7500 IOPS and 2 TB storage @danielmarbach

**Comment by SzymonPobiega** [comment]
Done.
