### ISSUE TITLE
Ensure we didn't break mixed version Master-Slave configuration in the V3 upgrade

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1341]
## Context

As a part of making audit processing more scalable we introduced a [scale-out mode for ServiceControl](https://docs.particular.net/servicecontrol/servicecontrol-instances/distributed-instances). This mode allows users to run multiple ServiceControl instances which present a single audit data store to tools like ServiceInsight. 

As a part of the upgrade process, customers will need to upgrade one instance at a time to V3 and potentially run in mixed mode where some instances are v3 and some are not.

We need to ensure that ServiceControl works properly when deployed in a mixed version configuration like this.

## Out of Scope

- Multi-instance deployments where all instances are running on v3 (this is covered by the Acceptance Tests)

## Plan of attack

- [x] Document the features of a Multi-Instance deployment (Audit message aggregation, Saga Audit aggregation, Endpoint detection aggregation, successful retry detection, ...) https://github.com/Particular/docs.particular.net/pull/3953
- [x] Decide on the best strategy to test these (automated/manual/etc.) -> manual
- [x] Brainstorm the configurations that need to be tested (Master V3/Slave V2, Master V2/Slave V3, etc.)
- [x] Document the scenarios to be tested (error ingested into master - retried - audited into slave - detected successful retry in master)
- [x] Run test scenarios
- [ ] Document results

## Required Knowledge

- Knowledge of ServiceControl Multi-instance mode
- Nothing else

This is a good opportunity for someone without much SC knowledge to pair with someone who does in order to learn

**Comment by SzymonPobiega** [comment]
I've started the part that really required deep SC knowledge and now it makes sense to recruit somebody who would like to learn more about how multi-instance SC works.

**Comment by mauroservienti** [comment]
I’m willing to join this one

**Comment by seanfarmar** [comment]
I’d like to join this one

**Comment by SzymonPobiega** [comment]
@seanfarmar I am afraid we've already staffed the TF with @Scooletz and @mauroservienti :-(

**Comment by mauroservienti** [comment]
took the liberty of removing the `Needs taskforce` label, as the task force is formed.

**Comment by SzymonPobiega** [comment]
After reviewing the code we decided to try a hybrid manual/automatic approach where we use the existing automated test cases but we start with manual setup procedure that involves installing on the test machine all required versions of ServiceControl.

The PR that refactors the SC acceptance tests so that they can run against an external instance of SC is in progress.

**Comment by mauroservienti** [comment]
Had a call about this with @danielmarbach and @boblangley. We realized that:

* the complexity of introducing automated testing for this feature is not worth it
* a set of manual test scenarios seems much more appropriate in this case

The main driver for the decision to go with manual test scenario is that it should be run really just once, or in the worst case every time a ServiceControl major is released.

The test case should instruct how to setup master/slave instances of ServiceControl, and which version matrix should be tested. Finally define the test that should be run, that could be as simple as:

* configure a receiving endpoint to send failed messages to SC master instance and audit messages to a slave instance
* send a message to the above endpoint
* make the message fail once
* retry the message from ServicePulse
* Ensure that when message succeed ServicePulse correctly display the message ad successfully retried

@boblangley will raise a PR to document the above in https://github.com/Particular/ServiceControl/tree/master/docs

**Comment by boblangley** [comment]
PR as promised: https://github.com/Particular/ServiceControl/pull/1348

I did not actually run this, it is all the detail I could create off the top of my head.

**Comment by mauroservienti** [comment]
I run the smoke tests outlined by @boblangley. Everything is OK. Should I document anything anywhere? or are we done here?

**Comment by danielmarbach** [comment]
The scenarios are document. This and youe comment here is good enough.
Let's close
