### ISSUE TITLE
Add support for V7 transports to ServiceControl

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1350]
As part of the 3.1 release of ServiceControl, we'll be introducing support for transports and topologies that are not yet supported by SC. This issue represents the high-level PoA to get this effort going

TF: @kbaley @tmasternak @danielmarbach 
Reviewer Azure: @SeanFeldman 
Reviewer RabbitMQ: @bording 
Reviewer SC: @SzymonPobiega 

## Plan of Attack

The transport verification and integration steps might be possible to parallelize onces the SCMU / UI changes have been implemented

- [x] Implement SCMU support for transport selection. Define meaningful names for all the to be supported transports (don't forget to change PowerShell as well) (Dependency for all other items)
  - [x] Document SCMU names including links to the transport sections on the docs site @kbaley ([PR](https://github.com/Particular/docs.particular.net/pull/3999))
  - [x] Update https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features. Make sure it is clear that in many scenarios transport adapters are no longer necessary @kbaley ([PR](https://github.com/Particular/docs.particular.net/pull/3999))
  - [x] Add guidance to https://docs.particular.net/samples/servicecontrol/events-subscription/ for ASBS and ASB to show how `ValidateAndHashIfNeedded` or Hashing rules for subscriptions and rule greater than 50 chars is required ([PR](https://github.com/Particular/docs.particular.net/pull/4000))

- [x] Support Azure Service Bus Forwarding Topology
  - [x] Verify or create build infrastructure to run ATTs under that topology
  - [x] Verify or come up with sensible defaults if not already present
  - [x] Smoke test
- [x] Support RabbitMQ Direct Topology
  - [x] Verify or create build infrastructure to run ATTs under that topology
  - [x] Verify or come up with sensible defaults if not already present
  - [x] Smoke test
- [x] Support SQS
  - [x] Verify or create build infrastructure to run ATTs under that transport
  - [x] Verify or come up with sensible defaults if not already present
  - [x] Smoke test
- [x] Support ASBS if deemed ready enough
  - [x] Verify or create build infrastructure to run ATTs under that transport
  - [x] Create transport integration assemblies
  - [x] Verify or come up with sensible defaults if not already present
    - [x] Discuss sanitization and hashing so that ` Entity path 'ServiceControl.Contracts.MessageFailures.MessageFailureResolvedByRetry' exceeds the '50' character limit.` can be avoided and still SC behavior is backward compatible with Forwarding topology
  - [x] Smoke test @tmasternak 
- [x] Verify new transports/topologies still work with PowerShell scripts
- [x] Release as 3.1
  - [x] Announcement @danielmarbach ([PR](https://github.com/Particular/Announcements/pull/283))

*Optional and time boxed*

- [x] Support Learningtransport
  - [x] Verify or create build infrastructure to run ATTs under that transport
  - [x] Create transport integration assemblies
  - [x] Verify or come up with sensible defaults if not already present
  - [x] Smoke test

## Expected outcome

All in the platform currently supported transports should be supported in ServiceControl running with sensible defaults

## Out of scope

- Advanced transport configuration. The transports will be supported with sensible defaults for now.

## You will learn

By joining this taskforce, you will be exposed to 

- ServiceControl v3 knowledge
- Exposure to the V7 transports
- WPF knowledge for the SCMU changes

## Other notes

[This sample](https://docs.particular.net/samples/servicecontrol/events-subscription/) is a good one to smoke test the new transports/topologies

**Comment by tmasternak** [comment]
I would like to participate in this.

**Comment by tmasternak** [comment]
@danielmarbach I see that support for new transports in monitoring instance in out of scope. Do we track that in any other place?

**Comment by WilliamBZA** [comment]
I don't think we have an issue for the monitoring transports anywhere @tmasternak, well not that I can find

**Comment by kbaley** [comment]
I'd like to help. Probably best to consider me under the TF apprentice role for anything not related to build infrastructure.

**Comment by boblangley** [comment]
Here is a branch used recently for troubleshooting a SQS bug, but it provides an example of how to add support for a transport to SCMU, in this case SQS: https://github.com/Particular/ServiceControl/tree/scmu-sqs-transport

**Comment by mauroservienti** [comment]
Is this going to be a single TF or multiple TFs for each transport? I’m trying to estimate the effort.

**Comment by danielmarbach** [comment]
@mauroservienti The effort should be in a reasonable range. Some things are already in place and need to be verified. Probably 3-4 people should be enough when the skills match. Once the SCMU changes are done things can be parallelized but we want to leave that up for the TF to decide.

**Comment by danielmarbach** [comment]
Kick off meeting scheduled for Tomorrow 3 PM MESZ with @kbaley @tmasternak and me. I'll be facilitating the issue. @mauroservienti is unfortunately not available to join this TF until next Wednesday so we will start without him. He can always join later if time permits

**Comment by kbaley** [comment]
Progress for the first item in the checklist:
- ASB - Forwarding Topology has been added ([PR](#1378))
- RabbitMQ - Direct Topology has been added ([PR](#1377))
- ASB entry renamed to ASB - Endpoint-Oriented Topology
- RabbitMQ entry renamed to RabbitMQ - Conventional Topology

TODO:
- Add SQS transport (needs some tweaks to the validation)
- Add ASBS

**Comment by danielmarbach** [comment]
The [PR ](https://github.com/Particular/ServiceControl/pull/1383) was added to support SQS

**Comment by danielmarbach** [comment]
Discussed in today's squad call the following proposals:

- Scope out ASBS from this effort because of the transaction scope issues that we discovered by removing the support for ASBS from the UI. Azure Service Bus Forwarding Topology is backward compatible and can be used
- Have an entry in SCMU that says ASBS but uses Azure Service Bus Forwarding topology behind the scenes
- Use ASBS with `ReceiveOnly` and mark it as experimental in the SCMU dropdown

Because the issue we are not 100% sure yet whether the issue is really just with Transaction Scopes and with the client or something else could be not working with ASBS we decided to remove the ASBS support from SCMU. The code that is in place, as well as the build configurations, will stay around for future efforts to be used.

**Comment by kbaley** [comment]
Release is done. @danielmarbach and I did a sort of mini-retrospective but I think the formal one can be done async in the comments here.

I really enjoyed working on this TF. It was a great introduction to ServiceControl providing enough technical work to get my hands dirty but not _too_ dirty. The fact that many of the transport configurations were done was good for me to understand how things worked and provided enough of a template for the remaining configurations.

Despite not having much overlap with @tmasternak, I didn't feel hindered by timezones. Hand-offs were smooth in both directions, daily-ish syncs were useful, and it was helpful to have @danielmarbach provide a bit of a buffer between work on both sides of the pond. In that regard, I think the only takeaway is to have "enough" overlap between timezones to facilitate these hand-offs.

That's it from me. I'm happy to have this closed when everyone else provides their input. If anyone has feedback on anything I did well or didn't do well, keep it yourself. I'm an island.

I kid of course. Post it here or ping me.

**Comment by tmasternak** [comment]
I really like the smoothness of this TF. What is more we were able to react to what was happening and scope down the PoA accordingly releasing as much value as we could right away - that's a win to me. Overall it was a pleasure to work with @danielmarbach  and @kbaley. As usual ;).
