### ISSUE TITLE
[TODO] AuditImporterFeature - fail startup if can't write to the forwarding queue

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1355]

**Comment by danielmarbach** [comment]
This one is tricky. How do you want to do this in a transport agnostic way? Can we even do this? Probably would add a startup task and then try to send into the forwarding queue but that feels very ugly. I'd rather see us adding a circuit breaker and shut down if the user request us to forward and we can't write.

**Comment by mikeminutillo** [comment]
> Probably would add a startup task and then try to send into the forwarding queue but that feels very ugly.

That's exactly how we used to do it 

https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Operations/AuditQueueImport.cs#L110-L129

I raised https://github.com/Particular/ServiceControl/pull/1363 with a similar implementation.
