### ISSUE TITLE
[TODO] AuditIngestor - Clean the time to be received header

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1357]
The old implementation went through [TransportMessageCleaner](https://github.com/Particular/ServiceControl/blob/ac3b4596abbba58e24288dd291a660e3602ee08d/src/ServiceControl/Operations/TransportMessageCleaner.cs#L11) which removed the TTBR.

**Comment by SzymonPobiega** [comment]
Since we are removing the TTBR/setting it to the max value when forwarding I don't think this is necessary any longer. @Particular/servicecontrol-maintainers thoughts? 👍 or 👎 ?

**Comment by WilliamBZA** [comment]
:+1: Remove the todo

**Comment by danielmarbach** [comment]
Addressed in #1351
