### ISSUE TITLE
[TODO] ErrorImporter - fail startup if can't write to error forwarding queue

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1358]

**Comment by WilliamBZA** [comment]
Wouldn't this fail anyway once we tried to write? I guess failing at startup would be a clearer message to the users though.

How would we check if we can write or not anyway?

**Comment by danielmarbach** [comment]
Similar comment to https://github.com/Particular/ServiceControl/issues/1355#issuecomment-414424151
