### ISSUE TITLE
[TODO] FailedMessagePersister - fan out enrichers?

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1359]

**Comment by SzymonPobiega** [comment]
Similar to https://github.com/Particular/ServiceControl/issues/1356 I guess we should not do it because of thread safety.

**Comment by danielmarbach** [comment]
I agree especially because there is an implicit assumption of execution order over some shared state. I'll send in PR which replaces the TODO with a comment

**Comment by danielmarbach** [comment]
I double checked [what @WilliamBZA said](https://github.com/Particular/ServiceControl/issues/1356#issuecomment-414283780) and can confirm they use all their unique keys. Sent in https://github.com/Particular/ServiceControl/pull/1361 to fix this TODO

**Comment by danielmarbach** [comment]
Merged the PR. Closing
