### ISSUE TITLE
[TODO] Processing attempt - do we need to persist intent, correlation ID and reply-to at the document level

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1360]

**Comment by SzymonPobiega** [comment]
Reply-to seems to be unused so I am 👍 for removing it. The other properties are used when staging a message in the `RetryProcessor`. I'd rather keep them then try to get these values from the headers.

**Comment by SzymonPobiega** [comment]
@Particular/servicecontrol-maintainers thoughts?

**Comment by WilliamBZA** [comment]
`ReplyToAddress` seems to be only used by the v1.27.0 migration. Which is not applicable anymore. Even if we have to support a v1 - v3 scenario. 👍 for removing `ReplyToAddress`.

This would change the storage format used though. What does removing stored properties do to backwards compatibility I wonder.
