### ISSUE TITLE
Spike RavenDB 4.1 embedded mode

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1367]
In this spike, we'd like to investigate the throughput and performance improvements we'd get when switching to RavenDB 4.1 embedded.

RavenDB 4.1 will bring back the [embedded mode](https://ayende.com/blog/183555-A/ravendb-4-1-features-running-ravendb-embedded). As another benefit, the instance will be running as a sidecar along with the main process and no longer need to share resources like the thread pool. Recent efforts already made significant resource utilization improvements in ServiceControl. Performance tests showed that ESENT's single writer thread can be the bottleneck in some scenarios. 

Timebox: 3 days

## Plan of attack

- Switch to RavenDB 4.1 embedded (hack)
- Setup loadtest resources on Azure on a single transport
- Run load test scenarios 1-2 days
- Document outcome under /docs

## Out of scope

- Migration from Esent to Voron 
- Tweak on the codebase in an attempt to improve performance

## Skills required

- Familiarity with RavenDB or willingness to learn
- Tolerance with pre-release software
- At least one member of @Particular/servicecontrol-maintainers who is familiar with the load test generator

## You'll learn

- RavenDB 4.1 and its new embedded mode
- ServiceControl and its marriage with RavenDB
- LoadTestGenerator and how to click through the Azure portal :)

**Comment by boblangley** [comment]
I am interested in joining this task force.

**Comment by SzymonPobiega** [comment]
After upgrading the package reference compilation of the `ServiceControl` project resulted in 200+ errors. Some of them are simple namespace changes but some are much more severe:
 * The `IndexQuery` API changed a lot (missing stuff)
 * The `AbstractTransformerCreationTask` does not exist any more
 * The `Etag` is no longer surfaced via the API. Instead we can access the change vector which contains etag and cluster node information.
   * A lot of advanced features was based on assumption that you can query the index Etag to see if it includes the most recent changes. This is probably not possible any more
   * No easy way to compare change vectors in our code as they are exposed as strings. We would probably have to re-implement the comparison algo described in RavenDB docs

I haven't even got through 20% of the errors. I am pretty sure we won't be able to get it to compile, let alone run and pass the tests in the time slot assigned. 

@boblangley I propose we try configuring our well known 3.5 RavenDB to use Voron and check if this setup is runnable and passes the tests. I don't expect much benefits in terms of performance though because of the architecture of RavenDB 3.5.

**Comment by danielmarbach** [comment]
How about comment out all the nancy modules and just enable the ingestion
part?

**Comment by SzymonPobiega** [comment]
@danielmarbach It is not only the nancy modules. It includes the cleaners and a lot of other stuff. The whole codebase it red.

**Comment by boblangley** [comment]
I spent a couple of hours and ended up migrating a few things. It is a doable task, but I agree with @SzymonPobiega the 3 day timebox isn't viable. 

It isn't as simple as migrating from one API to another, we also need to figure out the _right_ way for the new APIs. My commits to the branch are very likely wrong in some way.

@SzymonPobiega I agree, let's switch 3.5 to Voron and see what happens: https://github.com/Particular/ServiceControl/pull/1387

**Comment by boblangley** [comment]
## Status Update

@SzymonPobiega and I uploaded the Voron enabled SC 3.0.1 to a VM in Azure and started the load tests. We will evaluate the results tomorrow.

**Comment by SzymonPobiega** [comment]
### Status update

The RavenDB 3.5 Voron tests on Azure showed audit ingestion throughput of 48 msg/s. The same ServiceControl using Esent was able to process 113 msg/s.

Summary
 * Upgrading ServiceControl to Raven 4.1 is difficult and time consuming. As an alternative, in future we might consider
    * trying to upgrade only the audit ingestion part of it (if we had audits separated from the core it would be much easier)
    * do a synthetic test which would be just inserting documents to RavenDB as fast as possible
 * In version 3.5 Esent is more than two times faster than Voron so it does not make sense to switch

**Comment by SzymonPobiega** [comment]
@boblangley I think we're done here.

**Comment by boblangley** [comment]
Agreed, and this was too small to retro. Closing.

**Comment by danielmarbach** [comment]
Did a quick hack to see how they behave on my machine

https://github.com/danielmarbach/RavenDB.Embedded.Inserts

```
RavenDB 35 Embedded (Esent)

1. Run 1232.5 docs/s
2. Run 1250.33 docs/s

RavenDB 35 Embedded (Voron)

1. Run 1239.08 docs/s
2. Run 1218.25 docs/s

RavenDB 41 Embedded

1. Run 6056.58 docs/s
2. Run 6064.75 docs/s
```

**Comment by danielmarbach** [comment]
Test in Azure with DS14_V3 (16vCores)


```
RavenDB 35 (Esent, System Disk)

1. Run 264.13 docs/s
2. Run 270.03 doc/s

RavenDB 35 (Esent, 2x7500, Striped Disk)

1. Run 279.03 docs/s
2. Run 282.1 doc/s

RavenDB 35 (Esent, 2x7500, Striped Disk, Concurrency 30 instead of 10)

1. Run XX docs/s
2. Run XX doc/s

RavenDB 35 (Esent, 4x7500, Striped Disk)

1. Run 272.6 docs/s
2. Run 277.93 doc/s

RavenDB 35 (Esent, 4x7500, Striped Disk, Concurrency 30 instead of 10)

1. Run 277.23 docs/s
2. Run 276.93 doc/s

RavenDB 35 (Voron, System Disk)

1. Run 134.9 docs/s
2. Run 140.3 docs/s

RavenDB 41 (System Disk)

1. Run 1107.86 docs/s
2. Run 1111.43 docs/s

RavenDB 41 (2x7500, Striped Disk)

1. Run 1180.06 docs/s
2. Run 1182.36 docs/s

RavenDB 41 (2x7500, Striped Disk, Concurrency 30 instead of 10)

1. Run 2698.33 docs/s
2. Run 2667.43 docs/s

RavenDB 41 (4x7500, Striped Disk)

1. Run 1164.3 docs/s
2. Run 1149.63 docs/s

RavenDB 41 (4x7500, Striped Disk, Concurrency 30 instead of 10)

1. Run 2667.13 docs/s
2. Run 2677.13 docs/s
```
