### ISSUE TITLE
ServiceControl Management Utility: Allow error text to be copied

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#1372]
While configuring ServiceControl to run some tests I encountered an error and there was no way to copy the error message text. Only option to get some help was a screenshot.

![image](https://user-images.githubusercontent.com/1325611/44411843-b9125100-a567-11e8-8690-5c8915c9f7a2.png)

**Comment by seanfarmar** [comment]
This was resolved in 14.0

<img width="815" alt="Screenshot 2021-03-31 at 16 26 12" src="https://user-images.githubusercontent.com/125256/113170351-641a3980-923e-11eb-9bfd-345cd9c43a9f.png">
<img width="847" alt="Screenshot 2021-03-31 at 16 25 29" src="https://user-images.githubusercontent.com/125256/113170367-67adc080-923e-11eb-991d-926fc10d69e0.png">
