### ISSUE TITLE
ServiceControl Management Utility: Audit retention selection is too granular (and thus annoying)

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#1373]
When setting up ServiceControl if you want to change the Audit Retention value the slider allows to select hours, instead (as for errors) it should default to days only.

![image](https://user-images.githubusercontent.com/1325611/44411968-10b0bc80-a568-11e8-98cd-cbcc8c66ded0.png)

**Comment by kevison** [comment]
Along those lines the Error Retention Period should able to go less than 10 days to at least 5 days.
