### ISSUE TITLE
Update to ServiceControl 3: Keyword not supported: 'queue schema'

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/ServiceControl#1380]
## Who's affected

Customers using ServiceControl with SqlTransport in combination with queue schema

## Symptions

When upgrading from 2.1.3 to 3.0 and providing a queue schema in the connection string an `ArgumentException` is raised.

Example connection string
```
Server=...;Initial Catalog=...;Integrated Security=true; Queue Schema=Queues
```

## Original description

I updated to ServiceControl 3 and during upgrade process I am getting the following exception:

System.ArgumentException: Keyword not supported: 'queue schema'.

My transport connection string is (and this worked in 2.1.3):

Server=...;Initial Catalog=...;Integrated Security=true; Queue Schema=Queues

**Comment by danielmarbach** [comment]
@Tobias-Gr we are sorry that we caused this. That is definitely a regression. We will treat it with priority and fix it asap.

**Comment by SzymonPobiega** [comment]
@Tobias-Gr closing to generate release notes and proceeding with the release. Feel free to re-open if you find the 3.0.1 fix not helpful in your case.

**Comment by Tobias-Gr** [comment]
@SzymonPobiega , thanks! 3.0.1 solves the problem in my environment.
