### ISSUE TITLE
PowerShell cmdlet Invoke-ServiceControlInstanceUpgrade throws exception

### ISSUE THREAD

**Issue by AntoineDSW** [Particular/ServiceControl#1390]
We have automated the process of installing/upgrading ServiceControl via Powershell on our 20+ servers.

The update scripts are working till version SC 2.12. We now like to upgrade to 2.13 (for upgrading to 3.1), but get the following error running Invoke-ServiceControlInstanceUpgrade -Name <Instance To upgrade> :

       Invoke-ServiceControlInstanceUpgrade : Object reference not set to an instance of an object.
       + CategoryInfo          : NotSpecified: (:) [Invoke-ServiceControlInstanceUpgrade], ullReferenceException
       + FullyQualifiedErrorId :  System.NullReferenceException,ServiceControlInstaller.PowerShell.InvokeServiceControlInstanceUpgrade

As I said, the scripts work up to 2.12.  Versions 3.0 and 3.1 have the same error message. Manually upgrading via ServiceControl Management gives no issues.

Did something change in the way to use the command in 2.13? I saw there is an "improvement" #1228 new in this version that has something to do with upgrading.

Thanks

Additional Info:

I loaded the 2.11 powershell module and put the 3 zip files from version 2.13 in the 2.11 folder. Ran sc-upgrade -Name <instance_name> and it upgraded to 2.13 without any issues.

So i'm guessing it is an issue with the powershell module.

**Comment by mikeminutillo** [comment]
This is a bug. I think I've found it and have [a fix](https://github.com/Particular/ServiceControl/pull/1398). It should be released in 2.1.4

Thanks @AntoineDSW for bringing this to our attention.

**Comment by SzymonPobiega** [comment]
@AntoineDSW closing this issue to generate release notes. I'll ping you when the version is actually out.

**Comment by SzymonPobiega** [comment]
Smoke tested fix and proceeding with the release.

**Comment by SzymonPobiega** [comment]
@AntoineDSW the fix has been released as 2.1.4.
