### ISSUE TITLE
Confirm that ServiceControl >= 2.0.0 ingests very slowly on Windows Server 2012

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1407]
Since upgrading to RavenDB 3.5 it seems that there might be a problem with the performance of Esent running on Windows Server 2012.

A [customer](https://c.eu1.visual.force.com/apex/Case?num=00039024) reported ServiceControl running out of memory and losing locks on messages (using ASB). After upgrading to ServiceControl 3, the problem persisted showing an ingestion rate of only 1-2 messages a second. The upgrade effectively eliminates Azure Service Bus from the equation as version 2 of ServiceControl and version 3 run on different versions of the transport.

The customer then upgraded to Windows Server 2016, and the problem went away. They were able to ingest 135 messages per second.

This could mean that RavenDB 3.5. might have some problems with using Esent in Windows Server 2012. We should investigate and see if we can isolate the specific problem and perhaps document that upgrading to version 2 or greater of ServiceControl is not recommended on Server 2012.

We have already verified that ingestion works as expected in a Server 2016 environment.

### Plan of action

The plan of action is about reproducing the behavior that the customer observed i.e. slow ingestion on Windows Server 2012 R2.

* [ ] Create an azure VM running Server 2012 R2 and set up the load generator and ServiceControl tests
* [ ] Run the tests to see if the same problem exists

### Customer machine specifications

* Standard_DS12_v2 (4 vcpus, 28GB RAM)
  * 16K IOPS cached temp storage
  * 2.8K IOPS uncached disk
* RavenDB is on attached premium SSD - 5K IOPS
  * 200MB/s throughput limit

**Comment by SzymonPobiega** [comment]
I am going to present it to the @Particular/keeping-the-lights-on-squad today.

**Comment by SeanFeldman** [comment]
From Hibernating Rhinos:

> I'm not aware any Esent issues on 2012 R2 which could cause it. I'm pretty sure we have many customers still using this OS

**Comment by DavidBoike** [comment]
Squad cleanup: This issue seems too out-of-date to even be actionable.
