### ISSUE TITLE
ServiceControl 3.x attempts to create staging queue on normal run

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1413]
When ServiceControl 3.x instance starts it always attempts to create the staging queue.

If the ServiceControl instance is running without queue create privileges, this will prevent ServiceControl from starting.

Expected result:

ServiceControl should create the staging queue when it is run in setup mode, not when it is in run mode.

**Comment by WilliamBZA** [comment]
Fixed by #1414
