### ISSUE TITLE
ServiceControl uses unsupported version of AdvancedInstaller 

### ISSUE THREAD

**Issue by dbelcham** [Particular/ServiceControl#1417]
## Problem
ServicePulse uses AdvancedInstaller to create msi package during build. The version that is needed by the advanced installer package project file is outdated and not supported.

## PoA
- [ ] Update AdvancedInstaller version in the ServiceControl xml file.
- [ ] Update AdvancedInstaller installed on the build agents.
- [ ] Run SC build and validate that it creates msi package and one can install it.

**Comment by mikeminutillo** [comment]
AdvancedInstaller was updated to 17.7
