### ISSUE TITLE
Service Control 3.1.1 is not using the latest version of the SQS Transport (4.1.1)

### ISSUE THREAD

**Issue by Grendel** [Particular/ServiceControl#1419]
Service Control 3.1.1 uses the v 4.1.0 of the SQS Transport which is missing the JSON serialisation bugfix covered by 4.1.1: https://discuss.particular.net/t/nservicebus-amazonsqs-3-3-1-4-0-1-4-1-1-patch-releases-available/667

Impact: Endpoints running under v 1.x of the SQS transport cannot be monitored under SC as the serialisation issue causes audit and error messages to fail out to the SC poison message queue.

**Comment by boblangley** [comment]
Thanks for raising this. We will let you know when we release a version of ServiceControl with version 4.1.1 of the transport.

**Comment by Grendel** [comment]
Hi guys - do you have a rough ETA on this making it into a published release so we can decide whether we shelve our upgrade for now?

**Comment by kbaley** [comment]
@Grendel Can't give a specific date for the release but a PR has already been [created and merged](https://github.com/Particular/ServiceControl/pull/1422).

**Comment by WilliamBZA** [comment]
Fixed by #1422 

Closing for now, a release will be out shortly

**Comment by danielmarbach** [comment]
@Grendel the release 3.1.2 is out
