### ISSUE TITLE
Release .NET core support for SC.Contracts package

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1446]

**Comment by bording** [comment]
Where is this package produced from? Is this something that has to be manually uploading to nuget.org?

**Comment by SzymonPobiega** [comment]
@bording here's the build https://builds.particular.net/project.html?projectId=ServiceControl_ServiceControlContracts&tab=projectOverview and I pretty sure there is an Octopus project for it.

**Comment by bording** [comment]
Ah, so it actually comes from a different repo: https://github.com/Particular/ServiceControl.Contracts

That would explain how it hasn't been updated/released then. Looks like we have project cleanup to do in repo as well.

**Comment by bording** [comment]
Version 1.2.0 of ServiceControl.Contracts is now out, and it includes both `net40` and `netstandard2.0` versions of the library.

Because we didn't update to `net452` this isn't a breaking change, and doesn't cause any problems with assembly version changes.
