### ISSUE TITLE
Update Documentation for ServiceControl's required .NET Framework version

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1447]
ServiceControl is currently built to run under the .NET Framework v4.6.1.  Below is the error you get when attempting to perform the install on a machine without this version of the framework installed.

```
ServiceControl cannot be installed on systems with .NET Framework version lower than 4.6.1
```

# Incorrect Documentation link

https://docs.particular.net/servicecontrol/installation#prerequisites

# Related Issues

#1307 
#1371

**Comment by danielmarbach** [comment]
@TraGicCode 

thanks for pointing that out. We have it documented in the upgrade guide

https://docs.particular.net/servicecontrol/upgrades/2to3#prerequisites

but unfortunately not reflected that in the link you mentioned. I will raise corresponding issue in the documentation repository soon

**Comment by danielmarbach** [comment]
@TraGicCode Another question from my side. The ServiceControl installer bundles the .NET Framework 4.6.1 as part of the installation package. We tested that on clean machines and tests seemed to indicate that it got properly installed. Did this not work for you on the machine you tested?

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/4043

**Comment by TraGicCode** [comment]
Hey @danielmarbach ,

From my testing it is not bundled and the install failes on a fresh vagrant machine with windows server 2012 R2. 

Thanks,
Michael Fyffe

**Comment by danielmarbach** [comment]
Hi @TraGicCode 

Many thanks for reporting back. I think I've found the culprit in the installer logic. #1460 

Thanks
Daniel

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/ServiceControl/issues/1461 for further investigation
