### ISSUE TITLE
SQL transport example connection string does not show the Queue Schema option

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#1455]
https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControlInstaller.Engine/Instances/ServiceControlCoreTransports.cs#L75
https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControlInstaller.Engine/Instances/MonitoringTransports.cs#L38

This should also be added to https://docs.particular.net

**Comment by danielmarbach** [comment]
![image 1](https://user-images.githubusercontent.com/174258/48334672-bf423600-e65b-11e8-9862-3061bbca0164.png)

With SQS we added it to the UI
