### ISSUE TITLE
SQS Transport to accept EC2-Profile as  Credentials  Source

### ISSUE THREAD

**Issue by AbdoHassanUMG** [Particular/ServiceControl#1459]
Allow SQS Transport customisation to accept EC2 Profile ( Instance Role ) as a credential source.  Currently the transport **requires** API Keys to be passed in connection string. Which is less secure and introduces ops complexity around key rotation.

**Comment by yvesgoeleven** [comment]
@AbdoHassanUMG Thank you for the suggestion, I moved it to the sqs transport repository

https://github.com/Particular/NServiceBus.AmazonSQS/issues/247

**Comment by yvesgoeleven** [comment]
I stand corrected, it is in the right repo. The transport already allows this

**Comment by danielmarbach** [comment]
@AbdoHassanUMG 

You are absolutely right it is not yet ideal how the API keys are managed. The underlying SQS transport uses the standard SDK constructors of the clients thus it would follow the normal credential retrieval hierarchy defined in https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html. So given that we could support it by now longer requiring API keys in the connection string and only promoting environment variables if you specify the keys. Would that work for you? This would assume the default profile would be used or would you have the requirement to specify the profile name in ServiceControl?

**Comment by AbdoHassanUMG** [comment]
@danielmarbach 
Yes , It would be sufficient for our use case if the api keys in the connection string are not mandatory and the standard constructor falls back to the Ec2 role.

**Comment by boblangley** [comment]
Addressed in #1525
