### ISSUE TITLE
AdvancedInstaller keeps running in background on Windows 2012R2

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1461]
When executing the installer on a freshly installed non-patched Windows 2012 R2 the installation does not proceed and stops with the following warning

![installer](https://user-images.githubusercontent.com/174258/46875978-6e150b80-ce3d-11e8-857c-1be1c01e753a.PNG)

This happens even though the web installer for 4.6.1 is shipped as part of the advanced installer.

![webinstaller](https://user-images.githubusercontent.com/174258/46876844-a7e71180-ce3f-11e8-9b30-8a3a4f605844.PNG)

When I apply latest Windows updates on the server and execute the installer it starts doing something in the background but not even after 15 minutes it is done. Continuing in the background

![image](https://user-images.githubusercontent.com/174258/46877117-5f7c2380-ce40-11e8-8c84-1c3eb6c386ca.png)

**Comment by TraGicCode** [comment]
Awesome @danielmarbach ,

Is there a way in which i can see when this gets scheduled or picked up to be worked on?

**Comment by ramonsmits** [comment]
Resolved in [ServiceControl 3.6.2](https://discuss.particular.net/t/servicecontrol-3-6-2-patch-release-available/941)
