### ISSUE TITLE
ServiceControl Monitoring also requires 'SQS' queue prefix fix

### ISSUE THREAD

**Issue by Grendel** [Particular/ServiceControl#1462]
We have installed the 3.2.2 release of SC which includes this fix to implement our 'environment specific' queue prefix for AWS SQS: https://github.com/Particular/ServiceControl/issues/1452

This is all working fine for the core Service Control behaviours, including retries.

We have now looked at enabling the SC monitoring capability and this does not appear to support the queue prefix in the AWS SQS connection string.

We can apply the following work around: name the Service Control monitoring instance to match the full monitoring queue name including prefix. 

For example 'my-queue-prefix-Particular-Monitoring'.

It would  be good from a consistency perspective to have this work the same as the main Service Control instance install.

**Comment by Grendel** [comment]
...one update to this issue. Using the work around above I can see monitoring data flowing through to the ServicePulse dashboard. The one metric which is not visible is the queue length - I'm assuming this requires the queue prefix config to resolve the monitored endpoint receive queue in SQS?

**Comment by danielmarbach** [comment]
Hi @Grendel 

Yes currently the workaround you mentioned is the "recommended" way to go until we officially support the queue name prefix. When we fixed 3.2.2 with the queue name prefix we wanted to keep the scope of the bugfix focused on ServiceControl only. We will keep you posted

Daniel

**Comment by Grendel** [comment]
@danielmarbach - can we please increase the urgency of this issue. The work around above does not support resolving the 'queue length' metric as the monitoring service does not know how to resolve the business endpoint queue names with a prefix. 

This generates copious 'Error' log entries for the Monitoring service with full stack trace details. This generates GB's of log data which could easily bring the monitoring host down.

The end point 'GRM-Users-DataMigration-Host' called out below is our logical end point name. The actual SQS queue name includes our environment specific prefix - e.g: QA1-GRM-Users-DataMigration-Host

Log entry...

2018-10-29 13:43:23.7134|10|Error|ServiceControl.Transports.AmazonSQS.QueueLengthProvider|Obtaining an approximate number of messages failed for 'GRM-Users-DataMigration-Host'
Amazon.SQS.Model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
...snip...

**Comment by danielmarbach** [comment]
@Grendel this is currently being incorporated into ServiceControl.Monitoring. Maybe @tmasternak can give you some hints about the rough ETA when this will be released

**Comment by tmasternak** [comment]
@Grendel we are in the process of releasing and for what we can tell new version should go out this week. I'll keep you posted.

**Comment by Grendel** [comment]
Awesome guys!

**Comment by tmasternak** [comment]
@Grendel the 3.3.0 release just came out. Please have look at https://discuss.particular.net/t/servicecontrol-3-3-0-minor-release-available/835 for details.

**Comment by Grendel** [comment]
@tmasternak - your fix does not appear to be in 3.3.0: I've updated my local installed and I still get the following error logging under service control monitoring (note that the queue name GRM-Assets-DataMigration-Host is the endpoint name without the prefix): 

-------------------------------------------------------------
ServiceControl Monitoring Version:				2.0.0.0
Selected Transport:					ServiceControl.Transports.AmazonSQS.ServiceControlSqsTransport, ServiceControl.Transports.AmazonSQS
-------------------------------------------------------------
...snip...
2018-11-12 16:26:01.9125|9|Error|ServiceControl.Transports.AmazonSQS.QueueLengthProvider|Obtaining an approximate number of messages failed for 'GRM-Assets-DataMigration-Host'
Amazon.SQS.Model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
...snip...

Did you miss updating the SC deployment package with the patched version of the monitoring process?

**Comment by danielmarbach** [comment]
@Grendel 

have you tried providing the Queue Name Prefix in the configuration UI? 

![image](https://user-images.githubusercontent.com/174258/48365414-263b0b80-e6ab-11e8-95ee-5d64e864aeef.png)

**Comment by Grendel** [comment]
Yes. We're using exactly the same config as we use for the main ServiceControl process. Including the queue prefix.
