### ISSUE TITLE
Customer suggestion: Be able to automate maintenance tasks from command line

### ISSUE THREAD

**Issue by seanfarmar** [Particular/ServiceControl#1463]
we are looking to perform the backup and compaction of the DB with a scheduled task.

**Comment by mikeminutillo** [comment]
It should be possible to start/stop instances using `sc.exe` (built into windows).

Once, the instance is stopped, the [backup](https://docs.particular.net/servicecontrol/backup-sc-database#backup) and [compaction](https://docs.particular.net/servicecontrol/db-compaction#using-esentutl-preferred-approach) processes can be automated using existing windows tools as well.

**Comment by TraGicCode** [comment]
@mikeminutillo is indeed right. We should probably close this.

**Comment by dvdstelt** [comment]
@seanfarmar I'll close this, but if you think it should be re-opened, you know where to click ;-)
