### ISSUE TITLE
Custom checks for failed imports show broken link

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1483]
The custom checks added in https://github.com/Particular/ServiceControl/pull/1053 show broken link

**Comment by boblangley** [comment]
We should also tie this section to those articles : https://docs.particular.net/servicecontrol/servicecontrol-instances/#self-monitoring-via-custom-checks

**Comment by boblangley** [comment]
Added redirect from https://docs.particular.net/servicecontrol/import-failed-audits-messages to https://docs.particular.net/servicecontrol/import-failed-audits: https://github.com/Particular/docs.particular.net/commit/ae18a1ac6d19ba0070a3b5e9eb6785227ff18725
