### ISSUE TITLE
Control messages not being ingested with Azure Service Bus

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceControl#1484]
I'm seeing an issue where control messages are not being ingested, causing huge amounts of requests in ASB.

I've traced it down to what appears to be the SagaAudit plugin Start method (https://github.com/Particular/NServiceBus.SagaAudit/blob/a11114bdd52ce6173c1ed828b948b0bf84d0fda7/src/NServiceBus.SagaAudit/ServiceControlBackend.cs#L60) 

Note the DeliveryCount and lack of body:

![image](https://user-images.githubusercontent.com/2712328/48203475-35c5f780-e32d-11e8-924a-ff425a8c4867.png)

I'm also getting a ton of errors in the SC log file:

[logfile.2018-11-08.txt](https://github.com/Particular/ServiceControl/files/2562040/logfile.2018-11-08.txt)

I've verified it by restarting the endpoint and seeing this message get "stuck" in the queue, causing HUGE amounts of message requests.

![req](https://user-images.githubusercontent.com/2712328/48203858-21362f00-e32e-11e8-8e86-658f7279b4dc.jpg)

I've backed up this queue if you need any further information.

**Comment by SeanFeldman** [comment]
@markgould are you using `NServiceBus.Transport.AzureServiceBus`  or `NServiceBus.Azure.Transports.WindowsAzureServiceBus`? Looking at the issue description, looks like `NServiceBus.Transport.AzureServiceBus`.

**Comment by markgould** [comment]
My endpoints are using NServiceBus.Transport.AzureServiceBus.

ServiceControl appears to be using NServiceBus.Azure.Transports.WindowsAzureServiceBus (from looking at the installation directory)

![sc](https://user-images.githubusercontent.com/2712328/48205176-5ee88700-e331-11e8-99f5-33bb4f637b6b.jpg)

**Comment by SeanFeldman** [comment]
What SC version are you using and what transport it's using (SC config)?

**Comment by markgould** [comment]
![sc2](https://user-images.githubusercontent.com/2712328/48205841-88ee7900-e332-11e8-910d-1fa5b50678ab.jpg)

Config:
[ServiceControl.txt](https://github.com/Particular/ServiceControl/files/2562166/ServiceControl.txt)

**Comment by SeanFeldman** [comment]
@markgould what are the `particular.servicecontrol.test` queue settings?

**Comment by markgould** [comment]
Just the standard, SC created the queue.

![queueconfig](https://user-images.githubusercontent.com/2712328/48208053-9c501300-e337-11e8-9e15-a444aeddc706.jpg)

**Comment by markgould** [comment]
I forked SC and found there is an object ref error coming from here. I'll keep digging.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=NServiceBus.Azure.Transports.WindowsAzureServiceBus
  StackTrace:
   at NServiceBus.Transport.AzureServiceBus.BrokeredMessagesToIncomingMessagesConverter.Convert(BrokeredMessage brokeredMessage)

**Comment by markgould** [comment]
Looks like it's this:

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/c506167bd6172f63e140d79c92424c0bf47aacb3/src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs#L45

As there is no body, I'm sure bodyStream is being returned as null causing the exception when calling bodyStream.Length.

**Comment by markgould** [comment]
Yep:

![nullref](https://user-images.githubusercontent.com/2712328/48209377-a0c9fb00-e33a-11e8-9c98-7f15f28c117b.jpg)

**Comment by danielmarbach** [comment]
I was able to repro this as well and trace it down to the exact same method @markgould So that means SagaAudit plugin never really work with ASB because the audit plugin was always sending control messages... And that explains the delivery count because the messages fail in the transport pump and are never handed over to recoverability core so they can't be moved to the error queue

**Comment by markgould** [comment]
Glad you are able to repro it. I was about to fix and submit a PR, but I'll let you take over unless you want me to.

Luckily I caught it before running up a large Azure bill from all the requests 😢

**Comment by danielmarbach** [comment]
@markgould glad you have been able to catch it before your Azure bill went through the rooftop. Sorry if we caused inconvenience. 

We'll deal with this since it requires a coordinated effort over multiple repositories and products. We'll keep you posted.

**Comment by danielmarbach** [comment]
@markgould we released the patched versions of Azure Service Bus transports, see https://discuss.particular.net/t/nservicebus-azure-transports-windowsazureservicebus-7-2-15-8-0-6-and-9-0-3-patch-releases-available/845 

We will now start patching ServiceControl and release the fixes once we are ready

**Comment by danielmarbach** [comment]
Closed via #1497

**Comment by danielmarbach** [comment]
@markgould the updates are out see https://discuss.particular.net/t/servicecontrol-3-3-2-patch-release-available/852

**Comment by markgould** [comment]
Thanks!
