### ISSUE TITLE
ServiceControl default log level is insufficient

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1486]
The default log level for a new instance of ServiceControl is WARN. This is often insufficient to diagnose issues when customers send us log files. 

It only helps when we've previously considered what could go wrong and have thought to log at the WARN level. Without any of the context of what else was happening in ServiceControl at that time, we often have to ask the customer to update their logging level (requires messing with a config file) and then restart their instance and hope that the problem occurs again.

**Comment by WilliamBZA** [comment]
Added to maintenance release list

**Comment by SzymonPobiega** [comment]
Closed via #1518
