### ISSUE TITLE
Fix documentation on wrong Servicecontrol ravendb database name

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1506]
When looking at the documentation for how to compact the servicecontrol ravendb database it says the database name is called storage. 

https://docs.particular.net/servicecontrol/db-compaction#using-the-ravendb-management-portal-step-4-import-the-exported-data

**Comment by TraGicCode** [comment]
I raised this point in #1505 about the documentation showing the wrong name for the ravendb database.

**Comment by WilliamBZA** [comment]
PR Submitted, thanks @TraGicCode

**Comment by danielmarbach** [comment]
Documentation PR merged. Closing

**Comment by TraGicCode** [comment]
Hey @WilliamBZA & @danielmarbach ,

I think yall missed a spot in the documentation that has the wrong database name

https://docs.particular.net/servicecontrol/creating-config-file

**Comment by WilliamBZA** [comment]
Thanks, fixed!
