### ISSUE TITLE
Where are my rabbitmq timeouts and timeoutsdispatcher queues for my servicecontrol instance

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1517]
According to the documentation here ( https://docs.particular.net/servicecontrol/configure-non-privileged-service-account ) i would expect to see the timeouts and timeoutsdispatcher queue created in rabbitmq for my servicecontrol instance.  Unfortunately, i don't see it.  Is this outdated documentation?

**Comment by WilliamBZA** [comment]
Hey @TraGicCode, that section is for MSMQ and doesn't apply to RabbitMQ :)

**Comment by danielmarbach** [comment]
@TraGicCode thanks for bringing that up, I think the intention of this section is to be specifically for MSMQ, see the highlighted part

![image](https://user-images.githubusercontent.com/174258/49514311-fb9c3700-f893-11e8-9016-aeaff35a8d4c.png)

**Comment by TraGicCode** [comment]
Thanks sorry o missed that
