### ISSUE TITLE
Improvement: Migrate to new Azure Service Bus transport while upgrading Monitoring & ServiceControl Instances

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServiceControl#1557]
It would be nice to migrate automatically from "Azure Service Bus - Forwarding Topology (Legacy)" to the newest one from ServiceControl Management

**Comment by SzymonPobiega** [comment]
@JSCProjects what do you mean by *automatically*? Can you explain?

**Comment by JSCProjects** [comment]
@SzymonPobiega after installing an update via "Particular Service Platform Installation" 
![image](https://user-images.githubusercontent.com/19533149/50812735-2e62a080-1314-11e9-8e6c-48bac62de903.png)
 then you'll have to finish the installation with "Starting ServiceControl Management"
![image](https://user-images.githubusercontent.com/19533149/50812789-5d791200-1314-11e9-9769-bcacc6d86a38.png)
Now if "Monitoring Instance" or "ServiceControl Instance" has to be upgraded there is a hyperlink called "UPGRADE TO Vx.x.x"
![image](https://user-images.githubusercontent.com/19533149/50812867-ad57d900-1314-11e9-84bd-92f4e934a2bf.png)
Because I'm already using "Azure Service Bus - Forwarding topology (Legacy)" it should be possible to automatically upgrade to the latest and greatest Azure Service Bus Transport.

I know it's possible to do it by hand, but I'm lazy and it's error prone if you have to manage multiple clients in DTAP environments ;-)

**Comment by JSCProjects** [comment]
For me yes, from my understanding this new transport is compatible with the legacy one. And there is no usecase for me to stay on the legacy one for servicecontrol and monitoring.

**Comment by SzymonPobiega** [comment]
Thanks @JSCProjects . I marked is to consideration for the next release but we need to internally first make sure that there are really no visible differences between legacy forwarding and new ASB transports as far as SC is concerned.

**Comment by JSCProjects** [comment]
Thanx!

**Comment by mikeminutillo** [comment]
Is issues covered by this https://github.com/Particular/ServiceControl/pull/2165 ?

**Comment by danielmarbach** [comment]
Closing based on @mikeminutillo comment. This is [available in 4.13](https://github.com/Particular/ServiceControl/releases/tag/4.13.0)
