### ISSUE TITLE
Decommisioned Endpoints

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1561]
Hello,

Does if an endpoint gets decommissioned on our servers how does servicecontrol respond?

Will the endpoint hang around forever in servicecontrol or eventually fall off from the database?

**Comment by WilliamBZA** [comment]
Currently in ServiceControl the endpoints hang around forever, there is no automatic cleanup process. Manual intervention is required in order to remove an endpoint.

In ServiceControl Monitoring, the endpoints hang around until ServiceControl Monitoring is restarted.

**Comment by TraGicCode** [comment]
What are your thoughts on a feature where servicecontrol can identify if no messages have come in within n number of days ( heartbeats and monitoring included ) it can mark the endpoint as possibly identified as a decommissioned endpoint allowing the user to confirm or delay this in servicepulse ? Also how would this work with auto scaling endpoints if this was something worth discussing?

**Comment by WilliamBZA** [comment]
There are a number of ways an endpoint appears in ServiceControl (I'm excluding monitoring from this for now):

* A heartbeat is sent to ServiceControl from the endpoint
* An audit message is sent to ServiceControl from the endpoint
* A failed message appears in ServiceControl (this one is actually a bit weird and a special case as it doesn't appear on all screens, and technically doesn't appear in the endpoints list)

If an endpoint is scaled out it will generate a new hostId and will appear as a new endpoint every time an audit message is sent from a new instance. Heartbeats might do the same (I'd have to check). In this scenario, I can see some real value in automatically cleaning up after a set period of time.

If an endpoint is not accidentally generating new HostIds, and it appears, then it's a bit harder to know when it's ok to remove the endpoint. This could be a decommissioned endpoint or a testing endpoint that is no longer required. Or it could be a system failure (unlikely for it to persist for long though).

Endpoints from failed messages will never be removed. These messages may be consequential and must retain all endpoint information related to them.

So my initial thoughts are: it would be difficult to know the difference between the first 2 scenarios. If we can tell whether or not an endpoint is scaled up and then down again, we could safely remove it. But if we're not able to tell them apart, we should really have a UI option within ServicePulse to allow users to manually remove them.

I'll push this internally and see if we can get something going.

**Comment by fourpastmidnight** [comment]
Or perhaps an API endpoint to remove decommissioned endpoints. (Although I suppose by definition, this would exist if the UI exposes such a feature since the UI communicates through the API anyway?) I, too, am interested in such a feature for our deployment scenario where, to achieve maximum uptime without the associated costs of blue/green deployments, we decommission the "old" server after a new deployment of the application.

**Comment by TraGicCode** [comment]
Closed by #1782
