### ISSUE TITLE
New-ServiceControlInstance should error out when connection string is passed with MSMQ Transport

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1566]
It looks like the **New-ServiceControlInstance** cmdlet allows the user to pass a connection string when the MSMQ Transport is specified ( as can also be seen by the comment on the parameter  https://github.com/Particular/ServiceControl/blob/66350628c0981efe73044c2b29b2967ba20c339d/src/ServiceControlInstaller.PowerShell/Cmdlets/ServiceControlInstances/NewServiceControlInstance.cs#L78 ). 

This causes a nasty problem that allows the user to get in a state in which since the queues didn't get created at install time ( because the user passed in a connection string ) the user is unable to correct this problem even after removing the connectionstring from the servicecontrol.exe.config.  They are left with no other option but to destroy the instance and recreate it.

My proposal is to simply add some validation that throws an error when the MSMQ transport is used and a connectionstring is passed to prevent the user the possibility of getting into this state.

**Comment by SzymonPobiega** [comment]
This is a left over from times when MSMQ just ignored the connection string.
