### ISSUE TITLE
New-ServiceControlInstance should not default to creating audit forwarding log queue

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1567]
When creating a new service control instance the user is given some sane defaults of not having an audit forwarding log  & error forwarding log created.

![image](https://user-images.githubusercontent.com/6224270/51517395-2872c200-1de0-11e9-8993-99762185c2a9.png)

Unfortunately, either from a bug or different defaults, when utilizing the *New-ServiceControlInstance* cmdlet the default is to create the audit forwarding log queue and strangely enough not the error forwarding log queue.

The powershell cmdlet should be made consistent with the GUI experience and default to not creating the error forwarding log and audit forwarding log queues.

**Comment by SzymonPobiega** [comment]
@TraGicCode I think the behavior of the PS reflects the old version of the UI. Thanks for catching this.
