### ISSUE TITLE
New-ServiceControlInstance: Possible rename of forwarding queue parameters

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1568]
When dealing with the creation of error & audit forwarding queues i noticed the names of the parameter refer to them as Log queues and contain no mention of the word forwarding.  I think this can be a little confusing to the user and should match the terminology from the documentation to prevent the user having to second guess themselves when working with these parameters.

https://github.com/Particular/ServiceControl/blob/66350628c0981efe73044c2b29b2967ba20c339d/src/ServiceControlInstaller.PowerShell/Cmdlets/ServiceControlInstances/NewServiceControlInstance.cs#L58-L64

I'm proposing

```
-AuditForwardingQueue
-ErrorForwardingQueue
```

**Comment by TraGicCode** [comment]
Hey @janovesk,

I understand what your are saying but the terminology used in the powershell cmdlet is completely different then the wpf application as can be shown here https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior .

Im hoping to bring some alignment between the 2 because wether it’s a website, wpf app, or powershell cmdlet the interfaces should be consistent and if you know one of the interfaces the terminology maps seamlessly between the others.

**Comment by fourpastmidnight** [comment]
I see what you're saying @TraGicCode. However, I agree with @janovesk. So really, the issue is that the documentation should be updated.

**Comment by fourpastmidnight** [comment]
It would also seem, that maybe perhaps the UI should be updated to?

Instead of _ERROR FORWARDING QUEUE NAME_ and _AUDIT FORWARDING QUEUE NAME_, perhaps it should be _ERROR FORWARDING LOG QUEUE NAME_ and _AUDIT FORWARDING LOG QUEUE NAME_?

**Comment by fourpastmidnight** [comment]
I submitted Issue 4346 up on docs.particular.net to address the issue with the documentation. However, there's still the matter of the UI.
