### ISSUE TITLE
Question: Why are monitoring transport types different between monitoring and regular instances?

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1579]
I noticed that the TransportType ( Monitoring/TransportType & ServiceControl/TransportType ) both use different types and assemblies.  For Example for the rabbitmq conventional routing topology below are the differences in the transport type setting.

Monitoring/Transport
-----
ServiceControl.Transports.RabbitMQ.ConventialRoutingTopologyRabbitMQTransport, ServiceControl.Transports.RabbitMQ

ServiceControl/TransportType
-----
ServiceControl.Transports.RabbitMQ.RabbitMQConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ

I bumped into this when automating monitoring instances via puppet and am curious as to why they are different.

**Comment by SzymonPobiega** [comment]
@TraGicCode this difference is a result of SC and Monitoring having slightly different needs when it comes to a transport abstractions (e.g. Monitoring needs to be able to query the length of the queue). In future releases we will be working on combining them into a single abstraction.

**Comment by TraGicCode** [comment]
Thanks @SzymonPobiega .
