### ISSUE TITLE
Install ServiceControl module into one of the paths in $env:PSModulePath

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/ServiceControl#1619]
Please update your installer so that the Service Control management PowerShell module is installed into one of the paths listed in `$env:PSModulePath` so that PowerShell's "auto-module loading" works. Otherwise, you force your users to specify the full path to the module manifest in order to import the module.

**Comment by DavidBoike** [comment]
@fourpastmidnight Thanks for the issue! I've flagged it as a possible feature, and our enhancement release process will take a look at it at some point.

**Comment by HEskandari** [comment]
@fourpastmidnight I have updated the installer to install the cmd-lets into the global modules so it is more accessible. 

It will be available in the next minor with a caveat: our installer has a bug that installs the module in the x86 folder of Program Files which makes it accessible only in PowerShell x86 shell. The installer will be updated as part of the next major version of ServiceControl (currently in the works).

**Comment by fourpastmidnight** [comment]
Sounds good. Thanks for fixing this and the installer (in the next major release).

**Comment by HEskandari** [comment]
Resolved by #2304
