### ISSUE TITLE
Allow ServiceControl to log to STDOUT

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/ServiceControl#1622]
When running ServiceControl as a console application (versus as a Windows Service), allow ServiceControl to log output to STDOUT. This would make ServiceControl more "container-friendly".

**Comment by fourpastmidnight** [comment]
OK, this is working already. Yay!

**Comment by fourpastmidnight** [comment]
OK, this is _NOT_ working. (Well, not anymore, as seen by running 3.7.0; I'm running 1.48 locally on my machine, which does log to STDOUT).

**Comment by fourpastmidnight** [comment]
OK, looking at the ServiceControl code in question, it appears it is set up to log to the console, but at some point, the configuration was changed to only log errors to the console (with an exception for RavenDb). But, still, I maintain that this is a step backward for containerization.

Perhaps the logging level could be specified via a command line switch and/or an app.config setting?

**Comment by fourpastmidnight** [comment]
Could this be due to the fact that the instance in the container isn't licensed? I haven't mounted a volume containing a license for ServiceControl to use just yet, as I'm just putting the final finishing touches on my container image, but the lack of console output was bothering me.

**Comment by SzymonPobiega** [comment]
@fourpastmidnight nope, the logging level is not dependent on license checking. I'll take a look at this and let you know of my findings.

**Comment by fourpastmidnight** [comment]
So, I meant to post this last night, but never hit the Comment button. Oops.

> Ah, I mis-read the code, only RavenDb errors are loged to the console. Everything else goes into the log files. 

Anyway, thanks @SzymonPobiega . That's the code I was looking through.

It's a shame that the logging level cannot be changed for the console, as I was saying above. For docker, it would be nice to log at the Warn or Info level to the console so you can run a command like `docker container logs svccontrol`, for example. Because now, if you run this command, you get the very helpful output:

```
Press Ctrl+C to exit
```

That's it. Nothing, nada, zilch. (Unless, of course, you have errors--but then you have other issues....)

**Comment by SzymonPobiega** [comment]
@fourpastmidnight OK, I don't follow right now. The default console logging level is `Info` which means all `Info`, `Warn` and `Error` message should be logged to both console and the file. At least this is how it is supposed to work.

**Comment by fourpastmidnight** [comment]
@SzymonPobiega OK, wow, that's what I thought should be happening. But then I thought you said only Error and above would log to the console (I missed _to the console **and**_)--so I misread what you said.

OK, so now that that's all cleared up: ServiceControl should log Info and above messages to the console _and_ to file. But, that appears to not be happening. I'm wondering if it has anything to do with how I invoked ServiceControl within my Docker container:

```powershell
Start-Process ServiceControl.exe "--serviceName=${env:SC_INSTANCE_NAME}", '--portable' -NoNewWindow -Wait
```

I have to use `--portable` to run it "stand-alone" (otherwise, ServiceControl balks and won't start. I don't know when that parameter was added, but it wasn't required back as far as 1.48.0) since Docker watches a single running process within the container--and once that process ends, the container shuts down. Also, by running ServiceControl standalone, it _should_ log to STDOUT so that I can run `docker container logs svccontrol` (as an example) to get the output from STDOUT.

But all I'm seeing is `Press Ctrl+C to exit`. That's it. Nothing else. Now, in the configuration file, I have `ServiceControl/LogLevel` set to `Warn`. So, for kicks, I restarted the container changing the logging level to `Info`. I do see `Info` level logs in the log file, but still nothing from STDOUT except `Press Ctrl+C to exit`.

Does ServiceControl log to STDOUT, or some other stream/file descriptor? (I.e., do I need to redirect something other than 1, e.g. `ServiceControl.exe --portable *>&1`) Also, I'm questioning whether I should use `Start-Process` or just use the `&` call operator.... However, testing locally, using either `Start-Process` or the `&` call operator worked locally (for 1.48--I don't have 3.7.0 installed on my local machine). I'll do some testing using th `&` operator--but last time I tried this, I couldn't get it to work from within my bootstrapper powershell script.

**Comment by fourpastmidnight** [comment]
OK, I ran the container in interactive mode and invoked PowerShell with and without the `&` call operator and without using `Start-Process`. In all cases, all that's ever printed to the console is `Press Ctrl+C to exit`, unless there's an unhandled exception (like, when I forget to set the container's hostname and ServiceControl can't find it's queues... 😉 ).

**Comment by SzymonPobiega** [comment]
Ok @fourpastmidnight . We'll investigate further.

**Comment by fourpastmidnight** [comment]
@SzymonPobiega OK, so the only "lab" machine I have available to me is a Windows Server 2012 R2 w/ Desktop Exp. VM (i.e. **not** Core). On this installation, I used the following command line to invoke ServiceControl:

```powershell
PS C:\ServiceControl\Instance> Start-Process ServiceControl.exe "--serviceName=Particular.ServiceControl.1", "--portable" -NoNewWindow -Wait
```

I am getting things logged to the console as I would expect. However, this is _*NOT*_ happening when running SerivceControl in a container based on a Windows Server 2019 LTSC Core installation.

So, unfortunately, that leaves several scenarios open for differences in behavior, with permutations including the following variables:

* [ ] Full OS vs. Core installation
* [ ] OS Version -- 2012 R2 vs. 2019 (I haven't tried Windows Server 2016, mostly because I want to use MSMQ as my transport since that's what our application is currently using and I'm trying to containerize the solution with as few code changes as possible; and MSMQ support just wasn't there in Server 2016.)
* [ ] Container vs. non-container.
* [ ] Running as an account that is a member of the `Administrators` local group vs. the default container user (`User Manager\Container Administrator`, IIRC).

Other than the logging output to the console, ServiceControl _appears_ to be running just fine. I'll see if I can't spin up a few local VMs (or even ones in Azure) with Windows Server Core 2012R2 and Windows Server 2019 (both Core and Full OS) and see if I can replicate what I'm seeing in my containerized ServiceControl instance to nail down what, specifically, is causing the difference in behavior--unless one of you already know, from the list above, what could cause this behavioral difference.

**Comment by fourpastmidnight** [comment]
OK, Azure doesn't seem to have a Windows Server 2012 R2 core image available (unless I didn't look hard enough). But, I spun up a Windows Server 2019 Full and Core VM and installed ServiceControl and ran it the way I'm running it in my container. In all cases, output was logged to the console.

When performing these tests, they were always done under my current account--and that means, as an Administrator. So now I need to create a user which would have very similar permissions as the `User Manager\Container Administrator` user that's the default user on Windows Server 2019 containers and see if that makes a difference.

The only other thing I can think of that would result in different behavior is whether or not ServiceControl is run at the console interactively vs. a non-interactive, batch-type job, which is typically how container processes would be executed (i.e. there's no user profile loaded)

**Comment by fourpastmidnight** [comment]
Just updated my docker image, changing my `Start-ServiceControl.ps1` script to not use `Start-Process` (especially using the `-NoNewWindow` parameter), and see if invoking the executable directly would change anything. Unfortunately, all I still get is `Press Ctrl+C to exit`.

At this point, the next two things to try are:
* Modifying the user rights for the `User Manager\Container Administrator` user (the default container user for Windows Server containers)
* Create a new user during container image creation and use that user to run Service Control

It may be just easier to create a new user--and probably a best practice(?).

I'm thinking that perhaps there's something with the user, some user missing right perhaps, or maybe even the fact that the `User Manager\Container Administrator` user may not have a (suitable?) user profile. (I believe that account is a Service Account, like `NT AUTHORITY\NETWORK SERVICE`, but with less privileges?)

**Comment by fourpastmidnight** [comment]
@SzymonPobiega I found the offending line in `LoggingConfigurator.cs`: [#85](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/LoggingConfigurator.cs#L85).

We're using the same code to determine whether or not an endpoint is running as a service or as a user in a console. The problem is, in a container (at least, for the default Winows container users `User Manager\Container Administrator`), the user is not an interactive user (as defined by `System.Environment.UserInteractive`), but obviously, the program is not being run as a service either. In the case of ServiceControl, then, the console logging rules are removed.

**Comment by SzymonPobiega** [comment]
@fourpastmidnight awesome job! ❤️

**Comment by SzymonPobiega** [comment]
@fourpastmidnight can you verify if https://github.com/Particular/ServiceControl/pull/1641 fixes the problem?

**Comment by fourpastmidnight** [comment]
I didn’t get a chance to try your changes today. I did review the changes you made, however. They’re exactly the changes I would’ve made. So, on the surface, LGTM. I’ll try to get a chance to run them tomorrow.

Sent from my Windows 10 phone

**Comment by fourpastmidnight** [comment]
@SzymonPobiega OK, I was able to get a Docker image created with the PR version of ServiceControl. Unfortunately, no dice. I'll try to take a look at the changes you made again--but it LGTM..., so, I'm confused. 😕

**Comment by TraGicCode** [comment]
@SzymonPobiega i think i'm running into the same issue that @fourpastmidnight and it's really frustrating.

I'm writing a puppet bolt plan to automate the re-importing of failed audit/error messages in a hands off fashion.  What i'm noticing is that puppet bolt is not see any console messages going to stdout or stderr.  Is this something that can get looked into?

**Comment by SzymonPobiega** [comment]
@TraGicCode can you take a look at https://github.com/Particular/ServiceControl/pull/1641 and see if it solves it works for you? We'll also investigate on our side.

**Comment by TraGicCode** [comment]
@SzymonPobiega 

I took the changes in that PR and set printToConsole on the LoggingSettings class to true and it's now going to stdout like expected as shown below.


![image](https://user-images.githubusercontent.com/6224270/80553346-23130880-898f-11ea-8f1c-2f798895ae44.png)

**Comment by SzymonPobiega** [comment]
Awesome. Thanks for giving it a try @TraGicCode . We'll make sure it gets released soon.

**Comment by TraGicCode** [comment]
Hey @SzymonPobiega ,

Awesome i look forwarding to the fix!

**Comment by WilliamBZA** [comment]
This fix will be released in ServiceControl version 4.9.0 (expect it early next week)

**Comment by ramonsmits** [comment]
@fourpastmidnight @TraGicCode You can already enable console logging in any instance by providing a custom `NLog.config` file as documented here:

https://docs.particular.net/servicecontrol/logging#customize-logging

This fully overrides logging configuration by SC. You can do any formatting and use any target you would want.

**Comment by johnsimons** [comment]
@ramonsmits @danielmarbach From what I read above, this seems to have been fixed, can we close it?

**Comment by ramonsmits** [comment]
AFAIK logging is working as expected with all container images
