### ISSUE TITLE
SerivceControl API doesn't show the correct licensing information

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/ServiceControl#1624]
I read the licensing documentation, but I'm unclear as to what, exactly, is supported.

The documentation says that there is a configuration-file setting (`NServiceBus/LicensePath`). But it also mentions that "Instance Licensing is deprecated in version 1.18 and above." So the question is, is using the configuration setting mentioned "per instance" licensing?

I'm interested in getting a ServiceControl instance running in a container. To that end, I would like to have an image which has a ServiceControl instance installed, though unlicensed. The idea being that when the container is started, a user would provide a valid license file, e.g. `docker run -d -e ScLicenseFile="C:\path\to\license.xml" my-docker-registry/servicecontrol:latest`. Is this possible?

(Aside: I didn't show any volume mapping in the docker command above, though, that would clearly be required (unless you don't care about the RavenDB getting blown away every time the container stops)).

**Comment by fourpastmidnight** [comment]
Looking at the NServiceBus documentation, it appears that this is a valid way to "License" an endpoint, and so it would seem this _should_ be valid for ServiceControl. I'll test, and if no one answers, I'll relay my experience.

**Comment by fourpastmidnight** [comment]
This seems to not be working (see #1623). This would be hugely beneficial in a Docker-ized environment, especially if SC is ever made to be x-plat.

**Comment by fourpastmidnight** [comment]
OK, so, I upped the logging level to Info trying to determine why ServiceControl doesn't seem to be logging to the console. Anyway, on a whim, I decided to peer into the log files and I noticed that ServiceControl logged that it found the license file via the `app.config` setting:

```text
2019-04-26 14:50:24.0603|1|Info|NServiceBus.LicenseManager|Selected active license from app config 'NServiceBus/LicensePath' setting
License Expiration: 2019-06-28
```

BUT, when I query the API, this is the output that I get:

```text
PS C:\WINDOWS\system32> Invoke-RestMethod -Method 'Get' -Header @{ Accept = 'application/json' } -Uri 'http://172.18.117.152:33333/api/license'

trial_license                 : True
edition                       :
registered_to                 :
upgrade_protection_expiration :
expiration_date               : 5/10/2019 00:00:00
status                        : valid
license_type                  : Trial
instance_name                 : Particular.ServiceControl.1
license_status                : Valid
```

Therefore, I feel this is a legitimate issue.

**Comment by HEskandari** [comment]
@fourpastmidnight Did I understand correctly that the version of ServiceControl you are using is 1.18?

**Comment by fourpastmidnight** [comment]
No, sorry. In the container, I’m running 3.7.0.

Sent from my Windows 10 phone

**Comment by HEskandari** [comment]
@fourpastmidnight I just tried to reproduce the issue as you explain (factoring out the docker container) using ServiceControl 3.7.0. I can see that when loading the license through the ServiceControl.exe.config, I get the following WARN log:

>2019-04-30 11:23:09.0025|1|Warn|NServiceBus.LicenseManager|Reading license information from the app config file has been deprecated and will be removed in version 8.0. See the documentation for more details.

Despite the Warning, I can also see the following logs further down (:

```
License not found in C:\Program Files (x86)\Particular Software\Particular.ServiceControl\license.xml
License not found in %AppData%\Local\ParticularSoftware\license.xml
License not found in C:\ProgramData\ParticularSoftware\license.xml
License not found in HKEY_CURRENT_USER\SOFTWARE\ParticularSoftware
License not found in HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware
License not found in C:\Program Files (x86)\Particular Software\Particular.ServiceControl\License\License.xml
License not found in C:\Program Files (x86)\Particular Software\Particular.ServiceControl\ParticularPlatformLicense.xml
No valid license could be found. Falling back to trial license with start date '2018-11-10'.
```

I have also verified the trial license being used using the `/api/license` endpoint, the same as you did.

So at this point, although I don't think loading the license file through the ServiceControl.exe.config is recommended (as it will be removed once SC is upgraded to use NServiceBus 8), I think this might be a bug.

**Comment by fourpastmidnight** [comment]
@HEskandari Ah, I missed that warning log message, which came after the message saying that the licensing information has been found.

Well, let me be one of the first to say that deprecating that way of licensing an instance of ServiceControl (or, even an NSB Endpoint) is a _HUGE_ step backward for containerization. How do you expect people to license their endpoints (or ServiceControl) when, say, running in a Linux-based container, where putting licensing information in the Windows Registry plainly doesn't make any sense?

The ability to add an entry into a configuration file from which the endpoint/ServiceControl can read to obtain it's licensing information is very DevOps friendly. Or better yet, specify an environment variable which contains the path to the license file (or even the license file information itself--if that information is not considered sensitive). The Windows Registry, not so much.

Luckily, I think I'll still be running Windows Containers for a while. But even if that remains true, using the Windows Registry is not very DevOps nor container-friendly at all.

**Comment by WilliamBZA** [comment]
> deprecating that way of licensing an instance of ServiceControl (or, even an NSB Endpoint) is a HUGE step backward for containerization

Yet another thing we are actively working on, and yet more reason for you to send us a mail so that we can help you properly instead of dealing with so many disparate issues when we could simply provide you with internal builds as an early beta tester.

**Comment by fourpastmidnight** [comment]
@WilliamBZA  Just sent than support request!! I'm looking forward to speaking with Particular about this!
