### ISSUE TITLE
Starting in maintenance mode requires elevated privileges

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1643]
Starting an instance in maintenance mode requires elevated privileges due to an incorrect URLACL.

### Who's affected

All customers running a ServiceControl instance with non-elevated account. This only affects running the instance in maintenance mode. Applying the fix is not urgent.

### Symptoms

Attempting to start a ServiceControl instance in maintenance mode fails with a `System.Net.HttpListenerException` exception.

### Analysis

When we install the instance we create a URLACL for the maintenance port that looks like `http://localhost:PORT/`. When we give this address to the embedded RavenDB in maintenance mode and tell it to run it's own web server, it converts into an address that looks like this `http://+:PORT/`. Unfortunately, a URLACL cannot be applied unless the address being requested matches the one in the URLACL exactly. We are creating the wrong URLACL.

**Comment by mikeminutillo** [comment]
Until this is fixed, the workaround is to add a URLACL for the correct address. Something like this:

> netsh http add urlacl url=http://+:PORT/ user=BUILTIN\Users

**Comment by kbaley** [comment]
Relabeled as an improvement as there is a workaround and this doesn't affect the correctness of ServiceControl.

**Comment by tmasternak** [comment]
Done in #2476
