### ISSUE TITLE
Error Installing Service Control/Pulse/Inisghts on Azure VM

### ISSUE THREAD

**Issue by cpear** [Particular/ServiceControl#1714]
When you download the Platform Installer for Service Control/Pulse/Insights and try to run it on a VM in Azure it fails. It appears their are restrictions (maybe windows firewall) that block the installer files that are pulled from AWS.

If you copy the url listed in the error log (the AWS url) and paste it into a browser window you can download it that way by clicking through the security prompts that appear.

**Comment by dbelcham** [comment]
Thanks @cpear We've added this to the backlog of items to address in a future maintenance release.

**Comment by DavidBoike** [comment]
Given that we [no longer maintain the platform installer](https://docs.particular.net/platform/installer/) I'm guessing this issue can probably be closed.
