### ISSUE TITLE
SCMU 4.0.1 fails to create SC instance for ASB transport

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/ServiceControl#1727]
Error:

![image](https://user-images.githubusercontent.com/1309622/62806055-00faf280-baaf-11e9-9f47-99723b4d8ac6.png)

Settings (w/o connection string):

![image](https://user-images.githubusercontent.com/1309622/62806083-140dc280-baaf-11e9-8e5e-2d5760704a53.png)

**Comment by martinosk** [comment]
We're also affected by this. Here is a bit of the error message, to make this issue googleable:
ServiceControl.exe threw an error when creating queues. This typically indicates a configuration error. The error output from ServiceControl.exe was:

Unhandled Exception: System.MissingMethodException: Method not found: 'void Newtonsoft.Json.Converters.StringEnumConverters.set_NamingStrategy

**Comment by danielmarbach** [comment]
Fixed. Will go out with 4.1
