### ISSUE TITLE
ServiceControl Monitoring too Aggressive on Azure Service Bus

### ISSUE THREAD

**Issue by NArnott** [Particular/ServiceControl#1755]
I noticed while trying out the Service Control Monitoring on Azure Service Bus that it produces over 100 requests a second. It looks like there is a 200 ms interval checking for queue lengths. It would be nice to be able to control that as to control costs on those instances.

**Comment by SeanFeldman** [comment]
@NArnott based on our previous interaction, did you mean to title it as "ServiceControl Monitoring queue length check interval is too aggressive"? I'm assuming as it would not matter where SC.Monitoring or endpoints are running. Thank you.

**Comment by NArnott** [comment]
@SeanFeldman Ya, basically. I didn't want to get too technical. Basically, when SC Monitoring is running, without ANY endpoints or SC/SC Audit running, the load on the ASB instance is still very high.
