### ISSUE TITLE
Remove confusion and provide version deprecated in for MaximumMessageThroughputPerSecond

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1768]
When reading the documentation about ServiceControl/MaximumMessageThroughputPerSecond it says

> This setting is applicable in version 1.48.0 and below

Then below that it says 

> This setting was introduced in version 1.5

When looking through the code i see this is no longer existing.  Can the documentation be updated to remove the confusing statements above and also explain which version it got deprecated in?

**Comment by andreasohlund** [comment]
I've raised https://github.com/Particular/docs.particular.net/pull/4519 to address this.
