### ISSUE TITLE
Are these appsettings used for servicecontrol audit instances?

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1769]
Are the following appsettings used for servicecontrol audit instances?  I would think so but the documentation is missing them.

https://docs.particular.net/servicecontrol/audit-instances/creating-config-file

- Raven/IndexStoragePath
- Raven/Esent/LogsPath
- ServiceControl/LogPath

**Comment by andreasohlund** [comment]
Good catch,  they are still there

>Raven/IndexStoragePath
>Raven/Esent/LogsPath


https://github.com/Particular/ServiceControl/blob/master/src/ServiceControlInstaller.Engine/Configuration/ServiceControl/AppConfig.cs#L140


>ServiceControl/LogPath

https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Audit/Infrastructure/Settings/LoggingSettings.cs#L14

I've raised https://github.com/Particular/docs.particular.net/pull/4520 to address this, can you take a look?

**Comment by TraGicCode** [comment]
Hey @andreasohlund ,

If you want i can take create the PR to fix this.

**Comment by andreasohlund** [comment]
Already opened
https://github.com/Particular/docs.particular.net/pull/4520 🤗

**Comment by mikeminutillo** [comment]
@TraGicCode The Raven ones will get picked up by RavenDB automatically. 

You need to use `ServiceControl.Audit/LogPath`.

Added here https://github.com/Particular/docs.particular.net/commit/6597fd59ef26358aeb844cf49301f894a8c90a79

Should show up on the published docs site soon
