### ISSUE TITLE
Add ability to override service name or endpoint name

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1774]
When creating a SC instance the instance name is used as a command line argument:

When using `Particular.SC.ASB`
```
"C:\Program Files (x86)\Particular Software\Particular.SC.ASB\ServiceControl.exe" --serviceName=Particular.SC.ASB
```

This results in SC to use the queue `Particular.SC.ASB` too. If customers want to use a standard queue for ServiceControl like `Particular.ServiceControl` but want to name their instance differently then currently that is not possible.

## Workaround:

**Warning:** This is incompatible with upgrading instances via SCMU!

1. Install a SC instance via SCMU
2. Go to path of the SC instance
3. Run `ServiceControl.exe" --serviceName=Particular.ServiceControl setup`
4. Edit Windows Service entry via sc.exe and modify `binPath=` or edit the entry via the Windows Registry editor via path `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services`

**Comment by ramonsmits** [comment]
@WilliamBZA Specific reason why support was not added to SCMU?

**Comment by WilliamBZA** [comment]
I assumed this was more of an edge-case setting rather than something that should always be presented as configurable. If you think otherwise a new issue can be created to expose the setting via SCMU

**Comment by ramonsmits** [comment]
@WilliamBZA now you make me doubt it... I do think its advanced but you got me on another idea
