### ISSUE TITLE
ServiceControl does not support Azure File Storage

### ISSUE THREAD

**Issue by fmshk97** [Particular/ServiceControl#1788]
I created a Azure File Storage and mounted it as a storage drive on my computer. However, while creating a ServiceControl instance on the same machine, when I pass the location of this storage drive as installation path for ServiceControl instance, I get the below error from ServiceControl -

```
VERBOSE: Installing Service Control instance...
The log path does not go to a supported drive
```

**Comment by ramonsmits** [comment]
@fmshk97 Azure File Storage isn't suitable for database storage as its SMB based. ServiceControl requires storage that is optimized for high I/O.
