### ISSUE TITLE
Paging links use route template without replacing route variables

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#1808]
When messages for a specific endpoint are queried via `/api/endpoints/{endpoint}/messages/` the endpoint variable is not replaced.

### Symptoms

ServiceInsight is unable to correctly navigate message view pages when viewing an individual endpoint.

### Who's affected

* All users using ServiceControl 4.4.0 or greater

### Root Cause

We are using the template, not taking into consideration variables, resulting in broken next/prev links for the endpoint:

https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/WebApi/Negotiator.cs#L108

**Comment by mikeminutillo** [comment]
Corresponding issue in ServiceInsight repo https://github.com/Particular/ServiceInsight/issues/844
