### ISSUE TITLE
ServiceControl.Monitoring Runing Fail

### ISSUE THREAD

**Issue by junbao520** [Particular/ServiceControl#1830]
I Change the config
   <add key="Monitoring/TransportType" value="NServiceBus.RabbitMQTransport,NServiceBus.Transport.RabbitMQ" />

then I run ServiceControl.Monitoring  project ,it make a error:

System.InvalidOperationException: A routing topology must be configured with one of the 'EndpointConfiguration.UseTransport<RabbitMQTransport>().UseXXXXRoutingTopology()` methods.

**Comment by WojcikMike** [comment]
Hi @junbao520 thanks for raising the issue. First of all I moved it to ServiceControl repository as this is the one that you write about.

Can you explain what are you trying to do? If you are running an installed ServiceControl Monitoring instance you should be using ServiceControl Management to create new instance using Rabbit client. 

If you are trying to run ServiceControl.Monitoring from the code, copy dll's generated by ServiceControl.Monitoring.Transports (the one for Rabbit) into directory with ServiceControl.Monitoring and then run it.

**Comment by SzymonPobiega** [comment]
We could not reproduce this behavior while looking up for things to fix in the upcoming ServiceControl/ServicePulse release.
