### ISSUE TITLE
Add eventlogitems to /api path

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1838]
Looks like `/api/eventlogitems` is missing from the root `/api` endpoint

**Comment by mauroservienti** [comment]
Hi @TraGicCode,

I'm not familiar with the ServiceControl code-base, so I'm not sure if #1839 is enough. Let's wait for a reviewer.

**Comment by mauroservienti** [comment]
@TraGicCode we just merged #1839, it'll be released with the next release.
