### ISSUE TITLE
How to import failed audit messages in servicecontrol v4.x

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1952]
Previously, servicecontrol only consisted of 1 instance that handled both audit and error messages.  When an import failed we simply went to the 1 servicecontrol instance and imported failed audit or error messages based on the following documentation ( https://docs.particular.net/servicecontrol/import-failed-messages ).

In v4 there was a split of the audit instance from the error instance.  It's unclear from the documentation ( https://docs.particular.net/servicecontrol/import-failed-messages ) Which instance to use on failed audit imports.  Is it the audit instance or does the error instance still handle both failed audits and imports?  Can the documentation be further clarified with examples OR more detail?

**Comment by danielmarbach** [comment]
Michael,

With the new changes the error instance is no longer responsible to manage audit documents anymore. So import of failed audits should be done on the audit instance. I will see what I can do to further clarify the documentation sections you mentioned. Thank you very much for this helpful input!
