### ISSUE TITLE
Bug: Trailing spaces in "Name" can result in hang or otherwise result in trailing period characters in name / window service name for error and audit instances name

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1971]
Trailing spaces in "Name" field can result in a hang of the SCMU or results in trailing period characters in name / window service name for error and audit instances name.

Any data entered in the name field should be trimmed of trailing whitespace or have the trailing whitespace excluded.

**Comment by mikeminutillo** [comment]
This issue has been released in 4.32.1. Details in [the announcement](https://discuss.particular.net/t/servicecontrol-4-32-1-patch-release-available/3640).
