### ISSUE TITLE
Questions on how servicecontrol is installing the license when done through the UI

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2014]
Hello,

I'm currently the maintainer of the puppet module that helps users automate the installation and configuration of servicecontrol ( https://forge.puppet.com/tragiccode/nservicebusservicecontrol ) using the configuration management tool called puppet.

The module has the capability of installing the NServiceBus license into the registry automatically.  Generally, puppet should undo any manual changes made by users to the system on every puppet run ( typically 30 min ) to put things back into the desired state.  

Unfortunately, When a user goes into the service control management interface and uploads the license file servicecontrol does 2 things under the hood:

1. Installs it into the machine registry
2. Places a copy in a file at c:\programdata\particularsoftware\license.xml

Unfortunately, the next time puppet run it updates the key in the registry but not the file on the file system ( since it's not documented in the servicecontrol docs ).  The registry key is unfortunately ignored because servicecontrol gives precedence to the license on the filesystem.  

**Questions**

Does servicecontrol really need to store the license in 2 places on the computer ( the registry and the file system ) ?

There is no documentation about servicecontrol looking in c:\programdata\particularsoftware in the servicecontrol license documentation  https://docs.particular.net/servicecontrol/license ( it's documented under the section on options for installing a license for deployed nservicebus endpoints https://docs.particular.net/nservicebus/licensing/ ).  Can this be updated/added?  

Is it expected that the ability to pick up the license file on the filesystem ( c:\programdata\particularsoftware\license.xml ) will be the recommended way going forward for future servicecontrol updates?

**Comment by mikeminutillo** [comment]
Thanks for bringing this to our attention @TraGicCode.

I have [raised a PR](https://github.com/Particular/docs.particular.net/pull/4843) to inlcude both locations in our documentation. The original intent was to support backward compatibility as older versions of ServiceControl would not know to check that location in the file system. We should probably look at how long ago that change was made. It may be appropriate to turn off the registry check in the next ServiceControl version.

Having said that, ServiceControl will pick the "best" license file it can find. So if there are different licenses in the file system and the registry, and one of them is expired, it should pick the other one.

That puppet module looks really cool by the way :)

**Comment by TraGicCode** [comment]
Thanks for this clarification and updating of docs. I’ll update things on my end to simply update in both places until the registry portion gets removed in the future.

**Comment by TraGicCode** [comment]
Closed by Particular/docs.particular.net#4843
