### ISSUE TITLE
Log to console no longer working

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#2017]
Copied from https://github.com/Particular/ServiceControl/pull/2002#issuecomment-631172332

> Hey @WilliamBZA ,
> 
> At this point i don't think it works with docker as it looks like things are worse.  
> 
> I got the release with the fix ( 4.9.0) and i see nothing being reported in stdout.  I also no longer see anything printing to my powershell console when i run servicecontrol fior audit/error import. 
> 
> Before
> 
> ![image](https://user-images.githubusercontent.com/6224270/82393292-9ac2d900-9a0b-11ea-96d8-2626f957d2b2.png)
> 
> 
> After
> 
> ![image](https://user-images.githubusercontent.com/6224270/82393439-f9885280-9a0b-11ea-9371-f78a46aa0804.png)
> 
> 
> I tried adding the --portable flag and still saw nothing

**Comment by tmasternak** [comment]
The changes have been reverted. The remaining part is covered  in https://github.com/Particular/ServiceControl/issues/2175
