### ISSUE TITLE
Add ability to customize license cache time

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2022]
Looking at the code here ( https://github.com/Particular/ServiceControl/blob/1aab5a37eec230fb63cf99167ae00445a2006202/src/ServiceControl/Licensing/LicenseCheckFeature.cs#L32-L40 ) it looks like the license cache is updated every 8 hours.  It would be a simple and nice feature if this was fully customizable for the user.

**Comment by danielmarbach** [comment]
@TraGicCode would it be possible to give a bit more information why you think making this value configurable would help the user and in what way?

**Comment by TraGicCode** [comment]
Hey @danielmarbach ,

My initial thoughts was being able to update the license in a less intrusive way ( service restart ) and see the changes reflect relatively quickly for our change control process. That being said , I think the current behavior is fine and a service restart dows makes the most sense.  Closing this as we will add that to our code when we change the license on the machine.

Thanks!

**Comment by HEskandari** [comment]
@TraGicCode Just to be clear, if you update the license and do not restart the services, it will eventually catch up. The stale/expired/old license will not impact the execution of the service in anyway.
