### ISSUE TITLE
Failed message group stuck in retrying

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2040]
![image](https://user-images.githubusercontent.com/6224270/83651874-9526d080-a57f-11ea-8d2d-7c5d6961a148.png)

ServicePulse: 1.23.0
ServiceControl: 4.4.1

Any idea on how to get this failed message group that is stuck to go away?

**Comment by dvdstelt** [comment]
@TraGicCode We recently made some improvements to ServiceControl, possibly related to your issue. Would it be possible to upgrade and see if that helps?

**Comment by TraGicCode** [comment]
> @TraGicCode We recently made some improvements to ServiceControl, possibly related to your issue. Would it be possible to upgrade and see if that helps?

Hey David,

Once #2039 gets fixed we can upgrade to the latest.  Do you know what version this was fixed in?



> @TraGicCode We recently made some improvements to ServiceControl, possibly related to your issue. Would it be possible to upgrade and see if that helps?

**Comment by dvdstelt** [comment]
It's Dennis, but that's okay ;-)

It was possibly fixed in [4.10](https://github.com/Particular/ServiceControl/releases/tag/4.10.0). And #2039 is planned to be released on Monday if all goes well.

**Comment by dvdstelt** [comment]
I'll close this issue for now, but let us know if it's still a problem.
