### ISSUE TITLE
Seeing "ghost" failed message groups after messages have been archived

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2089]
Hello,

Currently we see the following failed message group

![image](https://user-images.githubusercontent.com/6224270/88828628-1de17780-d191-11ea-89cf-93fbd2672704.png)

Yet when you click it there it's empty ( Most likely because it got archived )

![image](https://user-images.githubusercontent.com/6224270/88828685-35206500-d191-11ea-9d79-36412b73bc68.png)

**Comment by timbussmann** [comment]
hey @TraGicCode 

what version of ServicePulse are you using? Are you able to reproduce this behavior reliably?

**Comment by TraGicCode** [comment]
Hey @timbussmann ,

We are on the following versions of servicepulse and servicecontrol

**ServicePulse** 
v1.25.4 

**ServiceControl** 
v4.10.2


> Are you able to reproduce this behavior reliably?

So...i went to look to see if i could see the failed message group again and it looks like it's gone.  Is there some eventually consistent cleanup process that can cause this to happen?

**Comment by timbussmann** [comment]
how long was this message group visible? There could definitely be some index that took a long time to update?

**Comment by TraGicCode** [comment]
Hey @timbussmann ,

Unfortunately i don't know.  I can keep an eye on this metric and report back here when it happens again.

**Comment by timbussmann** [comment]
sure, please do 👍

**Comment by timbussmann** [comment]
I'll close this case for now but please just reopen it in case you see this happening again.
