### ISSUE TITLE
Configurable naming of the shared Azure Service Bus topic (bundle-1)

### ISSUE THREAD

**Issue by pihalve** [Particular/ServiceControl#2137]
I would like to suggest making it possible to configure the name of the shared topic (bundle-1) when using Service Control with Azure Service Bus transport. This name is configurable in other endpoints, so I think it makes good sense to also have it configurable in Service Control, so it doesn't auto-create a topic called bundle-1 when all other endpoints may have been configured to use e.g. tst-bundle-1 (or whatever name makes sense in the given situation.)

**Comment by boblangley** [comment]
@pihalve Thank you for the request. We will update this issue when the status changes.

**Comment by SzymonPobiega** [comment]
This has been fixed in #2153. We will be releasing a new version of ServiceControl that includes this fix soon.

**Comment by SzymonPobiega** [comment]
@pihalve Let me close this issue now so that we can generate release notes. The fix will be released in 4.13.0 early next week.

**Comment by SzymonPobiega** [comment]
Hi @pihalve . I've just pushed the latest version that contains this fix.
