### ISSUE TITLE
!Disable with ServiceControl.Audit throws ArgumentException when creating new instance

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#2197]
`!disable` [is supported on the management UI](https://github.com/Particular/ServiceControl/blob/bf791cda005c210695c28c82005cd98e7b550af4/src/ServiceControlInstaller.Engine/Validation/QueueNameValidator.cs#L110) to be able to setup an instance that does not ingest. Unfortunately, this seems broken now. The following exception is raised

https://github.com/SzymonPobiega/NServiceBus.Raw/blob/c65bdb7f1967beb42304ecb18af655d9cb66b21f/src/NServiceBus.Raw/RawEndpointConfiguration.cs#L178

It seems that we are trying to start NSB.Raw even though we should not. 

The problem does not exist in the ServiceControl primary instance, only in the audit instance. Unfortunately, that is where it is probably most crucial to have giving our guidance for multi-instance scenarios.

````
ISSUES ADDING INSTANCE:
Could not add new instance because of the following errors:
ServiceControl.Audit.exe threw an error when creating queues. This typically indicates a configuration error. The error output from ServiceControl.Audit.exe was:
 
Unhandled Exception: System.ArgumentException: Endpoint name must not be empty
Parameter name: endpointName
   at NServiceBus.Raw.RawEndpointConfiguration.ValidateEndpointName(String endpointName)
   at NServiceBus.Raw.RawEndpointConfiguration..ctor(String endpointName, Func`3 onMessage, String poisonMessageQueue)
   at NServiceBus.Raw.RawEndpointConfiguration.Create(String endpointName, Func`3 onMessage, String poisonMessageQueue)
   at ServiceControl.Audit.Infrastructure.RawEndpointFactory.CreateAuditIngestor(String name, ... 
Please verify the details or contact support.
````

Interestingly when I uses the latest releases and start the audit instance directly with `!disable` it works. It seems to be a combination of SCMU and ServiceControl Audit.

it seems the problem got introduced with 4.7 via

https://github.com/Particular/ServiceControl/commit/3b7e9c55ba9e91e57478aa172d44fb8c1b567253

Because even when IngestAuditMessages is set to false we will attempt to create the audit queue which is `null`

```
            // settings.AuditQueue is null
            var config = factory.CreateAuditIngestor(settings.AuditQueue, (context, dispatcher) => Task.CompletedTask);

            if (settings.SkipQueueCreation)
            {
                log.Info("Skipping queue creation");
            }
            else
            {
                var additionalQueues = new List<string>
                {
                    $"{settings.ServiceName}.Errors"
                };
                if (settings.ForwardAuditMessages && settings.AuditLogQueue != null)
                {
                    additionalQueues.Add(settings.AuditLogQueue);
                }
                config.AutoCreateQueues(additionalQueues.ToArray(), username);
            }

            // throws the ArgumentException due to the audit queue being null
            //No need to start the raw endpoint to create queues
            await RawEndpoint.Create(config).ConfigureAwait(false);
```

I guess the question is if there is a way to create/setup an instance that has the audit queue set `!disable` while still having NSB Raw creating the other queues (audit log queue could also be null but that is already guarded against). Or is it better to assume when you have `!disable` also don't want the audit error queue and the log queue being created (I'm leaning towards this)

**Comment by timbussmann** [comment]
closing this as fixed in version 4.14.2
