### ISSUE TITLE
Sort on time_sent and direction asc doesn't work for every endpoint

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServiceControl#2201]
In serviceinsight it is possible to sort on time_sent but not every endpoint returns messages.
I think it's related to endpoints who have archived messages.

**Comment by WilliamBZA** [comment]
Is this on a single instance of ServiceControl Audit?

**Comment by JSCProjects** [comment]
Yes! Still did't got any time to multiple instances.

**Comment by WilliamBZA** [comment]
Archived failed messages or expired audit messages?

**Comment by WilliamBZA** [comment]
I'm struggling to reproduce this.

* I tried regular expired messages, they simply get cleaned up and don't return messages to be sorted.
* I also tried archived failed messages, they still show in SI and get sorted as expected.

When all messages for an endpoint are removed, the endpoint is also removed so I am not sure that it's related to archived messages.

**Comment by WilliamBZA** [comment]
Can you post the service insight network logs here?

**Comment by WilliamBZA** [comment]
Closing for now. If you have this happen again please capture the insight network logs and share them so we can track the requests happening.
