### ISSUE TITLE
ServiceControl license cache not refreshing after 8 hours

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2253]
Hello,

Our infrastructure team noticed they had updated the servicecontrol license but after the 8 hour cache ( that exists within the codebase ) the license was reflected in the servicepulse web application.  A simple restart of the servicecontrol service caused the new license to be picked up along with the servicepulse web application showing the license was no longer expired.

/cc @bluetex

**Comment by adamralph** [comment]
Hi @TraGicCode, I'm afraid I'm having trouble understanding what the problem is. Are you saying that the new license isn't being picked up by either ServiceControl or ServicePulse as you would expect it to?

**Comment by TraGicCode** [comment]
Hey @adamralph ,

there is supposed to be a license cache in servicecontrol in which after 8 hours it will pick up the new license if one was installed without the need to restart it.  We noticed that days after the installation of the new license servicepulse started showing the expired license message.  A simple restart of servicecontrol caused servicepulse to begin working again and utilizing the new license file on disk.  It appeared from our side that the 8 hour cache that is baked into servicecontrol was not behaving correctly.

**Comment by danielmarbach** [comment]
@TraGicCode Did you happen to have DEBUG log level on at that time? If yes could you check if you saw the `Refreshing ActiveLicense` in the log statements?

Could you also verify if the `LicenseCheckFeature` is active in the diagnostics file? Furthermore is there any `Unhandled error while refreshing the license.` entry available in the log files that would indicate problems with refreshing the license?

**Comment by TraGicCode** [comment]
Hey,

I'm going to close this.  I found this in the logs.  Our infrastructure team is in the process of moving from puppet to ansible so i'm going to assume there was a bug on our side somewhere

![image](https://user-images.githubusercontent.com/6224270/98011530-96be2400-1dbd-11eb-910f-f12e5fbef9ad.png)
