### ISSUE TITLE
Launching SCMU in a closed private network results in a startup failure

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2269]
Launching SCMU in a closed private network results in a startup failure. This likely is because a version check of somekind is performed and SCMU not gracefully handles the situation where outbound connections are not allowed.

The following failure is shown:

![image](https://user-images.githubusercontent.com/152998/98704536-0e232300-237d-11eb-8e44-fad3998e8d35.png)

**Comment by WilliamBZA** [comment]
The same as https://github.com/Particular/KeepTheLightsOn/issues/621?

**Comment by ramonsmits** [comment]
Closing in favor of https://github.com/Particular/ServiceControl/issues/2240
