### ISSUE TITLE
RavenDB v3.5 goes out of support 31 December 2020

### ISSUE THREAD

**Issue by antmeehan** [Particular/ServiceControl#2295]
Hi,

Are there plans for migrating to a later version of RavenDB? The perf improvements from v3.5 to v4.2 would be great improvement on their own 😄 

Thanks,

Ant.

**Comment by janovesk** [comment]
Hi, @antmeehan! 

First, we have the support thing covered commercially. So it's not like it falls off a cliff at January 1st :)

But, yes. We're working on it moving to a newer version of Raven. Performance is one thing, but it also unlocks some other interesting abilities for us, like ServiceControl running on Linux etc.

So, can't give you an exact timeline, but things will happen :)

**Comment by antmeehan** [comment]
Awesome thanks for the response.
