### ISSUE TITLE
New-ServiceControlAuditInstance fails after upgrade to 4.15

### ISSUE THREAD

**Issue by barrit** [Particular/ServiceControl#2381]
First, I create the Service Control instance. this works well.
Creating the Audit instance however, throws the following error:

`New-ServiceControlAuditInstance : Failed to retrieve release date for new version`

I checked the release notes of 4.15
Is it possible that some of the the changes in [this commit](https://github.com/Particular/ServiceControl/commit/36e55b35e479090c8a93aac6590c3afe7e0786dd#diff-eba1b0cd16ebc1a9437ea217e7a181648f9dcb971f071b7a7b0a35959aaa8809) have to be applied on the [audit instance cmdlets](https://github.com/Particular/ServiceControl/blob/36e55b35e479090c8a93aac6590c3afe7e0786dd/src/ServiceControlInstaller.PowerShell/Cmdlets/AuditInstances/NewServiceControlAuditInstance.cs#L148) as well?

**Comment by barrit** [comment]
Rolled back to 4.14 which does not have the PowerShell Module in a subfolder and everything works fine again.

**Comment by timbussmann** [comment]
I can reproduce and confirm this as not working, definitely seems to be a bug that has been added with 4.15

**Comment by Cogax** [comment]
I do also have this issue after upgrading.
This is the Error:
```
New-ServiceControlAuditInstance : Failed to retrieve release date for new
version
At C:\Users\**\**\ServiceControl\PowerShel
l\ServiceControlManagement.ps1:139 char:12
+     return New-ServiceControlAuditInstance `
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ServiceControlAuditInstan
   ce], Exception
    + FullyQualifiedErrorId : ServiceControlInstaller.PowerShell.NewServiceCon
   trolAuditInstance```

**Comment by mauroservienti** [comment]
@barrit @Cogax I raised #2391 to fix the problem. I'm still investigating the reason why the repo ended up in this state. I'll let you know as soon as a new release is available.

**Comment by mauroservienti** [comment]
For the records, here is the reason why it works in versions earlier than `4.15`: https://github.com/Particular/ServiceControl/pull/2391#issuecomment-759995316

**Comment by ramonsmits** [comment]
@barrit We will be releasing 4.15.1 after the weekend.
