### ISSUE TITLE
ServiceControl unable to install under RabbitMQ Vhost

### ISSUE THREAD

**Issue by allensanborn** [Particular/ServiceControl#2451]
I'm trying to learn more about monitoring NServiceBus and RabbitMQ, spinning up local environments and designing a much larger system to support our MSMQ to RabbitMQ transition.

To keep my various tests isolated from one another locally and different systems separate in higher envs, I'm writing up/down scripts and hoping to run everything in RabbitMQ in different vhosts. 

According to their [documents](https://www.rabbitmq.com/vhosts.html), "RabbitMQ is multi-tenant system: connections, exchanges, queues, bindings, user permissions, policies and some other things belong to virtual hosts, logical groups of entities. ".

That leads me to believe that I should be able to set everything needed for an application or an environment under a vhost.

When I try to set up a ServiceControl Monitoring instance using the PowerShell command below, I get an error stating that my vhost admin user can't access the root '/'. That makes sense since I didn't grant it any rights to the root. It only has permissions to the vhost. 
```
New-MonitoringInstance `
-Name Test.Monitoring `
-ConnectionString 'host=localhost;username=vhostadmin;password=vhostadmin;vhost=vhostadmin' `
-InstallPath C:\ServiceControlMonitor\Bin `
-LogPath C:\ServiceMonitor\Logs `
-Port 33335 `
-Transport 'RabbitMQ - Conventional routing topology'
```
```
ServiceControl.Monitoring.exe threw an error when creating queues. This typically indicates a configuration error. The error output from ServiceControl.Monitoring.exe was:
 RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - access to vhost '/' refused for user 'vhostadmin'', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Bo...
```

If I grant it admin rights to the root by mirroring the admin account, run the same command and check the RabbitMQ configuration, all the Exchanges and Queues have all been created at the root despite specifying the vhost in the connection string. The configuration is essentially the same as if I'd run it with the global admin account and not vhost in the connection string. The vhost does have the default set of Exchanges created. I attached the output of http://localhost:15672/api/definitions.
[dump.json.txt](https://github.com/Particular/ServiceControl/files/6198614/dump.json.txt)

Am I doing something wrong or are my expectations just not matching reality? 

Is it possible for the ServiceControl Monitoring create all of its many delayed delivery Exchanges and everything else under a vhost? 
If not, is there a reason why this isn't possible or is not preferred? I'm always interested in knowing the constraints and "best practices".
Is this just a bug or features request? 

Thanks!

**Comment by bording** [comment]
@allensanborn Looking at the connection string you're using, you don't have the virtual host setting correct: 

https://docs.particular.net/transports/rabbitmq/connection-settings#connection-string-options-virtualhost

If you change it from `vhost=` to `virtualhost=`, I suspect it will work properly for you.

**Comment by allensanborn** [comment]
Oh man... I saw the vhost in the uri and ran with that. I totally missed that difference on the NServiceBus side. 
https://www.rabbitmq.com/uri-spec.html

Thanks!

**Comment by bording** [comment]
@allensanborn Those sort of differences are why we started supporting the AMQP connection string format in the latest versions of the RabbitMQ transport. 

However, ServiceControl itself does not yet support it, so you still have to use the custom format we created for the transport.
