### ISSUE TITLE
Improve diagnostics and alerting around indexing performance (and staleness) and disk space usage

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#2494]
Consider adding following custom checks
- Ingestion is outpacing Retention
- Disk space growth will overflow the available space
- Indexing is getting more and more stale
- Indexes are disabled

In addition to that, add warning and error level logging for these topics.

**Comment by kbaley** [comment]
Another consideration: One or more indexes is corrupt

**Comment by ramonsmits** [comment]
@SzymonPobiega it seems only Ingestion is outpacing Retention isn't implemented right?

**Comment by SzymonPobiega** [comment]
@ramonsmits I don't know the current state. I heard that with Raven5 there is no danger of ingestion outpacing retention.

**Comment by ramonsmits** [comment]
@SzymonPobiega The other points are already covered by custom checks. I'm closing this issue because of this.
