### ISSUE TITLE
SCMU changes user provided instance casing 

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServiceControl#2578]
When deriving an instance name we try to ensure that the newly created instance name 
 * does not clash with existing instances 
 * that there are no spaces in the name
 * name has a proper casing

To achieve the last we use [ToTitleCase](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Config/UI/SharedInstanceEditor/SharedServiceControlEditorViewModel.cs#L148) which changes casing in words that already include upper case letters. For example, if users provide "OneTwoThree" as the service name this gets changed to "Onetwothree".  We should not change the casing for words provided by the user.

**Comment by gbiellem** [comment]
@tmasternak I think this is a duplicate of an issue I raised some time ago https://github.com/Particular/ServiceControl/issues/1730

**Comment by gbiellem** [comment]
@TraGicCode also raised it here https://github.com/Particular/ServiceControl/issues/1767 if you want to cleanup some duplicate issues

**Comment by tmasternak** [comment]
@gbiellem thank you for pointing to duplicates. I'll close this one in favor of https://github.com/Particular/ServiceControl/issues/1730.

I've also labeled it for the next enhancement release.
