### ISSUE TITLE
ServiceControl Management PowerShell module doesn't expose the version of the cmdlet

### ISSUE THREAD

**Issue by lailabougria** [Particular/ServiceControl#2652]
It would be beneficial to expose the version of the cmdlet so that users can verify which version they are using when managing ServiceControl instances.

**Comment by fourpastmidnight** [comment]
This can already be gotten rather easily:

```powershell
Get-Module Particular.ServiceControl.Management | Select-Object -ExpandProperty Version
```

If the module is not yet imported, you'll need to add the `-ListAvailable` parameter to the `Get-Module` cmdlet.

**Comment by dvdstelt** [comment]
[Updated the documentation](https://docs.particular.net/servicecontrol/powershell#installing-and-using-the-powershell-module) to include the command. Thanks @fourpastmidnight
