### ISSUE TITLE
The license status keeper for endpoints is not persistent.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl#271]
Currently, the `LicenseStatusKeeper` is a concurrent in-memory dictionary and we are not persisting this information.

What this means is, when ServiceControl is restarted, we are not going to have the license status for the endpoints and we have to wait for messages to get audited for us to report back the license status. 

https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Operations/LicenseStatusKeeper.cs

**Comment by johnsimons** [comment]
Still not done today, is this really required ?

**Comment by johnsimons** [comment]
@indualagarsamy it seems ServicePulse currently does not display the license status at all, so in other words, even thought that status is not up-to-date after a restart, that status is not being used by ServicePulse.
So should we create a new requirement for it instead and close this one ?

**Comment by indualagarsamy** [comment]
@johnsimons - to me this seems to me like a refactoring improvement. Not sure why we need to wait for auditing messages to try and see the license status. Shouldn't this be persisted, instead of having it in-memory? However, I am ok for closing this if we are not displaying license status in SP. I thought we do display license status in ServicePulse. 
Can you try the following use case:
1. Run SC with an expired license - Check SP. 
2. Update license. Restart SC and check SP.
3. Don't process any messages, is SP displaying the correct license status?

**Comment by indualagarsamy** [comment]
@johnsimons - Having said that, if you want to open a new requirement for displaying license status in SP, feel free to close this issue. We just need to make sure that this implementation is re-factored for license information recalculation.

**Comment by johnsimons** [comment]
> Can you try the following use case:
> 1. Run SC with an expired license - Check SP. 
> 2. Update license. Restart SC and check SP.
> 3. Don't process any messages, is SP displaying the correct license status?

@indualagarsamy that is a different scenario, this scenario you describe above is to check if SC is licensed, not the individual endpoints.

`LicenseStatusKeeper` keeps track of running endpoints licenses statuses, and that info is currently not displayed in ServicePulse at all.

So based on that I will close this one for now.

BTW, the reason `LicenseStatusKeeper` is in-memory only is because there is no point in saving this data because of it being so volatile.

**Comment by indualagarsamy** [comment]
@johnsimons - thanks for the explanation. I did get confused between the 2 issues.
