### ISSUE TITLE
Azure Service Bus Managed Identity is not supported

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServiceControl#2755]
_Issue description has been edited_

### Symptoms

Exception is thrown when ServiceControl starts up or during installation.

### Who's affected

Users on Version 4.21 who are configuring ServiceControl instances to use Azure Service Bus with Azure Active Directory Managed Identity authentication.

### Root cause

The new SDK used since 4.21.0 no longer support the `Authentication=Managed Identity` option.

### Original issue content

ServiceControl 4.21.0 updated [NServiceBus.Transport.AzureServiceBus](https://www.nuget.org/packages/NServiceBus.Transport.AzureServiceBus) version 2.x, which also updated the Azure SDK from [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) to [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/).

The old Azure SDK permitted a connection string that allowed connection to Azure Service Bus using [Managed Identity](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-managed-service-identity), but in the new Azure SDK, this fails with the following message:

> The connection string used for an Service Bus client must specify the Service Bus namespace host and either a Shared Access Key (both the name and value) OR a Shared Access Signature to be valid.

While the ServiceControl binaries can be updated, there is currently no way for these versions of ServiceControl to connect to Azure ServiceBus using managed identity, and the app fails at startup.

**Comment by andreasohlund** [comment]
Will be released in 4.21.8
