### ISSUE TITLE
Esent version store maximum size exceeded

### ISSUE THREAD

**Issue by Asopus** [Particular/ServiceControl#2758]
Hello 

Since installing version 4.21.0 of Servicecontrol, we sometimes notice following error in the eventlog:

```
Event 623, ESENT


Raven (8120,D,23) 1-6BmDnyW34uH/88u8fklW8g2-<InstallationPath>\Db\Data: The version store for this instance (0) has reached its maximum size of 1023Mb. It is likely that a long-running transaction is preventing cleanup of the version store and causing it to build up in size. Updates will be rejected until the long-running transaction has been completely committed or rolled back. 
Possible long-running transaction: 
	SessionId: 0x00000216F6DE5F20:0x462a48 
	Session-context: 0x00000000 
	Session-context ThreadId: 0x0000000000004378 
	Cleanup: 1 
	Session-trace: 
52005@14:55:44
57573@14:52:47
```

This seems to prevent indexes from updating, rendering them stale rather quickly.
Is this something known and if yes, is there something that can be done by us in order to avoid these kind of stacktraces?

Kr
Pieter

**Comment by andreasohlund** [comment]
Hi, I've asked around internally and so far we haven't had any other reports of this.

ServiceControl 4.21 does [update to RavenDB 3.5.10-patch-35311](https://github.com/Particular/ServiceControl/pull/2660) which is the latest version. Looking at the [release notes](https://ravendb.net/docs/article-page/5.3/Csharp/start/whats-new) nothing stands out as a potential source of this issue.

What version of ServiceControl did you update from? 

Is there anything that you can observe in regards to load on SC (high volume of audit or error messages etc) around the time when you get those logs?

Can you share the logs with us? (email support@particular.net and attach them to the email)

**Comment by WojcikMike** [comment]
I shall close it. If you have any questions please follow up via [support](https://particular.net/support)
