### ISSUE TITLE
Email Notifications not working when message goes to error queue

### ISSUE THREAD

**Issue by smartindale** [Particular/ServiceControl#2761]
In attempting to use the email notification feature (as documented [here](https://docs.particular.net/servicepulse/health-check-notifications)) in pulse/insight, we have observed that emails are never actually sent whenever a message hits the error queue.

It should be noted, however, that the "test email notification" does function properly in sending a successful test email, so we know that the email configuration is correct.

ServicePulse v1.30.0
Service Control:  v4.19.0

![image](https://user-images.githubusercontent.com/2644559/149224396-d0fbb713-9443-445a-84d5-89f7e4be8711.png)

**Comment by mikeminutillo** [comment]
@smartindale this feature only sends emails for status changes on the internal health checks and not for every external integration event. It would not send an email for a message going to the error queue. This would be for things like:

- There are messages in the dead-letter queue
- Audit ingestion has stopped working
- A remote audit instance could not be reached

**Comment by mikeminutillo** [comment]
Answered via support case.

For anyone else that is looking to do this, you will need to create a custom endpoint that subscribes to the [`MessageFailed` ServiceControl integration event](https://docs.particular.net/servicecontrol/contracts) and sends an email. Use [this sample](https://docs.particular.net/samples/servicecontrol/events-subscription/) as a starting point.

**Comment by madhugilla** [comment]
"and messages in error queue"  in the page is misleading, we were wondering if we configured service pulse incorrectly.  the sample helped.

thanks
