### ISSUE TITLE
ServiceControl Installer fails for Sql connection string with Azure Active Directory authentication

### ISSUE THREAD

**Issue by raelyard** [Particular/ServiceControl#2767]
The Sql Transport uses Microsoft.Data.SqlClient for interacting with Sql Server databases. This is good and necessary to be able to connect to Azure Sql using Azure Active Directory credentials. This works fine having installed a Service Control instance with the Sql Transport if one is able to work around this problem with installation of the instance.

For example, the following connection string can be used successfully in a context with an Azure Active Directory Managed Identity to authenticate. If an already installed Service Control instance (or other type of endpoint) is using this connection string in an Azure context, like a virtual machine, with a managed identity, it works flawlessly.

```
Server=sometransportdatabaseserver.database.windows.net;Database=sometransportdatabase;Authentication=Active Directory Managed Identity;
```

Installing such an instance, though, fails via both the Service Control Management graphical tool and the PowerShell modules. This is because the ServiceControlInstallerEngine library validates connection strings by attempting to connect to the database specified. It does so using System.Data.SqlClient in the `ConnectionStringValidator` class, which does not support the use of Azure Active Directory authentication types in the connection string.

```
Connection String is invalid - Invalid value for key 'authentication'.
```

To make a seamless experience when using Sql for transport, it's necessary for such connection strings to successfully validate.

I want to script the setup of these instances with the PowerShell modules as a part of a broader Terraform environment setup and this issue is standing in my way.

**Comment by kentdr** [comment]
I added Symptoms, Who's affected, and Root Cause sections to the issue description for release notes.

**Comment by kentdr** [comment]
@raelyard [4.21.6](https://github.com/Particular/ServiceControl/releases/tag/4.21.6) is out with this fix.  Thank you for your contribution!

**Comment by raelyard** [comment]
Thank you for this @kentdr . Unfortunately, it's still not working for me. It appears to me the commit for 4.21.6 is the same commit as 4.21.5: e09139d3. Both tags are on that one commit. It looks to me like the intent was that it should be 5d5df04c that resulted from merging #2792 .

**Comment by kentdr** [comment]
@raelyard, we pushed [4.21.7](https://github.com/Particular/ServiceControl/releases/tag/4.21.7), sorry for the mix-up.  Thank you again!

**Comment by raelyard** [comment]
👍 Thank you @kentdr This looks like it will do the trick. I'll give it a try. I expect you won't be hearing from me again on this.
