### ISSUE TITLE
Show Host Identifier on heartbeat failure and recover events

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2769]
Hello,

When heartbeat failures occur the host identifier is not being used in the event shown in servicepulse.  This means if an endpoint is scaled out on 2 physical machines, it's impossible to know which machine hosting the endpoint had the issue.

We are using octopus deploy and the below code to customize the host identifier of our endpoints

```
configuration.UniquelyIdentifyRunningInstance().UsingNames(endpointName, Environment.MachineName);
```

![image](https://user-images.githubusercontent.com/6224270/150186511-f4a6cffb-e550-4db3-aa0c-b0e38b252e29.png)

**Comment by helenktsai** [comment]
Hi @TraGicCode, thanks for pointing this out. This will be considered in a future enhancement release.
