### ISSUE TITLE
Powershell cmdlet sc-upgrade fails but SCMU servicecontrol upgrade works 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#2780]
I've Installed 4.21.4 and tried to upgrade an existing servicecontrol instance via the sc-upgrade powershell cmdlet.  

This fails with the error:

```
sc-upgrade : Failed to retrieve release date for new version
```
Updating the same instance via SCMU works fine

**Comment by raelyard** [comment]
I'm also experiencing this problem.

In my case, it's on `sc-add`, but it's really on trying to run any of the modules for dealing with mutating Service Control instances. I haven't tried, but I expect this is the case for any of the types of instances.

I looked closer to try to track it down. It appears the `TryReadReleaseDateAttribute` function of the `ReleaseDateReader` class is using a `MetadataLoadContext` to do a reflection-only load of the assembly to get the release date for a license check.

The [call to the constructor for MetadataLoadContext](https://github.com/Particular/ServiceControl/blob/019c41b7d08d6d3006ee8b6ed1edc1dd269c3c33/src/ServiceControlInstaller.Engine/FileSystem/ReleaseDateReader.cs#L26) is blowing up with

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ReadOnlySpan`1..ctor(T[] array)
   at System.Reflection.PathAssemblyResolver.Resolve(MetadataLoadContext context, AssemblyName assemblyName)
   at System.Reflection.MetadataLoadContext.TryFindAssemblyByCallingResolveHandler(RoAssemblyName refName)
   at System.Reflection.MetadataLoadContext.ResolveToAssemblyOrExceptionAssembly(RoAssemblyName refName)
   at System.Reflection.MetadataLoadContext.TryResolveAssembly(RoAssemblyName refName, Exception& e)
   at System.Reflection.MetadataLoadContext.TryGetDefaultCoreAssembly(Exception& e)
   at System.Reflection.MetadataLoadContext.TryGetCoreAssembly(String coreAssemblyName, Exception& e)
   at System.Reflection.TypeLoading.CoreTypes..ctor(MetadataLoadContext loader, String coreAssemblyName)
   at System.Reflection.MetadataLoadContext..ctor(MetadataAssemblyResolver resolver, String coreAssemblyName)
   at ServiceControlInstaller.Engine.FileSystem.ReleaseDateReader.TryReadReleaseDateAttribute(String exe, DateTime& releaseDate)
```

System.Reflection.MetadataLoadContext was updated from 5.0.1 to 6.0.0 with this commit: https://github.com/Particular/ServiceControl/commit/2b3a950a0.

That is the change that caused this problem to surface with this version. The quickest and easiest way to fix this would be to revert that. It does not appear it would impact anything else.

**Comment by WilliamBZA** [comment]
Thanks @gbiellem and @raelyard. I'll review the issue and PR.

**Comment by WilliamBZA** [comment]
PR incoming to address the binding redirect issue.

**Comment by WilliamBZA** [comment]
@gbiellem @raelyard [4.21.5](https://github.com/Particular/ServiceControl/releases/tag/4.21.5) is out and fixes this!

**Comment by raelyard** [comment]
Excellent. Thank you @WilliamBZA .

**Comment by raelyard** [comment]
@WilliamBZA 4.21.5 does fix this, but it looks to me like it has lost the changes from 4.21.4. The tag for 4.21.4 is indeed not in the lineage from 4.21.5. I expect this is not what was intended, right?

**Comment by WilliamBZA** [comment]
4.21.5 includes the 4.21.4 changes, but the 4.21.4 changes were removing `IsDebugEnabled` checks whereas 4.21.5 re-introduced those checks to get the string interpolation out of the hotpath. So 4.21.5 does definitely include the 4.21.4 changes.

**Comment by WilliamBZA** [comment]
@raelyard It looks like #2767 was never released. I'm working with @kentdr to get that done now.

**Comment by raelyard** [comment]
Oh, ok. Thanks for the clarification.
