### ISSUE TITLE
Certain boolean app.config values are inconsistently being capitalized

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2862]
I noticed that boolean values within the app.config are sometimes and sometimes not being capitalized.  It would be great if case was not being changed and everything was consistent.  For me this is causing me to have to sometimes and sometimes not capitalize boolean values to prevent automation from changing the config file when nothing really changed

![image](https://user-images.githubusercontent.com/6224270/168329722-a1aa6c2b-76ee-4a02-a217-944d6fb7f285.png)

**Comment by boblangley** [comment]
Mike, thanks for reporting this. Based on one of those values, reviewing the code, we call `.ToString()` which will format it with the capital. We should probably review all of these `.ToString()` calls and add `.ToLowerInvariant()` to make them compatible with XML spec.

I will mark this as an improvement so it can be picked up as part one of the next rounds of enhancements. I do not have a timeline, but the team will update this issue when work starts.
