### ISSUE TITLE
Email notifications endpoint is returning UTF-16 causing consumption issues

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2870]
Hello,

For some reason the `/api/notifications/email` api endpoint is returning the json payload as UTF16 which makes it incredibly hard to consume VIA powershell.  I think this is mainly from the BOM that exists.

![image](https://user-images.githubusercontent.com/6224270/169043563-91c5e2de-5d3a-4399-95df-1667b857eb59.png)

This is also inconsistent with other api endpoints such as which works fine and returns utf-8 `/api/eventlogitems`

```
Invoke-RestMethod -Method Get -Uri "http://localhost:33333/api/eventlogitems" # ( convert from json not needed, powershell did it automatically )
```

After investigation it looks like the responses are being returned using different strategies which is the root cause.

https://github.com/Particular/ServiceControl/blob/f8d3d2f25f41b6dccbcc8448a97527d87d1b0499/src/ServiceControl/EventLog/EventLogApiController.cs#L29-L31

https://github.com/Particular/ServiceControl/blob/ec8277576f5e9f91a7d9c27c00f05c078df93fa4/src/ServiceControl/Notifications/Api/NotificationsController.cs#L32

**Comment by bording** [comment]
This definitely appears to be a bug. We'll be working on it as soon as we can.
