### ISSUE TITLE
Multi database support, following SqlTransport feature

### ISSUE THREAD

**Issue by roycornelissen** [Particular/ServiceControl#289]
As per @andreasohlund's request, I hereby raise an issue for adding multi-database support to SC, following the same feature added to the SqlTransport (see PR https://github.com/Particular/NServiceBus.SqlServer/pull/15).

The desired behavior would be that failed messages contain the original queue and connection string, so that they can be put back into the correct queue when a retry is done.

**Comment by SzymonPobiega** [comment]
This might be tricky depending on authentication settings i.e. including a connection string containing a user/pass in the message would not be a good idea.

**Comment by andreasohlund** [comment]
We could detect and throw if we see user/pass and instead tell users to
create an alias that they pass?

This alias could just be a key in the connection string keys? (yes you
would have to sync aliases across the involved endpoints)

**Comment by SzymonPobiega** [comment]
With NSB 5.x and SQL 2.1 we could just hook SC to the same connection string repository as regular endpoints.

**Comment by johnsimons** [comment]
This will be added as part of v1.7 release
