### ISSUE TITLE
Flaky acceptance tests

### ISSUE THREAD

**Issue by cquirosj** [Particular/ServiceControl#2893]
This issue captures a set of tests that failed multiple builds between May 6th, 2022. and June 10th, 2022

## Learning Transport

* `ServiceControl.Monitoring.AcceptanceTests.Tests.When_querying_disconnected_count`
  * Test fails with the message "Disconnected count after all endpoints started"
  * Failed runs samples
    * https://github.com/Particular/ServiceControl/runs/6814132962?check_suite_focus=true#step:14:12098
    * https://github.com/Particular/ServiceControl/runs/6815743810?check_suite_focus=true#step:14:11912

## AzureServiceBus-EndpointTopology 

* `Particular.Packaging.targets(78,5)`
  * Test fails with the message "The process cannot access the file because it is being used by another process" 
  * Failed run sample:
    * https://github.com/Particular/ServiceControl/runs/6775548203?check_suite_focus=true#step:6:57

```
EndpointTopology failed to build:
2022-06-07T14:00:26.1686750Z C:\Users\runneradmin\.nuget\packages\particular.packaging\2.0.0\build\Particular.Packaging.targets(78,5): error MSB3491: Could not write lines to file "D:\a\_temp\_runner_file_commands\set_env_c220d7cb-08f0-4a0d-9021-7565b80e9aba". The process cannot access the file 'D:\a\_temp\_runner_file_commands\set_env_c220d7cb-08f0-4a0d-9021-7565b80e9aba' because it is being used by another process. [D:\a\ServiceControl\ServiceControl\src\ServiceControl.SagaAudit\ServiceControl.SagaAudit.csproj]
```

in https://github.com/Particular/Particular.Packaging/blob/master/src/Particular.Packaging/build/Particular.Packaging.targets L:78

## AzureStorageQueues 

* `Particular.Packaging.targets(78,5)`
  * Test failes with the message "Could not write lines to file process cannot access the file"
  * Failed run sample:
    * https://github.com/Particular/ServiceControl/runs/6796807158?check_suite_focus=true#step:6:51

## AzureServiceBusNetStandard 

* `ServiceControl.AcceptanceTests.Monitoring.InternalCustomChecks.When_a_critical_error_is_triggered+MyContext`
  * Test fails with the message "System.TimeoutException : The maximum time limit for this test(90s) has been reached"  
  *  Failed run sample:
    * https://github.com/Particular/ServiceControl/runs/6775547937?check_suite_focus=true#step:14:912

## RabbitMQ

* RabbitMQ setup fails on both topologies
* Failed run sample:
 * https://github.com/Particular/ServiceControl/actions/runs/2375958039/attempts/1
 * https://github.com/Particular/ServiceControl/runs/6568194569?check_suite_focus=true

```
Failed to connect after 10 attempts
Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1
Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\Particular\setup-rabbitmq-action\v1.0.0\dist\index.js:1307:25)
    at ExecState.CheckComplete (D:\a\_actions\Particular\setup-rabbitmq-action\v1.0.0\dist\index.js:1290:18)
    at ChildProcess.<anonymous> (D:\a\_actions\Particular\setup-rabbitmq-action\v1.0.0\dist\index.js:1184:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5
```

**Comment by timbussmann** [comment]
added some additional error information for the ASB build error. At first glance there seem to be some issues when trying to [write environment variables as part of the build process](https://github.com/Particular/Particular.Packaging/blob/master/src/Particular.Packaging/build/Particular.Packaging.targets#L78) in case multiple projects in the same solution that is being built reference `Particular.Packaging.targets`. I'm not sure whether that is something due to potential parallel builds within the solution or if that really is just a problem with the file system itself.

**Comment by andreasohlund** [comment]
With the new dedicated transport seam tests we haven't observed any flakiness. Should we close this issue for now @cquirosj ?
