### ISSUE TITLE
Unbounded ProcessingAttempts collection can cause ingestion timeouts

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2913]
Unbounded ProcessingAttempts collection can cause ingestion timeouts. When the collection expands due to a very large amount of unique processing attempts the document grows very large. The ProcessingAttempts collection for a failed messages is expanded via a RavenDB patch operation:

https://github.com/Particular/ServiceControl/blob/747bf6c4ba85994101f457565801f2e8f3e667a4/src/ServiceControl/Operations/ErrorProcessor.cs#L203-L212

This patch operation might be able to be truncated to a bounded set of attempts. For example, to only store the 10 most recent processing attempts

**Comment by tmasternak** [comment]
Dupliate of https://github.com/Particular/ServiceControl/issues/2916
