### ISSUE TITLE
Inefficient storage of processing attempts can result in outage

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2916]
Message data (headers+body) and message processing attempt is not stored in isolation but is stored as part of the `FailedMessage` document. This is fine when there are only a few attempts but it can happen many duplicates are generated within a system. Meaning, that multiple physical copies exist in the transport. Each duplicate gets processed but can also fail thousands of times. Especially when copies of the same message are processed concurrently.

Not only is each attempt stored but it's stored with all headers and body data that is identical. If the headers or body contain more than just a few kilobytes of data the size of the FailedMessage document gets larger even faster.

Some examples:

- Misbehaving outbox that generates duplicates
- A user custom outbox pattern implementation generating duplicates
- An idempotent API that sends messages but is invoked with the same data and generates duplicates

This eventually causes ingestion performance issues after that timeouts which complete block ingestion entirely. Especially in environments where hosts are optimized for efficient costs and regular day-to-day ingestion rates.

When systems are in this state the FailedMessage documents must be reduced in size to get the system back. Run [FailedMessageCleaner](https://github.com/tmasternak/ServiceControl.FailedMessagesCleaner) to truncate the ProcessingAttempts collection for all FailedMessages that have more then 10 processing attempt. This operation can take a while depending on database size and host CPU/RAM/IO resources.

If urgency is required because the error queue could run out of storage quota an emergency procedure can be performed:

1. Stop SC
2. Rename DB folder (DB Path in SCMU)
3. Start SC

This will recreate the DB folder with a clean empty state.

The old DB folder can be dealt with at a later time.

Keep in mind that if the error queue contains many duplicates that this can happen again and that this is only a temporary solution.

## References

- https://github.com/tmasternak/ServiceControl.FailedMessagesCleaner
- https://github.com/Particular/ServiceControl/issues/2913
- https://github.com/Particular/NServiceBus/pull/6264

**Comment by ramonsmits** [comment]
Several users have been affected by this. Here an example of the output of one of the runs:
![image](https://user-images.githubusercontent.com/152998/207294506-3db22d4b-5233-4fb3-906a-c7dfeb512ced.png)

**Comment by tmasternak** [comment]
Fixed in https://github.com/Particular/ServiceControl/pull/3372
