### ISSUE TITLE
Add authentication and authorization support to ServiceControl

### ISSUE THREAD

**Issue by helenktsai** [Particular/ServiceControl#2937]
- Network Access Control Lists (NACLs).
- Role-Based Access Control (RBAC).

### Workaround

- Set up the tools on an isolated virtual machine, with RDP access employed to handle security. It would be better to be able to securely expose Service Pulse over the network.
- Move ServicePulse and ServiceControl behind a reverse proxy. This has a downside in that a user needs to do manual updates/installs of newer version of the tools

**Comment by DavidBoike** [comment]
Dupe of:

- https://github.com/Particular/ServiceControl/issues/400

**Comment by ramonsmits** [comment]
Help us design authorization for ServicePulse and ServiceControl. [We'd appreciate your feedback in our community discussion on our forum](https://discuss.particular.net/t/we-need-your-input-authorization-is-coming-to-servicepulse-and-servicecontrol/4648), on this issue, or privately via <support@particular.net>
