### ISSUE TITLE
Create approval tests for ServiceControl dockerfiles

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceControl#2959]
ServiceControl docker files are text based and very similar in terms of structure. As there are multiple files we need to ensure dockerfiles are consistent, to name a couple of cases:

- Target .NET Framework may make sense to update all together
- All the .init files should have the additional --setup flag

A set of approval tests would be able to quickly verify this and ensure changes happen intentionally and consistently.

## Suggested plan

- [x] Add new approval tests https://github.com/Particular/ServiceControl/pull/2965
- [x] Ensure tests are run in our CI environment

**Comment by jpalac** [comment]
Tests created, tested and merged.
