### ISSUE TITLE
 ServiceControl: Maintenance mode requires an additional container for Docker

### ISSUE THREAD

**Issue by kbaley** [Particular/ServiceControl#2986]
_This issue was transferred from a private repository_

To run a Docker container for ServiceControl in maintenance mode, requires shutting down the current ServiceControl container that is running and create a new container with additional parameters to initiate maintenance mode.
Having the ability to execute this from ServicePulse itself would be better and require less actions/input/considerations from operations.

**Comment by DavidBoike** [comment]
Closing this issue as it is no longer relevant.

ServiceControl containers do not embed the database in the container, and instead use an external database container, so there is no concept of maintenance mode in ServiceControl Linux containers.
