### ISSUE TITLE
Add a backup/view/restore override settings to ServiceControl.exe 

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#306]
A user may want to backup or restore existing configuration settings:
`ServiceControl.exe --backup --file="Mybackup"`
`ServiceControl.exe --restore --file="Mybackup"`

Add an option to output the current overridden settings:
`ServiceControl.exe --display-config`

**Comment by gbiellem** [comment]
Closing this as it doesn't make sense based on were we are going with the SC installer
