### ISSUE TITLE
Azure ServiceBus & Storage Queues acceptance tests failing with timeouts

### ISSUE THREAD

**Issue by synhershko** [Particular/ServiceControl#308]
On the build server - probably because the build server (EC2) is remote to the Azure data-center we use.

This shouldn't be that slow, but for some reason it apparently is.

So if the Azure-based transports happen to have a good connection they will pass otherwise the tests will fail with a timeout

/cc @andreasohlund @yvesgoeleven @gbiellem @johnsimons

**Comment by SeanFeldman** [comment]
When SC is used with a transport that requires HTTP, `ServicePointManager.DefaultConnectionLimit` needs to be increased. If not, default 10 connections are used up quickly causing threads that need to make an http web request to block.
