### ISSUE TITLE
Investigate enabling support for external RavenDB 5 (with the additional benefit of simplifying the tests)

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3168]
The new persistence seam enables using an external RavenDB instance. We don't have data about the performance impact of externalizing the storage over HTTP.

Externalizing the storage might also benefit the acceptance tests currently made more complex by the embedded RaenDB instance lifecycle management.

**Comment by DavidBoike** [comment]
ServiceControl 6, with RavenDB 6.2, does support external databases, including Raven Cloud.
