### ISSUE TITLE
Monitoring instances report the wrong persister type

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3186]
This is a minor visual bug.

Starting 4.26.0, SCMU reports the persister type and version. For monitoring instances, it defaults to the wrong value of RavenDB 3.5. It should be "In Memory."

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1325611/200601082-9c3dab19-30b5-4413-b7fe-d6145ebcfb95.png">

**Comment by andreasohlund** [comment]
Wrong type is shown no matter how its installed so adjusted title to reflect this
