### ISSUE TITLE
Remove NServiceBus dependency on ServiceContracts.Contracts

### ISSUE THREAD

**Issue by kstrauss** [Particular/ServiceControl#319]
Currently, the ServiceContracts assembly depends on NSB because the messages implement IEvent. I believe this is undesirable and that they should have no dependency at all; as it ties listening endpoints to the version of NSB that the assembly was built with Instead the using endpoint should be able to use unobtrusive mode.

This would be important given a scenario similar to the one illustrated by the ServiceControl.Integration.Demo.

**Comment by johnsimons** [comment]
This was done as part of the v1 release
