### ISSUE TITLE
Docker images are using RavenDB 3.5 and cannot be easily updated to use RavenDB 5

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3210]
Docker images use RavenDB 3.5 as the default persister. That is true also for 4.26.0, which supports RavenDB 5 for new audit instances. The reason is to prevent the following scenario, for example:

-  A set of docker images is running using the `latest` tag (at the time it was pointing to 4.26.0, and thus using RavenDB 3.5)
- The images are recreated, still using `latest` but now pointing to a new version that defaults to RavenDB 5
- New databases will be created, and no data imported.

There is no data loss. However, the user experience is awful. Users won't find their data, and when they realize what happened, they'll be in a position in which, in the folder on disk, there are files from the RavenDB 3.5 persister and files from the RavenDB 5 one.

A possible solution is forcing users to set an environment variable to specify which persister to use and make the only option RavenDB 5. That will cause the upgrade scenario described above to fail, data will be preserved without mixing in new persister data, and users will have to read the upgrade guide.

**Comment by boblangley** [comment]
With the deprecation of the Windows SC containers and the creation of the Linux containers that only support Raven 5, this can be closed.
