### ISSUE TITLE
ServiceControl doesn't propagate some settings to RavenDB 5

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3253]
In the documentation, it's stated that

- `ServiceControl.Audit/IndexStoragePath`
- `ServiceControl.Audit/RavenDBLogLevel`

They can be set to control some of the RavenDB behaviors. However, those settings are not propagated to the new RavenDB 5 embedded instance in the codebase. Previously, RavenDB 3.5 was reading from the application config file. Now RavenDB 5 runs in a separate process and comes with its settings configuration mechanism.

We should first check if both settings still apply (It looks like [RavenDBLogLevel still applies](https://ravendb.net/docs/article-page/5.4/csharp/server/configuration/logs-configuration)), and then patch the RavenDB 5 audit instance to honor them.

**Comment by TraGicCode** [comment]
Hey @mauroservienti ,

Do you know if this bug is still valid?

**Comment by mauroservienti** [comment]
It's still pending a resolution. There is a group working on ServiceControl right now; I'll see if they can include this as well.

**Comment by ramonsmits** [comment]
## ServiceControl.Audit/IndexStoragePath

Based on the following RavenDB 5 guidance the index location can no longer be set. The docs state that you should use soft (symbolic) links. I've validated this as any sub folder can be targeted to a different drive. RavenDB studio is even able to determine actual disks used if subfolders use symlinks on Windows Server (did not test Linux).

- https://ravendb.net/docs/article-page/5.4/csharp/server/storage/customizing-raven-data-files-locations

This means that `ServiceControl.Audit/IndexStoragePath` is no longer supported. I've updated guidance regarding this setting in:

- https://github.com/Particular/docs.particular.net/pull/6232

I'll also validate support for `RavenDBLogLevel` and will report that here but I do think we map and propagate that to RavenDB 5.

**Comment by ramonsmits** [comment]
Regarding `RavenDBLogLevel`, validated this and SC5 will map this to the RavenDB5+ LogsMode argument. It allows new RavenDB5+ values but also allows old RavenDB35 values and maps these. Improvements/fix added in the following:

- https://github.com/Particular/ServiceControl/pull/3796
