### ISSUE TITLE
User cannot set retention to cleanup inactive/deleted endpoint instances

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3260]
As per audit messages, it could be helpful (in [specific scenarios](https://discuss.particular.net/t/delete-inactive-endpoints/3274)) to automatically expire inactive endpoints.

connects to:

- https://github.com/Particular/ServicePulse/issues/468
- https://github.com/Particular/ServicePulse/issues/1257

**Comment by PhilBastian** [comment]
fixed in SP 1.42.1 and SC 5.9.1

**Comment by mauroservienti** [comment]
@PhilBastian, should the note at the bottom of the documentation page reflect the version numbers mentioned above?

![image](https://github.com/user-attachments/assets/7e1cfdf3-0f5f-4e67-b69c-5a138ed9106e)

Also, is it 6 hours or 1 hou?

**Comment by PhilBastian** [comment]
6 hours for heartbeat instances, 1 hour for monitoring
