### ISSUE TITLE
Distribute the PowerShell module both via the SCMU installer and via the PowerShell Gallery

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#3286]
Required for https://github.com/Particular/ServiceControl/issues/3152
Required for https://github.com/Particular/ServiceControl/issues/3287

As a result of [creating a PowerShell module that can be published to the PowerShell Gallery](https://github.com/Particular/ServiceControl/pull/3283), we now need to deploy the built modules to the gallery.

The PowerShell module is currently deployed alongside the SCMU installer. It would be better if the module were distributed on the [PowerShell Gallery](https://www.powershellgallery.com/) as this makes it easier for users to update their powershell scripts without needing to download an installer.

By adding a new distribution avenue through the PowerShell Gallery, we do not break anything in our users' environments. Those that are more serious about PowerShell use can then start switching their PowerShell code to point to the gallery version instead of the SCMU Installer version at this point if they want to get ahead of the curve.

**Comment by bording** [comment]
This work is now done. The next release of ServiceControl will include pushing a module to the PowerShell Gallery.

The following things were done to enable this:
- PRs
  - https://github.com/Particular/push-octopus-package-action/pull/21
  - https://github.com/Particular/ServiceControl/pull/3354
  - https://github.com/Particular/ServiceControl/pull/3358
  - https://github.com/Particular/ServiceControl/pull/3374
- particular-powershell-gallery feed created in MyGet
- ParticularSoftware account created for https://www.powershellgallery.com/
- PowerShellGet 2.2.5 module installed on the Octopus VM
- `Publish PowerShell modules` Octopus step template created
- Feed variables for the step template added to `Package feeds` variable set
- Step template added to the ServiceControl Octopus release process
