### ISSUE TITLE
Duplicate Endpoints appear in ServicePulse after re-deployment

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#329]
Raised by @dannycohen
Migrated from by https://github.com/Particular/ServicePulse/issues/134

Customer raised issue:

> What the problem looks like is this:
> 1. We deploy a bunch of NServiceBus endpoints through Octopus. They
>    report as active in ServicePulse, and the heartbeats stay consistent.
> 2. (The Problem) When we deploy again, our Octopus process is to stop and
>    uninstall all the running endpoints, then re-install and start the
>    endpoints from the newly deployed directory. The names have not changed,
>    but ServicePulse reports the newly installed endpoints as entirely
>    new/different heartbeats. The heartbeats from the past deploy begin to
>    display as inactive.
> 3. The effect is apparently duplicate endpoints in ServicePulse; one set
>    that reports as inactive and one set that reports as active.
> 4. A third deploy puts a third set of endpoints into the mix, and so on.
> 
> Why does ServiceControl/ServicePulse see the same endpoints as new
> heartbeats?
> 
> I see I can go into ServicePulse and manually click to deactivate the old
> inactive endpoints, but that's pretty tedious. Is there a better way?

**Comment by lindamccarthy** [comment]
We're experiencing the same issue with endpoints hosted in Azure - sometimes seeing duplicate endpoints and sometimes no endpoints.  Will the workaround solve this? Thanks.

**Comment by gbiellem** [comment]
@lindamccarthy  - What version of NServiceBus.Azure are your endpoints using?  Looks like this was fixed here https://github.com/Particular/NServiceBus.Azure/issues/196

**Comment by lindamccarthy** [comment]
@gbiellem - We're using NServiceBus.Azure version 5.3.0 with NServiceBus version 4.6.1.  Will I need to use the workaround (above) until we upgrade? Thanks..

**Comment by gbiellem** [comment]
@lindamccarthy  apologies I missed you question.  I believe @johnsimons said the workaround won't work for old versions [here](https://github.com/Particular/ServiceControl/issues/329#issuecomment-44606580)

**Comment by SimonCropp** [comment]
@johnsimons would this fix https://github.com/Particular/ServicePulse/issues/174#issuecomment-76653513 work for this issue?

**Comment by johnsimons** [comment]
It does seem to be related @SimonCropp
