### ISSUE TITLE
In scaled out environments: define a policy to report stopped heartbeats only when instances count goes below a threshold

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3317]
Allow defining a policy that sets/configs some minimum instance count and only reports when the number of instances goes below it. Instead of reporting stopped heartbeats for every instance.

**Comment by eirikurharaldsson** [comment]
Is there any update on this?

**Comment by mauroservienti** [comment]
Thanks for chiming in, @eirikurharaldsson. At the moment, there isn't an ETA or an update. Being labeled as `candidate-for-next-release`, it might be picked up anytime soon.

**Comment by eirikurharaldsson** [comment]
Is this supported in ServiceControl 5?

**Comment by eirikurharaldsson** [comment]
Can i override the host identifier, so that the name is stable like dev1, dev2, dev3, test1, test2...
 (make it unique per container stage (dev, test, prod). 
https://docs.particular.net/nservicebus/hosting/override-hostid

I noticed this issue. Do you know if heartbeat plugin support override of the hostid?
https://github.com/Particular/NServiceBus/issues/7026

**Comment by awright18** [comment]
Thanks, 
The latest version of the platform (ServicePulse 1.42.1 and ServiceControl 5.9) included this [fix](https://github.com/Particular/ServicePulse/pull/2019). Can you let us know if that helps in your scenario?

**Comment by johnsimons** [comment]
@mauroservienti I think we can close this one now that we handle scaled-out environments better, thoughts?

**Comment by mauroservienti** [comment]
I'm not sure about it, @johnsimons. This is more about defining a lower bound threshold. The feedback was more about _"I don't want to be bothered by an alarm if my instances count is still greater than X."_

**Comment by johnsimons** [comment]
@mauroservienti regarding "I don't want to be bothered by an alarm if my instances count is still greater than X."

So, the new functionality enables this scenario, 
> I don't want to be bothered by an alarm if my instances count is still greater than 1.

It does not allow customers to set a >1 lower bound, which we discussed in the internal RFC. 
The decision was that it felt like we would be reinventing what K8s does out of the box, and it would also have the risk of possible maintenance burden on customers to ensure the replica number is kept in sync with what is in K8s.

So, given we now handle scaled-out environments better, I feel we can close this issue, and if this surfaces again, we can re-evaluate it at that time, thoughts?

**Comment by johnsimons** [comment]
Based on my previous comment, I am closing this one.

**Comment by eirikurharaldsson** [comment]
If this only raises an alarm if no instance of the same endpoint is running, 
and does not leave dead replicas in inactive heartbeat endpoints, then it´s fine by us.
We will upgrade to the new version of ServiceControl asap.
Thanks.
