### ISSUE TITLE
Release workflow is much slower after changes to how Docker images are built - can now be collapsed to just 3 images

### ISSUE THREAD

**Issue by bording** [Particular/ServiceControl#3338]
The changes introduced in #3241 to how docker images are built has had some negative side effects to the time it takes to release ServiceControl, making it much slower.

Previously, the release workflow built the docker images in parallel via a matrix configuration. That has been removed with the move to using a project to build the images instead.

We should try and find a way to keep the benefits of the project-based way of building, but also re-introduce the parallel building that was lost.

**Comment by WilliamBZA** [comment]
This has been done as part of the ServiceControl on Linux work, closing.
