### ISSUE TITLE
Enable Custom Checks to run at specific times

### ISSUE THREAD

**Issue by davidsavagejr** [Particular/ServiceControl#351]
It would be very useful to enable PeriodicChecks to run at specific times.
ie: daily at 8:00 AM

An example of when this would be used is if I wanted to verify that "Nightly Process X" ran successfully.

**Comment by gbiellem** [comment]
@indualagarsamy  since this is a change for the SC plugins not ServiceControl itself.  I think we should move it to one of the SC plugin repos.  Which is the preferred repo for plugin issues?

**Comment by gbiellem** [comment]
@indualagarsamy  see above

**Comment by gbiellem** [comment]
Closing this as at this time as we have no plans to implement this at this time. @indualagarsamy has advices that this will be considered in conjunction with https://github.com/Particular/Requirements/issues/218
