### ISSUE TITLE
RavenDB\IndexStoragePath setting not honoured for RavenDB 5

### ISSUE THREAD

**Issue by herrJones** [Particular/ServiceControl#3511]
#### Description
We try to move the indexes for the RavenDB5 audit databases to a separate disk (as we do for the 'normal' ServiceControl instances)
We notice however the new index folder remains empty.
The indexes remain in the main database folder.

ServiceControl.Audit.exe.config:
```
<configuration>
<appSettings>
...
<add key="ServiceControl.Audit/DBPath" value="D:\<instance>\Db" />
<add key="Raven/IndexStoragePath" value="I:\<instance>\Indexes" />
...
</appSettings>

</configuration>
```

#### Expected behavior
Indexes are created in the specified folder

#### Actual behavior
Indexes remain in the default folder / audit database storage 

#### Versions
tested with version 4.29.3
Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

add Ravendb/IndexStoragePath setting to config file
restart the service

#### Additional information
maybe linked to report #3498

**Comment by boblangley** [comment]
This [setting is no longer supported after the upgrade to Raven 5](https://github.com/Particular/ServiceControl/issues/3253#issuecomment-1789018832), so we are closing this issue.
