### ISSUE TITLE
Cannot install secondary instance that ingests from the same audit queue

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3535]
#### Description

When installing SC it shows an error when adding a secondary instance that is already configured to read from the same queue:

![SCMU - Audit queue is already assigned to another instance](https://github.com/Particular/ServiceControl/assets/152998/0acbc8b0-cf12-4c23-84e1-b694f551a967)

#### Expected behavior

Allow multiple instance to be installed. This is also allowes when scaling out over multiple machines so should also be allowed on the same machine.

#### Versions

4.30.0

### Steps to reproduce

1. Add first instance
2. Add secondary instance that ingest from the same queue
3. Observe the error message "Audit queue is already assigned to another instance" in SCMU installer

#### Workarounds

Maybe add the instance via powershell?

**Comment by ramonsmits** [comment]
I don't know, its an observation and to me it doesn't make sense to enforce this.

It would also just be a warning or require a "trust me, I know what I'm doing" check.

**Comment by awright18** [comment]
@ramonsmits I ran across this documentation about a[zero downtime upgrades](https://docs.particular.net/servicecontrol/upgrades/zero-downtime) that suggests using a remote audit instance that ingests messages from the same audit queue. So there is a scenario where that would be needed, but I don't believe this specific scenario is supported by the Service Control Management application.

**Comment by ramonsmits** [comment]
There is not much to "support" except that besides not blocking the port to also add the audit instance to the config of the primary instance.

**Comment by mauroservienti** [comment]
Would that work using PowerShell?

**Comment by ramonsmits** [comment]
> Would that work using PowerShell?

Not sure, would need to test it
