### ISSUE TITLE
Reduce the number of docker images by bundling all supported transports and persisters in a single image per instance typee

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#3582]
### Describe the suggested improvement

In #3528, we changed the primary, audit, and monitoring instances to enable loading transports and persisters from a subdirectory of the root directory. Currently, that change enables running each instance on the local machine via the IDE. The transports and persisters directories are copied from the deploy folder to the output folders at build time. A `transport.manifest` file has been added to each transport to mimic the audit instance persistence setup.
At startup, each instance will load all the transports and persistence manifest files from subfolders and setup the instance to use the specified transport and persistence (for audit) in its `app.config` file.

The transport and persisted can be selected, at runtime, via environment variables or config settings, and the instance will look first in the output/root directory and then in the subdirectories.

Those changes enable changing the structure of the docker images from this: https://github.com/Particular/ServiceControl/blob/335aed2bb0cc21c075d2b8f41784ee933bf4d381/src/ServiceControl.DockerImages/servicecontrol.transport-windows.dockerfile-template#L3-L7

to something like this (pseudo code):

```
WORKDIR /servicecontrol

ADD /deploy/Particular.ServiceControl/ServiceControl .
ADD /deploy/Particular.ServiceControl/Transports ./Transports
ADD /deploy/Particular.ServiceControl/Persisters ./Persisters
```

At runtime, the docker image will use the corresponding environment variable value to decide which transport and persister to load.

This change enables collapsing all docker images to one per instance type instead of one per transport and per instance type. With this change in place, we can deploy to Docker Hub only 6 images (three sidecars and three production images). This change should also fix, or at least greatly alleviate #3338

**Comment by WilliamBZA** [comment]
All transports have been bundled into the 3 docker images, the persistence is still separate but that brings the total images to 4. That should be sufficient to address this. Closing.
