### ISSUE TITLE
Custom checks can't be sorted and no default sorting order defined

### ISSUE THREAD

**Issue by synhershko** [Particular/ServiceControl#365]
In CustomChecksModule.cs where the HTTP endpoint `/customchecks` is defined there is no default sort order defined (I'd expect them to be sorted by reported_at desc), and there's no way of explicitly define it on query.

That is quite important especially for external consumers, and when there are custom checks defined on multiple endpoints that are being reported async

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers @Particular/servicepulse-maintainers thoughts on this one, should we gather requirements ?

**Comment by mauroservienti** [comment]
> should we gather requirements ?

Yes

**Comment by johnsimons** [comment]
This is currently not prioritised to be done any time soon, I will close this one for now and if we ever redesign ServicePulse to cater for this we will reopen this issue.
