### ISSUE TITLE
Provide custom registration of custom checks.

### ISSUE THREAD

**Issue by rosieks** [Particular/ServiceControl#371]
I would like to be able to register custom check by myself. Unfortunately nowadays it's not possible because `CustomChecksFeature` register all types that implement `ICustomCheck` and `IPeriodicCheck` despite of there is no parameterless constructor or type is generic.

**Comment by johnsimons** [comment]
Moved to https://github.com/Particular/ServiceControl.Plugin.Nsb6.CustomChecks/issues/10

**Comment by danielmarbach** [comment]
@rosieks A currently workaround would be this

    abstract class FtpStorageDirectoryCheck : PeriodicCheck
    {
    
       protected FtpStorageDirectoryCheck(string path) 
    }

    Ftp1DirectoryChecker : FtpStorageDirectoryCheck 
    {
        FtpStorageDirectoryCheck() : base("C:\Path1")
    }

    Ftp2DirectoryChecker : FtpStorageDirectoryCheck 
    {
        FtpStorageDirectoryCheck() : base("C:\Path2")
    }

Not beautiful but works.
