### ISSUE TITLE
Remove all Windows registry based configuration

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#385]
Since multiple instances of ServiceControl can reside on the one machine it is misleading to have the registry configuration. It's also problematic as the registry entries are used when a settings is not defined in the config file.  So a change to the registry entry can apply to multiple instances.

**Comment by johnsimons** [comment]
@gbiellem is this one done as part of 1.7?

**Comment by gbiellem** [comment]
@johnsimons  

Since completely removing the registry reader  was a breaking change we took an alternative approach,  The 1.7 installer now writes a more verbose config file which should mask the entries which we deemed shouldn't be common such as port number.

**Comment by johnsimons** [comment]
So what do we do here @gbiellem, keep this open?

**Comment by gbiellem** [comment]
Let's close it for now as we've worked around it.
