### ISSUE TITLE
Unify the validation logic in SCMU and Powershell 

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServiceControl#3877]
### Describe the suggested improvement

SCMU and Powershell have independent validation logic - due to the difference in how the validation feedback is shown to the user (UI vs Console). 

This makes it easy for the validation rules to diverge. The logic should be the same no matter how a management action is triggered i.e. from SCMU or Powershell console. 

It might, be also beneficial to enhance the validation logic to enable showing a "validation report". Currently, each validation rule throws an exception right away when a condition is not met.

**Comment by DavidBoike** [comment]
This was (accidentally) accomplished last year in https://github.com/Particular/ServiceControl/pull/3811
