### ISSUE TITLE
New-ServiceControlInstance -Transport parameter taking different values in v5.0.0

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#3886]
### Describe the bug

Before v5, when calling `New-ServiceControlInstance`, you could pass `RabbitMQ - Conventional routing topology (classic queues)` for the Transport parameter.  Now, i must pass `RabbitMQ.QuorumConventionalRouting`.  Is this a bug or an expected breaking change that was made?

### Steps to reproduce

Download Particular.ServiceControl.Management powershell module

**Comment by ramonsmits** [comment]
@TraGicCode yes, that is a breaking change. We now pass codes/keys instead of descriptions.

I've improved our upgrade guide based on your comment:

- https://github.com/Particular/docs.particular.net/pull/6364
