### ISSUE TITLE
V5 Bug - Maintenance Mode Broken

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#3889]
### Describe the bug

On ServiceControl v5, starting the instance in maintenance mode, always throws an error and the url never load anything in the browser

![image](https://github.com/Particular/ServiceControl/assets/6224270/1d60b745-769e-40e5-9810-96566e45d522)

### Steps to reproduce

Download v5, create a new instance, attempt to start servicecontrol

**Comment by ramonsmits** [comment]
@TraGicCode I'll try to reproduce it. What instance type(s) (primary, error) are effected?

**Comment by TraGicCode** [comment]
Thanks.  Wanted to verify if this one slipped through the cracks!

**Comment by ramonsmits** [comment]
Fixed in https://github.com/Particular/ServiceControl/releases/tag/5.0.2
