### ISSUE TITLE
Disk Space CustomCheck warning me that I have 99% disk space free

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#3897]
### Describe the bug

The Disk Space custom check is telling me I have 99% disk space free,  This is displayed in red in service pulse as though this is an error I need to deal with.  

![image](https://github.com/Particular/ServiceControl/assets/2351700/0b79e079-1eda-417f-a4dd-12753e3da663)

ServiceControl Version is  5.01   
Windows Server 2019     

### Steps to reproduce

Installed ServiceControl on C:  but placed data on E:

### Relevant log output

```shell
N/A
```

**Comment by SzymonPobiega** [comment]
Thanks @gbiellem for reporting it! I've reproduced it with a fresh installation of SC 5.0.1 and labeled as `priority` in the triage process.

**Comment by ramonsmits** [comment]
Fixed in https://github.com/Particular/ServiceControl/releases/tag/5.0.4
