### ISSUE TITLE
Dismissing a CustomCheck in ServicePulse is rejected by ServiceControl 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#3898]
### Describe the bug

Call to dismiss a custom check in Service Pulse is rejected by Service Control.

![image](https://github.com/Particular/ServiceControl/assets/2351700/265484ae-f138-4143-8e76-f6069eb84498)

ServiceControl: 5.01
ServicePulse: 1.37
Browser: FireFox 120.0,1

### Steps to reproduce

After install of 5.01 I got an erroneous custom check about DiskSpace on the SP Dashboard ( See #3897)
Opened the Custom Check Tab in ServicePulse
Clicked the Dismiss buttom against the custom check. 
 Nothing happens except for error in console provided  in the description

**Comment by SzymonPobiega** [comment]
Thanks @gbiellem for reporting it! I've reproduced it with a fresh installation of SC 5.0.1 and labeled as `priority` in the triage process.

**Comment by soujay** [comment]
The bug has been addressed and released in [ServicePulse 1.37.1](https://github.com/Particular/ServicePulse/releases/tag/1.37.1)
