### ISSUE TITLE
SCMU: Cannot enter `/` or `_` in Service Account Name / Password

### ISSUE THREAD

**Issue by demoversionOo** [Particular/ServiceControl#3906]
#### Description
In Service Control Management, while adding a new Instance - I am not able to type neither dashes nor underscores in the Service Account Section (Account Name and Password Field). The Key instead checks or unchecks the Checkbox for the Expansion Panels Service Control (Audit).

Not sure if this is relevant: I use a German QWERTZ Keyboard.

#### Expected behavior

The inputs should work as expected.

#### Actual behavior

Characters are not typed.

#### Versions

Tested in Version 5.0.3 of Service Control Management

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

- Open Service Control Management.
- Open Wizard to add a new Instance
- Try to type dash or underscore in the listed input boxes.

#### Workarounds

Copy and Paste of the strings works fine.

#### Additional information
German QWERTZ Keyboard Layout was used.

**Comment by ramonsmits** [comment]
I can confirm that I cannot enter all special characters in the "Service account" and "Password" fields with both NL and US keyboard layouts and I also cannot enter `-`, `+`, and `=`.

However, as a workaround it seems possible to paste these characters from the clipboard. Unfortunately I don't have a local useraccount to validate if this works when selecting ADD.

**Comment by awright18** [comment]
According to this [Microsoft Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.serviceinstaller.servicename?view=netframework-4.8.1) Windows Service names cannot contain forward (/) or back slashes (\).

**Comment by awright18** [comment]
After researching this issue it appears this is a default behavior of WPF and the checkboxes need be explicitly modified so that they don't handle these events. https://stackoverflow.com/questions/49213841/prevent-wpf-checkbox-from-checking-unchecking-with-the-keys

**Comment by soujay** [comment]
@demoversionOo - We have been able to recreate the bug and a fix for it will be released in our next release cycle.

**Comment by soujay** [comment]
The fix has been released [5.0.4](https://github.com/Particular/ServiceControl/releases/tag/5.0.4) and [4.33.2](https://github.com/Particular/ServiceControl/releases/tag/4.33.2)
