### ISSUE TITLE
Incorrect ordering of events in Dashboard and Events page

### ISSUE THREAD

**Issue by saschanm** [Particular/ServiceControl#3921]
#### Description
When viewing ServiceControl events via ServicePulse either from dashboard (last 10 events) or via Events tab (all events - paged) the returned results are incorrectly showing oldest first rather than most recent first.

#### Expected behavior
1) Dashboard should show most recent 10 events
2) Events tab should show most recent first (page 1)

#### Actual behavior
Dashboard shows the oldest retained events (14 day retention) so need to drill down into events tab to see recent events.
Events tab also in reverse order, so we have to go to last page to see most recent events.

Note also there is another bug that means that last page also includes some old events, adding a further impedence to viewing recent events - see:

- https://github.com/Particular/ServicePulse/issues/1559

####
This appears to have been introduced when upgrading Service Control instance to v5 - currently on v5.0.3 

### Steps to reproduce

Open ServicePulse to dashboard and see most recent events are old.

**Comment by soujay** [comment]
@saschanm - Thank for reporting the bug.

**Comment by soujay** [comment]
This has been released in [ServiceControl 5.0.4](https://github.com/Particular/ServiceControl/releases/tag/5.0.4)
