### ISSUE TITLE
Search is Very Confusing and/or Broken

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceControl#399]
<a href="https://github.com/fafachd"><img src="https://avatars.githubusercontent.com/u/13546?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fafachd](https://github.com/fafachd)**
_23/10/2014 6:51:06 PM +00:00_

_Originally opened as https://github.com/Particular/ServiceInsight/issues/406_

----

V 1.1.7
Commit Hash: 96c4a2e

If I search for "systematicwithdrawalcommand", SI returns SystematicWithdrawalCommand messages but no TlsSystematicWithdrawalCommand:
![systematicwithdrawalcommand](https://cloud.githubusercontent.com/assets/13546/4759144/2811f4c4-5ae5-11e4-8909-377d9c32812b.png)

If I search for "systematicwithdrawal", SI returns TlsSystematicWithdrawalCommands but no SystematicWithdrawalCommands:
![systematicwithdrawal](https://cloud.githubusercontent.com/assets/13546/4759155/47c89426-5ae5-11e4-8176-b0a0e6f0cd7e.png)

If I search for "systematic", SI returns other message types that have "systematic" in their bodies, but SI doesn't return any of the systematic withdrawal commands from above:
![systematic](https://cloud.githubusercontent.com/assets/13546/4759161/4fa0991e-5ae5-11e4-93d0-b701a8b411d1.png)

I'm very confused!

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers not sure what to do to this, we have been talking about it for a while, but nothing done, so close it ?

**Comment by mauroservienti** [comment]
I think that this needs to be fixed/improved sooner or later, shall we prioritize this instead if closing?

**Comment by fafachd** [comment]
You know my vote!

**Comment by johnsimons** [comment]
> shall we prioritize this instead if closing?

Go for it @mauroservienti, but if nothing happens for another 6mths, I say we close it

**Comment by mauroservienti** [comment]
I'll assign it to me and look for a Task Force. @boblangley wanna join?

**Comment by boblangley** [comment]
@mauroservienti Count me in.

**Comment by mauroservienti** [comment]
I don't think we have capacity, at least I don't have, right now to tackle this. I shared with @boblangley what should be the high level plan of attack:

* form a proper task force
* better define the requirements in the description of the issue
* Involve @fafachd to validate our assumptions
* Define a plane of attack listing the changes we propose in SC
* Involve the SC maintainers to validate requirements and plan of attack
* implement
* test, test impact on perf
* ship

Thoughts?

**Comment by johnsimons** [comment]
@mauroservienti @boblangley do you see anything happening here in the next 6mths ?

**Comment by mauroservienti** [comment]
No, at least not given my actual capacity.

**Comment by johnsimons** [comment]
I'll close this one for now, once we ready to tackle this one, we will reopen it.
