### ISSUE TITLE
Validation in SCMU does compute intense tasks that can take more than a second, decreasing the user experience significantly

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#4127]
With the changes introduced in 5.1.0 (probably primarily https://github.com/Particular/ServiceControl/pull/4046) the validation is now properly wired up. Some of these validations are quite compute intensive and lead to deteriorating the user experience. 

Example profile of 5.0.5 of selecting a transport

![image](https://github.com/Particular/ServiceControl/assets/174258/10603ceb-2120-4298-a09e-4f7dd20c5441)

Example profile of 5.1.1 selecting a transport

![image](https://github.com/Particular/ServiceControl/assets/174258/9e900cf8-9c99-4f00-9975-da155d700d41)

UsedPath validation can for example, take almost 2 seconds to enumerate the registry of all known instances, which causes the transport selection to hang noticeably. 

![image](https://github.com/Particular/ServiceControl/assets/174258/99207968-a26e-4b26-9c39-c005dfbf7f31)

This problem affects all input fields that have validation. You'll experience a significant slowdown even in port selection or name text boxes.

#### Describe the suggested solution

Some of the information we use in the validation can be cached and/or refreshed in the background. For all instance finding methods we can invalidate the cache when a new instance is added. Of course, if someone has SCMU open and installs things with powershell SCMU might not catch up but in the worst case we could invalidate all caches when someone explicitly hits the refresh button on SCMU

**Comment by WilliamBZA** [comment]
This will be improved sufficiently in 5.1.2
