### ISSUE TITLE
ServiceControl audit store acceptance criteria

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#413]
Assuming two possible topologies
 * Storage nodes collocated with endpoints (each endpoint hosts a storage node)
 * Storage nodes form a separate cluster (SC cluster)

Acceptance criteria for the spike
* Loading throughput of 5Kmsg/s per node in cluster mode or 1Kmsg/s in collocated mode
* Deleting throughput at least same as loading throughput
* Ability to query messages by:
   * id
   * endpoint name
   * keyword (full-text search)
   * endpoint name and keyword

**Comment by johnsimons** [comment]
@SzymonPobiega not following what this is ? Can it be closed ?

**Comment by SzymonPobiega** [comment]
Yeah, not relevant any more.
