### ISSUE TITLE
Windows Service wasn't terminated after service control instance was removed.

### ISSUE THREAD

**Issue by bh3605** [Particular/ServiceControl#4143]
#### Description
Removed a service control instance and when I created a new one w/ the same one found the previous one was still lingering
#### Expected behavior
The windows service is removed when the service control instance is removed.
#### Actual behavior
The windows service was not removed
#### Versions
5.1.1
Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Add a Service Control instance (ASB if that really matters)
Remove it
Add it back. Warning in UI says Windows Service with this name already exists.

**Comment by andreasohlund** [comment]
Hi @bh3605 I was trying to reproduce this on 5.1.1 but it all worked on my end 

1. Installed a fresh ServiceControl main + audit instance
2. Removed both
3. Verified that Windows services were removed
4. Installed them again with the same name

Can you share some more details to help us pinpoint the issue? 

Was there anything in the [logs](https://docs.particular.net/servicecontrol/logging) that looked suspicious?
Was there any error shown in the ServiceControl management utility when you uninstalled it?
Anything in the windows event log at the time of uninstallation?

**Comment by andreasohlund** [comment]
@bh3605 did you get this sorted out?

**Comment by bh3605** [comment]
I'm not sure what happened. I wasn't able to replicate. Maybe it was a typo somewhere? Probably not since I was using the UI then used the PowerShell CLI to investigate why I couldn't use the same name. All is working now.

**Comment by ramonsmits** [comment]
This is fixed by:

- https://github.com/Particular/ServiceControl/pull/4217

It is part of ServiceControl 5.3.x

**Comment by bh3605** [comment]
oh sweet!
