### ISSUE TITLE
Need to also expire and delete saga data

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#415]
Messages are auto expired as detailed in https://github.com/Particular/ServiceControl/issues/116. 
We need to do the same for saga data.

**Comment by SzymonPobiega** [comment]
When splitting audits I included saga data in the expiry index so this should be fine.

**Comment by SimonCropp** [comment]
this is done

**Comment by johnsimons** [comment]
@SimonCropp is this still done ? We rollback develop

**Comment by SimonCropp** [comment]
@johnsimons where is the old develop?

**Comment by johnsimons** [comment]
@SimonCropp https://github.com/Particular/ServiceControl/tree/GenericGroupSpike

**Comment by SzymonPobiega** [comment]
before resetting develop I made a copy here https://github.com/Particular/ServiceControl/tree/extracted-audits
