### ISSUE TITLE
Stop forwarding SagaAudit messages from the primary instance to the audit instance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#4177]
The primary instance forwards SagaAudit message to the audit instance and logs a warning:

https://github.com/Particular/ServiceControl/blob/6fe6ededf5bcf70f8dae1f7201d29c7b87fcd448/src/ServiceControl/SagaAudit/SagaUpdatedHandler.cs#L28-L30

As the comment mentions, in v6, we want to remove that behavior. Evaluate if it's worth throwing an error.

**Comment by DavidBoike** [comment]
Decided not to deprecate this "workaround" after all, as it provides a self-healing aspect to a misconfigured ServiceControl system. Instead we will elevate the log warning to a custom check that will be visible in ServicePulse in https://github.com/Particular/ServiceControl/pull/4523.
