### ISSUE TITLE
Service Control install doesn't check for NSB Perf Counters

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#418]
Service Control uses the NSB Perf Counters [here] (https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Operations/MsmqAuditImporterPerformanceCounters.cs) but neither the MSI install or the command line check for their presence or install them.

If the install is kicked off through chocolatey the perf counters are installed as the choco package lists the NServiceBus.PerCounters,Install package as a prerequisite

**Comment by johnsimons** [comment]
@gbiellem is this still an issue?

**Comment by gbiellem** [comment]
@johnsimons Since 1.7 is NSB 5 it shouldn;t be an issue. Right?

**Comment by johnsimons** [comment]
Good point @gbiellem, I think so

**Comment by johnsimons** [comment]
So do we close?

**Comment by gbiellem** [comment]
I think so
