### ISSUE TITLE
Throughput queue named incorrectly

### ISSUE THREAD

**Issue by bh3605** [Particular/ServiceControl#4343]
#### Description

Found this throughput data queue when I created a service control and audit instance. It's missing the prefix "nservicebus". Tried looking up what it's for and I don't have a clue

![image](https://github.com/user-attachments/assets/61e70ee0-c117-443d-a284-9228cee97539)

#### Expected behavior

All queues are named correctly

#### Actual behavior

This throughput queue was possibly named incorrectly.

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Create a service control instance named nservicebus.servicecontrol and an audit instance named nservicebus.servicecontrol.audit

**Comment by jpalac** [comment]
This queue is used to collect usage data - it has a default value of `ServiceControl.ThroughputData` to minimise the setup required for users. Documentation can be found [here](https://docs.particular.net/servicecontrol/servicecontrol-instances/configuration#usage-reporting-when-using-servicecontrol-licensingcomponentservicecontrolthroughputdataqueue).

**Comment by Jokelab** [comment]
It becomes a problem when you must follow naming conventions for queue resources in an (Azure) servicebus. It is also an annoying exception when trying to script the deployment of the queues in a uniform way.
