### ISSUE TITLE
Scheduling DocumentExpiry too frequently causes high CPU utilization

### ISSUE THREAD

**Issue by Romiko** [Particular/ServiceControl#435]
Hi,

I did a stress test to send around 50 000 messages. I notice SC using over 75% of the CPU. Is it possible to throttle this? I need a way to allow SC to work, but not use so much CPU power.

**Comment by Romiko** [comment]
Hi,

   - Which version of SC have you been using?

Using File versiuon 1.4.1.0.

   - Which transport?

using msmq

   - How many messages per second have been processed?

Roughly 5 to 10 per second


   - What's the spec of the machine

[image: Inline image 2]


[image: Inline image 1]

On Mon, Dec 29, 2014 at 3:28 PM, Szymon Pobiega <notifications@github.com>
wrote:

> Hey
>
> Few questions:
>
>    - Which version of SC have you been using?
>    - Which transport?
>    - How many messages per second have been processed?
>    - What's the spec of the machine
>
> When doing our internal tests SC has not been eating a significant portion
> of a decent AWS box even when maxed out throughput (@350
> <https://github.com/350> msg/s).
>
> Generally you can throttle on transport level if needed
> http://docs.particular.net/nservicebus/how-to-reduce-throughput-of-an-endpoint.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceControl/issues/435#issuecomment-68231780>
> .
>



-- 
Romiko Derbynew
*Mobile:* +61 4000 90251
*Email:* romikov@gmail.com

*Website: *http://rangerrom.com
*Blog: *http://rangerrom.com/blog

**Comment by indualagarsamy** [comment]
@Romiko:
While we investigate this further, can you please see if changing the configuration to a longer duration helps with the CPU consumption?
Frequent deletes could cause RavenDB to get re-indexed and could cause this according to this:
https://groups.google.com/forum/#!msg/ravendb/3tszl0VlhHg/n_19MxB_HfMJ

Also if you can let us know, after extending the duration and if the problem was resolved, that would be great.

**Comment by Romiko** [comment]
Hi,

I have the following settings.
<add key="ServiceControl/ExpirationProcessTimerInSeconds" value="120" />
<add key="ServiceControl/HoursToKeepMessagesBeforeExpiring" value="12" />

What do you recommend I set them to?

On Wed, Jan 7, 2015 at 8:08 AM, Indu Alagarsamy <notifications@github.com>
wrote:

> @Romiko <https://github.com/Romiko>:
> While we investigate this further, can you please see if changing the
> configuration to a longer duration helps with the CPU consumption?
> Frequent deletes could cause RavenDB to get re-indexed and could cause
> this according to this:
> https://groups.google.com/forum/#!msg/ravendb/3tszl0VlhHg/n_19MxB_HfMJ
>
> Also if you can let us know, after extending the duration and if the
> problem was resolved, that would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceControl/issues/435#issuecomment-68933960>
> .
>



-- 
Romiko Derbynew
*Mobile:* +61 4000 90251
*Email:* romikov@gmail.com

*Website: *http://rangerrom.com
*Blog: *http://rangerrom.com/blog

**Comment by indualagarsamy** [comment]
@Romiko 
The default value for `ExpirationProcessTimerInSeconds` is `600` (10 mins)
and the default value for `HoursToKeepMessagesBeforeExpiring` is `720` (a month)

Can you set the value for `HoursToKeepMessagesBeforeExpiring` to `168` ? (i.e. a week)
And see if that helps?

What is your message load?

**Comment by gbiellem** [comment]
Hi @Romiko   

Just to clarify what @indualagarsamy  said above.  
Please adjust `ExpirationProcessTimerInSeconds` not just the  `HoursToKeepMessagesBeforeExpiring`.    

If you only adjust the `HoursToKeepMessagesBeforeExpiring` you're only delaying deletion processing til you have something that is a week old in your DB.

We'll look at either changing the `ExpirationProcessTimerInSeconds` setting name to something that does not imply it should be set to run so frequently  (breaking change) or implementing a lower limit to prevent it from doing so.

**Comment by Romiko** [comment]
Hi,

I have them both on
<add key="ServiceControl/ExpirationProcessTimerInSeconds" value="120" />
<add key="ServiceControl/HoursToKeepMessagesBeforeExpiring" value="30" />


I have disabled SC in production. I will wait for the next release where
the following are hopefully improved:

1. Concurrency with PUT operations on SLR in Raven
2. Memory Utilization

On Thu, Jan 8, 2015 at 12:04 PM, Greg Bielleman <notifications@github.com>
wrote:

> Hi @Romiko <https://github.com/Romiko>
>
> Just to clarify what @indualagarsamy <https://github.com/indualagarsamy>
> said above.
>
> Please adjust ExpirationProcessTimerInSeconds not just the
> HoursToKeepMessagesBeforeExpiring.
>
> If you only adjust the HoursToKeepMessagesBeforeExpiring you're only
> delaying deletion processing til you have something that is a week old in
> your DB.
>
> We'll look at either changing the ExpirationProcessTimerInSeconds setting
> name to something that does not imply it should be set to run so frequently
> (breaking change) or implementing a lower limit to prevent it from doing
> so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceControl/issues/435#issuecomment-69120692>
> .
>



-- 
Romiko Derbynew
*Mobile:* +61 4000 90251
*Email:* romikov@gmail.com

*Website: *http://rangerrom.com
*Blog: *http://rangerrom.com/blog

**Comment by johnsimons** [comment]
Is this still an issue @Romiko ?

**Comment by johnsimons** [comment]
No reply from user
