### ISSUE TITLE
ServiceControl Windows Service should depend on MSMQ and MSDTC

### ISSUE THREAD

**Issue by sveinfid** [Particular/ServiceControl#439]
The ServiceControl Windows Service should depend on MSMQ and MSDTC

As of now, we have experienced problems when rebooting our production servers.
Sometimes ServiceControl isn't started automatically due to the fact that MSMQ hasn't been started yet.

Error message in Application Event Log:

Service cannot be started. System.InvalidOperationException: There is a problem with the input queue: FormatName:DIRECT=OS:<server_name>\private$\Particular.ServiceControl. See the enclosed exception for details. ---> System.Messaging.MessageQueueException: Message Queue service is not available.

**Comment by gbiellem** [comment]
Hi @sveinfid 

I'll tweak the install to add the service dependency.  In the meantime you can manually do this from the command line:

```
sc config particular.servicecontrol depend= MSMQ
```

**Comment by gbiellem** [comment]
After thinking about this, it's not as straight forward as adding the services dependencies as these dependencies would need to be altered if the transport isn't MSMQ. This looks like another reason to revamp the SC installation to include transport configuration

**Comment by gbiellem** [comment]
Closing this as it'll be addressed in ServiceControlInstaller
