### ISSUE TITLE
ServiceControl creates duplicate messages in the DB if the log queue is not writable

### ISSUE THREAD

**Issue by mackie1001** [Particular/ServiceControl#440]
Please refer to this discussion topic for more details: https://groups.google.com/forum/#!topic/particularsoftware/dlorCAKqHcY

Summary of my findings:

I think if you have the option to copy messages to a further audit queue turned on but for whatever reason it fails (in my case it not having permission) it still writes the message to the FailedMessages/ProcessedMessages as well as the FailedAuditImports/FailedErrorImports collections. This means than on restart it will process FailedErrorImports and FailedAuditImports again and create a duplicate in FailedMessages/ProcessedMessages. If the problem persists then it's possible to create multiple duplicates like this.

I propose that if the import process fails to write to the .log queue then it should roll back the write to FailedMessages/ProcessedMessages and only write to FailedAudtiImports/FailedErrorImports. Some form of deduplication check on import would be a good catch-all too but might affect performance significantly (I'm no RavenDB expert!)
![servicecontrol duplicates](https://cloud.githubusercontent.com/assets/2169646/5835235/07dce7f8-a15e-11e4-9b5d-acf1caf65f96.png)

It might be an idea to check that the .log queues can be written to before allowing the service to start too. Better that than potentially failing import of thousands of messages all for the same reason.

**Comment by indualagarsamy** [comment]
@mackie1001 - that sounds like a bug to me. We'll look into it and keep you posted.

**Comment by johnsimons** [comment]
Because we do not use distributed transactions this is impossible to achieve.
Even if we write first to the .log queue then we could end up failing the write to db and end with duplicates in the forwarding queue.
Which one is worse, not sure.

**Comment by mackie1001** [comment]
I think just testing the log queues for writeability on startup would have prevented the issue I had. 
Is it possible to make distributed transactions an option for ServiceControl or is that too far removed from the existing approach?
As for which is worse, duplicates in the DB causes strange display issues and crashes in ServiceInsight but then if someone wants to replay their error queue and they don't have idempotent handlers duplicates in the log queue could actually break stuff.

**Comment by indualagarsamy** [comment]
Since the user has setup either `error.log` or `audit.log` , if we can't forward it to them, then maybe we can trigger a circuit breaker for it.
Since error.log and audit.log affects all endpoints, I see this as a valid point for shutting down SC. 
Thoughts? @gbiellem @johnsimons ?

**Comment by gbiellem** [comment]
-1 The long term goal is to have ServiceControl be the source of routing and other compnenets so we shouldn't shut it down because one piece of the puzzle is misbehaving. I'd prefer we stop the ingestion process, flag it on SP and once the user has fixed the problemwe allow them to start it again

**Comment by gbiellem** [comment]
@mackie1001  unfortunately the ravendb bulk insert api doesn't support DTC so it would be a big change

**Comment by gbiellem** [comment]
@johnsimons  do you want to implement the change you suggested for this?

**Comment by johnsimons** [comment]
@gbiellem not sure, do you consider this critical?

**Comment by gbiellem** [comment]
@johnsimons IMO we should just test the log queues for existance/writeability on startup as suggested by @mackie1001 to minimize the possibility of it happening.  I'm not certain about the option we discussed as it just shifts the duplication problem to the audit.log queue.

**Comment by johnsimons** [comment]
agree, that sounds good.
Raise a different issue?
