### ISSUE TITLE
ServiceControl failing to import messages, stopping

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#445]
Version: 1.4.3

### Symptoms:

SC fails to import messages with following error:

2015-02-02 08:26:37.0941|46|Info|NServiceBus.Unicast.Transport.TransportReceiver
|Failed to process message
System.Collections.Generic.KeyNotFoundException: The given key was not present i
n the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceControl.Contracts.Operations.ImportFailedMessage..ctor(TransportMes
sage message) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\Contract
s\Operations\ImportFailedMessage.cs:line 10
   at ServiceControl.Operations.ErrorQueueImport.InnerHandle(TransportMessage me
ssage) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\Operations\Erro
rQueueImport.cs:line 36
   at ServiceControl.Operations.ErrorQueueImport.Handle(TransportMessage message
) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\Operations\ErrorQueu
eImport.cs:line 31
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object send
er, TransportMessageReceivedEventArgs e, ISatellite satellite) in c:\BuildAgent\
work\1b05a2fea6e4cd32\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line
92
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived
(TransportMessage msg) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Co
re\Unicast\Transport\TransportReceiver.cs:line 453   at NServiceBus.Unicast.Tran
sport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\BuildAgen
t\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Transport\TransportReceiver
.cs:line 390
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessag
e message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\T
ransport\TransportReceiver.cs:line 260
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in c:\BuildAgent\
work\1b05a2fea6e4cd32\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.c
s:line 207

The message that failed to import is following:
```
"Message": {
    "Id": "bde7ee4b-57ae-40f4-a9a6-a43300924379",
    "IdForCorrelation": "bde7ee4b-57ae-40f4-a9a6-a43300924379",
    "CorrelationId": "b8ecb7d9-644b-4990-9b57-a41f00f1c196",
    "ReplyToAddress": {
      "Queue": "[SomeAddress]",
      "Machine": "[SomeMachine]"
    },
    "Recoverable": true,
    "MessageIntent": 1,
    "TimeToBeReceived": "49710.06:28:15",
    "Headers": {
      "NServiceBus.MessageId": "bde7ee4b-57ae-40f4-a9a6-a43300924379",
      "NServiceBus.CorrelationId": "b8ecb7d9-644b-4990-9b57-a41f00f1c196",
      "NServiceBus.OriginatingEndpoint": "Particular.ServiceControl",
      "$.diagnostics.originating.hostid": "6c78c59ba24d55c0a4e9743e368c9d08",
      "NServiceBus.MessageIntent": "Send",
      "NServiceBus.Version": "4.6.5",
      "NServiceBus.TimeSent": "2015-02-02 08:52:31:762900 Z",
      "NServiceBus.OriginatingMachine": "[SomeMachine]"
    },
```

The config file:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<configuration>
  <appSettings>
    <add key="ServiceControl/DbPath" value="D:\ParticularSoftware\ServiceControl\Database" />
    <add key="ServiceControl/Hostname" value="*" />
    <add key="ServiceControl/Port" value="33333" />
 
    <add key="ServiceBus/AuditQueue" value="[SomeName].Audit" />
    <add key="ServiceBus/ErrorQueue" value="[SomeName].Error" />
   
    <add key="ServiceControl/ForwardAuditMessages" value="true" />
    <add key="ServiceBus/AuditLogQueue" value="[SomeName].Audit.log" />
    <add key="ServiceBus/ErrorLogQueue" value="[SomeName].Error.log" />
   
    <add key="ServiceControl/HoursToKeepMessagesBeforeExpiring" value="720" />
   
    <add key="ServiceControl/TransportType" value="NServiceBus.Msmq, NServiceBus.Core" />
    <add key="NServiceBus/Transport" value="" />
  </appSettings>
</configuration>
```

**Related Google Post:** https://groups.google.com/forum/#!topic/particularsoftware/dlorCAKqHcY

**Comment by SzymonPobiega** [comment]
@indualagarsamy @gbiellem @sfarmar Here's the issue documenting Paul's problem. I have the original message that caused it if you need it.

**Comment by indualagarsamy** [comment]
@SzymonPobiega - can you please add the original message when you get a chance to https://nservicebus.desk.com/agent/case/8963

**Comment by SzymonPobiega** [comment]
Added

**Comment by indualagarsamy** [comment]
**Root Cause**
If an error message arrives to the error queue it can get failed to get imported improperly for the following reasons:
- We can't generate a unique Id (using the MessageId and the ProcessingEndpointName) - results in an [exception](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Infrastructure/TransportMessageExtensions.cs#L35)
- Or the FailedQ header isn't present.  (results in [Key Not Found exception](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Contracts/Operations/ImportFailedMessage.cs#L31))

In both cases an exception will be thrown. This results in
- the exception detail written to disk where the `[ConfiguredPathForLogFiles]\FailedImports\Error` and not the `Particular.ServiceControl.Errors` queue as the ErrorImporter is an advanced satellite that has its own custom fault manager. 
- the message itself is saved in the RavenDB storage under the `FailedErrorImports`  collection.

The problem here is that, during the retry process within ServiceControl, the headers get overwritten, i.e. the `OriginatingEndpoint` becomes `Particular.ServiceControl` which is incorrect.

Also if the number of FailedErrorImports increases within a short span, it can also trigger the circuit breaker to cause a shutdown.

**Comment by SzymonPobiega** [comment]
The reason why a message without a mandatory header arrived at the queue this time was that the reimporting process loses the headers while deserializing messages from the database. The original headers are lost and some default headers (like `OriginatingEndpoint`) are added. Such a message cannot be imported and goes (again) to the failed import collection in the database.

Because of the lost headers it is not possible to guess why the original message failed to imported in the first place. As a first step towards fixing this issue, we are going to release [1.5.1 hotfix](https://github.com/Particular/ServiceControl/pull/451) that disables the automatic reimporting.

**Comment by SzymonPobiega** [comment]
I think we prematurely closed this one, half way through solving the problem. The result is that now failed audit imports can never be reimported and customers won't even see the warning. Failed errors will generate the warning but there is nothing customers can do about it.
