### ISSUE TITLE
Remove the MSMQ batch importer

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#450]
Since we're throttling the import to 300 msg/s anyway there is no need for the batch imports in the future.

I propose that we remove https://github.com/Particular/ServiceControl/blob/fix-failed-imports/src/ServiceControl/Operations/Msmq/MsmqAuditQueueImporter.cs in order to clean up the code

**Comment by gbiellem** [comment]
@SzymonPobiega looking at develop this looks like it's been done as part of your refactoring efforts.

**Comment by SzymonPobiega** [comment]
That's correct. Closing this issue.

**Comment by gbiellem** [comment]
re opening since we're rolling back the refactoring in develop

**Comment by SzymonPobiega** [comment]
Since we're now working to list that artificial 300/s limit, does it still make sense to remove that thing? Maybe we need to find a place for it where it can live long and prosper?

**Comment by johnsimons** [comment]
This is done as part of the upgrade to NServiceBus v5 in 1.7.0 release
