### ISSUE TITLE
RequestRetryAll fails due to timeout

### ISSUE THREAD

**Issue by TheNr1Guest** [Particular/ServiceControl#452]
We recently had an outage which resulted in 20.000 failed messages. When trying to utilize the "Retry All" option via Service Pulse we see that the resulting RequestRetryAll message gets a timeout.

Furthermore, our RavenDB size is about 20GB.

The stacktrace:
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.TimeoutException: Transaction Timeout 
--- End of inner exception stack trace --- 
at System.Transactions.TransactionStateAborted.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState) 
at System.Transactions.CommittableTransaction.Commit() 
at System.Transactions.TransactionScope.InternalDispose() 
at System.Transactions.TransactionScope.Dispose() 
at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 260 
at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.Action(Object obj)

The machine it runs on:
![image](https://cloud.githubusercontent.com/assets/8267168/6229275/1dc31052-b6b6-11e4-9eb6-273d9c89dd08.png)

**Comment by SzymonPobiega** [comment]
@TheNr1Guest I assume from the stack trace that you are using RabiitMQ transport. The reason the timeout happens is the handler for this message tries to go through all the failed messages and re-send them in one go. What version of SC and NSB are you running?

@gbiellem @indualagarsamy can we tell SC to use longer timeout? I only found this machine.config max timeout thing.

**Comment by TheNr1Guest** [comment]
@SzymonPobiega Your assumptions are correct. About the versions:
SC: 1.4.2
NSB: 4.6.5
RMQ: 3.1.5

**Comment by gbiellem** [comment]
>can we tell SC to use longer timeout? 

@SzymonPobiega No that I'm aware of,  @johnsimons may better though

**Comment by johnsimons** [comment]
@SzymonPobiega we possible could configure SC to increase the transaction timeout but I still think that we need to address this issue in a different way, see #225 that I have raised before regarding some issue

**Comment by gbiellem** [comment]
@johnsimons so how do you think it should be addressed?

**Comment by johnsimons** [comment]
Not sure @gbiellem, happy to brainstorm it with u ?

**Comment by gbiellem** [comment]
Since it's part of the failedmessages screen that's beening revamped we should take it into account 
//cc @indualagarsamy  @sergioc

**Comment by johnsimons** [comment]
If we turn on DoNotWrapHandlersExecutionInATransactionScope, that should solve this issue

**Comment by johnsimons** [comment]
This is now fixed as part of https://github.com/Particular/ServiceControl/commit/21a2709e7303fe134f36da66e8459eb4672390ef

However, it takes way too long to replay all my messages :disappointed:

**Comment by danielmarbach** [comment]
@johnsimons @gbiellem @SzymonPobiega any ideas why this hasn't been merged as a hotfix in one of the latest 1.5.x releases? I have a case which stumbled over the same issue.

**Comment by johnsimons** [comment]
I guess it hasn't been seen as critical as maybe it should be?

**Comment by johnsimons** [comment]
And I didn't count on v1.6 take so long to be released

**Comment by gbiellem** [comment]
@johnsimons should this be reopened based on the refactor rollback?

**Comment by johnsimons** [comment]
@gbiellem no  need to, already released in master, https://github.com/Particular/ServiceControl/commit/1943a5f48238fb62c39e7c35081bcfc571875a50
