### ISSUE TITLE
Install Service doesn't work for Azure Storage Queues

### ISSUE THREAD

**Issue by tomsave** [Particular/ServiceControl#455]
## Who's affected
All users that are using `AzureStorageQueue` transport and have a key that ends with `==`.

## Symptoms
Following documentation here: http://docs.particular.net/servicecontrol/multi-transport-support

Using Windows Azure Storage Queues.

When I run the suggested command (using actual values for account name and account key)

:\Your_Installed_Path\ServiceControl.exe --install -serviceName=“Particular.ServiceControl” -displayName=“Particular ServiceControl” -d=“ServiceControl/TransportType==NServiceBus.AzureStorageQueue, NServiceBus.Azure.Transports.WindowsAzureStorageQueues” -d="NServiceBus/Transport==DefaultEndpointsProtocol=https;AccountName=[account-name];AccountKey=[account-key];"

I get the following error from ServiceControl

Error: Found 3 option values when expecting 2.
ServiceControl by Particular Software

The issue is because my base64 encoded account key ends with == (eg XXXXX/XXXXX+XXXXX....XXX==).  If I remove the trailing == from the account key, ServiceControl starts to install but it eventually fails since the key isn't correct.

It looks like your command argument parser is treating == as a token, rather than part of the connection string value

**Comment by gbiellem** [comment]
@johnsimons  do you want to take a look at this?

**Comment by johnsimons** [comment]
I'm pretty sure this has been raised before

**Comment by dvdstelt** [comment]
Is this bug back? Because I just installed 1.6.1 and have this problem again.

**Comment by johnsimons** [comment]
Very sorry @dvdstelt, We will add it to the next minor release

**Comment by dvdstelt** [comment]
Workaround is to remove one of the = from == and try to install it. Immediately ServiceControl says it can't connect to TableStorage Queues. But the config has been set. So open up the .config, add the additional = again, save it. And run the service.

**Comment by SeanFeldman** [comment]
Still broken. The [test for `Options`](https://github.com/Particular/ServiceControl/blob/dd5aaadf41bd7186b848473c99b70d491bb25d69/src/ServiceControl.UnitTests/ArgumentParsing/OptionsTests.cs#L12) is not parsing a correct string. 
It should test a quoted value:
```c#
@"-d=""ServiceControl/TransportType==NServiceBus.AzureStorageQueue, NServiceBus.Azure.Transports.WindowsAzureStorageQueues", "-d=NServiceBus/Transport==DefaultEndpointsProtocol=https;AccountName=account-name;AccountKey=XXXXX/XXXXX+XXXXX....XXX==;"""
```

**Comment by johnsimons** [comment]
@greg is this fixed in develop ?

**Comment by gbiellem** [comment]
@johnsimons  I'll test to be sure but really i'm inclined to pull out the command line switches out since the new installer in 1.7 makes them redundant IMO

**Comment by gbiellem** [comment]
Command line switches have been removed in 1.7 - refer https://github.com/Particular/ServiceControl/issues/570
