### ISSUE TITLE
Service control Crashes after changing the config file to new Audit and Error log 

### ISSUE THREAD

**Issue by sanilpaul** [Particular/ServiceControl#457]
Create a Nservicebus 5.2 Endpoint
set the config
    MessageForwardingInCaseOfFaultConfig ErrorQueue="N5Experiments.Error" 
    AuditConfig QueueName="N5Experiments.audit"

Install Service Control 1.5.1
Stop Service Control Service
Change the ServiceControlConfig.exe.config to the audit and error queues created above
Start the ServiceControl service
**Error : The Particular ServiceControl Service on LocalComputer Started and Stopped....** 
![image](https://cloud.githubusercontent.com/assets/484817/6802981/f4fc6ad6-d20a-11e4-98f9-eba3b62db220.png)

*The only way out is 
 uninstall service control
leave the updated config file in the service control installation directory
install service control*

**Comment by gbiellem** [comment]
Hi @sanilpaul 

This is expected.   This would be because ServiceControl requires access to the queues you've created.  The re-install will have modified the ACLs on the queue you've specified in the config.   We don't try and modify the ACLs on service start as we can't assume the service account has privileges to do this.  

Does that make sense?

**Comment by sanilpaul** [comment]
@gbiellem I understand its the permissions. this is only from the latest service control and I had noticed that the permissions were different. the version prior to this seems to work fine. 

Now are you saying that in order to get a service control on a new machine, pointing to a custom queue, we have to install it, put the custom config in the installation directory, uninstall it and reinstall again? if its the expected steps that really doesn't make sense. Let me know if there is any other way?

**Comment by gbiellem** [comment]
Hi @sanilpaul  

Sorry I misunderstood your question,  I thought you wanted to know why it was failing.
No you don't have to uninstall/reinstall the MSI  or copy a prepopulated .config file.
The easier way is to issue the following commands after the MSI installation

```
net stop particular.servicecontrol
servicecontrol.exe --install --d="ServiceBus/Error==N5Experiments.Error" --d="ServiceBus/Audit==N5Experiments.Audit"
net start particular.servicecontrol
```

This will add the entries to the .config file and set the ACLs on the queues and also create the queues if they don't exist

**Comment by gbiellem** [comment]
@sanilpaul  Did you need any more info on this or am I OK to close this issue?

**Comment by gbiellem** [comment]
No response so closing

**Comment by sanilpaul** [comment]
@gbiellem So the .Config file will have the previous Error/Audit queues. Do we have to manually delete the previous ones?

**Comment by gbiellem** [comment]
Hi @sanilpaul  

I had no idea what you meant about multiple entries until I double checked what I wrote above.
I owe you an apology,  I somehow messed up the command line switches I gave you above

I told you:

```bat
--d="ServiceBus/Error==N5Experiments.Error" --d="ServiceBus/Audit==N5Experiments.Audit"
```
but it should have been 

```bat
--d="ServiceBus/ErrorQueue==N5Experiments.Error" d="ServiceBus/AuditQueue==N5Experiments.Audit"
```

So the ServiceControl.exe.config should have end up looking something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings>
        <add key="ServiceControl/ForwardAuditMessages" value="true" />
        <add key="ServiceBus/ErrorQueue" value="N5Experiments.Error" />
        <add key="ServiceBus/AuditQueue" value="N5Experiments.Audit" />
    </appSettings>
</configuration>
```

I tested this config and realized you may hit another problem - The default forwarding queues names are based on the error and audit queue names.  So by changing them ServiceControl is going to expect two queues called N5Experiments.Error.log and N5Experiments.Audit.log which also aren't going to exist.  

You can also specify these on the --install command line so the resultant command line should be something something like:

```bat
net stop particular.servicecontrol
Servicecontrol.exe --install --d="ServiceBus/ErrorQueue==N5Experiments.Error" --d="ServiceBus/AuditQueue==N5Experiments.Audit" --d="ServiceBus/ErrorLogQueue==N5Experiments.Error.Log" --d="ServiceBus/AuditLogQueue==N5Experiments.Audit.Log"
net stop particular.servicecontrol
```
I assumed the Audit Log and Error Log queues would be based on the names you provided 
So the end result is a ServiceControl.exe.config is something like this.  

```xml
?xml version="1.0" encoding="utf-8"?>
configuration>
   <appSettings>
       <add key="ServiceControl/ForwardAuditMessages" value="true" />
       <add key="ServiceBus/ErrorQueue" value="N5Experiments.Error" />
       <add key="ServiceBus/AuditQueue" value="N5Experiments.Audit" />
       <add key="ServiceBus/ErrorLogQueue" value="N5Experiments.Error.Log" />
       <add key="ServiceBus/AuditLogQueue" value="N5Experiments.Audit.Log" />
   </appSettings>
/configuration>
```

Let me know how you go and it you need further assistance with this

**Comment by sanilpaul** [comment]
@gbiellem Thank you. I will try this in next couple of days and let you know. 

That probably explained why I didn't see any messages in service insight regardless of servicecontrol service running. I had to delete ravendb and reinstall service control leaving the updated config file in the installation directory, trying to force my way through. We have highly distributed systems and rely on the awesomeness of service control/insight for our debugging. If you can make switching queues easier that will be highly appreciated.

**Comment by gbiellem** [comment]
Hi @sanilpaul  

How did you go reconfiguring the queuenames.  Do you need anymore info.

**Comment by sanilpaul** [comment]
@gbiellem It worked. thanks
