### ISSUE TITLE
How to override the default "dbo" schema when using ServiceControl with SQL Server Transport?

### ISSUE THREAD

**Issue by pedroreys** [Particular/ServiceControl#459]
NServiceBus.SqlServer recently released a new version that allows to override the default "dbo" schema that is used by the SqlServerTransport when creating the queue tables.

How can I configure ServiceControl to look for the audit and error queues in a schema that is not "dbo"?

**Comment by gbiellem** [comment]
Hi @pedroreys

ServiceControl doesn't support that feature yet,  The current release  is built on NServiceBus 4.x.  and  that feature is only available for the SQL Transport for NServiceBus 5.x.  

This is something I'll raise internally as this is obviously a show stopper for you using ServiceControl to monitor your endpoints.

**Comment by pedroreys** [comment]
Thanks @gbiellem

**Comment by johnsimons** [comment]
Hi @pedroreys 

I did some research and I think the following will work (please be aware I have not tested this!).

Specify in ServiceControl the queue names to use for errors and audits, see http://docs.particular.net/servicecontrol/creating-config-file#configuration-options.  
Example:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<configuration>
  <appSettings>
      <add key="ServiceControl/AuditQueue" value="myschema.audit" />
      <add key="ServiceControl/ErrorQueue" value="myschema.error" />
      ...
  </appSettings>
</configuration>
```

Give this a go and let us know if it works.

**This only works if both audit and error tables are in the same database, if they are in separate dbs this won't work**

**Comment by johnsimons** [comment]
This will be supported from v1.7
