### ISSUE TITLE
Finish migrations

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#463]
Includes both saga audit documents and new failed message / processed message documents (3 migrations)

### Plan of attack

- [x] Make it work
- [x] Test performance (20 docs/s sagas, 50-100 docs/s processed/failed messages)
- [ ] Decide if performance is OK
- [ ] Add migration status UI to the health page
- [ ] Distinguish optional and mandatory migrations and allow users to disable/enable optional migrations as part of installation

**Comment by SzymonPobiega** [comment]
@andreasohlund @indualagarsamy does that match what we were talking about? /cc @SimonCropp @gbiellem

**Comment by indualagarsamy** [comment]
@SzymonPobiega - yes, only thing I'd add is that the migration would be a background process allowing SC to be functional after installation.

**Comment by gbiellem** [comment]
> Add migration status UI to the health page

What health page?

**Comment by SzymonPobiega** [comment]
@gbiellem the one @andreasohlund is proposing (https://github.com/Particular/Requirements/issues/240)

**Comment by gbiellem** [comment]
That's what I thought.  @andreasohlund backlogged Particular/Requirements#240  
So are we reviving that  as part of this?

**Comment by gbiellem** [comment]
@SzymonPobiega - are you still working on this?

**Comment by SzymonPobiega** [comment]
Not actively @gbiellem . @andreasohlund do you still believe in the health page? If so, can we pair up to get it accepted so that we can unlock this one? Or should we cut the scope here?

**Comment by gbiellem** [comment]
I'm still + 1 for the health page

**Comment by SzymonPobiega** [comment]
Health page is a relatively large effort so not sure if we want to block things. Do we still want to sync that with installer changes?

**Comment by andreasohlund** [comment]
Let's make all migrations mandatory for now and just run them? (how much does it impact performance for users with large DB's)

**Comment by SzymonPobiega** [comment]
Who's making the call if the performance I measured if fine?

**Comment by andreasohlund** [comment]
Not sure, do we have any numbers?

**Comment by SzymonPobiega** [comment]
Yes, in the description:)

**Comment by andreasohlund** [comment]
I think that's good, how much cpu/disk/memory is this churning while doing the migration? is SI/SP responsive during this?

**Comment by SzymonPobiega** [comment]
Not relevant any more.
