### ISSUE TITLE
Feature: Query sagas by type and completion state

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceControl#465]
It would be nice to be able to query sagas by saga type and completion state:

http://[host]:33333/api/sagas/?saga_type={sagatype]
http://[host]:33333/api/sagas/?completion_state={state}

Kind regards
Christian

**Comment by cjoergensen** [comment]
And to be able to sort Sagas by Start and Completion date

**Comment by johnsimons** [comment]
@cjoergensen what exactly would this be useful for ? Can you explain how you intend to use this capability ? Is it used outside ServiceInsight ?

**Comment by johnsimons** [comment]
Since our REST api is not supported for public consumption, we are not going ahead with this change.
