### ISSUE TITLE
An expired license can take precendence over an active one depending on where it is installed

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#466]
The license detection code in SC returns the first license that it finds when searching the following locations (in order)  :

<bin dir>\license\license.xml
<bin dir>\platformlicense.xml
HKCU:\SOFTWARE\ParticularSoftware\License
HKLM:\SOFTWARE\ParticularSoftware\License

This means if the user installs a new license in say HKLM:\SOFTWARE\ParticularSoftware\License and an older license exists in any of the other locations the new license will not be picked up.

**Comment by distantcam** [comment]
Hey! That's the same bug I had here Particular/ServiceInsight#362

**Comment by gbiellem** [comment]
Good to see we are consistent :)
