### ISSUE TITLE
Storage Emulator 100% with Azure Storage Queues

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceControl#470]
We're running NServiceBus over Azure Storage Queues. Running ServiceControl locally on the Azure Storage Emulator, pretty fast the storage emulator starts running at 100%. Upon shutting down the ServiceControl service, immediately the emulator runs at 0%.

We're not running ServiceControl in production yet because of this issue. We haven't checked if this is because of a lot of communication with the storage queues or anything, but I'm a bit afraid that ServiceControl will completely spam Azure Storage Queues once we activate it in production?

**Comment by gbiellem** [comment]
Hi @dvdstelt 

Can I get a bit more detail so we can try and repro the issue?
 - What version of ServiceControl are you running?
-  Do you have auditing turned on for endpoints? i.e Is SC collecting Audit and Error messages or just errors?
-  What SC plugins are running on the endpoints?

**Comment by dvdstelt** [comment]
FileVersion is 1.5.2.0 and I was running on storage queues via storage emulator.
Microsoft.Data.Services.Client.dll was downgraded to 5.6.0.61587 because latest installable version of ServiceControl doesn't work with Azure Storage Queues.

Auditing is indeed turned on and I have 4 endpoints sending data with the Heartbeat and SagaAudit plugins running. However, none of the 4 endpoints have to be running to produce the CPU spike in the Storage Emulator I was referring to.

**Comment by gbiellem** [comment]
Hi @dvdstelt 

I've not been able to replicate this so far.  I tried this with ServiceControl 1.5.2 using the Microsoft.Data.Services.Client.dll you specified and the one that comes out of the box using a assembly redirect.  On my PC the CPU sits at 20% against the Windows Azure Storage Emulator 3.4

What version of the emulator you using?  let me know and I'll retest

**Comment by dvdstelt** [comment]
Dunnow, just updated the SDK to the latest version because of another issue! :) Sorry...
With the original Microsoft.Data.Services.Client.dl and binding redirect it's now working for a few hours.

**Comment by gbiellem** [comment]
So CPU is more normal after the SDK update?

**Comment by dvdstelt** [comment]
Yeah, with the correct dll and latest sdk it's somewhere between 10% and 20%. Has never been that high, but that's extremely doable. :) I'll start it up and monitor it on the production environment soon.

**Comment by gbiellem** [comment]
Thanks.  I'll close the issue - Feel free to reopen it if you think it's not resolved. 

BTW - There's a known issue for high CPU usage with the emulator on MS Connect which might be related:  https://connect.microsoft.com/VisualStudio/feedback/details/790897/azure-local-storage-emulator-bug

**Comment by dvdstelt** [comment]
It's a ServiceControl issue. My emulator is running perfectly, until I start ServiceControl. I can start it right now and it immediately runs at 100%. A colleague of mine has the same problem. I'm not too familiar with ServiceControl and configuration to start intense logging, so I can send them to you.

**Comment by gbiellem** [comment]
@SeanFeldman Any advice here?

**Comment by SeanFeldman** [comment]
Issue with Storage Emulator is that it's an emulator :)
It's known for issues. Emulator also hides some of the things a real storage account would have (some exceptions, etc). If it's possible to execute against real Storage account rather than emulator, I'd advise that. Limit emulator for development and some testing, but that's it.

@dvdstelt is your storage emulator version 4.0?

**Comment by dvdstelt** [comment]
Yes it is.

And although it's just the emulator, I don't have any insight in messages or way to transfer messages from error queue back to original queue, which makes debugging & testing pretty hard. Is there a smaller tool than service insight to do this?

**Comment by SeanFeldman** [comment]
@dvdstelt I wish there would be a tool, but there's non. Here's a challenge: Storage Queues API support no more than 32 messages for peek. No tool (that I'm aware) does what you need. So it's either using SI or creating something custom. I have tried to ping MSFT to add tooling to the Azure portal (Ibiza), but haven't seen anything yet.

**Comment by gbiellem** [comment]
@dvdstelt I'm closing this as we've not repro'ed it and as @SeanFeldman suggested we' d recommend using Azure rather than the emulator.
