### ISSUE TITLE
System.Data.SqlClient.SqlException: Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'

### ISSUE THREAD

**Issue by sfarmar** [Particular/ServiceControl#471]
[Posted on the user group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/JLr4XvmvZEo/w7RhLGdG5-wJ)

Product name:Heartbeat + SqlTransport
Version:Heartbeat 1.0.0, SQLServer 2.0.0
Stacktrace: System.Data.SqlClient.SqlException: Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'
Description:

When installing a service using nservicebus.host (or even with a custom host), the heartbeat sends a control message to ServiceControl queue. If the queue is not accessible, a critical error is thrown and the installation fails.

The particular scenario we encountered is when we use automatic remote deployment using PS-Remoting or PSEXEC. With Windows 2008 and above the 2nd hop to the ServiceControl database is anonymous.

There is a way to solve the second hop securtity problem using CredSSP (http://blogs.technet.com/b/heyscriptingguy/archive/2012/11/14/enable-powershell-quot-second-hop-quot-functionality-with-credssp.aspx) which we haven't tested yet.

Invoking the same installation locally works fine as long as the ServiceControl queue exists.

It makes more sense to only issue a warning during installation and to issue a critical error at at startup (or not to send a control message during installation at all)

What we see is there is a bus instance created during installation and it doesn't have the proper security context to send messages during installation. Some of the platform's components are trying to send control messages at this point and it fails the installation process.

**Comment by gbiellem** [comment]
Hi @sfarmar 

I'm not following how is this an SC issue?  The problem is related NSB Host/Custom Host and the fact that when an endpoint installation is run the bus is created and run under the installer credentials.  To me this is a flaw with the core as it it mixes installation and initialization concerns in the name of providing the OOTB F5 experience for the developer.

**Comment by andreasohlund** [comment]
@gbiellem I think the problem here is that since the installers are initializing the bus to perform the install combined with the heartbeat plugin incorrectly hooking into `IWantToRunWhenConfigurationIsComplete` is causing a heartbeat to be sent during install? (which seem incorrect to me)

**Comment by gbiellem** [comment]
>  hooking into IWantToRunWhenConfigurationIsComplete is causing a heartbeat to be sent during install? (which seem incorrect to me)

@andreasohlund you requested that change so heartbeats would work on sendonly endpoints - See https://github.com/Particular/ServiceControl/issues/304.  

So where to now?  We can't hook to `IWantToRunWhenConfigurationIsComplete`  or `IWantToRunWhenTheBusStartsAndStops` without something being broken

**Comment by andreasohlund** [comment]
Sigh, what a mess. Should we get on a call to try to find a way out of this?

**Comment by gbiellem** [comment]
Definitely - I'll ping you tomorrow on slack and pull @indualagarsamy in as well as she's the plugin's caretaker

**Comment by sfarmar** [comment]
@gbiellem @andreasohlund As Greg said this is an installers issue related to authentication...

Shell w move it to the NServiceBus core repo?

**Comment by andreasohlund** [comment]
No, this is due to the fact that the plugin uses the wrong hook in the core

**Comment by gbiellem** [comment]
@sfarmar  there was a quick sync about this yesterday.  The upshot was that in the short term we rollback and use `IWantToRunWhenTheBusStartsAndStops`.  This will mean the plugin would no longer function for sendonly endpoints.   @indualagarsamy pointed out this is already the case with customchecks.

Longer term @andreasohlund also proposed investigating core changes as well - either adding an addition hook or some sort of installation flag.

**Comment by sfarmar** [comment]
@gbiellem thanks for the update!

**Comment by gbiellem** [comment]
Relates to Desk Case [#11212](https://nservicebus.desk.com/agent/case/11212)

**Comment by gbiellem** [comment]
@indualagarsamy as discussed I've assigned you this one

**Comment by gbiellem** [comment]
Note  the customer in the related desk case worked around the issue by not using the NSB host installation and using a script to register the service instead

**Comment by johnsimons** [comment]
@gbiellem is this still an issue, now with the release of the new installer?

**Comment by yossita** [comment]
I'm on vacation until mid November, I'll let you know then.

**Comment by yossita** [comment]
@johnsimons, we did a quick test with the new version and it seems it doesn't cause the insallation to fail anymore. Thanks for addressing this, however we decided to keep our current workaround in place.

**Comment by gbiellem** [comment]
new installer addressed this
