### ISSUE TITLE
ServiceControl 1.5.3 upgrade fails when Azure Storage Queues is the configured transport

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#480]
To Repro

Install ServiceControl 1.5.2
Install ASQ transport as per http://docs.particular.net/servicecontrol/multi-transport-support
Attempt to upgrade to 1.5.3 -> Boom

This will fail consistently.

**Comment by johnsimons** [comment]
Any ideas why?

**Comment by gbiellem** [comment]
@johnsimons -  Yep  I've worked it out. It's a version problem with Microsoft.WindowsAzure.Storage.dll.   Our instructions on docs say to use 3.1.0.1and put in an ASM redirect for that DLL but SC 1.5.3 clobbers it on upgrade with an older version.  

I'll fix it up an release it as 1.5.4
