### ISSUE TITLE
Black on black

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#504]
![image](https://cloud.githubusercontent.com/assets/122651/9593166/a702cd36-508e-11e5-95c5-be7f474f511f.png)

Email address text is black on black background, hard to read

**Comment by petersgiles** [comment]
![capture](https://cloud.githubusercontent.com/assets/1644481/9596031/8652ac9a-50b2-11e5-96e2-2072e101ba12.PNG)
