### ISSUE TITLE
No validation for email address

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#505]
![image](https://cloud.githubusercontent.com/assets/122651/9593201/0d55dfc4-508f-11e5-9f6c-371ad9b0bee8.png)

Should at least validate that email is in the correct format

**Comment by gbiellem** [comment]
@petersgiles  Not 100% fixed.  

If I add something to email field and then remove it the validation still prevents Send

**Comment by petersgiles** [comment]
ok I'm on it

**Comment by petersgiles** [comment]
https://github.com/Particular/ServiceControl/commit/3e5c5fa5b5712a7327ac74194b83f724be96a69f
