### ISSUE TITLE
Provide feedback to user when reporting bug

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#507]
![image](https://cloud.githubusercontent.com/assets/122651/9593420/5eb43d32-5091-11e5-9edb-bc706920091b.png)

It seems after I have clicked the "disabled" looking button caller "Report", the dialog freezes and no feedback of what is going on.
It would be nice to provide feedback that error is being submitted + success message.

**Comment by petersgiles** [comment]
Progress overlay added
