### ISSUE TITLE
Icon folder should be standard icon and positioned correctly

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#513]
![image](https://cloud.githubusercontent.com/assets/122651/9594214/8b11b378-509b-11e5-9269-64025b697c71.png)

At the moment it doesn't look like a folder icon and not positioned at the end of the text so it feels weird and easily missed out, and since the text is not selectable it is confusing how to open the folder.

Maybe allow the paths text to be selectable so users can still use copy

**Comment by gbiellem** [comment]
How about making the paths clickable links?

//cc @sergioc

**Comment by johnsimons** [comment]
IMHO this can be mitigated by:
- moving icon to end of text;
- using the default folder system icon;

**Comment by sergioc** [comment]
@gbiellem I think that's a good idea. Change the path text color too to the blue we use elsewhere on the app.

@johnsimons an icon is probably not needed anymore after turning the path into a link.

**Comment by distantcam** [comment]
How do people feel about this?

![image](https://cloud.githubusercontent.com/assets/1298847/9622622/061da17c-5168-11e5-9c1d-7213bb237a2c.png)

- Should the host link also be clickable?
- I swapped the host and the transport, good or bad?

**Comment by gbiellem** [comment]
> Should the host link also be clickable?

yeah seems sensible

> I swapped the host and the transport, good or bad?

:+1: I think that's a good call as host name is an unknown length.

**Comment by johnsimons** [comment]
:+1:

**Comment by sergioc** [comment]
:+1: @distantcam

**Comment by gbiellem** [comment]
@distantcam  - Looks like you did this in https://github.com/Particular/ServiceControl/commit/00d7b41f66bff36035806d57cbc48c62826c0eb1 
Is there still stuff to do or can we close it?
