### ISSUE TITLE
Validate text is supposed to be uppercase on all screens

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#519]
@sergioc pointed out that the validation text is supposed to be uppercase

**Comment by gbiellem** [comment]
@distantcam  @petersgiles  

I don't remember who was doing this one.

**Comment by petersgiles** [comment]
@distantcam said he was going to run with this if he is unable to I am happy to take a crack at writing a converter

**Comment by distantcam** [comment]
@petersgiles I'll assign you.

**Comment by petersgiles** [comment]
@distantcam and another WPF adventure begins :)

**Comment by petersgiles** [comment]
I've check the Add, Edit and Feedback screens all validations appear in Upper Case
