### ISSUE TITLE
Block start and stop service when service status is pending

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#525]
UI allows stop and start when the service is in a stop pending or strat pending state.  Click on either button throws an unhandled exception

**Comment by distantcam** [comment]
Ahem

![image](https://cloud.githubusercontent.com/assets/1298847/9714583/75d82c18-558b-11e5-99be-7f1d003f8a97.png)

**Comment by gbiellem** [comment]
@distantcam I fixed the displaying of icons to stop both icons showing however I noticed another related bug I need help with.  When multiple instances exist the those status icons are only present on the last instance in the list.

**Comment by gbiellem** [comment]
Closed - @distantcam  fixed it
