### ISSUE TITLE
Show error after clicking link to protected Log path instead of opening internet browser

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#529]
SC Management - Log Path link opens in internet browser instead of file explorer:

https://dl.dropboxusercontent.com/s/mlh0e2ryxr4jy54/2015-09-08%20at%2010.04.gif

**Comment by sergioc** [comment]
Error is due to the fact this is a protected path. In that case it should fire an error message indicating the path can't be opened and explaining why can't the path be opened.

**Comment by gbiellem** [comment]
Fixed
