### ISSUE TITLE
Radio button jumps out of place if "user" is selected on Windows 7

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#531]
SC Managemetn - User account selection radio in add instance form jumps out of place if "user" is selected:

![2015-09-08 at 10 06](https://cloud.githubusercontent.com/assets/493451/9729705/858422d0-5611-11e5-95b4-1413b9cf0d15.gif)

**Comment by gbiellem** [comment]
@distantcam has already fixed this one

**Comment by sergioc** [comment]
This is still occurring in 1.7.2.

**Comment by gbiellem** [comment]
@sergioc  I haven't been able to repro this.  Works fine for me.  
@distantcam @petersgiles  - What about you?

**Comment by sergioc** [comment]
Here's a new screencast showing v1.7.2:

![2015-11-02 at 09 06](https://cloud.githubusercontent.com/assets/493451/10876879/37c4111c-8141-11e5-90ac-8600bdf4da01.gif)

**Comment by gbiellem** [comment]
I never doubted you @sergioc.   I can't repro though - Works fine on my dev machine and a couple of test VMs I've run up.  The styling of the radio buttons looks slightly different to me as well, what OS are you running?

**Comment by sergioc** [comment]
@gbiellem Windows 7. That's the default system style, so you're probably on another Win version.

**Comment by gbiellem** [comment]
@sergioc  Yep. I tried Win 8, Win10, Windows 2012 R1 and R2...so everything but Win 7 :)
