### ISSUE TITLE
Connection string input should be multiline and have example in help tooltip

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#532]
Reference design (multi-line input, use word wrapping):

![screenshot 2015-09-08 10 24 18](https://cloud.githubusercontent.com/assets/493451/9730018/ffd8839e-5613-11e5-839d-cd86924b3f2d.png)

Current implementation:

![screenshot 2015-09-08 10 28 18](https://cloud.githubusercontent.com/assets/493451/9730087/568a85c0-5614-11e5-93fc-be05c2b910f2.png)

**Comment by johnsimons** [comment]
@gbiellem is this still planned or not ?

**Comment by sergioc** [comment]
@johnsimons this should still be implemented since a single line input makes it harder to read a long connection string.

**Comment by johnsimons** [comment]
This is fixed.
![image](https://cloud.githubusercontent.com/assets/122651/15735241/5c6c8e0e-28da-11e6-88bd-35f97c827058.png)

The textbox auto expands automatically
