### ISSUE TITLE
Help tooltip style

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#534]
Need to create a help tooltip style containing extra information or examples of info that can be used when adding an instance. 

The tooltip is not an hover state. It's activated via a click on an help icon and dismissed by clicking outside.

Help tooltips may contain text that can be selected and copied and/or links that can be clicked (on click, dismiss tooltip)

Visuals TBD

**Comment by johnsimons** [comment]
I thought we already provide good info, what exactly are we missing ?

**Comment by sergioc** [comment]
@gbiellem I recall we wanted to add a help tooltip next to e.g. HOST NAME:

![screen shot 2016-02-17 at 09 13 10](https://cloud.githubusercontent.com/assets/493451/13097777/c2cc469e-d556-11e5-93e1-5257a450ca12.png)

Can you remind why and are there other fields for which we might want to provide additional info?

**Comment by sergioc** [comment]
Here's another example for the connection string input. Reference design (would provide example in tooltip to have form cleaner): 

![screenshot 2015-09-08 10 24 18](https://cloud.githubusercontent.com/assets/493451/9730018/ffd8839e-5613-11e5-839d-cd86924b3f2d.png)

Current implementation (adds example under the field, thus cluttering the form):

![screenshot 2015-09-08 10 28 18](https://cloud.githubusercontent.com/assets/493451/9730087/568a85c0-5614-11e5-93fc-be05c2b910f2.png)

**Comment by johnsimons** [comment]
@sergioc I actually like the current version because I can copy/paste the example connection string as a starting point

**Comment by sergioc** [comment]
> Help tooltips may contain text that can be selected and copied and/or links that can be clicked (on click, dismiss tooltip)

The tooltip would also allow for that.

**Comment by johnsimons** [comment]
Not sure if that is my prefered option, I like the in-place hints/help, not a great fan of hover/click tooltips, mostly because I tend to fill this in using keyboard only

**Comment by sergioc** [comment]
@johnsimons can you copy paste the example using keyboard only?

**Comment by johnsimons** [comment]
> can you copy paste the example using keyboard only?

Nope

**Comment by sergioc** [comment]
Before we decide what's the best way to provide auxiliary info in the form (which is what this solution is about), I think we need to first determine which auxiliary info might be useful. @gbiellem can you chime in?

**Comment by gbiellem** [comment]
Sure.

Hostname - Important to stress the security implications of setting this to anything other than localhost ( this has been done)

Anything to do with the log queues and audit forwarding.  Users don't grok what these are  based on the name and can't make an informed decision as to whether to turn it off or on.

**Comment by sergioc** [comment]
Here's another example provided by @gbiellem https://github.com/Particular/ServiceControl/issues/601

We're starting to require a lot of explanatory info in the form, so the reason why help tooltips are useful is that they help us handle large amounts of in-context information without cluttering the UI.

I'll work on the tooltip style today.

**Comment by sergioc** [comment]
Proposed style:

![screenshot 2016-02-17 16 41 49](https://cloud.githubusercontent.com/assets/493451/13105359/633d86f4-d595-11e5-9f87-4a9aad92b924.png)

**Comment by sergioc** [comment]
@gbiellem I think the way it currently works for the host name is probably best since it's a warning, not an explanatory text.

**Comment by sergioc** [comment]
We could use display a warning icon if the user changes the host name to something different than localhost and use the same toolip pattern to display the message (plus a link to doco if necessary):

![screenshot 2016-02-17 17 28 40](https://cloud.githubusercontent.com/assets/493451/13106663/099df898-d59c-11e5-85b8-2acc18d16269.png)

**Comment by johnsimons** [comment]
@gbiellem @sergioc  have we seen any users struggling to fill in our forms yet ?

**Comment by johnsimons** [comment]
#666 is now implemented, so the need for this is probably diminished considerably.

**Comment by johnsimons** [comment]
If we receive user feedback eluding for the need of this feature we can reopen it.
