### ISSUE TITLE
Revise display of error texts for form input

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#535]
Revise display of error texts for form input in order to have more room for more descriptive error texts and for allowing a 2-column layout in add/edit instance forms.

**Comment by sergioc** [comment]
@distantcam can you point me to the location of the custom validation error messages?

**Comment by sergioc** [comment]
@gbiellem let me know when possible to show custom messages.

**Comment by johnsimons** [comment]
@sergioc so what exactly is the current problem with the way we display error messages, can you give examples ?

**Comment by johnsimons** [comment]
#666 is now implemented, so the need for this is probably diminished considerably.

**Comment by johnsimons** [comment]
If we receive user feedback eluding for the need of this feature we can reopen it.
