### ISSUE TITLE
Change "Report" button label to "Report error" in unhandled exception dialog

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#536]
![image](https://cloud.githubusercontent.com/assets/122651/9750269/c8c68868-56d8-11e5-8096-1b175af9e349.png)

IMO it would be nicer to change the "Report" button to "Report error to Particular Software"

Also it would be nice for all buttons to have consistent font size

**Comment by sergioc** [comment]
> IMO it would be nicer to change the "Report" button to "Report error to Particular Software"

You should not make GUI elements like that too verbose. As a rule of thumb, avoid exceeding 2-3 words inside a button. If something longer is absolutely required, better turn it into a link. I would rename the button label to "Report error", though.

**Comment by johnsimons** [comment]
@sergioc unfortunately if we are not explicit about what will happen once you click the button, I am not sure if we are conveying to the user that we are about to send data over the Internet. Also what data are we exactly sending over the wire, related to https://github.com/Particular/ServiceControl/issues/539#issuecomment-138744216

So could the user be misinformed and do something unintentional ?

**Comment by johnsimons** [comment]
Here is an actual recent great article on this subject - https://medium.com/@thomasfuchs/how-to-write-an-error-message-883718173322

**Comment by sergioc** [comment]
@johnsimons I do agree that "Report" alone is insufficient and recommend "Report error". However, I'd let user testing inform whether people understand or not what that button does, once renamed, before overdoing it.

**Comment by gbiellem** [comment]
:+1: for  "Report Error".  

Also If we go with @johnsimons suggestion - https://github.com/Particular/ServiceControl/issues/539#issuecomment-138744216  the button would load a more detailed confirmation screen anyway.

**Comment by gbiellem** [comment]
Done
