### ISSUE TITLE
Please stop shouting at me!

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#537]
![image](https://cloud.githubusercontent.com/assets/122651/9750310/45fbef1c-56d9-11e5-8d4d-6f8513bd5c4f.png)

**Comment by johnsimons** [comment]
@sergioc I understand you driving this upper case all text in the installer.

It is my understanding that is bad form to use upper case in messages since that is seen as shouting at people, is that the intent ?

**Comment by distantcam** [comment]
Yeah I have to agree with @johnsimons here. I know it's more consistent to be the same style as the header, but it looks bad and given it's a different color and separated from the header and means something else anyway I don't see the need to be consistent with the header style.

**Comment by distantcam** [comment]
Reversed the commit for #519
