### ISSUE TITLE
Audit forwarding not selected when editing instance 

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#538]
![image](https://cloud.githubusercontent.com/assets/122651/9750362/0365a1ce-56da-11e5-80f1-900eafeb995f.png)

**Comment by gbiellem** [comment]
@distantcam  reproed this.  Works fine when audit forwarding is on,  the problem is the off state.  
Then the edit view looks like the screenshot @johnsimons  provided.    

I still think a dropdown would have been less work and less problematic. We seem to keep fixing audit forwarding

**Comment by johnsimons** [comment]
> I still think a dropdown would have been less work and less problematic.

:+1: 
I also think that those iPhone looking buttons are confusing for our audience

**Comment by sergioc** [comment]
Although I understand @distantcam's desire to save 1 click, I'd advise going for a dropdown as well.

**Comment by distantcam** [comment]
> I still think a dropdown would have been less work and less problematic. We seem to keep fixing audit forwarding

You'd be wrong. The reason it keeps breaking has nothing to do with the control type.
