### ISSUE TITLE
What configuration information is included ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#539]
![image](https://cloud.githubusercontent.com/assets/122651/9750396/a586f156-56da-11e5-8b6d-f3ae6dc21bb9.png)

It would be nice to be more explicit about exactly what we are including in the feedback

**Comment by gbiellem** [comment]
@johnsimons This enables the Raygun feature that collects the current system information such as CPU, Memory etc.   

Would this label  work for you ->  "Include hardware and operating system information"

**Comment by johnsimons** [comment]
@gbiellem looking at what others do, they tend to have the option to see the raw data being sent, what do you think ?
I am just concern that we are sending "data" without being explicit about it.

**Comment by gbiellem** [comment]
@johnsimons  If we are going to do this then it should be done across the board.  Platform Installer and Serviceinsight and the unhandled exception handler in this installer are collecting the same info on an unhandled exception and I don't believe they even present the option to exclude the data.

**Comment by johnsimons** [comment]
> If we are going to do this then it should be done across the board

:+1:

**Comment by johnsimons** [comment]
So we all agree that we should do this but it is closed :disappointed:

**Comment by johnsimons** [comment]
I have just noticed we have changed the label of the checkbox to be more descriptive. That is a step in the right direction but IMO it can still be open for interpretation.
Is it possible to see the raw data that we are about to send ?

**Comment by gbiellem** [comment]
@johnsimons No I'll still plan to do it.  I opened a new feature issue for showing the raygun data prior to sending. I had a quick look at it yesterday and grabbing the data prior to send is no problem.

We'll just need to build a confirmation screen and decide the best way to display the data. 
See https://github.com/Particular/ServiceControl/issues/555
