### ISSUE TITLE
Banner disappears

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#540]
![image](https://cloud.githubusercontent.com/assets/122651/9750427/1f39686c-56db-11e5-935d-96667f442101.png)

When there are no instances, the banner above is displayed in the middle of the screen.
If you then click an "add instance" and press "cancel" to go back to main screen
the banner disappears.
![image](https://cloud.githubusercontent.com/assets/122651/9750462/86df0a44-56db-11e5-8797-9d647f289470.png)

it seems the banner reappears if I minimize and restore the window

**Comment by gbiellem** [comment]
@johnsimons I can't reproduce this bug

**Comment by johnsimons** [comment]
No idea, I can't seem to repro it either.
But I wasn't dreaming

**Comment by johnsimons** [comment]
@gbiellem  I think I got it.

Start with no instances

First create one instance
Then delete that single instance
Then new instance and cancel it

That is it

**Comment by gbiellem** [comment]
Still not having any luck reproing it... I'll keep trying.  @distantcam any ideas what could cause this?

**Comment by gbiellem** [comment]
Ok .. reproed when no debugging is attached
