### ISSUE TITLE
Should textboxes be more prominent/standard ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#542]
![image](https://cloud.githubusercontent.com/assets/122651/9751097/dc6fb00a-56e3-11e5-8d7f-f01a468d89bc.png)

The current styling used for the textboxes is concerning IMO, it is not the standard bordered rectangle.
Looking at the main audience for this tool (OPS) and the machines they will be running this tool on (servers with low resolutions), will these users be able to identify the proposed textboxes ?

I recommend at least to add the four borders to the styling to make it more "standard".

**Comment by distantcam** [comment]
> I recommend at least to add the four borders to the styling to make it more "standard".

What about 32 borders?
![Tesseract](https://upload.wikimedia.org/wikipedia/commons/5/55/Tesseract.gif)

**Comment by johnsimons** [comment]
@distantcam is this your way of saying "I disagree" ?

@gbiellem @petersgiles @SimonCropp thoughts ?

**Comment by gbiellem** [comment]
@johnsimons  

i don't think @distantcam disagrees,  he already proposed some alternatives on [slack]( https://particularsoftware.slack.com/archives/servicecontrolinstall/p1440059184000138)

**Comment by johnsimons** [comment]
Cool, I misunderstood the joke then!

Here is the final proposal from slack
![pasted image at 2015_08_20 04_46 pm](https://cloud.githubusercontent.com/assets/122651/9753051/5b034c94-56fb-11e5-8e09-6451156fbea8.png)

**Comment by gbiellem** [comment]
@sergioc thoughts on this?
 I know you wanted to have another go at the layout after the initial release.

**Comment by sergioc** [comment]
I previously agreed with the boxed input proposal. However, you need to ensure those rectangles have sufficient padding. Reference design:

![99b add instance form](https://cloud.githubusercontent.com/assets/493451/9755684/41bcf784-56d4-11e5-8107-49979705c741.png)

**Comment by johnsimons** [comment]
Fixed as part of #557
