### ISSUE TITLE
Add button should not be disabled after form is submitted incomplete / incorrect

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#543]
When we open the Add instance:
![image](https://cloud.githubusercontent.com/assets/122651/9751901/d99fc194-56ed-11e5-9301-d63c9521ece6.png)

the Add button is enabled but as soon as u click it and the errors show up the button then only becomes enabled if the form is complete.
I think it would make sense to disable the button from the beginning and only enable it when form is complete

**Comment by sergioc** [comment]
No, the button should never be disabled. If the user clicks the "Add" button, we guide the user to complete the form by showing immediately which info is missing or incorrect.

**Comment by gbiellem** [comment]
Fixed
