### ISSUE TITLE
Version of new SC is 0.0.0

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceControl#544]
![image](https://cloud.githubusercontent.com/assets/1298847/9752016/5c97ebcc-56de-11e5-8c07-4712bebb34b4.png)

**Comment by gbiellem** [comment]
@dis What this after upgrading an instance to 1.7

**Comment by gbiellem** [comment]
@distantcam 

The only way I've managed to reproduce this is if I have a configured instance but then delete the ServiceControl.exe file out of  the installed path.  We default to a verison of 0 if no file is present.
Your screenshot show "Stopped".  Could it be you removed the files?

If not I'll need some repro steps

**Comment by distantcam** [comment]
All I do is add a new instance, not upgrade.

The code doing the version check:
```
var fileVersion = FileVersionInfo.GetVersionInfo(Service.ExePath);
return new Version(fileVersion.ProductMajorPart, fileVersion.ProductMinorPart, fileVersion.ProductBuildPart);
```

When I check the `fileVersion` object in LinqPad
![image](https://cloud.githubusercontent.com/assets/1298847/9752902/52abed66-56e8-11e5-86cb-e49d80773fc0.png)

Notice the Product version parts are 0, but the File parts are not.

**Comment by gbiellem** [comment]
Reproed - So it works fine when compiled with VS2013 but with VS2015 the product version parts are 0 
I'll switch to the File version parts as they work regardless of VS version
