### ISSUE TITLE
Dismissing error overlay  dismisses underlying form

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#546]
When the "report card" error overlay is shown dismissing it closes the underlying form as well as the  overlay.  

To reproduce:

- Open the Add New instance form
- Fill in all details
- Add an asterisk in the install path to make it an invalid path.
- Click Add
- Error overlay appears
- Clicking OK to dismiss the overlay 
- Add instance screen is dismissed.

Not very user friendly.   The add instance should stay open so I can correct my mistake

**Comment by distantcam** [comment]
@gbiellem First problem is the path validation throws an unhandled exception when you put an asterisk in the path.
