### ISSUE TITLE
Upgrade option still available after upgrade

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#547]
@distantcam 

Repro:
Have older SC installed
![upgrade-bug-1](https://cloud.githubusercontent.com/assets/2351700/9752637/0cad3708-56f6-11e5-952d-220586dd622f.PNG)

Upgrade to 1.7 successfully
Afterwards the upgrade option is still visible

![upgrade-bug-2](https://cloud.githubusercontent.com/assets/2351700/9752663/46f22c0c-56f6-11e5-9f76-a513f19e643d.PNG)

Refresh button doesn't clear it.  Restarting  the app and the upgrade option is not shown

**Comment by distantcam** [comment]
@gbiellem Soooo... I'll fix this by removing the option to upgrade?

**Comment by gbiellem** [comment]
If no upgrade is necessary then the option shouldn't be shown.  correct?
That's what you get if run the app and the instances are up to date already
So after the upgrade has occured I'd expect the option to no longer be shown

**Comment by sergioc** [comment]
What @gbiellem [described](https://github.com/Particular/ServiceControl/issues/547#issuecomment-138770990) should be the correct behavior.
