### ISSUE TITLE
Link to api is not updated correctly

### ISSUE THREAD

**Issue by weralabaj** [Particular/ServiceControl#548]
After changing the API url (e.g. changing port number) the correct address is displayed under HOST, however after clicking on the link I'm redirected to the old url. After restarting installer, the link is updated correctly.
![connecting after clicking the link](https://cloud.githubusercontent.com/assets/7335079/9789724/1ea8d23c-57d2-11e5-84fe-7fbac080ffd6.PNG)

**Comment by gbiellem** [comment]
Works now.  Thanks @weralabaj
