### ISSUE TITLE
When something goes wrong during SQL transport installation

### ISSUE THREAD

**Issue by weralabaj** [Particular/ServiceControl#549]
I'm trying to install a new SC instance with SQL Transport. I specify connection string that points to non-existing database. I'm then presented with an error message that looks not quite right (duplicated title and icon):
![nasty error](https://cloud.githubusercontent.com/assets/7335079/9790365/e98a5914-57d5-11e5-8275-afd088fe691c.PNG)
If I then correct connection string and try to finish the installation I'm informed that "The directory specified as the install path is not empty". After clicking OK on popup I have to start the whole process from scratch, all data is cleared from the form.

**Comment by gbiellem** [comment]
So this is two problems.

@distantcam  can you fix the display issue?
I'll tackle the logic problem with "The directory specified as the install path is not empty".

**Comment by gbiellem** [comment]
Actually it's three problems - The OK button closng the Add screen  @weralabaj experienced is a known issue ( #546 ) which also needs to be resolved.

**Comment by distantcam** [comment]
Whoops. I left in the old title when I refactored the titles of both windows into a shared control. Fixed now.

![image](https://cloud.githubusercontent.com/assets/1298847/9805617/8d4c4340-586d-11e5-914c-71857999c184.png)

**Comment by distantcam** [comment]
@weralabaj I just read the exception you got ... your machine is called butterfly?

**Comment by weralabaj** [comment]
@distantcam Schmetterling :D My favourite German word.

**Comment by weralabaj** [comment]
Btw one more thing - I think the error message "ServiceControl failed to run and created queues..." is confusing. If it's technically correct then wouldn't it be better to say "ServiceControl created queues but failed to run"?

**Comment by gbiellem** [comment]
Not really. the installer launches servicecontrol.exe as a seperate process
to create the queues. The stack trace etc you see is from that process not
the installer so tehniquely the error message is correct

**Comment by gbiellem** [comment]
Fixed the "The directory specified as the install path is not empty" issue here - https://github.com/Particular/ServiceControl/commit/d14ba0fc7a6e5a5387de459a6532212010ec0217

And since @distantcam  fixed #546  this is now resolved
