### ISSUE TITLE
Splash screen for SC Management Utility

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#550]
SC Management Utility does not have an exactly fast load time. A splash screen would greatly help in giving the user feedback after opening and reassure the app is starting:

![splasha](https://cloud.githubusercontent.com/assets/493451/9831975/221bca28-596c-11e5-8666-c7de3345f5bd.png)

Or:

![splashb](https://cloud.githubusercontent.com/assets/493451/9831976/282cf64e-596c-11e5-848a-c9fd739d2741.png)

**Comment by sergioc** [comment]
![sc_splash](https://cloud.githubusercontent.com/assets/493451/9832058/497931ca-596f-11e5-9f62-86abdbd3b19f.gif)

**Comment by gbiellem** [comment]
It's not that slow so I think the banner screen short would be sufficient.  Animation are terrible over remote desktop connections, a pretty standard mechanism for managing servers so I'd be :-1: for adding the spinning cogs

**Comment by sergioc** [comment]
Then I'd vote for a static version of the icon - easier to implement, does not contain detailed info (the user may have no time to read it, because it's gone too quick).

![splash](https://cloud.githubusercontent.com/assets/493451/9898514/2d9316ba-5c53-11e5-925c-e3516c43498f.png)

**Comment by gbiellem** [comment]
@sergioc  can you give send me your preferred splash as a PNG of the correct size. This one seems a little large (750px x 750 px).  The PI splash screen is only 538 x 328 and looks similar to your first effort.  In the interests of consistency I think we should make them roughly the same size and similar fonts etc

**Comment by sergioc** [comment]
@gbiellem I need to revise the PI splash screen, so let's not use that as a reference for the moment.

Instead I'd prefer to use something like the 2nd version (icon only). I'll provide resources for all standard Win DPI scales.

**Comment by sergioc** [comment]
@gbiellem splash resources: https://www.dropbox.com/sh/2e3l7w0dk5b64s3/AACDUL3iW3FUEdRNoaMqrMt8a?dl=0

**Comment by gbiellem** [comment]
Done - https://github.com/Particular/ServiceControl/commit/ba3b6c82900d631728830017a0264bb999cd512f

**Comment by gbiellem** [comment]
I've added a single png as a splashscreen.  Not convinced we need to have 4 splash screens targeting multiple DPIs.
