### ISSUE TITLE
Alert user if add form is incomplete before submitting

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#551]
Some of the fields in the add form are not selected or have filled in information by default. To help gently make the user aware that an explicit choice is required before triggering an error, we could:

- Show a warning sign next to empty fields
- Show a status text next to the "Add" button. If the text is clicked, cycle through each empty field each time the text is clicked (this behavior could also be used in the error status text)
- At this point it makes sense to grey out the button if the form is incomplete

![sc installer 11](https://cloud.githubusercontent.com/assets/493451/9832380/9d0dca62-5979-11e5-949f-cda698a34459.png)

This concept could be extend to also validate on the form on the fly, at the measure the user takes focus after each field.

**Comment by gbiellem** [comment]
@sergioc  I'm not sure i get it.  To me it looks like your just toning down the "angry" red validations.  Is this a replacement or complementary to those error messages?  it might help if you could explain in a bit more detail how you would see this working with the current validation.

**Comment by sergioc** [comment]
@gbiellem this would be complementary to the red errors. Since this form is a bit long, it may be too easy for users to miss some fields that need to be explicitly filled-in or selected and submit an incomplete form. To avoid having the user prematurely trigger errors, we warn in advance that the form is not yet completed.

The status next to the "Add" button would update automatically at the measure the user completes the form. If the user decides to submit the incomplete form anyway, we'd show the errors we already have.

I don't think this would be a critical feature to have, but may be useful to have as an option if we see that users submit incomplete forms too many times.

**Comment by gbiellem** [comment]
It sound like the length/complexity of the form is what you are trying to address. Lets get on a call to discuss this as I'm not sold on adding a second level of validation to address that.

**Comment by sergioc** [comment]
@gbiellem let's gather some user feedback first, it may not be an issue.

**Comment by johnsimons** [comment]
@sergioc @gbiellem have we heard any dissatisfaction with the current forms, should we close this ?

**Comment by gbiellem** [comment]
@johnsimons  The main feedback I here is to do with #678  - I'd view fixing that as more important

**Comment by johnsimons** [comment]
Agree, we haven't heard much complain about this
