### ISSUE TITLE
Redistributable package for perpetual license users

### ISSUE THREAD

**Issue by satyajit-behera** [Particular/ServiceControl#552]
It may be good to come up with a redistributable package of service control which can be distributed with the application (licence embedded in the package).

It will help in easy manageability of distribution of NSB with the custom applications / products.

**Comment by gbiellem** [comment]
Hi @satyajit-behera 

We don't have any plans at this stage to build a specific redistributable package for ServiceControl.
One recent change which may help you though is that you can now import the license as install time via a command line switch.  Take a look at http://docs.particular.net/servicecontrol/installation-silent
