### ISSUE TITLE
Redevelopment of ServiceControl Installation

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#572]
The ServiceControl Installation has been redeveloped to address many of the the limitations of the old installer.  The installation now includes a management application which is launched at installation time and is also available from the Start Menu.

#### Choice of transport
When adding the ServiceControl service the out of the box transport choice is no longer just MSMQ. The other [supported  transports](http://docs.particular.net/ServiceControl/multi-transport-support) are the included within the installation and do not need to be downloaded and manually added.

#### Multiple Instances 
The management application allows for [one or more instances](http://docs.particular.net/ServiceControl/multi-instances-on-one-host) of the ServiceControl service to be added. This is primarily intended for development and test environments.   Each service can be upgraded separately so it is possible to have side by side installs of different versions.

#### More options when adding the ServiceControl service
When adding the ServiceControl service(s) through the Management Utility you can now specify where the logs, database and binaries are stored as well as set the service account to use. 

#### Improved Unattended Installation Support
The Installer now support a number of [command line options](http://docs.particular.net/ServiceControl/installation-silent) such as:
- Adding the license at install time
- Passing a detailed unattended installation file to the installer to setup the service the way you want it
- Optionally upgrade a specific service or update all instances of ServiceControl

#### PowerShell Support
The Installation provides a [PowerShell module](http://docs.particular.net/ServiceControl/installation-powershell) that provides the ability to:
- Generate the unattended installation files
- Add/Remove/Upgrade ServiceControl service instances
- Add the license file
- Port availability testing
- URLACL diagnostic cmdlets.

For more detailed information on the new installer please refer to the [Particular documentation web site](http://docs.particular.net/ServiceControl)

**Comment by johnsimons** [comment]
@gbiellem should the link point to http://docs.particular.net/servicecontrol/installation ?

**Comment by gbiellem** [comment]
@johnsimons Since there are multiple docs I'll add some specific links and change the final link to http://docs.particular.net/servicecontrol so they can view the index
