### ISSUE TITLE
ServiceControl 1.7.1 upgrade overwrites the custom RavenDB data directory

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServiceControl#577]
I had ServiceControl 1.6.3 installed with the following config value specified:
`<add key="ServiceControl/DbPath" value="D:\NServiceBus\ServiceControl" />`

After installing the ServiceControl 1.7.1 upgrade, the config value had been reset to the default value. This caused a few moments of panic as it looked like ServiceControl had lost all of the data on the production server. I was able to resolve the issue by changing the config value again and restarting the ServiceControl service, but it would be nice if the upgrades respected the custom config values.

**Comment by johnsimons** [comment]
@gbiellem this will be fixed as part of 1.7.2 right?

**Comment by gbiellem** [comment]
@johnsimons  I repro`ed the issue 
The management utility has a case sensitivity bug reading settings.
So working on a fix now for 1.7.2

**Comment by gbiellem** [comment]
@BishBulb 

If you want to confirm your old vs new settings the management utility takes a copy of the config prior to upgrading and stores it in `<CommonAppData>\Particular\ServiceControlInstaller\ConfigBackups\<ServiceName>` which typically resolves to `C:\ProgramData\Particular\ServiceControlInstaller\ConfigBackups\Particular.ServiceControl`
