### ISSUE TITLE
Show option to open SCMU when installation completes instead of auto opening

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#578]
Currently the SC installation seems to end abruptly because there's no indication it completed successfully. In addition, SCMU is opened automatically which is something we don't know the user wants.

As an improvement, it would be better to have an install conclusion screen with a check box option (ticked by default) to "Run the ServiceControl Management Utility after exiting" the installer.

**Comment by johnsimons** [comment]
> Currently the SC installation seems to end abruptly because there's no indication it completed successfully.

Good point @sergioc 



> it would be better to have an install conclusion screen with a check box option (ticked by default) to "Run the ServiceControl Management Utility after exiting" the installer

That may work but will the user know what to do if they untick the box. Do we need some help text explaining what "ServiceControl Management Utility" is for an how to launch it manually ?
Also, how about the unattended installation.

**Comment by gbiellem** [comment]
@johnsimons  Unattended installs don't launch the utility. When we do an unattended via the PI we show a button on the final screen of the PI with some text telling the user to launch the utility it if they  the user need to update or install a instance of the servicecontrol service.  Otherwise we rely on them to have read http://docs.particular.net/servicecontrol/installation-silent

@sergioc - Adding the screen you want would be a simple change. In fact there is already a screen which does this which we've hidden so we could force the auto launch.  All that would be required would be to unhide it and probably tweak the copy a little.  The reason the current installer doesn;t ask the question is that I don't really like the idea of not auto-launching during the setup.  IMO it is really unlikely that they've installed SCMU and are not going to want to update one or more instances at that time.

**Comment by gbiellem** [comment]
Here's what that hidden screen looks like:

![capture](https://cloud.githubusercontent.com/assets/2351700/10873955/903e2e70-8170-11e5-8677-d72b70dbb0e4.PNG)

If we are going to add the screen I'd suggest we remove the checkbox and keep the auto launch behavior

**Comment by johnsimons** [comment]
Perfect, do it

**Comment by gbiellem** [comment]
Yeah and I'll fix the text so it makes a bit more sense

**Comment by sergioc** [comment]
> That may work but will the user know what to do if they untick the box.

@johnsimons We could add a text to the first screen of the installer saying something like "This setup wizard will install ServiceControl and the ServiceControl Management Utility. With that being said, we're at the same level of all other installers that put entries in the start menu, but do not advertise them in the installer because it's standard expected behavior to access apps in the start menu.

> IMO it is really unlikely that they've installed SCMU and are not going to want to update one or more instances at that time.

@gbiellem even though that's the likely follow-up action, you shouldn't surprise the user like we do now, plus it's currently done without proper feedback on the transition.

The alternative that is being proposed here only takes one extra click for the user in order to start adding/upgrading instances, because the default option is to open SCMU automatically on exit. When it opens, the user will understand where it comes from.

I recommend changing the copy to "Run the ServiceControl Management Utility after exiting" so that we don't crowd the UI with a lot of text, i.e. better quickly convey the consequence of having the option enabled.

**Comment by gbiellem** [comment]
@sergioc 
> @gbiellem even though that's the likely follow-up action, you shouldn't surprise the user like we do now, plus it's currently done without proper feedback on the transition.

:+1: I couldn't agree more!

Just to be clear though I want to:

- Add the extra screen, 
- Remove the tick box from view 
- Change the copy to indicate that the SCMU will launch whne they click "Finish"

Are we in agreement?

**Comment by sergioc** [comment]
@gbiellem I agree with everything except removing the checkbox - having it there is essential to allow the user to make a choice consistent with standard behavior in the majority of the installers that offer to open an app or doc at the end of the installation.

If you want to deviate from this, we'd have to first user test the option with the checkbox to see if people uncheck it (thus validating your latent concern of seeing people not going straight to SCMU after installing or having trouble finding it).

So we need the checkbox there anyway.

**Comment by gbiellem** [comment]
Good enough - I'll take 99% agreement and leave the tickbox in ( and defaulted to ticked)

**Comment by sergioc** [comment]
:-)

**Comment by gbiellem** [comment]
Implemented in https://github.com/Particular/ServiceControl/commit/5e2a4b7114bbab35765dbc88d4b6e6873b0e6a26
