### ISSUE TITLE
Remove BOM from message body

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServiceControl#579]
When importing a message, the message body is read using `Encoding.UTF8.GetString(...)` (https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Operations/BodyStorage/BodyStorageFeature.cs#L69). For an UTF8 string it's valid to contain Byte Order Mark (BOM) bytes at the beginning to indicate an UTF8 encoding. By using Encoding.GetString, these bytes will be preserved in the resulting string. This will cause issues with most deserializers when trying to deserialize the the body string (e.g. on `MessageFailed.MessageDetails.Body`).

This is related to Particular/NServiceBus#3050. As you can see this is mainly an issue when using JSON serializer. 

The BOM can be removed by reading the bytes with a `StreamReader` or by manually removing it using:

    if (body.StartsWith(ByteOrderMarkUtf8))
    {
        body = body.Remove(0, ByteOrderMarkUtf8.Length);
    }

//cc @sfarmar

**Comment by johnsimons** [comment]
@timbussmann unfortunatelly this could be a breaking change, we currently handle this on the consumers.
So not sure how to proceed?

**Comment by timbussmann** [comment]
@johnsimons how would this break existing consumers?

**Comment by johnsimons** [comment]
@timbussmann if I correctly understand u are proposing to remove the BOM before sending the message out?
If that is the case, any consumer that currently expects a BOM could incorrectly now parse the data correct ?

**Comment by timbussmann** [comment]
@johnsimons no one should expect a BOM on a UTF8 string to always be there. It's entirely optional. And it depends on how that message body is represented. If for example that `MessageFailed.MessageDetails.Body` property would be of type `byte[]`, having that BOM would be fine imho, but having it on a `string` is the issue.
The important thing is, that having a BOM at the beginning of a message body should be fine (although I recommended to remove it for JSON serialization), but we should avoid to contain a BOM somewhere within the message body.

**Comment by johnsimons** [comment]
> no one should expect a BOM on a UTF8 string to always be there

@timbussmann want to put some money on that ?

**Comment by timbussmann** [comment]
if someone removes the first characters on that string without checking if they are the BOM chars, he clearly is doing it wrong (remember, when using XML serialization, there is no BOM on that string).

from the unicode FAQ:

> In the absence of a protocol supporting its use as a BOM and when not at the beginning of a text stream, U+FEFF should normally not occur

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers thoughts on this one ?

**Comment by mikeminutillo** [comment]
The copy of the body that gets read as a string is only used for the full text search and should not be sent to downstream clients. The Body in BodyStorage is a direct copy of what was on the wire. That is kept is kept in a binary format and is the thing that gets passed to downstreams. 

If there is a BOM in our Full Text Index we should get rid of it. It's not necessary and doing so shouldn't break anything.

**Comment by timbussmann** [comment]
I'd argue this is a bug because the BOM isn't really a part of the incoming message and therefore shouldn't be persisted with the message itself.

**Comment by hmemcpy** [comment]
I believe serializers handle streams with/without BOM just fine. In any case, we can verify it with the wire/serializer compat tests.

**Comment by timbussmann** [comment]
> I believe serializers handle streams with/without BOM just fine. In any case, we can verify it with the wire/serializer compat tests.

Only when the BOM is at the beginning of the stream, not in the scenario described in the description.

**Comment by ramonsmits** [comment]
@hmemcpy @timbussmann its the text reader that takes care of the decoding. Depending on its configuration it will use the BOM for auto detection of the encoding (utf8 vs. ascii) and the BOM will then not be passed to the deserializer. 

The encoding should not be forced to utf8 but be configurable of read from the `Content-Type` header its `charset` attribute if present.

**Comment by ramonsmits** [comment]
In this case, the BOM could not be stored in the document itself. A StreamReader could read the body, and store it in the default encoding of servicecontrol.

However, as @mikeminutillo mentioned, SC should leave the body intact and not modify it when importing it to keep it bit exact. So it that byte[] contains a BOM then so should the import. I don't know what this import logic is about.

The issue here is that `Encoding.GetString` is used. This is the culprit and must not be used to read the body text. The BOM should not be present in *a string* only at the start of a *stream*. The body should be treated as a stream and then it unravels itself as a stream is always in a certain encoding and can be detected.

Quick implementation for supporting charset: https://github.com/Particular/ServiceControl/commit/4308b944b877b3a6fdc3e2e8c34b91da881d34c0  / https://github.com/Particular/ServiceControl/commits/body-storage-charset-support

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers can we make a decision here, do we can about this or not ?

**Comment by johnsimons** [comment]
Because we now store both error and audit as attachments and only use the call `ToString()` for the full text search and the existence of the BOM does not affect full text search.
