### ISSUE TITLE
Invalid Password error appears with correct password for Domain Accounts

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#581]
### Who's affected

Anyone trying to set the service account for a ServiceControl service instance to a domain account in the ServiceControl Management Utility or the Management PowerShell module

### Symptoms
When a domain account is specified as the service account the validation on submit incorrectly rejects  the valid password

***
#### Bug Report
I cannot create a ServiceControl instance running under a domain service account using either the UI (1.7.2) or PowerShell modules.
I've tried different machines and different service accounts. 
I can create an instance using an SQL login. 
I’ve also checked the account has permissions to host services on the machine.
I can run the Service Control Instance as the service account if I manually change the service ‘log on as’ account after installation.

Could you provide some advice on how I can troubleshoot this issue?

**Comment by petersgiles** [comment]
Screen shots from Kye

![kye-console](https://cloud.githubusercontent.com/assets/1644481/10930312/2166ce06-8311-11e5-812d-67de37ea8488.png)

![kye-ps](https://cloud.githubusercontent.com/assets/1644481/10930334/42d5cb96-8311-11e5-8018-d7d4678b1ed5.png)

**Comment by gbiellem** [comment]
@kye based on what you have provided it's a bug. I'll work on a hotfix and get it out ASAP

**Comment by kye** [comment]
Thank you. I can work around the issue in Dev/Test. We plan to go to preprod on 11/11/2015.

**Comment by gbiellem** [comment]
Hi @kye  

We've released ServiceControl 1.7.3 which addresses this bug.  Let us know if you have any issues with the fix
