### ISSUE TITLE
Add config setting to disable ServiceControl plugins

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#582]
I've added the HeatBeat nuget package and have the plugin assembly referenced from my project.

https://www.nuget.org/packages/ServiceControl.Plugin.Nsb5.Heartbeat/

When I deploy the host project into an environment with ServiceControl deployed, I specify ServiceControl/Queue in the app.config and everything works.

When I run the applicaton locally, I do not have ServiceControl installed so the queue does not exist. This causes errors and warning.

Is there an easy way to disable plugins for different environments?

**Comment by johnsimons** [comment]
Unfortunatelly no @kye 
The only solution is to delete the heartbeat dll from the bin folder.

**Comment by gbiellem** [comment]
@johnsimons  Isn't another option to add code to exclude it from assembly scanning base on config?

**Comment by johnsimons** [comment]
> Isn't another option to add code to exclude it from assembly scanning based on config?

Yes @gbiellem that is also an option

**Comment by kye** [comment]
You should do that options. :) Otherwise it's one more manual step to forgot each deployment.

**Comment by johnsimons** [comment]
Hi @kye 


> You should do that options. :) Otherwise it's one more manual step to forgot each deployment.

Just trying to understand what you mean ?

**Comment by kye** [comment]
@johnsimons Please implement the config value to turn off directory scanning. This will make it easier to deploy nServiceBus.Host.exe applications since it is easier to configure config values based on environments then it is to add/remove assemblies.

**Comment by johnsimons** [comment]
@kye if we add such a config setting, what guarantees do we have that our customers do not forget to reset that config setting when migrating to other environments?
So what I am saying is that, if we want to be safe by default for production environments, we want the plugins to be on by default in all environments and if we were to add a config setting to disable them, we would add the risk of a customer forggetting to resetting that config setting prior to releasing.
Hope this make sense ? 

We may need to think instead of having some other way of disabling these plugins, maybe a reg key ?

**Comment by kye** [comment]
Fair point. A reg key would make life harder for us since any developer who wants to work on the application locally would need to make the change, as opposed to just getting the latest source and config from source control.

Would you be able to add some sort of endpoint interface and let the customer determine whether or not the plugins should be disabled? Similar to IConfigureThisEndpoint?  

That way if the customer wants to configure a regkey or config value, they can implement the logic themselves?

**Comment by johnsimons** [comment]
> Would you be able to add some sort of endpoint interface and let the customer determine whether or not the plugins should be disabled? Similar to IConfigureThisEndpoint?

Sorry @kye, not sure I follow you, can you provide an example ?

**Comment by kye** [comment]
That's ok. I will try adding an additional Octopus Deploy step to ensure the assemblies are deployed.
