### ISSUE TITLE
If handling a message uses Bus.Reply, when reprocessing such message after a failure through ServiceControl, the reply is sent to ServiceControl instead of the intended destination

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#583]
Related to [Google Group post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/N2Bv3HKZNrw/BpGXcLpKBAAJ).

### Root cause

Failed messages sent for reprocessing have callback address header set to SC's callback receiver

### Who's affected

Users who have ServiceControl configured on RabbitMQ transport

### Symptoms

When a message is retried, the transport dispatcher adds the callback address header (its own, pointing to SC's callback queue). If the handler for the retried message uses `Bus.Reply`, the callback address is used (instead of `ReplyTo` field) which results in sending the reply to ServiceControl callback input queue instead of the endpoint which send the original message.

### Fix script

```
public static void ReturnMessageToOriginalReplyToQueue(string broker, string errorQueueName, string userName, string password, string messageId)
{
    using (var connection = OpenConnection(broker, userName, password))
    {
        var query = new Dictionary<string, object>
        {
            {"message_id", messageId}
        };

        var consumer = new QueueingBasicConsumer(connection);
        connection.BasicConsume(errorQueueName, false, Environment.UserName, false, true, query, consumer);

        var deliverArgs = consumer.Queue.Dequeue();

        var replyToQueue = deliverArgs.BasicProperties.ReplyTo;

        connection.BasicPublish(string.Empty, replyToQueue, true, false, deliverArgs.BasicProperties, deliverArgs.Body);
        connection.BasicAck(deliverArgs.DeliveryTag, true);
    }
}

private static IModel OpenConnection(string machine, string userName, string password)
{
    var factory = new ConnectionFactory
    {
        HostName = machine,
        Port = AmqpTcpEndpoint.UseDefaultPort,
        UserName = userName,
        Password = password,
    };
    var conn = factory.CreateConnection();
    return conn.CreateModel();
}
```

### Plan of attack

 - [x] Reproduce the problem
 - [x] Add `INeedInitialization` class to SC that disables the callback receiver for RabbitMQ transport
 - [ ] ~~Create a dll containing the mentioned type so that users can just drop it into the SC folder to fix their existing installations~~
 - [x] Document the scripts that takes the message from `SC.error` queue, removes the callback address header and places the message back into the proper queue
 - [ ] Send out an annoucement

**Comment by SzymonPobiega** [comment]
I've reproduced that problem on RabbitMQ. On SQL transport it does not occur because the problematic header is being set via a behavior, not in the message sender impl (so it is not executed while retrying via ServiceControl).

**Comment by johnsimons** [comment]
@SzymonPobiega @DavidBoike so is the proposed solution to ensure SC does not add any headers to the original message regardless of transport ?

**Comment by gbiellem** [comment]
@SzymonPobiega  This is marked as milestone 1.7.4 which has been released.  Should this still be open?

**Comment by SzymonPobiega** [comment]
@gbiellem the announcement has not been sent so I reopened this one
