### ISSUE TITLE
Detect new endpoints from custom checks

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#588]
We don't use custom check to find new endpoints. 

To repro:

1. Add custom checks to a endpoint
2. Create a check that fail
3. Run endpoint
4. Check shows up as failed in SP but no endpoint is shown

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers this is definitely a bug but could we just assume users are also using heartbeats and hence the endpoint will be registered ?
We could also rely on error and audit messages, I know all these could be turned off!

I guess what I am trying to access is if this is really an issue or not, thoughts ?

**Comment by andreasohlund** [comment]
>We could also rely on error and audit messages, I know all these could be turned off!

I thought we already did that?

Arguably the idea that you and @mikeminutillo came up with (which I love, actually has a similar idea that I showed to @mikeminutillo ) regarding a single `NServiceBus.ServiceControl` package would solve this since that would be the thing that registered the endpoints. Heartbeats, CustomChecks etc would just be add-ons

**Comment by johnsimons** [comment]
> I thought we already did that?

Yes we are doing it.
So can we assume it will work in the end ? And therefore we close this ?

**Comment by andreasohlund** [comment]
Yea, closing
