### ISSUE TITLE
Write powershell script to remove an obsolete endpoint

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceControl#598]
relates to: https://github.com/Particular/docs.particular.net/pull/929#issuecomment-158261262 
relates to: https://github.com/Particular/ServicePulse/issues/197
relates to: https://github.com/Particular/ServicePulse/issues/162

We don't really want users messing with our SC database so publishing instructions on how to do that isn't a great idea. However since this feature isn't available in our platform a simple script would help customers deal with obsolete endpoints

Something in this format would be good

`Remove-ServiceControlExternalIntegrationSubscription http://localhost:33333 mysubscriptionname`

**Comment by gbiellem** [comment]
@petersgiles  after the conversion we had with @johnsimons  are you still keen on this option?

To me it sounded like the better option is to provide a method on the SC HTTP API and add a UI in pulse for this.

**Comment by petersgiles** [comment]
@gbiellem yep I think you're right... go to https://github.com/Particular/ServicePulse/issues/162

**Comment by johnsimons** [comment]
It is sounding more and more that what we need is a way for the user to administer subscribers
