### ISSUE TITLE
UI should use Service Account credentials when testing SQL database connection

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#601]
When creating an instance through the ServiceControl user interface I specify a Service Account and SQL connection string using Integrated security = SSPI.

I then get “SQL connection failed – Login failed for user Domain\ME” and cannot continue since I do not have access to the database (but the Service Account does).

The interface should not attempt to check the database if a Service Account is supplied. Or test the connection using the supplied credentials.

**Comment by johnsimons** [comment]
@gbiellem I think we should just skip validation ?

**Comment by gbiellem** [comment]
G'Day @Kye 

Thanks again for the feedback

Could you `RunAs` and launch the installer as the service account?

This is interesting flaw.  We've always assumed the installation user has greater rights that the service account. When you press `Save` the installer is not just validating the connection string, it's also running the table creation to create any required queues.  This has the advantage that the service account can be lower privilege than the service account.

Alternatively when SSPI is configured we could show an checkbox to  run the table create as the service account or the installer.  Although this complicates things significantly as on we'd also need to provide the same option on upgrade, update and also through the powershell and unattended install equivalents.

//cc @petersgiles

**Comment by kye** [comment]
Thanks Greg. I've managed to find a SQL login so I can continue.

**Comment by gbiellem** [comment]
@johnsimons  Not sure which way to go with this one.  Any thoughts?

**Comment by johnsimons** [comment]
@gbiellem 
Make it optional validation ?
So the user triggers it explicitly ?

**Comment by gbiellem** [comment]
@johnsimons  It's not exactly a validation issue.
We run the installers directly after the validation step  as the currently logged in user, not the service account.   This is in line with what we used to did prior to introducing the SC utility. 

The question is should we default to running them as the service account and assume the service account has table create privs etc or stick with the current method.   I'd assume the same issue exists for the NSB Host when it runs the installation so I guess the question is broader than SC and relates to how we setup queues in SQL in general.

**Comment by johnsimons** [comment]
So @gbiellem, how do we proceed here ?

**Comment by gbiellem** [comment]
@johnsimons I think at this stage we document the behavior but I'm not sure it should be changed.

**Comment by kye** [comment]
So my manager just spent 30 minutes suffering through the same experience. Can we atleast add some text to the page or add some more details if the installer has an access denied exception.

**Comment by gbiellem** [comment]
@kye 

That makes sense so yes i'll we add some explanatory text

**Comment by gbiellem** [comment]
@sergioc  you asked for other areas of the SC UI were explanatory text are required.  This fits that bill

**Comment by johnsimons** [comment]
Here is my view on this issue.

The administrator that is creating the ServiceControl instance via the SC Managment UI, has to have rights to create the tables in the sql database, so the creation of the tables is done using  the current logged on user.
The validation of the connection string should be using the credentials specified in the connection string, so if the user uses integrated security and the service is going to be run with a service account or a specific account then the validation is using that account.

@gbiellem does this make sense ?

**Comment by gbiellem** [comment]
@johnsimons Yeah it does.

**Comment by johnsimons** [comment]
@gbiellem have you had any amazing ideas how we going to fix this ?

**Comment by mauroservienti** [comment]
What if the SQL Box is configured to use SQL authentication only and the user needs to use a login at install time to be able to create queues and a different login to run SC? Or a similar scenario with integrated auto or a mixed auth?

Should we provide a facility to make the SC Management UI generate the SQL script that the admin need to run against the SQL box manually to create tables?

**Comment by gbiellem** [comment]
Closed in favor of #869
