### ISSUE TITLE
Make ServiceControl a host for databus storage purging policies

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#607]
Currently the databus is only used on the endpoints. When SC is a host for databus purging routines and policies than customers do not have to create their own purging routines.

## Purging policy

Purging policy could be based on:

- Message TimeToBeReceived
- Message create timestamp
- Blob last access timestamp

## Auditing hook

SC could do the actual deletions but we could also provide an audit hook that makes sure that blobs are stored for archiving.

## Blob combining

SC could even combine the blobs with the message for archiving purpose so that the blob and message data can be archived as a single item.

**Comment by johnsimons** [comment]
IMO, each message owner should look after themselves

**Comment by dvdstelt** [comment]
There's no way of telling what the intention is of a file and its message. What if a message is deferred? What if another message is send out to process the file? What if it never should be deleted? What if the message is in the error queue?

A lot of different possible scenarios where purging might still be necessary, but we didn't take the scenario into account. Resulting in an overload of options for just purging.

**Comment by gbiellem** [comment]
The fact that the databus does not purge has always seemed like a flaw in the databus implementation/design to me. Not sure that a workaround for that is a ServiceControl concern.

**Comment by johnsimons** [comment]
I don't think this purging belongs in ServiceControl

**Comment by ramonsmits** [comment]
@johnsimons If it does not belong in SC, then atleast say where it should belong? Its a blob not in control of the receiver(s). The error messages is stored in SC, as long as a message that uses that BLOB is stored in SC that blob should not be removed. Same applies to auditing.

So either provide one or more solutions where you specify a solution that is aware of messages stored in SC, that knows about expiration policies and message storage.

So I'll reopen this issue until there is a good alternative mentioned where it is indeed clear that it does not belong in SC.

**Comment by johnsimons** [comment]
@ramonsmits please open this issue in plat dev to figure out where this belongs, for now I'll close this
