### ISSUE TITLE
Fails to start when using SQLTransport with multiple databases

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceControl#609]
Versions:
ServiceControl 1.8.0.0
NServiceBus.Core 5.2.1.0
NServiceBus.SQLServer 2.2.0.0

Trying to start ServiceControl with multiple connection strings such as this:

    <add name="NServiceBus/Transport" connectionString="..." />
    <add name="NServiceBus/Transport/EndPointA" connectionString="..." /> 

Fails on startup with the following error:

2015-12-11 14:31:55.8483|26|Fatal|NServiceBus|Startup task failed to complete.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: The transport is running in native SQL Server transactions mode without an outbox, but configuration uses multi-database sending (http://docs.particular.net/nservicebus/sqlserver/multiple-databases). Multi-database sends can only be used when either in ambient transaction mode or when outbox is enabled. Please check your endpoint configuration.
   at NServiceBus.Features.ValidateOutboxOrAmbientTransactionsEnabled.ValiateTask.OnStart() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Config\ValidateOutboxOrAmbientTransactionsEnabled.cs:line 36
   at NServiceBus.Features.FeatureActivator.StartFeatures(IBuilder builder) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 139
   at NServiceBus.Unicast.UnicastBus.<Start>b__92_0(IWantToRunWhenBusStartsAndStops toRun) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 685
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass133_0`1.<ProcessStartupItems>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 927
   at System.Threading.Tasks.Task.Execute()

**Comment by johnsimons** [comment]
@SzymonPobiega can you give me a hand here, I have no idea what this is ?

**Comment by johnsimons** [comment]
Here is how SC runs:
```c#
configuration.Transactions()
                .DisableDistributedTransactions()
                .DoNotWrapHandlersExecutionInATransactionScope();
```

**Comment by petersgiles** [comment]
Looks like Service Control isn't configured to use this feature

**Comment by johnsimons** [comment]
@SzymonPobiega from my understanding reading the conde in SqlTransport, it seems multi database needs either Outbox or distributed transactions on, so as u can see from the code above, SC does not rely on DTC or/and outbox.

So this mean multi database is not support in SC.

**Comment by mauroservienti** [comment]
@johnsimons @SzymonPobiega I tested the above scenario with ServiceControl 1.8.1 and due to 

```c#
configuration.Transactions()
                .DisableDistributedTransactions()
                .DoNotWrapHandlersExecutionInATransactionScope();
```

It breaks, I can make ServiceControl startup successfully (not tested operations, yet) by dropping in the ServiceControl runtime folder an assembly with a class as simple as

```csharp
    public class ServiceControlConfigFix : NServiceBus.INeedInitialization
    {
        public void Customize(BusConfiguration configuration)
        {
            configuration.Transactions()
                .EnableDistributedTransactions()
                .WrapHandlersExecutionInATransactionScope();
        }
    }
```

Since `INeedInitialization` is run, during the bus [startup sequence](http://docs.particular.net/samples/startup-shutdown-sequence/), after the original ServiceControl configuration is evaluated but before the bus is created I could hook into the ServiceControl configuration steps and change the original intent making the `SQL transport` happy.

The above is enabling DTC Transactions that maybe not the desired intention, but using the same exact approach we could enable the `Outbox` for example and satisfy `SQL transport` requirements as well.

Thoughts?

**Comment by tmasternak** [comment]
@mauroservienti :+1: 

Additional question that I have is: why the multi-db setup does not work without DTC or Outbox? I'm not saying that we should configure SC in this way but we do support NoTransactions for sql on single db which can have same consequences as multi-db without DTC.

**Comment by mauroservienti** [comment]
@tmasternak I don't know :)

**Comment by johnsimons** [comment]
@mauroservienti if we are planning to enable DTC inorder to support this feature, I think we need to modify the installer to ask the user the question and then we need to somehow enable it, @gbiellem any ideas ?

**Comment by tmasternak** [comment]
@johnsimons I that case mabye outbox would be a better option?

**Comment by mauroservienti** [comment]
@johnsimons that is why a long time ago I suggested that the chosen transport should partecipate in the ServiceControl instance setup adding its own UI step and logic to the setup otherwise transport related tweaks are a nightmare.

At a high level what I expect it that the ServiceControl management UI when I chose the `SqlTransport` (or any other) will:

* download a `Particular.ServiceControl.SqlTransport` package that has a dependency on the `NServiceBus.SqlTransport` one
* the `Particular.ServiceControl.SqlTransport` package will be used by the management UI to look for:
    * Extensions to the management UI itself in order to configure that specific transport
    * addition assemblies to deploy to ServiceControl along with the transport ones, assemblies containing ServiceControl specific code such as the above sample

The `Particular.ServiceControl.SqlTransport` will behave exactly as a control designer behaves in an IDE when dealing with design time controls.

//cc @gbiellem @distantcam

**Comment by johnsimons** [comment]
@tmasternak outbox is harder to setup and I am not sure it works on satellites, @andreasohlund do u know ?

**Comment by gbiellem** [comment]
> will: download a Particular.ServiceControl.SqlTransport package that has a dependency on the NServiceBus.SqlTransport one

:-1:  SC installer needs to work offline. We avoided downloads on purpose.  You can't assume a server has internet access.

**Comment by gbiellem** [comment]
>The Particular.ServiceControl.SqlTransport will behave exactly as a control designer behaves in an IDE when dealing with design time controls.

Unattended installations do not us the GUI installation at all.

**Comment by mauroservienti** [comment]
@gbiellem 

> :-1: SC installer needs to work offline. We avoided downloads on purpose. You can't assume a server has internet access.

Transport packages are downloaded by the Platform Installer or included in the MSI? Include or download this as well.

> Unattended installations do not use the GUI installation at all.

My proposal does not need to be GUI only.

The intention is to highlight that a transport may have the right to do some custom configuration when ServiceControl is using it. A sample: SqlTransport when using multi-database and or when using multi-schema, both scenarios not supported by the default configuration mechanism

**Comment by gbiellem** [comment]
> Transport packages are downloaded by the Platform Installer or included in the MSI? 

Included.  We want to control the installation and version of transport

> My proposal does not need to be GUI only.

@mauroservienti   Let's have the SC installer architecture conversation separately - While it's related i don't want us to derail this issue.

**Comment by johnsimons** [comment]
As explained in http://docs.particular.net/nservicebus/sqlserver/deployment-options#modes-overview-multi-instance, multi-instance feature is going to be unsupported, hence I am closing this issue
