### ISSUE TITLE
Cannot re-use queue names for different SC instance with different connection string

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#610]
### Symptoms

When adding  instances through the ServiceControl Management Utility the validation attempts to prevent two instances being configured to use the same queues on the same transport.  The validation does this by comparing queue names but it neglects to compare the connection strings. 

When adding a new ServiceControl instance with a different connection string you get the following error when the same  queue names are used:

>Queue names must be unique across all instance on the same transport

This should not be the case

### Who's affected

This would primarily affect users who wish to configure multiple instances of ServiceControl on all transports other than MSMQ.

**Comment by gbiellem** [comment]
Thanks @ramonsmits  - will fix
