### ISSUE TITLE
Extend the max rentention limit from 60 day to 6 month

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#616]
We've had some customers asking for a longer retention limit and it seems resonable to allow this as long as we clearly document the repercussions.

The default should still be the same value as today

**Comment by andreasohlund** [comment]
@gbiellem makes sense?

**Comment by gbiellem** [comment]
Documentation amended  - https://github.com/Particular/docs.particular.net/commit/e1de36c5ee60cf89115e12a66f96f6de1dcd9da9

**Comment by gbiellem** [comment]
@andreasohlund As 6 months was just as arbitrary as 60 days I opted to just remove the upper limit from the code.  If we need to stress the important of not setting this too high we can do so via documentation.
