### ISSUE TITLE
MessageMapper complains about ICustomAttributeProvider

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#617]
Every time SC starts up the following warning appears in the log. 

```
2015-12-10 11:28:49.1204|4|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
```

This started [after this commit](https://github.com/Particular/ServiceControl/commit/ef29ada591008ab22e93ea4bfbc3051ca55c1516) and is happening because we have a message type (`ExternalIntegrationEventFailedToBePublished`) with a property of type `System.Type`. This means that when an event fails to be published we serialize a whole type (and associated serializable stuff) into a message.

We need to alter `ExternalIntegrationEventFailedToBePublished` to only contain the name of the failing event type (instead of the whole type). 

There may be in-flight messages of this type to be dealt with so this change needs to consider that.

**Comment by ramonsmits** [comment]
Seems my local installation suffers from this issue when I try to start the windows service.

If I run SC in the console it runs fine....

**Comment by gbiellem** [comment]
@ramonsmits  that warning does not result in the  service not starting.  There has to be something else in play. Anything in the Eventlog?

**Comment by johnsimons** [comment]
this is non critical, it is just a warning that can be safely ignored

**Comment by ramonsmits** [comment]
@johnsimons Would you say that using `Type` instead of `string` is a bug and that this issue is now about converting it to a string? 

The warning indicates an issue, and that issue is correct as it is done wrong just as @mikeminutillo mentioned?

**Comment by ramonsmits** [comment]
@Particular/servicecontrol-maintainers Can this be made into an improvement?
