### ISSUE TITLE
RijndaelEncryptionService.cs NotSupportedException: "Please use overload Encrypt(string, OutgoingContext)"

### ISSUE THREAD

**Issue by fafachd** [Particular/ServiceControl#620]
I just upgraded from NServiceBus v5.2.8 to 5.2.12. Now when I try calling the Encrypt(string) method using the RijndaelEncryptionService I get the following NotSupportedException: "Please use overload Encrypt(string, OutgoingContext)". However I cannot find this new overload; I still only see Encrypt(string) implemented.

Thanks,
Danny

**Comment by johnsimons** [comment]
@fafachd did you mean to log this issue against https://github.com/Particular/NServiceBus repo ?

**Comment by gbiellem** [comment]
@fafachd  wrong repository. Can you report this against NServiceBus?  If not I'll open an issue for you and link it to here. I'd prefer not to do this though as you'll not receive  notifications

**Comment by fafachd** [comment]
Moved to https://github.com/Particular/NServiceBus/issues/3490
