### ISSUE TITLE
Set default logging level to WARN and enable customers to adjust logging level via config

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#621]
At the moment the logging level is hard-coded to INFO. Some operations and some transports can be very chatty at this log level.

This feature will add a flag to the config to allow users to control the default logging level. As a part of this change the default log level will be lowered to WARN.

**Comment by gbiellem** [comment]
@mikeminutillo  On the face of it it seems like we should just default to warn and and a bool setting for enabling verbose logging or did you have something more granular in mind?

**Comment by WilliamBZA** [comment]
Why not just expose the full logging configuration? Why do we want to restrict it?

**Comment by gbiellem** [comment]
> Why not just expose the full logging configuration? Why do we want to restrict it?

In previous discussions on customizing the logging  levels the decision was taken not to leak the specific implementation details into the settings.

**Comment by johnsimons** [comment]
Leg level can be overwritten by adding:
```xml
<add key="ServiceControl/LogLevel" value="Info" />
```
