### ISSUE TITLE
Validation of domain service account throws LDAP error for some users

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#626]
### Symptom 

When validating the service account credentials of a domain account the following  LDAP exception is thrown "The server cannot handle directory requests".  This issue was reported via desk case https://nservicebus.desk.com/agent/case/15344

### Who's affected

Potentially any user who want to setup a ServiceControl instance using a domain service account could be affected. At this stage I have not been able to reproduce the error locally so it could be environmental

**Comment by gbiellem** [comment]
I've set a potential patch to the affected customer. If they report it solves the issue I'll create a hotfix,

**Comment by gbiellem** [comment]
Changed the context options to negotiate so the call will work on kerberos and ntlm

**Comment by cwaymanuk** [comment]
I have installed the latest version of ServiceControl and I am still receiving the error:

"The server cannot handle directory requests"

![image](https://cloud.githubusercontent.com/assets/6755138/12949128/58165fcc-cffe-11e5-933a-0e9adea63796.png)

**Comment by cwaymanuk** [comment]
Sorry just read it is for the 1.8.4 release.  Do you have any idea of when this will be?
