### ISSUE TITLE
Fetch DLQ messages from the transport and store them in ServiceControl

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#63]
As Opie I want all messages in the dead letter queues to be imported to SC so that I can investigate the reason for failure

## Questions

* Do we need this for other transports than MSMQ? (SqlServer doesn't have a DLQ)
* At least for MSMQ the DLQ is per machine so we need to use the endpoint plugin for this
* Do we support retries?

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers 

This issue is 2.5 years old, according to a [thread in SP](https://github.com/Particular/ServicePulse/issues/8#issuecomment-171501765)
> The blocker is that we need to run as admin in order to read from the local DLQ's in msmq and we currently don't have anything that is running with those priviliges.


I propose we close this one ?

**Comment by mauroservienti** [comment]
> I propose we close this one ?

Let me disagree :-)

what if we could deploy a SC component that runs on its process as Admin and that can talk to SC?

This could be part of the Platform Componentization effort.

**Comment by johnsimons** [comment]
> what if we could deploy a SC component that runs on its process as Admin and that can talk to SC?
> This could be part of the Platform Componentization effort.

@mauroservienti I am happy to consider that, but at the moment as far as I know there are bigger fish to fry, so do you see us acting on this any time soon ?

**Comment by johnsimons** [comment]
This is currently not prioritised to be done any time soon, I will close this one for now and if we ever go down this path we can reopen it.

**Comment by andreasohlund** [comment]
For azure service bus a workaround for now is to use https://github.com/andreasohlund/AzureServiceBusDLQ?tab=readme-ov-file#nservicebus
