### ISSUE TITLE
Cross version environment testing

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#632]
Before v6 is released we need to perform a few tests with ServiceControl.

1. Can ServiceControl read data (audits, errors, heartbeats, etc.) from a v6 endpoint.
2. Can ServiceControl Retry a message to a v6 endpoint

More advanced scenarios
1. v5 endpoint fails to process a message and forward it to error queue. Endpoint is upgraded to v6. Retry message from ServiceControl.

Wire Compatability should ensure that these all work. We should smoke test that assumption at the very least.

related to https://github.com/Particular/ServiceInsight/issues/552#event-573048900

**Comment by petersgiles** [comment]
happy to help with this one

**Comment by johnsimons** [comment]
Message retry working as expected, tested with NServiceBus.6.0.0-unstable1656

**Comment by johnsimons** [comment]
> v5 endpoint fails to process a message and forward it to error queue. Endpoint is upgraded to v6. Retry message from ServiceControl.

Tested using v4 and v5, everything works :smile:

**Comment by johnsimons** [comment]
> Can ServiceControl read data (audits, errors, heartbeats, etc.) from a v6 endpoint.

Tested audit and errors, heartbeats is not ready to test, but that said I assume the dev that upgraded heartbeats to v6 should have tested it

**Comment by johnsimons** [comment]
So anything else, or can we close this one ?

**Comment by mikeminutillo** [comment]
:+1:
