### ISSUE TITLE
Configuration error not logged when running as a Windows Service

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#634]
### Symptom

If I configura a invalid timespan in the `ServiceControl.exe.config file`

```
  <add key="ServiceControl/HeartbeatGracePeriod" value="00:00:60" />

```

SC blows up as expected when running on the cmd line:

```
C:\Program Files (x86)\Particular Software\Particular.ServiceControl> .\ServiceControl.exe
2016-02-03 14:21:24.901 INFO  DefaultFactory Logging to 'C:\Program Files (x86)\Particular Software\Particular.ServiceCo
ntrol\' with level Info

Unhandled Exception: System.TypeInitializationException: The type initializer for 'ServiceBus.Management.Infrastructure.
Settings.Settings' threw an exception. ---> System.OverflowException: The TimeSpan could not be parsed because at least
one of the numeric components is out of range or contains too many digits.

```

But when starting as the win service it blows with

```
C:\Program Files (x86)\Particular Software\Particular.ServiceControl> Start-Service Particular.ServiceControl
Start-Service : Failed to start service 'Particular.ServiceControl (Particular.ServiceControl)'.
At line:1 char:1
+ Start-Service Particular.ServiceControl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```
and the logfile only contains

```
2016-02-03 14:21:43.502 INFO  DefaultFactory Logging to 'C:\Program Files (x86)\Particular Software\Particular.ServiceControl\' with level Info
```

This makes it hard for users to debug issues

### Who's affected

All users of ServiceControl

**Comment by gbiellem** [comment]
That's because we don't have an unhandled exception handler in ServiceControl so the error ends up in the Windows Eventlog not the SC log . So it's not lost completely but I agree this is not intuitive.

**Comment by gbiellem** [comment]
Looked into this further. 

Other settings use the SettingReader class which wraps everything in a try/catch. These settings correctly log and default.  This specific setting fails because it is subsequently passed to a TimeSpan.Parse an then blows up.  So it an implementation issue on that specific setting. I'll fix it.

**Comment by christoffer-lundqvist** [comment]
I also think that SC should log that the default value (40 sec) has been changed to the user setting. 
We found it hard to know if the setting had any effect.

**Comment by gbiellem** [comment]
@christoffer-lundqvist  :good idea.  We should do that for all settings that have a default

**Comment by johnsimons** [comment]
That is funny, I actually planned to have a cmd line  command to do a print of the current settings

**Comment by gbiellem** [comment]
@johnsimons  I had a similair idea. I was going to go with  a summary of settings logged as startup  
Similar to the way that features are logged.  As part of the summary we highlight those that have been overridden by config

**Comment by johnsimons** [comment]
My idea was to do it on demand, so if user runs `ServiceControl.exe --displayCurrentSettings`, it would output the settings to console.

**Comment by gbiellem** [comment]
@johnsimons I like the logging idea better.  Command line options on a service exe  doesn't seems all that discoverable or intuitive..
