### ISSUE TITLE
Pause message consumption

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#637]
Currently RavenDB is embedded. If SC starts, RavenDB is started too. Sometimes indexes are stale and need updating. When SC consumes messages it can conflict with the updating of stale indexes. We have given the advice to make temporary audit+error queues so that SC will not consume messages and RavenDB is able to update huge stale indexes and when its done to configure SC to use the original queues again. This requires manual editing of the configuration file but also the creation of two temporary queues. Having the option to pause/resume message processing would help to achieve this goal in a much easier and logical way.

//cc: @WilliamBZA @mikeminutillo

**Comment by gbiellem** [comment]
@ramonsmits We already have a way of doing this.

If you start ServiceControl from the command line with the -maint switch RavenDB is started but the bus is not so no ingestion occurs, No manual editing of the config is required.  It also makes the RavenDB management studio available so you can see what's going on.

**Comment by mikeminutillo** [comment]
But it does not allow you to connect Insight / Pulse to it.

We wanted to disable ingestion but still process heartbeats and allow
retries of messages already ingested.

**Comment by gbiellem** [comment]
> But it does not allow you to connect Insight / Pulse to it. We wanted to disable ingestion but still 
process heartbeats and allow retries of messages already ingested.

@mikeminutillo yep I agree but that's not what @ramonsmits  described which is why I launched into an explanation of `-maint`.   I went looking for info about it in docs and AFAIK it's  only documented in  [Compacting RavenDB](http://docs.particular.net/servicecontrol/db-compaction) so not surprised @ramonsmits  didn't know about it

**Comment by ramonsmits** [comment]
@gbiellem Indeed, not aware of this argument! So starting it with this argument will automatically make RavenDB available so `<add key="ServiceControl/ExposeRavenDB" value="true" />` is not required?

But indeed my request is to make an option that you can toggle in SP through the SC API.

**Comment by ramonsmits** [comment]
By the way @gbiellem , that doco page is super slow when scrolling on my Chrome.

**Comment by gbiellem** [comment]
>  Not aware of this argument! Starting it with this argument will automatically make RavenDB available so <add key="ServiceControl/ExposeRavenDB" value="true" /> is not required?

Correct.

**Comment by gbiellem** [comment]
> My request is to make an option that you can toggle in SP through the SC API.

:+1:

**Comment by mikeminutillo** [comment]
Or the management utility.

**Comment by ramonsmits** [comment]
IMHO the Windows Service Pause command could behave the same. Pause message processing.

**Comment by gbiellem** [comment]
It's an interesting idea,  I'm not sure that it would be very intuitive or discoverable to the end user though.  I'd prefer an explicit UI option that spells out what it's doing

**Comment by johnsimons** [comment]
I think this scenario is handled by the maint mode, can we close this ?

**Comment by ramonsmits** [comment]
@johnsimons Its not, it seems that RavenDB is not updating its stale indexes in maintenance mode. At least, that is the behavior I observed.

**Comment by ramonsmits** [comment]
Also, having to stop SC, go to maintenance mode and also needing to be administrator is basically not really possible for an application operator.

**Comment by gbiellem** [comment]
@ramonsmits that argument would also rule out the windows service pause - it also requires elevated rights

**Comment by ramonsmits** [comment]
@gbiellem That is why I request it as an option in SP :-)

>My request is to make an option that you can toggle in SP through the SC API.

**Comment by gbiellem** [comment]
:+1:

**Comment by gbiellem** [comment]
>  seems that RavenDB is not updating its stale indexes in maintenance mode

Nope - In maint mode RavenDB is fully operational.  We just take don't start the SC rest api amd the document expiration processing

**Comment by johnsimons** [comment]
So given that we improved the story for maintenance mode, this can now be closed
