### ISSUE TITLE
RavenDB Silverlight management UI is a blocker

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#638]
In some environments Silverlight is a no go, especially on production servers, and it is preventing customers to directly access the ServiceControl data stored in RavenDB.

**Comment by johnsimons** [comment]
@mauroservienti technically it should be very rare for users to have to access the raw data, not saying that it won't happen but very rare IMO.

Not sure what to do with this @mauroservienti, as you know the only way out of this is by upgrading Raven, which u had a go and decided not to go ahead, so what do you think we should do with this issue ?

**Comment by mauroservienti** [comment]
@johnsimons it's a good question I have no answer for :(

> technically it should be very rare for users to have to access the raw data, not saying that it won't happen but very rare IMO.

I agree, the issue is that in a lockdown environment in those very rare scenarios there is nothing you can do.
And yes the only option we have is to upgrade to RavenDB 3.0, when @weralabaj and I tested it the effort was not worth the result. 

Is the upgrade to 3.0 required if and/or when we move ServiceControl from NServiceBus V5 to NServiceBus V6?

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers not much we can do here till we move either to raven v3 or something else, I think we can close this one ?

**Comment by gbiellem** [comment]
Agreed. No matter what the the vNext DB is this will be solved so no point keeping it around

**Comment by mauroservienti** [comment]
Another Desk case where Silverlight is a no go, is upgrading to RavenDB 3 an option in the short term? It will remove the problem entirely.

**Comment by gbiellem** [comment]
@mauroservienti i'd be :+1: for doing that  - The hard part would be getting it prioritized at the moment :(

**Comment by johnsimons** [comment]
Upgrading to Raven v3 is probably the easy part, the bigger issue is the migration of the data and the massive inconvenience it puts on users, no monitoring.

**Comment by gbiellem** [comment]
@johnsimons  but do we need to migrate the data? This has never been clear to me.
Is there anything stopping us from continuing to use the system DB.   
When we start splitting capabilites we can make use of multiple DBs and not put the new data in system.

**Comment by johnsimons** [comment]
@gbiellem it is my understanding that v3 does not let us write to system db, so yes we have to migrate it

**Comment by gbiellem** [comment]
@johnsimons  I'd  heard that too but I just tested it and it absolutely does work!  I also went looking for upgrade guides for Raven embedded and I can't find any advice that this is not supported.  In fact i found a post from Ayende querying a user as to why they wanted NOT to use the SystemDB with Raven 3 embedded,

Based on that I think we should re-open and consider a straight upgrade with no migration.

@mikeminutillo  @mauroservienti Thoughts?

**Comment by mauroservienti** [comment]
It is supposed to work, when testing RavenDB 3 performance with @weralabaj, several times it happened to me that the migration of the existing databases failed.

**Comment by gbiellem** [comment]
@mauroservienti  what migration were you performing?

**Comment by mauroservienti** [comment]
It's done automatically by RavenDB in V3 the internal data format changed if compared to 2.5. On small DBs is very fast, on some we tried it took maybe a minute so no issues at all, but it happened that it crashed sometimes even when using the same V2.5 db multiple times, one worked the second attempt failed.

**Comment by gbiellem** [comment]
That's a blocker unless it's been fixed.  It has been more than 6 months since the original spike, perhaps we should retest with latest RavenDB?

**Comment by mauroservienti** [comment]
:+1:

**Comment by gbiellem** [comment]
@johnsimons  I know you went ahead with spiking this.  Update?

**Comment by johnsimons** [comment]
Spike is complete, we have a branch that is running on RavenDb v3, we still need changes done to the installation to do the db folder migration as we previously discussed.

**Comment by gbiellem** [comment]
@johnsimons 

Aside from the required installation changes we still have two other things to resolve:

- we're waiting on a Raven 3 fix to be released 
- we need to verify the Raven 3 license we used is OK to embed in SC or whether we need a specific one.  I guess we'd take that up with @SamCamhi

**Comment by mauroservienti** [comment]
> we're waiting on a Raven 3 fix to be released

Should be out this week, at least this is @DavidBoike's plan as discussed yesterday during the sync.

**Comment by gbiellem** [comment]
@mauroservienti  not that fix :) 

@johnsimon found a bug with Raven 3 and the Hibernating Rhinos guys  have fixed it on an unstable but no released yet.

**Comment by mauroservienti** [comment]
oooops :wink:

**Comment by SamCamhi** [comment]
@gbiellem @johnsimons  Please note:  @udidahan had a recent meeting with Hibernating Rhinos.  

@udidahan please reply to comment below:

> we need to verify the Raven 3 license we used is OK to embed in SC or whether we need a specific one.

**Comment by udidahan** [comment]
We are continuing to pay them for RavenDB licenses (less though) so we can continue embedding as before.

**Comment by johnsimons** [comment]
This will be addressed once we upgrade to raven v3
