### ISSUE TITLE
Log file should roll over for large log files

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#641]
Log file is not rolling over. Log file becomes too large to open with 'standard' windows tools.

![capture-logfile-size](https://cloud.githubusercontent.com/assets/152998/12946698/ad6ef9a0-cff6-11e5-92fc-0c97d4cae6d5.PNG)

**Comment by johnsimons** [comment]
We have increased the default logging level to Warn in v1.9, so large logging files should be a rare occasion.

@Particular/servicecontrol-maintainers 
So do we still want to do this ?

**Comment by gbiellem** [comment]
Warn may now be the default but when diagnosing an issue the log level will be bumped to info or debug leading to  the same unwieldy file sizes. So I'd be +1 for still doing this

**Comment by johnsimons** [comment]
@gbiellem want to do this one ?

**Comment by gbiellem** [comment]
Sure thing, I'll take it

**Comment by ramonsmits** [comment]
@gbiellem Here is the NLog configuration that I used:

```xml
	<nlog>
		<variable name="LogDir" value="C:\Windows\System32\config\systemprofile\AppData\Local\Particular\ServiceControl\logs"/>
		<variable name="LogDay" value="${date:format=dd}"/>
		<targets>
			<target name="logfile" type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
				<target name="LogTarget1" type="File" fileName="${LogDir}/sc-${LogDay}.log" encoding="utf-8" maxArchiveFiles="100" archiveNumbering="Sequence" archiveAboveSize="250485760" archiveFileName="${LogDir}/sc-{#######}.log" layout="${longdate}|${threadid}|${level}|${logger}|${message}${onexception:${newline}${exception:format=tostring}}"/>
			</target>
			<target name="logfileRaven" type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
				<target name="LogTarget1" type="File" fileName="${LogDir}/raven-${LogDay}.log" encoding="utf-8" maxArchiveFiles="100" archiveNumbering="Sequence" archiveAboveSize="250485760" archiveFileName="${LogDir}/raven-{#######}.log" layout="${longdate}|${threadid}|${level}|${logger}|${message}${onexception:${newline}${exception:format=tostring}}"/>
			</target>
		</targets>
		<rules>
			<logger name="Raven.*" minlevel="Trace" writeTo="logfileRaven" final="true"/>
			<logger name="NServiceBus.Transports.*" minlevel="Info" writeTo="logfile" final="true"/>
			<logger name="NServiceBus.Unicast.Messages.*" minlevel="Info" writeTo="logfile" final="true"/>
			<logger name="*" minlevel="Trace" writeTo="logfile" />
		</rules>
	</nlog>
```

This creates two log files, one with the all output of RavenDB (huge!) and SC.

I wanted to log WARN+ from RavenDB in the SC log too and a separate log for exception details but NLog is very complicated to setup.

Also, I wanted to log INFO+ for two very chatty NServiceBus DEBUG namespaces but that also doesn't work.

**Comment by gbiellem** [comment]
out of interest what were the chatty namespaces you couldn't get working with your nlog config?

**Comment by ramonsmits** [comment]
@gbiellem They are mentioned in the XML snippet. `NServiceBus.Transports.*` and `NServiceBus.Unicast.Messages.*`

**Comment by gbiellem** [comment]
> Also, I wanted to log INFO+ for two very chatty NServiceBus DEBUG namespaces but that also doesn't work.

I works for  me using your config. 

> I wanted to log WARN+ from RavenDB in the SC log

Got to watch the order of rules.  Just add 
```
<logger name="Raven.*" minlevel="Warn" writeTo="logfile" />
```
prior to  

<logger name="NServiceBus.Transports.*" minlevel="Info" writeTo="logfile" final="true"/>

If you add it after it won't work.  The "final" flag will prevent any message from that namespace that is info or above from being processed by subsequent rules.

**Comment by gbiellem** [comment]
@ramonsmits take a look at https://github.com/Particular/ServiceControl/pull/657 which @johnsimons  got me to work on. It basically does something very similar to what your config does.

**Comment by gbiellem** [comment]
As #657 implements log rolling at 30Mb I'm closing this one
