### ISSUE TITLE
Actions on the API are not logged

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#642]
Selecting an action like a group retry seems to not be logged.

**Comment by gbiellem** [comment]
@mikeminutillo isn't there a change in 1.10 that covers this?

**Comment by mikeminutillo** [comment]
@gbiellem [this change](https://github.com/Particular/ServiceControl/pull/668) adds OWIN Middleware that will log all HTTP traffic to the debug log. It has been included in 1.11

@ramonsmits this allows us to turn the requests on in a production environment. It may be insufficient for what you are wanting. Can you provide some more details about what you'd expect to see here? Should we log all non-GET requests perhaps?

**Comment by mikeminutillo** [comment]
Is this covered by https://github.com/Particular/ServiceControl/issues/651

**Comment by gbiellem** [comment]
yep.  #651 is more general and I think it would cover thi so I'll close this one as a duplicate.  
@ramonsmits  if you disagree feel free to reopen
