### ISSUE TITLE
ArchiveAllInGroupHandler is doing an unbounded stream update in one operation

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#650]
ArchiveAllInGroupHandler is doing an unbounded stream update in one operation.

If we need to archive 100.000+ messages then this operation will take a very long time at each document is processed sequentially and patched separately.

The logic should to doing this by moving through all items either one by one or in (small) batches.

Possible fix:

- Query should be bounded by using `.Take(100)`
- If there are results, then at the end do a SendLocal of the same message

On a side node, we should add logging about its behavior.

**Comment by ramonsmits** [comment]
Possible we can use a completely different implementation by doing a `UpdateByIndex` containing a patch request. Making roundtrip do RavenDB instead of the number roundtrips based on the number of matching documents.

- http://stackoverflow.com/questions/8595636/conditional-patch-requests-in-ravendb

**Comment by ramonsmits** [comment]
By running a patch via the admin interface interface on an index we could update a large set of matching documents within a second.

**Comment by ramonsmits** [comment]
```
            var store = Session.Advanced.DocumentStore;
            store.DatabaseCommands.UpdateByIndex("FailedMessages/ByGroup",
                new IndexQuery { Query = string.Format(CultureInfo.InvariantCulture, "FailureGroupId: {0} AND Status:{1}", message.GroupId, (int)FailedMessageStatus.Unresolved) },
                new[] {
                            new PatchRequest
                                {
                                    Type = PatchCommandType.Set,
                                    Name = "Status",
                                    Value = (int)FailedMessageStatus.Archived
                                }
                        },
                false);
```

The published `FailedMessageGroupArchived` has GroupName and MessageIds properties which we cannot set based on this patch logic so it requires additional queries but are we really going to publish an event with 100.000+ ID's?

**Comment by johnsimons** [comment]
Being addressed as part of #652

**Comment by ramonsmits** [comment]
@johnsimons #652 talks about breaking out of a stream operation. This issue is talking about replacing the stream operation by making use of UpdateByIndex.

Its a completely different issue.

**Comment by johnsimons** [comment]
@ramonsmits here is the PR that is fixing this https://github.com/Particular/ServiceControl/pull/656

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/issues/656
