### ISSUE TITLE
Logging detail not sufficient for proper debugging

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#651]
When dealing with a customer support case it became very clear that while we log a lot of information in a lot of places, we are still missing log messages in plenty other places making it difficult to identify where in the code the process is breaking.

The solution might be to add more log messages in places that have none, or perhaps look at instrumentation.

**Comment by johnsimons** [comment]
@WilliamBZA do you have a list where we need to provide more diagnostic logging ?

**Comment by mikeminutillo** [comment]
I can add some based on my experience with this case. We do not log retry requests. We don't log anything to do with a retry until we start actually staging it. There is a whole batching process before this step that we have no visibility on. Obviously from #650 we know that there is no logging in that area either. I will start a PR to add at least these logging pieces.

**Comment by ramonsmits** [comment]
Another one, log progress and size in unbounded query processing.

**Comment by gbiellem** [comment]
@Particular/servicecontrol-maintainers  How do we address this and get it to  point were it could be closed?  At the moment the issue seems very open ended.

**Comment by mauroservienti** [comment]
This is not related to ServiceControl only, this spans the entire platform from Core to transports, I think we should move this to Platform Dev.

For example one of the issues I faced at a customer while dealing with SC and the SQL Transport is that the transport might fail to create queues, it logs the error but misses the queue that is causing the failure. It's not that SC misses something, something is not logged correctly at the transport level in this case.

**Comment by johnsimons** [comment]
@gbiellem how about we close this one and raise specific smaller issues to deal with, eg better logging to diagnose retries, archival, ...

**Comment by mikeminutillo** [comment]
I'm all for that @johnsimons. The alternative is to do an audit of the entire code-base looking for opportunities to provide better context via logging.

**Comment by johnsimons** [comment]
So I am closing this one, and every time we find an area that needs better logging for diagnostics purpose, we will create specific issues to deal with it
