### ISSUE TITLE
ServiceControl RavenDB logging in insufficient to pass on to Hibernating Rhinos support

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#654]
The embedded RavenDB logging is hard coded to "Error" and the log entries are mixed in with the ServiceControl logs.  The logging level was set to remove the Raven "noise" from the ServiceControl logs however this presents a problem when we want detailed RavenDB logs from a customer to   hand over to Hibernating Rhinos support for analysis.

To address this I suggest we add another logging target specifically for the Raven logs and add a config entry to enable verbose raven logging.

**Comment by gbiellem** [comment]
@johnsimons  as discussed

**Comment by johnsimons** [comment]
> To address this I suggest we add another logging target specifically for the Raven logs and add a config entry to enable verbose raven logging.

:+1:

**Comment by gbiellem** [comment]
Implemented in #657
