### ISSUE TITLE
Expired Documents Cleaner is not logging enough information

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#662]
If a user wants to know if the expired message clean task is running as expected the only information that are found in the logs are relative to the `ExpiredDocumentsCleanerBundle` startup settings, all the other logged information are logged at `DEBUG` level making them unavailable by default in the logs (default logging level is now `WARN`). The only option the user has is to change the log level to `DEBUG` generating a lot of noise.
Would be interesting to make the cleaners log, as `INFO`, the fact that a clean task succeeded and how many documents have been purged.

**Comment by johnsimons** [comment]
> Would be interesting to make the cleaners log, as INFO, the fact that a clean task succeeded and how many documents have been purged.

But that is still not ideal because the users by default won't see it. They would have to override the logging settings to INFO.
Maybe the logging of actions performed on the data should be logged differently and exposed separatelly, same as TC logs ?

**Comment by gbiellem** [comment]
>  But that is still not ideal because the users by default won't see it. They would have to override the logging settings to INFO

Unless we hardcode to always show INFO from that namespace same as we've done for the licensing.  Not advocating we do this just highlighting it as an option.

> Maybe the logging of actions performed on the data should be logged differently and exposed separatelly, same as TC logs ?

@andreasohlund proposed a SC health page in SP a while back which would show info like this.  Do we want to resurrect that idea?

**Comment by mauroservienti** [comment]
> But that is still not ideal because the users by default won't see it. They would have to override the logging settings to INFO.

good point @johnsimons 

> @andreasohlund proposed a SC health page in SP a while back which would show info like this. Do we want to resurrect that idea?

I like it, users need to have a way to monitor the health of the monitoring system as well.

**Comment by johnsimons** [comment]
So it seems this issue is a bit more complex then the initial description, should we close it and raise something else ?

**Comment by mauroservienti** [comment]
I'll do and link back to this one.

**Comment by mauroservienti** [comment]
Health monitoring discussion moved to #672
