### ISSUE TITLE
SCMU instance action buttons shouldn't show dropshadow under tooltips

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#665]
SCMU instance action buttons shouldn't show dropshadow under tooltips:

![2016-02-17 at 15 21](https://cloud.githubusercontent.com/assets/493451/13103642/63cbf264-d58a-11e5-921c-1f6ee8008afc.png)

CC // @distantcam @gbiellem

**Comment by gbiellem** [comment]
@sergioc  Not seeing that drop shadow on Window 10.  Are you still on Win 7?  Might be an OS specific bug with the theme

**Comment by sergioc** [comment]
I'm on Win7.

**Comment by johnsimons** [comment]
I can't repro this either :disappointed: 

@HEskandari @distantcam are you guys aware of any issue in win7 that causes this to happen ? And do you know how to fix it ?

**Comment by distantcam** [comment]
That doesn't look like a dropdown. It looks like something else is going wrong.

There are default themes based on the system theme (aero, classic, luna, etc) but we should have overrides for all the relevant controls.

**Comment by johnsimons** [comment]
> That doesn't look like a dropdown. It looks like something else is going wrong.

@distantcam it is a dropshadow

@HEskandari has a copy of win7 around, he is going to try to repro it

**Comment by johnsimons** [comment]
@HEskandari any news ?

**Comment by HEskandari** [comment]
@sergioc which version of Win 7 does this happen on? is it x86 or x64? do you have any service packs installed? I can't reproduce it on Win 7 / x64 with SP1 with the latest version of SCMU. Would you be able to check and see if still happens?

![scmu-win7](https://cloud.githubusercontent.com/assets/132117/15840187/8e376ca6-2c8b-11e6-977c-df4e7f09273c.png)

**Comment by johnsimons** [comment]
@HEskandari did u try to hover over it and display the tooltip ?

**Comment by HEskandari** [comment]
@johnsimons ah okay, got it reproduced. I didn't see the mouse pointer in the original screenshot.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/pull/743
