### ISSUE TITLE
SCMU Better layout for form error and warning messages

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#666]
Better layout for form error and warning messages to create to better signify hiearchy (label > data > error/warning) and leave more room for messages:

![screenshot 2016-02-17 17 25 10](https://cloud.githubusercontent.com/assets/493451/13106678/2134feca-d59c-11e5-91a4-ec9f87a9a333.png)

**Comment by johnsimons** [comment]
So this looks like we just need to display errors below the field
