### ISSUE TITLE
SCMU license dialog doesn't display the edition

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#669]
SCMU license dialog  displays the "License Type" from the underlying licensing component.  This is either Trail or Standard which causes some confusion since the expectation is this will show the license edition.   

e.g.  I paid for an enterprise license. Why does the license dialog say "Standard"

Relates to https://github.com/Particular/Operations.Licensing/issues/15

**Comment by johnsimons** [comment]
@gbiellem should we consider removing the license type for now, till we fix the license generation ?
Fixing the license generator is the correct fix but we then still have to provide new licenses to users, so it may take a long time till it goes away

**Comment by gbiellem** [comment]
> should we consider removing the license type for now  till we fix the license generation ?

Nope. Should be an easy fix

The license generation is not broken. It generated two fields, one for whether the license is a standard or trial and another for the edition.  It's just when the license is read back the edition  is ignored as the license class doesn't have a field to populated with this info.  

I'll patch the Operations.Licensing code to fix this and add double check what other metadata should be available for display purposes.

**Comment by johnsimons** [comment]
@gbiellem haven't u done this ?

**Comment by gbiellem** [comment]
I did some work on it but I don't think I ever pushed it in.  I'll take a look
