### ISSUE TITLE
SCMU Add license screen gives no feedback when updating a license

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#670]
When you update a perpetual license to one that has a new maintenance date there is no visual queue that the update was successful.

//cc @sergioc  as discussed

**Comment by sergioc** [comment]
We can take the existing layout for import errors:

![screenshot 2016-02-18 14 13 48](https://cloud.githubusercontent.com/assets/493451/13136301/e90a7a2a-d64a-11e5-96ae-b0f14a1adf98.png)

And slightly modify to display success messages:

![screenshot 2016-02-18 14 13 22](https://cloud.githubusercontent.com/assets/493451/13136305/f508318c-d64a-11e5-8699-1f098c395c6a.png)

**Behavior notes**
- Currently visible error and success messages are updated after the user imports a file again
- Currently visible error and success messages are cleared after the user closes the license modal

Success icon resource: https://www.dropbox.com/s/2tgiknfi7f2dia8/success.svg?dl=0

**Comment by gbiellem** [comment]
:+1:  Great @sergioc  that exactly what i was after
