### ISSUE TITLE
ServiceControl performance baseline

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl#673]
We should define some ServiceControl performance baseline when using the tool in different environments and in different configurations (clouds especially). It's always super hard to understand if a production environment is behaving as expected or performance improvements can be expected by tweaking (and how) the environment itself.

**Comment by ramonsmits** [comment]
We considered few numbers like IOPS required for ingesting a certain amount of messages per second with a certain size for a given database size.

**Comment by johnsimons** [comment]
This sounds like documentation/guidance, closing it
