### ISSUE TITLE
License dialog is not refreshed when importing a new license file

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceControl#676]
Here are the steps to reproduce the issue. I have the following license entries in my Registry:

HKLM -> Software -> ParticularSoftware -> License (using Particular's internal license file)
HKLM -> Software -> ParticularSoftware -> TrialStart = 2015-09-30
HKCU -> Software -> ParticularSoftware -> License (again, using Particular's internal license file)
HKCU -> Software -> ParticularSoftware -> TrialStart = 2015-09-30

I launch the Management Utility app. Open the license dialog. I can see that the effective license is shown correctly.

I then update the license (using another valid license file) and import it. Here's what happens:

- There's no indication that the license is updated. (Related to #670)
- I checked the registry, the License key is actually updated

But now when I close the dialog and re-open it, although the content of the license registry key has changed, in the dialog the old license information is shown.

**Comment by gbiellem** [comment]
Thanks @HEskandari  I'll address this in the release after 1.10

**Comment by johnsimons** [comment]
@gbiellem is this fixed ?

**Comment by gbiellem** [comment]
No but since you have me messing with licensing code I'll tackle it

**Comment by johnsimons** [comment]
@gbiellem I fixed this, but I am sure you won't be happy with the fix!
