### ISSUE TITLE
Error message Groups should return more information about their processing

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceControl#679]
We have had a lot of cases where users are confused about the state of their retries and archives in ServicePulse.

- It takes time to process these requests
- If the screen is refreshed new data is collected from ServiceControl that doesn't contain the current state of the processing
- ServicePulse is just a view of ServiceControl data and therefore displays information that is confusing to customers.
- Customers then attempt to retry the messages again, and again, and again. This puts more stress into the system causing more errors

Could probably be solved by an in-memory concurrent dictionary that you do an outer join against the results of the raven query. flush the dictionary when you have confirmation that the processing is done. This wouldn't require any change to service pulse

**Comment by johnsimons** [comment]
@petersgiles should this be raised in plat dev and close this one ?

**Comment by petersgiles** [comment]
Yep

**Comment by johnsimons** [comment]
Issue raised internally in plat dev, this issue will for now be closed.
