### ISSUE TITLE
Log ServiceControl.Contracts events to Windows Event Log

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServiceControl#687]
Related to #659 but rather than ServiceControl log messages, instead focusing on writing ServiceControl.Contracts events to the Windows Event Log:

* MessageFailed
* HearbeatStopped
* HeartbeatRestored
* CustomCheckFailed
* CustomCheckSucceeded

If you wanted to integrate with SCOM, Nagios, etc. currently you would need to:

* Set up a new endpoint
* Add ServiceControl.Contracts package
* Configure for ServiceControl conventions
* Add 5 message handlers
* Make some decisions about what information is important in each event
* Log each event to the event log

This is a lot of busywork and a lot of extra moving parts for something that should really be easy, and would be trivial for us to do. When publishing these events, we could easily also log info to the Windows Event Log, and then we would get integration with every decent monitoring software out there, *for free*.

Additionally, many ops people will scoff at relying on X to monitor the same X. Basically, if there's something wrong with the NServiceBus endpoints, but we have to rely on another NServiceBus endpoint to find out if there's a problem, that's a non-starter.

A Windows Event Log message does have a [limitation of somewhere in the neighborhood of 32K characters](https://msdn.microsoft.com/EN-US/library/windows/desktop/aa363679.aspx) (this is [different depending upon OS]() and we should probably never exceed 30K characters) and so for these events, we should probably not publish *all* of the details we publish via the contracts. I only see that being problematic for stack traces. In that case, the full stack trace is almost never that useful anyway. We could take the first X characters, or the first X stack frames, etc.

The real valuable information would be how to find more details somewhere else. Including a URI for ServiceInsight would be very helpful here.

Windows Event Logs do present a wrinkle for .NET Core, however, that is still quite a ways off, and there are a lot bigger fish to fry (Raven) before ServiceControl could ever run cross-platform. I would suggest implementing this as a plug-in assembly that just wouldn't get installed for a non-Windows installation.

**Comment by johnsimons** [comment]
@DavidBoike this is an interesting suggestion, can you please raise it in plat dev for furthe discussion

**Comment by mikeminutillo** [comment]
I have concerns over flooding the event log of one machine when a failure happens somewhere on a different machine. When an infrastructure error occurs it's possible that we'll write hundreds (if not thousands) of error messages to the event log but the SC server isn't even the machine that has the issue.

**Comment by mauroservienti** [comment]
I don't see that as a real issue, Ops people are usually used to deal with such things

**Comment by johnsimons** [comment]
Have we had any requests from users to do this ?

**Comment by DavidBoike** [comment]
I was asked specifically about this during a training I delivered for one of our site license customers this year.

**Comment by gbiellem** [comment]
I'd be uncomfortable with us sinking any time into this prior to the componentization effort,

**Comment by johnsimons** [comment]
@gbiellem so we close it for now right ?
