### ISSUE TITLE
Valid whitespace is not allowed in queue paths

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#688]
### Symptom 

Queues with spaces in the name are not allowed by ServiceControl Management UI.
For MSMQ [spaces are valid characters](https://msdn.microsoft.com/en-us/library/ms706083(v=vs.85).aspx). Raised by a customer in [this support case](https://nservicebus.desk.com/agent/case/17481).

###  Work Around
In the meantime you can follow the [instructions in the Configuration Settings article](http://docs.particular.net/servicecontrol/creating-config-file) to set the queue path name by hand.

**Comment by gbiellem** [comment]
@boblangley  was this linked to a support case or just something you've noticed?

**Comment by boblangley** [comment]
@gbiellem yes it was raised in a support case, I have updated the description.
