### ISSUE TITLE
Update ServiceControl to SQL Server transport v2.2.2

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/ServiceControl#689]
SQL Server transport v2.2.2 has been released to address the issue of delayed endpoint startup caused by a backlog of expired messages at the front of the queue.

For more information see https://github.com/Particular/NServiceBus.SqlServer/releases/tag/2.2.2

**Comment by johnsimons** [comment]
Done in https://github.com/Particular/ServiceControl/commit/e9765a1b9dc6297f9c817371b0db0d0fb414f5f3
