### ISSUE TITLE
Create a Retention policy for archived and waiting to be retried error messages

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceControl#691]
From the customer

> Our problem is that errors and archived messages are not removed. There really isn’t a reason for us to hold onto errors or archived messages past the 30 days retention policy. Is there any possibility that Particular could add a flag to the ServiceControl config so that errors and archived messages are removed with the 30 day?

> Right now when I open up ServiceInsight in production it says we have about 5.8 million messages within ServiceControl. When I go to the development and staging we have less than 800K in each environment. My assumption is that we are having more failures in the production system that are retired and resolved or archived which is filling up the database.

Also on google groups https://groups.google.com/forum/#!msg/particularsoftware/6xlFLM2RH-A/lyRqIQMPBQAJ

Lately we have seen a few high volume customers pushing the limits of ServiceControl's data store. This customer's is around 50 GB. Not the biggest one we've seen but certainly indicative of the issue. He doesn't need the data so we should provide a safe/responsible way for him to get rid of the data he doesn't need.

//cc @Particular/servicecontrol-maintainers @Particular/serviceinsight-maintainers  @Particular/servicepulse-maintainers

**Comment by johnsimons** [comment]
@petersgiles this sounds like something that should be raised in plat dev for further discussion

**Comment by petersgiles** [comment]
moved to platform dev for triage
