### ISSUE TITLE
Console log entries which detail log filenames are not rendered with date

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#696]
Cosmetic bug

The console log entries that detail the current SC and RavenDB logs show up as 

```
Logging to 'C:\Users\Greg\AppData\Local\Particular\ServiceControl\logs\logfile.${shortdate}.txt' with LoggingLevel 'Warn'
```
The ${shortdate} should be rendered to include the actual date.

**Comment by johnsimons** [comment]
I have modified the PR to contain the correct description, so there is no need for a buddy issue
