### ISSUE TITLE
Documentation section about uninstalling ServiceControl / ServicePulse

### ISSUE THREAD

**Issue by dsaf** [Particular/ServiceControl#702]
There is already a document about installing it: http://docs.particular.net/servicecontrol/installation
It would be handy to have a section about uninstalling it cleanly. This would be helpful for situations when re-installing for a clean start is the best choice.

**Comment by johnsimons** [comment]
@gbiellem how do you want to handle this suggestion ?
Should we add extra sections to the existing pages ?

**Comment by gbiellem** [comment]
Probably new page.
We can detail what the MSI uninstall and SCMU deletes do and list the things that are left behind such as the queues, any empty directories, UrlAcls etc.  I'll open an issue and start a PR

**Comment by johnsimons** [comment]
Issue created in docs
