### ISSUE TITLE
REST API can be improved

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#708]
Based on https://github.com/Particular/ServiceControl/pull/694#issuecomment-205354313 

@johnsimons his comment:

> @ramonsmits I am sorry that the REST api feels weird to you, maybe raise another issue if you feel strong about it.

I would expect the following:

    /api/errors/unarchive?from=2016-01-25T15:38:35.6767764Z&to=2016-01-25T15:38:36.6767764Z

Instead of:

    /api/errors/2016-01-25T15:38:35.6767764Z...2016-01-25T15:38:36.6767764Z/unarchive

That would be much more consistent with all the other arguments listed in the description.

It is weird that you can also do 

    /api/errors/unarchive

Also, based on the description it seems you cannot do:

    /api/errors/unarchive?id=e989a17f-4cf5-79f4-6399-2bddd3084412

or

    /api/errors/unarchive?id=e989a17f-4cf5-79f4-6399-2bddd3084412,5feb1b8c-c171-abfe-afad-f863b7681d09

As an example, its weird to have date ranges in the paths because they can overlap. On a real filesystem you would not have that.

    /api/errors/2016-01-25...2016-01-28/unarchive

    /api/errors/2016-01-27...2016-01-31/unarchive

Consider another API structure that improves the above.

Please add an emotion to express what you think about the current api.

**Comment by johnsimons** [comment]
@ramonsmits I think this boat has sailed, and since the api is not for public consumption I think we can live with it the way it is, what do you think ?

**Comment by ramonsmits** [comment]
@johnsimons I don't know, maybe 'the boat has sailed' but what can we do to improve our api (private or not) for future endeavours?

**Comment by mikeminutillo** [comment]
I think improving the API may be something that is much easier to do once we start to look at Platform Componentization. At the moment, changing this API means changing Pulse as well. Even if we did that we'd need to continue to support this version of the API until such time as all customers have migrated from the current version of Pulse and I don't know that aesthetics of an undocumented API is important enough to warrant that effort at the moment. 

As we aren't going to directly address this any time soon I'm :+1: to close it.
