### ISSUE TITLE
Slider for audit and retention period is not precise

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#713]
Slider for audit and retention period is not precise. If you know that you can use the arrow keys to inc/dec the value then you see that it has a precision of one hour.

![image](https://cloud.githubusercontent.com/assets/152998/14630311/07ba7dca-060d-11e6-923b-8089a711fcc4.png)

Improvements:

- Make it obvious that the user can use the arrow keys
- Add plus and minus / arrow buttons to inc / dec the sliders.
- Popup a value if the user wants to archive for more then two months stating that SC is not meant for archiving and that the audit forwarding feature should be used.

**Comment by gbiellem** [comment]
fyi @sergioc
