### ISSUE TITLE
Support "NT AUTHORITY\LocalService" in installer

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#715]
I almost always install SC using the *NT AUTHORITY\LocalService* account and have to search for the exact string to paste into the box.

it would help if this account could be added in the list:

![image](https://cloud.githubusercontent.com/assets/152998/14665735/908021d2-06d5-11e6-9700-aad5f0c6d1ae.png)

This makes it possible to install SC for SQL with integrated security.

**Comment by gbiellem** [comment]
If you just enter 'localservice' it works it out so no need to remember the "NT AUTHORITY\Local Service"

**Comment by gbiellem** [comment]
And yeah we should add it to the UI

**Comment by gbiellem** [comment]
@sergioc if we add another option do  you want to change this to a dropdown?

**Comment by sergioc** [comment]
I think the number of options is still low enough to not justify changing to a dropdown.

**Comment by johnsimons** [comment]
I don't think this is as easy as it looks. It seems by default the local service account has no rights to log on as a windows service, so I think we would need to check that ?
@gbiellem thoughts ?

**Comment by johnsimons** [comment]
@gbiellem I am stuck on this one, not sure if we need to modify everything or not, have started a PR in #740

**Comment by gbiellem** [comment]
No problem @johnsimons  I'll take a look

**Comment by johnsimons** [comment]
Fixed in #740
