### ISSUE TITLE
User's culture is used to serialize objects sent through the endpoints

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceControl#717]
If user are using a culture like Turkish where there are different upper/lower case characters it will affect how the output json is rendered. 

In the example of accessing /messages endpoint, the rendered json will have "message_ıd" instead of "message_id" for that property (notice the different "i). This is not limited to any given endpoint and is applied through all the property names.

**Comment by johnsimons** [comment]
This sounds like a critical issue to me, is this right @HEskandari ?
The affected user would not be able to use ServiceControl ?

**Comment by HEskandari** [comment]
@johnsimons I'd say so. Although it surfaced through ServiceInsight where the diagrams didn't work and some of Message Ids were displayed as "Unknown". I'm not sure if users with other languages (other than Turkish that's confirmed) are affected as well but it is likely.

**Comment by johnsimons** [comment]
Cool, can u raise it in plat dev and label it as critical

**Comment by muratzorer** [comment]
Thanks to Hadi's effort we found the source of [#576](https://github.com/Particular/ServiceInsight/issues/576) (from ServiceInsight Repo)

Here is also an analysis about the issue (for dotless i):
http://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you-should-care.aspx/
