### ISSUE TITLE
ServiceControl Management Utility MSMQ unsupported features message is badly worded

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#719]
User may only be told to turn off the first couple of optional features. The complete list is here:

- MSMQ Directory Services integration
- MSMQ Multicasting Support
- MSMQ Routing
- MSMQ Triggers

**Comment by gbiellem** [comment]
The message also gives a command line to execute.  If this is truncated it is useless to the end user

**Comment by johnsimons** [comment]
So do we just need to make the box bigger ?

**Comment by gbiellem** [comment]
> So do we just need to make the box bigger ?
 
probably or maybe make it scrollable.  
.

**Comment by johnsimons** [comment]
I would try making the text box as big as possible first, scrolling would be the last option IMO

**Comment by gbiellem** [comment]
Took a quick look at this and I was wrong.  The message is not being truncated,  it's just worked badly so it looks like a partial command line.  I'll clean it up.

**Comment by johnsimons** [comment]
I actually think we should just have a button "Fix it", where we execute the dism command, thoughts ?

**Comment by mikeminutillo** [comment]
> I actually think we should just have a button "Fix it", where we execute the dism command, thoughts ?

That would make sense. Are we already running in an elevated context when we show this error?

**Comment by johnsimons** [comment]
I think we are, otherwise we can force `Process.Start` to request elevation

**Comment by gbiellem** [comment]
@johnsimons Managment Util always runs elevated.

That dialog isn't specific to the MSMQ config.  It shows any number of validation issues, MSMQ is just one of the possible issues. So I'm not sure how a Fix It button would make sense without a major overhaul of how this works

**Comment by johnsimons** [comment]
Maybe the error messages need to be richer and include possible solution, in this case in the form of a "fix it" button
