### ISSUE TITLE
Group errors by message type

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#721]
The grouping that currently is supported really only caters for errors that occur in handlers.

Any error that occurs outside handlers, will have a very generic stacktrace, eg if an error occur in a behavior, a mutator, uow or just a a handler missing, the stacktrace does not include the message type.
This makes it quite difficult for a user to triage issues for replay or archive.

It seems we need to have an additional grouping strategy that groups by messagetype.

For an example see https://groups.google.com/d/msg/particularsoftware/EQ4k-VHCeKg/LBSWnyDpAgAJ

**Comment by boblangley** [comment]
This is waiting on https://github.com/Particular/ServicePulse/issues/239 before deploying.

**Comment by johnsimons** [comment]
Done in https://github.com/Particular/ServiceControl/pull/781
