### ISSUE TITLE
ServiceControl cannot be used through an ARR reverse proxy in ServicePulse

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#723]
## Symptoms

ServicePulse does not receive updates from the ServiceControl

## Who is affected

Any user attempting to install ServicePulse using ARR proxy in a non-root directory.

## POA

- [x] Update ServiceControl SignalR version to latest stable. #724 
- [x] Smoke Test ServiceControl / ServicePulse
- [ ] Create new release of ServiceControl
- [ ] Announcement

**Comment by johnsimons** [comment]
@boblangley is there an link to when this was fixed in SignalR ?

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/pull/724
