### ISSUE TITLE
Wait for all indexes to become non-stale at start

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#731]
At start ServiceControl should check if there are any stale indexes and if so wait until there are 0 stale indexes left before starting message ingestion. This way we avoid conflicting IO operations. This should also be logged.

An alternative would be to check this every minute and pause ingestion or automatically throttle ingestion rate.

**Comment by johnsimons** [comment]
That is an interesting suggestion. Not sure what the impact would have on monitoring and service availability.
Also if we take a long time for the indexes to catch up we could end-up with a large backlog of messages that we may not be able to recover from.

So not sure if there is a good balance.

@ramonsmits so why this suggestion, what are you seeing that this may solve ?

**Comment by gbiellem** [comment]
If SC is offline for some time then there will also be a significant backlog from the doc expiry process.
Monitoring shouldn't be offline while we wait for that indexing.  I don't think this is practical suggestion with the current architecture. Suggest we close it @Particular/servicecontrol-maintainers
