### ISSUE TITLE
Add option to run in maintenance mode to the Management Utility

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#735]
![image](https://cloud.githubusercontent.com/assets/122651/15458931/104877b2-20e3-11e6-8547-a20ee694450e.png)

This is ideal for compacting the database that in Raven v3 is part of the studio

**Comment by johnsimons** [comment]
@sergioc  where do you see this option being displayed ?

**Comment by sergioc** [comment]
Can you explain what the option does exactly?

**Comment by johnsimons** [comment]
it would stop the instance if it is running (it probably needs to warn about that), it would then start ServiceControl in maintenance mode (we probably would display the url to raven), this would pop up the console app and then is up to the user to exit the console.

**Comment by johnsimons** [comment]
Majority of time a user would use this mode for compacting the database, see http://docs.particular.net/servicecontrol/db-compaction#using-servicecontrol-in-maintenance-mode

**Comment by sergioc** [comment]
@johnsimons this is small task for me, can you add it to the current SC budget?

**Comment by johnsimons** [comment]
@sergioc we can do that but I actually see this be a complement to #728.

**Comment by gbiellem** [comment]
@johnsimons At the moment we get users to run in maint mode interactively because that's the easiest way to add a command line switch. If we are going to add it to the UI though there is no need to pop up the console - we could just toggle the mode and restart the service.  Where we store the switch we can discuss later.  Thoughts?

**Comment by johnsimons** [comment]
@gbiellem  Yep that works for me, and an easy solution to implement
