### ISSUE TITLE
Determine OSS license

### ISSUE THREAD

**Issue by kbaley** [Particular/ServiceControl#737]
Since we have no license.md file, ServiceControl is technically using the default GitHub license which is fairly restrictive.

**Comment by johnsimons** [comment]
@kbaley PR :wink:

**Comment by kbaley** [comment]
@johnsimons: There was some concern that RPL1.5 (which NSB uses) may not be appropriate for the rest of the platform. Created the issue to discuss.

**Comment by johnsimons** [comment]
@kbaley In that case does this discussion really belong here, wouldn't we want to discuss it company wide in plat dev ?

**Comment by kbaley** [comment]
Good point. Closing.
