### ISSUE TITLE
Require explicit ServiceControl configuration for v6 plugins

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#742]
All of the plugins use an algorithm to determine where ServiceControl is. 

If it's explicitly configured in appSettings then we use that.

Otherwise, if the Faults Forwarding Error Queue exists then we guess a ServiceControl queue based on the Machine Name of the error queue.

Finally, if Auditing is switched on, we try to craft a ServiceControl queue based on the Machine Name of the audit queue. 

This is not going to work in V6. In V6 it is possible to configure the error/audit queues using code and the result of that is not visible outside of core.

We can either:
a) Drop this capability from the V6 plugins and require that they have an explicit configuration set.
b) Push an update back into core to make error/audit queue visible again.

NOTE: The MACHINE NAME concept is only really relevant for MSMQ. For the other transports that don't use this value, the derived queues will simply be `Particular.ServiceControl` on the broker that SC is connected to. In most cases this is probably accurate. With that in mind, a default queue name of `Particular.ServiceControl` with a way to explicitly override might be enough.

**Comment by johnsimons** [comment]
:+1: for option b

**Comment by mikeminutillo** [comment]
@Particular/nservicebus-maintainers should it be possible to get access to the configured error queue outside of the core? There is not currently a public API for this. Even the v5 implementation is flawed as we are only looking at the error queue in the config file (or from an IProvideConfiguration instance) but not the registry. Should `ErrorQueueSettings` be public?

What about the audit queue? Should `AuditConfigReader` be public?

Alternatively, should those implementations be copied into each plugin? That could lead to issues if they get out of sync.

**Comment by timbussmann** [comment]
Since we use the `GetConfiguredErrorQueue` for internal features already, I can't come up why we shouldn't allow external features to use that method too.

But I still wonder whether it's worth having that mechanism which tries to find the SC machine based on error/audit queues? If the only thing to continue support this is making that method public, it probably is.

**Comment by johnsimons** [comment]
So @mikeminutillo is this something the @Particular/platform-dev-squad needs to manage ?

**Comment by johnsimons** [comment]
Also, it seems we agree that pushing this to the core is the way to go, so should this issue be raised in the core repo ?

**Comment by mikeminutillo** [comment]
Opened an issue in core. I won't close this one as the outcome will be dependent on what happens there.

**Comment by johnsimons** [comment]
I don't see a point to keep this open, this belongs to plugins repos not SC repo

**Comment by mikeminutillo** [comment]
There are 3 V6 plugins and they each have their own repo and they'll all need an update when https://github.com/Particular/NServiceBus/issues/3811 is resolved. I'll raise issues in those repos. 

https://github.com/Particular/ServiceControl.Plugin.Nsb6.SagaAudit/issues/5
https://github.com/Particular/ServiceControl.Plugin.Nsb6.Heartbeat/issues/8
https://github.com/Particular/ServiceControl.Plugin.Nsb6.CustomChecks/issues/13
