### ISSUE TITLE
Users should be warned when they turn on audit and error forwarding

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl#766]
When installing SC, users need to be aware that they should only choose audit and error forwarding if they already have a process that consumes messages from the forwarded queue. 

If users aren't aware, they might choose it, not knowing that messages will start piling up in the forwarded queues and eventually run out of disk space causing bad things to happen.

**Comment by gbiellem** [comment]
@indualagarsamy  I knew there was a related issue.

Do you see this as just explanatory text in line with the options or via some sort of help tip - See @sergioc's suggestion here - https://github.com/Particular/ServiceControl/issues/534#issuecomment-185142743

**Comment by indualagarsamy** [comment]
@gbiellem @sergioc - I don't think tooltip is the way to go. It can be easily missed. I prefer always readable text. 
Something like: Select this option only if you have a service consuming the forwarded messages
or like it.

**Comment by sergioc** [comment]
I agree with @indualagarsamy in principle, but that comes at the cost of added clutter.

How about showing the in your face text only if the user starts typing something in that input?

**Comment by indualagarsamy** [comment]
How about the default set to No for forwarding, with a line of text that's inside the group box option for forwarding that says:
"Turn on forwarding only if the forwarded messages are being consumed by another service"
I don't think 1 line of text will be adding clutter. In this case its more meaningful to the user.

**Comment by sergioc** [comment]
@indualagarsamy why would you need to give that information in advance, before the user would turn the option ON?

**Comment by indualagarsamy** [comment]
@sergioc - because if users know that in advance, they might not even find the need to change the default from No to Yes. It helps them decide correct in first place. Much more intuitive.

**Comment by johnsimons** [comment]
We currently already display a warning text when upgrading, here it is:
"Error messages can be forwarded to a secondary error queue known as the Error Forwarding Queue. This queue exists to allow external tools to receive error messages. If you do not have a tool processing messages from the Error Forwarding Queue this setting should be disabled."

So I suggest we use about the same ?

**Comment by sergioc** [comment]
@indualagarsamy I don't think that's worth the cost of the additional clutter. The first time you turn that option ON, you'll get that message and learn about the consequences of having the option ON. After you learn about that it is unlikely you'll need the default message clutter again.

**Comment by johnsimons** [comment]
@gbiellem this one would be an easy one to work on ?
