### ISSUE TITLE
Decouple the audit transport from the business transport

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServiceControl#767]
Hi!

We are doing a big project with NSB. In general all is great and we love the serviceinsight/servicepulse features, it is really good for finding bugs and know what is happening. In our project we are using msmq as transport.

The problem came when we increase the load in a constant way, SC could not consume messages and it collapsed its audit queue and with it every msmq in the system. I think the audit transport should be change to something low level superfast tcp/udp communication. That way we could have auditing without risk and **totally decoupled from the business transport** (msmq).

Thanks

**Comment by johnsimons** [comment]
@pablocastilla we are entirely in agreement with you.
We actually have raised exactly the same issue internally.
Given this is a big change to tackle and we have not made any plans to when we will be going in this direction and we have already capture this intent internally, I am closing this issue. But don't take this as we are not doing it. We will, just not sure when!
