### ISSUE TITLE
Retry failing under SQL transport sometimes

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceControl#770]
Had an issue with DTC configuration on a new install, had to retry some failed messages and noticed some weren't being retried. I attempted to restart ServiceControl through services and it wouldn't stop. Had to kill it with task manager and start it back up, it was then able to retry the messages. This happened a couple times. ServiceControl version 1.21.0.

This is in production at a client site, so I have very limited access, but can have them pull some log files if need be.

**Comment by johnsimons** [comment]
@markgould it would be great to send us those log files for us to examine

**Comment by markgould** [comment]
Should I have the logs in the db folder sent too? I'll have someone get them.

**Comment by johnsimons** [comment]
Send it john.simons at particular.net

**Comment by markgould** [comment]
Logs sent.

**Comment by johnsimons** [comment]
Opened a desk case instead, closing this one

**Comment by ramonsmits** [comment]
FYI: We have released SC 1.47.3 with a fix that resolves a SQL transport relaxed issue that might be related to this:

- https://discuss.particular.net/t/servicecontrol-1-47-3-patch-release-available/482
