### ISSUE TITLE
Improve license reporting to ServicePulse

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#783]
Related to #782 

License status reported to ServicePulse has only two states - either the license is good or expired.
No indication of expiration dates.  upgrade protection dates or type of license is forwarded to ServicePulse.  This can lead to confusion from the customer perspective as to why the license is being reported as expired

**Comment by johnsimons** [comment]
So what can we improve exactly ?

**Comment by gbiellem** [comment]
@johnsimons  Make the license details available for display (Licensee,  expiration date and upprade protection date, and type of license)  

We could also include a warning status if the license is out of maintenance or almost of out of maintenance or that can be left to SP to derive from the data we make available.
