### ISSUE TITLE
Improve "more details" disclosing link in SCMU v2

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#784]
![2016-09-20 at 09 32](https://cloud.githubusercontent.com/assets/493451/18661412/fa167232-7f15-11e6-92a0-395705b2e1e3.png)

The "more details" disclosing link must be blue (and underline on hover) to look like a link people can click on instead of looking like a static label.

The disclosing arrow colors should also match the style from the instance control buttons.

**Comment by gbiellem** [comment]
E
