### ISSUE TITLE
Instance control button tooltips should be blue not green

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControl#785]
![2016-09-20 at 09 37](https://cloud.githubusercontent.com/assets/493451/18661404/eea82756-7f15-11e6-8b89-3137d8f991f9.png)

**Comment by SimonCropp** [comment]
@sergioc you have VS installed. would like to have a go at doing a PR to fix this ? I can screen share and show you where that color is configured in a style

**Comment by sergioc** [comment]
@SimonCropp :+1: my schedule is packed today, I'll schedule something for tomorrow.

**Comment by sergioc** [comment]
Just went through the code with @SimonCropp and we found it's actually referenced as blue we use elsewhere in the app. I later concluded the green is due to the agressive font anti-aliasing from Win7 after confirming it's blue with anti-aliasing off.
