### ISSUE TITLE
We use grey for both an action button and a disable button

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#788]
So which one is enabled?

![image](https://cloud.githubusercontent.com/assets/122666/18734548/f08ea9a6-80b8-11e6-81d9-6f4c5e9f6e0c.png)

**Comment by SimonCropp** [comment]
ping @sergioc

**Comment by sergioc** [comment]
"Exit". But I see your point. Using grey is not really a problem, but the contrast should be higher. Which screen shows those 2 buttons?

**Comment by SimonCropp** [comment]
ok so i raised this in the wrong repo. it should be in the PI

![image](https://cloud.githubusercontent.com/assets/122666/18740459/2925e246-80ed-11e6-8736-46f9ea298ef5.png)

**Comment by sergioc** [comment]
Issue opened in https://github.com/Particular/PlatformInstaller/issues/188, so this can be closed.

**Comment by sergioc** [comment]
Scratch that, we're using the same button styles in SCMU, so the problem also applies here.

**Comment by sergioc** [comment]
We could represent disabled buttons with 30% opacity 

Normal:

![screenshot 2016-09-26 18 32 52](https://cloud.githubusercontent.com/assets/493451/18843083/a5d325f6-8417-11e6-8df9-f078d7028f30.png)


Disabled:

![screenshot 2016-09-26 18 31 43](https://cloud.githubusercontent.com/assets/493451/18843067/9900f876-8417-11e6-93a2-a58e3e7f956b.png)

**Comment by johnsimons** [comment]
![image](https://cloud.githubusercontent.com/assets/122651/19712203/24ae2000-9b7f-11e6-971e-63960a46518a.png)

@sergioc I can clearly see a difference in 1 but in 2 I don't, are you sure the disabled in 2 has 30% opacity ?

**Comment by sergioc** [comment]
@johnsimons apologies for the confusion. I didn't apply the disabled effect to 2. Reducing opacity to 30% should also work for 2.
