### ISSUE TITLE
Handle Duplicate messages in Error queue

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#790]
With our current level of concurrency and the RavenDB PUT mechanics, duplicate error messages can trip the circuit breaker and cause ServiceControl to crash.

/cc @bording @SeanFeldman

**Comment by boblangley** [comment]
In talking with @johnsimons SC 2.0 (which is currently in development) addresses this issue. I am going to write a failing test for this in the 1.x branch (ignored for builds) and then port it to the 2.0 branch (if necessary) to confirm this has been resolved there.

**Comment by johnsimons** [comment]
@boblangley given v2 upgrade is cancelled, I think we need to repro this and address it in the current version.
We can pair on this and try to figure it out ?

**Comment by boblangley** [comment]
Yes, I will contact you shortly to coordinate.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/pull/818
