### ISSUE TITLE
Deleting custom check is a bit confusing

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServiceControl#793]
## Origin

The issue is a discussion over: https://github.com/Particular/ServicePulse/issues/324
## Problem

In ServicePulse we offer button mute next to Custom Checks. But what it does is actually deleting Custom Check from DB. Which means that if next custom check result will come it will be created again. So basically reappear on the screen.
## Solutions

The discussion that I would like to spin off is what should we do:
- Implement proper muting of custom checks, which means that if the check will be failing it will not be shown on the UI
- Remove this functionality from the Service Pulse as it is obviously not working in the manner that could be expected.

cc: @Particular/servicepulse-maintainers

**Comment by johnsimons** [comment]
The initial intent of "muting" custom checks was to cater for when a custom check is decommissioned (not needed anymore).
So in this scenario, if a custom check that has been muted starts beacon again then it will show up again as it happens today.

To me it seems there are 2 different requirements, first is the above, and an extra one is to desactivate a custom check for x period and then reactivate it again.
Is this right @WojcikMike @boblangley  ?

**Comment by johnsimons** [comment]
ping @WojcikMike @boblangley

**Comment by WojcikMike** [comment]
Let me talk about this with @sergioc . As we should probably call this functionality a bit different. What is more I found that our doco describes the functionality exactly the way how it works

**Comment by johnsimons** [comment]
> Let me talk about this with @sergioc . As we should probably call this functionality a bit different. What is more I found that our doco describes the functionality exactly the way how it works

@WojcikMike what was the outcome ?

**Comment by sergioc** [comment]
@johnsimons we didn't discuss this yet. I'll schedule a sync with @WojcikMike.

**Comment by johnsimons** [comment]
@sergioc @WojcikMike it seems this is now addressed in the latest version of ServicePulse - https://github.com/Particular/ServicePulse/issues/384?
So can we close this one or do you see this one as a different requirement?

**Comment by sergioc** [comment]
Discussed with @WojcikMike 

This issue is about actual muting (preventing custom checks from creating alerts, temporarily or permanently) and/or removing custom checks. This has not yet been addressed. The last version of SP only addresses #788.

We recommend having first a discussion to assess the value of custom checks in SP, whether we really want that or not. In case we do, then this issue should not be closed.

**Comment by ramonsmits** [comment]
Closing as solved as mentioned in https://github.com/Particular/ServicePulse/issues/324
