### ISSUE TITLE
CorrelationId is set to null when missing in failed message

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServiceControl#794]
This issue originates in a customer reporting it in the RabbitMQ transport repo: https://github.com/Particular/NServiceBus.RabbitMQ/issues/239

The issue has a very good repro.

### Behavior 
When a native message fails and is passed to the error queue it does not have a CorrelationId (which is valid). Yet, during the import of that message, CorrelationId is set to null, which happens around here:
https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Contracts/Operations/ImportMessage.cs#L15

I can see in RavenDB that after the import CorrelationId is already set to null. Later, when the message is retried, it is moved to the destination queue, but the RabbitMQ transport propagates the null value to RabbitMQ client which throws an exception, which is then handled by the transport resulting in a requeue, and hence, an infinite loop.

### Resolution

SC should be changed so that it does not add a null CorrelationId header to the message.

We will take measures in the RabbitMQ transport to defend against null CorrelationId headers in https://github.com/Particular/NServiceBus.RabbitMQ/issues/239 which is scheduled for 4.1.0.

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers see my comment in https://github.com/Particular/NServiceBus.RabbitMQ/issues/239#issuecomment-253089153
