### ISSUE TITLE
Inconsistent sliders for Audit Retention Period and Error retention Period

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl#797]
The Audit retention slider includes days and hours, while the error retention slider seems to have just days. Why have the hours for audit and not days? Can we keep the UI consistent?

<img width="1060" alt="screen shot 2016-10-04 at 8 58 50 am" src="https://cloud.githubusercontent.com/assets/854553/19081962/05dfb6fe-8a11-11e6-96df-6c6327429a60.png">

**Comment by gbiellem** [comment]
> Why have the hours for audit and not days?

Audit Retention minimum can be as low as 1 hour 
Error Retention minimum is in 10 days

Initially it was all in hours but that made it difficult for users to read. So we opted for hours and days
Not saying it's right, just giving you the background.

It has also been suggested to drop the sliders completely and have edit boxes see - https://github.com/Particular/ServiceControl/issues/787

**Comment by indualagarsamy** [comment]
@gbiellem - makes sense. Thanks. Since we have an issue to drop the sliders, I will close this issue.
