### ISSUE TITLE
Lost functionality: open a new case from a customer response

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/ServiceControl#810]
From Slack:

Sean Feldman [11:54]  
@here does anyone know how to start a new case from an existing case?.... I'm lost at how to achieve it :confused:

William Brander [12:05]  
Not sure @sean.feldman, what do you mean? Spawn off a new case while continuing with a current one?

Sean Feldman [12:21]  
@williambza from time to time customers use one support thread to follow up on other issues. We used to start a new case from the follow up by selecting the customer reply and "creating a new case". This would create a new case with all the required information copied over and and linked to the customer.

Indu Alagarsamy [12:26]  
@williambza - for example. customer might have started a case and we might have answered that question. In that same case, they might ask a completely new unrelated question. In which case, we start a new case. That's the use case I think @sean.feldman is referring to.

William Brander [12:28]  
Ok, I'm not sure how to do that in SC yet

Sean Feldman [12:28]  
@indu indeed

William Brander [12:28]  
We might need an issue raised for it

**Comment by johnsimons** [comment]
@SeanFeldman is this in the right repo ?

**Comment by SeanFeldman** [comment]
Sign, no. Hooray to multi-tasking :)
Sorry @johnsimons
