### ISSUE TITLE
Overriding default schema name "dbo" doesn't seem to work

### ISSUE THREAD

**Issue by buyshans-cegeka** [Particular/ServiceControl#820]
Hello

The schema name seems to be fixed to "dbo" for the AuditQueue and ErrorQueue setting. 

We are currently storing our audit and error table in the schema "nsb". When trying to setup ServiceControl to enable ServiceInsight, an error gets logged when attempting to access these tables.

There has already been a similar issue that was closed that suggested to try the following setup.

The "ServiceControl.exe.config" file contains the following settings:

        <add key="ServiceBus/AuditQueue" value="nsb.audit" />
        <add key="ServiceBus/ErrorQueue" value="nsb.error" />

When starting the service, eventually an error is logged in the logfile that looks like this:

> 016-10-26 09:24:34.4853|9|Fatal|NServiceBus|Repeated failures when communicating with SQL
> System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.nsb.error'.
>   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, >Action`1 wrapCloseInAction)
>   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, >Boolean callerHasConnectionLock, Boolean asyncClose)
>   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, >SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject >stateObj, Boolean& dataReady)
>   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>   at System.Data.SqlClient.SqlDataReader.get_MetaData()
>   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior >runBehavior, String resetOptionsString)
>   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, >RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean >asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, >RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, >Int32 timeout, Task& task, Boolean asyncWrite)
>   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, >RunBehavior runBehavior, Boolean returnStream, String method)
>   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>   at NServiceBus.Transports.SQLServer.TableBasedQueue.ExecuteReader(SqlCommand command) in >C:\Build\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 117
>   at NServiceBus.Transports.SQLServer.TableBasedQueue.ReceiveWithNativeTransaction(String sql, >SqlConnection connection, SqlTransaction transaction) in >C:\Build\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 110
>   at NServiceBus.Transports.SQLServer.TableBasedQueue.TryReceive(SqlConnection connection, >SqlTransaction transaction) in C:\Build\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 100
>   at >NServiceBus.Transports.SQLServer.NativeTransactionReceiveStrategy.TryReceiveFrom(TableBasedQueu>e queue) in C:\Build\src\NServiceBus.SqlServer\NativeTransactionReceiveStrategy.cs:line 44
>   at NServiceBus.Transports.SQLServer.AdaptivePollingReceiver.Try(Boolean& success) in >C:\Build\src\NServiceBus.SqlServer\AdaptivePollingReceiver.cs:line 55
>   at NServiceBus.Transports.SQLServer.AdaptiveExecutor`1.ReceiveLoop(Object obj) in >C:\Build\src\NServiceBus.SqlServer\AdaptiveExecutor.cs:line 110
>   at System.Threading.Tasks.Task.Execute()
>ClientConnectionId:000cabc5-3e26-4579-bc8e-a87b919d89d9
>Error Number:208,State:1,Class:16

**Comment by johnsimons** [comment]
@buyshans-cegeka the way to specify the schema in ServiceControl is via the connection string, eg:
 
![image](https://cloud.githubusercontent.com/assets/122651/19748285/0c63d4c2-9c24-11e6-9868-d6ffdb889fd3.png)

And this will create:
![image](https://cloud.githubusercontent.com/assets/122651/19748306/1f792e86-9c24-11e6-9d49-18f390462bda.png)

Will this address the issue ?

**Comment by buyshans-cegeka** [comment]
That seems to be doing the trick, thank you very much. 

I tried to find this in the documentation, but I was unable to find it.

**Comment by johnsimons** [comment]
@buyshans-cegeka no problem, I'll close this now.
BTW, I found the answer in https://docs.particular.net/nservicebus/sqlserver/connection-settings?version=SqlServer_2#connection-configuration-via-a-named-connection-string
