### ISSUE TITLE
Empty failed message group

### ISSUE THREAD

**Issue by harumph** [Particular/ServiceControl#828]
I noticed that ServicePulse is showing an empty failed message group after the messages were re-queued.
The bug comes from ServiceControl, which is returning inconsistent data from its APIs.

/api/recoverability/groups/

```
[
  {
    "id": "88cb7e68-26a3-55b8-6fff-29c9fdc5dc80",
    "title": "System.Exception: redacted",
    "type": "Exception Type and Stack Trace",
    "count": 1,
    "first": "2016-10-20T13:36:45.417065Z",
    "last": "2016-10-20T13:36:45.417065Z"
  }
]
```

/api/recoverability/groups/88cb7e68-26a3-55b8-6fff-29c9fdc5dc80/errors

```
[]
```

Is there any mechanism I could use to clean this up? I guess I could use RavenDb Studio but that seems pretty invasive.

**Comment by johnsimons** [comment]
@harumph what version of ServiceControl and ServicePulse are you running ?

**Comment by johnsimons** [comment]
@harumph it is possible the index is corrupted, to fix this run the following in curl:
```
curl -X RESET http://localhost:33333/storage/indexes/FailureGroupsViewIndex
```
This assumes you are using the default port and host name, if this is not the case you need to adjust the url to your own settings.

let us know if this fixes the issue ?

**Comment by gbiellem** [comment]
@harumph 

Just expanding on what @johnsimons said.  The above has no chance of  working  if  you haven't exposed the RavenDB via HTTP - That's not on by default.

You can enable this temporarily by entering maintenance mode  - See https://docs.particular.net/servicecontrol/use-ravendb-studio

Or if you are on an older version that does not have the maintenance option you can expose the underlying RavenDB by modifying the App Settings in the ServiceControl config file: 

```
<add key="ServiceControl/ExposeRavenDB" value="true" />
```

**Comment by harumph** [comment]
@johnsimons, @gbiellem 
Thank you both. I should get a maintenance window on Monday I think. I will keep you posted.

**Comment by harumph** [comment]
@johnsimons 
I only just got to the office, we're running:
- ServicePulse v1.6.6
- ServiceControl v1.22.0

**Comment by harumph** [comment]
I got the green light to do it today, It was quite painless. :)

I suggest adding a note on resetting indexes in the Troubleshooting section of the ServicePulse docs.
https://docs.particular.net/servicepulse/troubleshooting

**Comment by johnsimons** [comment]
@harumph thanks for the feedback, added help to https://docs.particular.net/servicepulse/troubleshooting#servicepulse-reports-empty-failed-message-groups
BTW, if you see any doco missing in the future feel free to add it, see https://github.com/Particular/docs.particular.net#how-to-contribute

Thanks
John
