### ISSUE TITLE
SC error queue is piling up messages

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/ServiceControl#832]
From a support case: [SF case 00022144](https://eu1.salesforce.com/console#%2F001D000000oSd4F)

## Description

SC: 1.23.0

SC is subscribing to it's own events and processing those. When processing is failing (3 immediate retries only, hardcoded), the message is moved to the SC error queue. With certain event types, this is just destined to happen (e.g. `ServiceControl.Contracts.HeartbeatMonitoring.HeartbeatStatusChanged`) as those events are becoming stale and will fail insertion to the RavenDB due to optimistic concurrency:
```
PUT attempted on document 'EventLogItem/HeartbeatMonitoring/EndpointHeartbeatRestored/bd429712-86b0-4d5b-96b7-a6a3010257c6' using a non current etag
```

Once this kind of event is failing immediate retries, message will be forwarded to the SC error queue that is growing over time and not necessarily even monitored.

/cc @Particular/servicecontrol-maintainers

**Comment by johnsimons** [comment]
Pretty sure that the change #822 fixes this specific issue.
