### ISSUE TITLE
Consistent app naming

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceControl#833]
There seem to be several flavours of naming for the ServiceControl Management Utility (screenshots below).

In summary:

* Installer component selection: *ServiceControl*
* Installer installation completion: *ServiceControl Management*
* ServiceControl Management Utility: *ServiceControl Management Utility*
* Start Menu: *ServiceControl Management*
* Programs and Features: *ServiceControl Management*

Would it be possible to align these on *ServiceControl Management Utility*?

![image](https://cloud.githubusercontent.com/assets/677704/19932299/e7a8da74-a10f-11e6-8505-ef4ba247a1f2.png)

![image](https://cloud.githubusercontent.com/assets/677704/19932308/f1302110-a10f-11e6-895d-200abb95860a.png)

![image](https://cloud.githubusercontent.com/assets/677704/19932321/fbd1d7b2-a10f-11e6-902d-a3533a1d16d1.png)

![image](https://cloud.githubusercontent.com/assets/677704/19932336/05580e3c-a110-11e6-9381-4f38de879866.png)

![image](https://cloud.githubusercontent.com/assets/677704/19932423/65e4e8ec-a110-11e6-8d92-8fcdbef24d61.png)

**Comment by gbiellem** [comment]
@adamralph good point 

I'm more in favour of dropping "utility" off the end and just calling it ServiceControl Management.
Having utility on the end really seems odd.. it would akin to labelling ServiceInsight as ServiceInsight Application

**Comment by johnsimons** [comment]
👍 to drop "utility"

**Comment by adamralph** [comment]
"ServiceControl Management" sounds good to me.

**Comment by gbiellem** [comment]
Note - Seperate issue raised for the PI change

**Comment by adamralph** [comment]
👍 thanks @gbiellem 

BTW - there are plenty of instances of "ServiceControl Managment Utility" in docs: https://github.com/Particular/docs.particular.net/search?utf8=%E2%9C%93&q=utility&type=Code

**Comment by gbiellem** [comment]
@adamralph  Yeah I know - Already working on a docs PR :)

**Comment by adamralph** [comment]
@gbiellem awesome!
