### ISSUE TITLE
"Please select" instead of blank in Audit Forwarding dropdown

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceControl#839]
When I create a new instance via Management, the Audit Forwarding dropdown is pre-selected with a blank entry, which co-exists alongside the "On" and "Off" entries. ~~I see that the Error Forwarding dropdown only has "On" and "Off" with the latter pre-selected. This leads me to believe that the blank entry in the Audit Forwarding should be removed.~~ The reason for this is that there is no sensible default, so we force the user to select an entry. It would be better if this entry read "(Please select)" than be blank.

**Comment by gbiellem** [comment]
@adamralph what've described is by design.  Error forwarding has a default of off as it's rarely a good idea to have it one.  So it's a sensible default. With audit forwarding though there is no sensible default.

**Comment by adamralph** [comment]
@gbiellem ah, I see, thanks. I just tried to submit without selecting and indeed it tells me "Must select audit forwarding".

Would it be better for the entry to say "(Please select)" rather than be blank?

**Comment by gbiellem** [comment]
Sure we could do that

**Comment by adamralph** [comment]
Thanks @gbiellem, I've re-titled and altered the description to make this an improvement. Will send a PR.

**Comment by adamralph** [comment]
I can't work out where the blank entry is coming from. I can only see the On and off entries in the ItemsSource: https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Config/UI/SharedInstanceEditor/SharedInstanceEditorViewModel.cs#L29

Can anyone help?

**Comment by gbiellem** [comment]
@adamralph I also had a look. It's not straight forward.  Basically the blank entry is because we bind to a list but don't select an entry.  The hacky way to add the "Please Select" would be be to add another entry to the list with a null value but I think I've got a better way.  Leave it with me and I'll try and get my idea into a PR over the weekend

**Comment by adamralph** [comment]
👍 thanks @gbiellem

**Comment by gbiellem** [comment]
@adamralph take a look at the PR and see what you think.
