### ISSUE TITLE
ExternalIntegrationDispatchRequests documents not being processed after a restart

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#854]
### Symptoms

If there are ExternalIntegrationDispatchRequests documents pending delivery at shutdown, when ServiceControl starts up again, those remain pending till a new ExternalIntegrationDispatchRequest document in inserted.

### Who's Affected
Users that are running ServiceControl v1.26.0 or earlier version and have external integrations enabled.

**Comment by SzymonPobiega** [comment]
This is no longer a problem.
