### ISSUE TITLE
Introduce app.config setting for endpoint name

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#868]
Currently the queue names reflect the Windows Service name at service installation time.
When the service is installed the command line specified includes a switch that indicates the Service Name. What that setting actually controls is the endpoint name and the associated queue names created/used.

![image](https://cloud.githubusercontent.com/assets/2351700/20955121/ac9e862c-bc94-11e6-86e3-a8cd518b73cb.png)

It's confusing to have part of the configuration on the command line and the rest in the app.config.
Suggest we introduce an endpoint name app.config setting so it's more explicitly visible how this is controlled and deprecate the command line switch.  

@mikeminutillo  also suggested we display this value in the Mgmt tool to make it easier for end users installing plugins to discover the queue name

The servicecontrol ingest queue should be immediately visible on the SCMU instance overview.

Optionally show an ⚠️ emoji f the ingest queue does not have the same name as the service name.

**Comment by WilliamBZA** [comment]
Correct, this is already supported. Closing.
