### ISSUE TITLE
Update instance port number fails - Queue already used by another instance

### ISSUE THREAD

**Issue by manuelsalvatori** [Particular/ServiceControl#873]
Step to reproduce:
- Create one first instance
- Create another instance
- Edit the second instance configuration for example changing the port number

Error:
The queue is already assigned to another instance

The error occurs on my second instance only, not the first one.
In order to edit the instance I need to delete it and create a new one.

**Comment by gbiellem** [comment]
Hi @manuelsalvatori 

I ran through the steps above but I didn't get a validation error.   So can I get some more info to try an reproduce the issue?

Specifically:

- Which version are you using? 
- Do you have audit and error forwarding off or on in each instance?
- Are the queue names unique between the instances?  I'm asking this because my assumption is an issue with the edit validation but if the add validation was broken then it may have allowed a bad config that is only picked up on edit.

**Comment by manuelsalvatori** [comment]
Hi @gbiellem 
sorry I forgot to mention the version:
ServiceControl: v1.29.0 / a41846d

Both instances have unique audit and error queues with forwarding enabled following the current pattern:

Instance 1:
a.audit
fw > a.audit.log
a.error
fw > a.error.log

Instance 2:
b.audit
fw > b.audit.log
b.error
fw > b.error.log

Editing the Instance 1 doesn't cause trigger validation issue.
Editing the Instance 2, no matter what I try to change, causes both error queue name and audit queue name to report the validation failure "This queue is already assigned to another instance".

I can't remember exactly the steps but I'm pretty sure I created with an older version of ServiceControl (sorry I don't remember the version, probably 1.06)  an instance to monitor b.error and b.audit.
Maybe there is some "dirt" somewhere?

**Comment by gbiellem** [comment]
Thanks @manuelsalvatori  👍

**Comment by manuelsalvatori** [comment]
Hi, after the update now I can save the changes but none of my services are running.
In the windows event's log viewer I have:

> Failed to stop service. System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'MsmqDequeueStrategy'.
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.ThrowIfDisposed() in C:\Build\src\NServiceBus.Core\Outbox\OutboxRecordBehavior.cs:line 0
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Stop() in C:\Build\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 125
>    at NServiceBus.Unicast.Transport.TransportReceiver.InnerStop() in C:\Build\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 386
>    at NServiceBus.Satellites.SatelliteLauncher.<Stop>b__3_0(SatelliteContext context, ParallelLoopState state, Int64 index) in C:\Build\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 72
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfRepl...

and

> Faulting application name: ServiceControl.exe, version: 1.29.0.0, time stamp: 0x584781ce
> Faulting module name: KERNELBASE.dll, version: 6.1.7601.23569, time stamp: 0x57f7c0b4
> Exception code: 0xe0434352
> Fault offset: 0x000000000001a06d
> Faulting process id: 0x573c
> Faulting application start time: 0x01d259d31df1f841
> Faulting application path: C:\Program Files (x86)\Particular Software\ServiceControl.Processing\ServiceControl.exe
> Faulting module path: C:\Windows\system32\KERNELBASE.dll
> Report Id: 5e23a084-c5c6-11e6-99ea-bc8556836e7a

and

> Application: ServiceControl.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ObjectDisposedException
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.ThrowIfDisposed()
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Stop()
>    at NServiceBus.Unicast.Transport.TransportReceiver.InnerStop()
>    at NServiceBus.Unicast.Transport.TransportReceiver.DisposeManaged()
>    at NServiceBus.Unicast.Transport.TransportReceiver.Dispose()
>    at Autofac.Core.Disposer.Dispose(Boolean)
>    at Autofac.Util.Disposable.Dispose()
>    at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean)
>    at Autofac.Util.Disposable.Dispose()
>    at Autofac.Core.Container.Dispose(Boolean)
>    at Autofac.Util.Disposable.Dispose()
>    at Particular.ServiceControl.Hosting.Host.OnStop()
>    at System.ServiceProcess.ServiceBase.DeferredStop()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 

and

> Failed to stop service. System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'MsmqDequeueStrategy'.
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.ThrowIfDisposed() in C:\Build\src\NServiceBus.Core\Outbox\OutboxRecordBehavior.cs:line 0
>    at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Stop() in C:\Build\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 125
>    at NServiceBus.Unicast.Transport.TransportReceiver.InnerStop() in C:\Build\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 386
>    at NServiceBus.Unicast.Transport.TransportReceiver.DisposeManaged() in C:\Build\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 434
>    at NServiceBus.Unicast.Transport.TransportReceiver.Dispose() in C:\Build\src\NServiceBus.Core\Outbox\OutboxRecordBehavior.cs:line 0
>    at Autofac.Core.Disposer.Dispose(Boolean disposing)
>    at Autofac.Util.Disposable.Dispose()
>    at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
>    at Autofac.Util.Disposab...

The service first starts, at least given the event log entry, and then starts with the errors above.

**Comment by gbiellem** [comment]
Hi @manuelsalvatori

V1.31 is the version that will fix this.  The V1.30 contained a new feature but not this patch 
I got the same error  when testing/researching this issue (see #874).  I'm just going through the release process for 1.31 right now so you should be able to download the fix shortly.

**Comment by gbiellem** [comment]
@manuelsalvatori  V1.31 has been released and can be downloaded from [here](https://github.com/Particular/ServiceControl/releases/download/1.31.0/Particular.ServiceControl-1.31.0.exe)

**Comment by manuelsalvatori** [comment]
@gbiellem thanks now it works have, good time

**Comment by gbiellem** [comment]
Thanks @manuelsalvatori -  👍
