### ISSUE TITLE
Stopped Heartbeat Event not fired when Endpoint down

### ISSUE THREAD

**Issue by danielHalan** [Particular/ServiceControl#886]
Hi, 

Seems as the events HeartbeatStopped and HeartbeatRestored are not being published until the Service is re-started.

Noticed that ServicePulse picks-up that the Endpoint has been deactivated within a minute, and updates the Web UI. But no HeartbeatStopped Event is being published to Event Handler until starting the Service, and at that point 3 events are being sent at the same time with HeartbeatRestored event sometime coming first. See log bellow

```
2017/01/04 04:37:59.875 Info HeartbeatRestored::svc:stopped:name_of_serviceA@XXXXX, RestoredAt: 1/4/2017 4:37:44 AM 
2017/01/04 04:37:59.903 Info HeartbeatRestored::svc:stopped:name_of_serviceA@XXXXX, RestoredAt: 1/4/2017 4:37:44 AM 
2017/01/04 04:37:59.903 Info HeartbeatStopped::svc:stopped:name_of_serviceA@XXXXX, DetectedAt: 1/4/2017 4:30:35 AM, LastReceivedAt: 1/4/2017 4:29:53 AM 
```

**Comment by mikeminutillo** [comment]
Thanks @danielHalan 

I suspect that this is being caused by a timing issue in the external integration event dispatch code. We have worked on a fix https://github.com/Particular/ServiceControl/pull/882 and it will be deployed soon.

**Comment by mikeminutillo** [comment]
@danielHalan the fix for this was released in [1.33](https://github.com/Particular/ServiceControl/releases/tag/1.33.0) yesterday. Can you check to see if this update resolves your issue?

**Comment by danielHalan** [comment]
@mikeminutillo it works now. 👍 that is the message is being delivered as the service stops. But I've noted a minor issue, that two messages are sent at the aprox. same time, for both HeartbeatStopped and HeartbeatRestored, for same service/host event.

**Comment by mikeminutillo** [comment]
@danielHalan there is a slight delay between when an event is detected and when the publisher wakes up to forward them. If an endpoint is restarted (i.e. Stopped and then Started again in a short timeframe) it is possible that both events get raised before either of them are published. Is this possibly what is going on?

**Comment by danielHalan** [comment]
Here is the flow, 
1. Manually Stop Service A
~10sec..
2. Receive HeartbeatStopped for Service A
3. Receive HeartbeatStopped for Service A
..
4. Manually Start Service A
~10sec..
5. Receive HeartbeatRestored for Service A
6. Receive HeartbeatRestored for Service A

**Comment by mikeminutillo** [comment]
Oh. You're getting multiple events raised. I didn't realize that.
