### ISSUE TITLE
API to allow endpoints to be deleted

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#891]
When an endpoint is added to ServiceControl (either via heartbeats or by watching the error/audit queues), it cannot currently be removed without directly removing it from the embedded RavenDB database. If a ServicePulse user wants to prevent the endpoint from appearing in the list of endpoints, the monitoring for that endpoint can be turned off but the endpoint will still be tracked by ServicePulse. Over time, these "dead" endpoints can add up. 

It should be possible to remove an endpoint from ServiceControl if the user has decommissioned it.

**Comment by dvdstelt** [comment]
I would also like this. I'm not sure how they are identified, but I currently have 9 `Billing@MyMachine` endpoints in ServicePulse. When demoing heartbeats to customers, I have no idea which one to turn off or on! :)
A customer in support case #00027249 also requested this. They are afraid removing the endpoints from RavenDb will somehow break functionality because of an unknown link. Coupling in the database is always the hardest to see! :)

**Comment by SimonCropp** [comment]
when will this be done?

**Comment by WilliamBZA** [comment]
We're in the process of a major overhaul to ServiceControl which will mean that this is not a problem anymore, but there is no ETA for when to expect this.

**Comment by TraGicCode** [comment]
@WilliamBZA I'm really hoping this new "overhaul" will bring better features and usability.  Is there a list of the changes that are going into the overhaul?

**Comment by WilliamBZA** [comment]
We're breaking it up so far into smaller releasable pieces, with each cycle resulting in a release. The release notes for each version will list the changes involved.

Do you have a list of features that you'd like us to prioritize @TraGicCode? We're focusing less on features and more on solving problems with the design of ServiceControl as we go.

**Comment by TraGicCode** [comment]
@WilliamBZA Well just off the top of my head.

- It would be nice to be able to edit headers and content of the error message when replaying.  We've had situations in which we need this for one-off issues.

- How about having some temporal storage of audit message with some searching?  In our case we have splunk but this might be something of interest for others.

- Possible call-out of "new issues" that might have started happening and not seen before to help finding production issues quicker.

That is just some.   I know these might be out of scope of servicepulse's intent but i think the first one is something that seems feasibly in scope.  I can Open github issues if that is where these need to live.

**Comment by yfesenko** [comment]
Is there any update on this issue? We are deploying endpoints in containers quite often. Each container has an auto-generated ID, so on each deployment, the list of decommissioned/inactive endpoints grows. It would be nice to clear these down

**Comment by Smoles** [comment]
I think this API for deleting Endpoints was added as part of this PR https://github.com/Particular/ServiceControl/pull/1782. I'm assuming this issue could be closed.

**Comment by mikeminutillo** [comment]
Thanks @Smoles 

It looks like you're correct. I'll close this one.
