### ISSUE TITLE
ServiceControl: control channels & adapters

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#894]
That's a discussion issue intended to organize information about SC architecture destinations. Here's a diagram that shows both ideas: adaptes and control channels:

![servicecontrol adapter 1](https://cloud.githubusercontent.com/assets/163318/22020474/c21857c8-dcb8-11e6-8bc3-bf97489e0958.png)

The control channel infrastructure sits on top of an endpoint. It has its own input queue. The audit and error messages are channeled through the control channel. The audit and/or error metadata can be potentially transmitted via a separate control messages (not shown here). The plugins (like HB, custom checks etc.) use the control channel to send their messages to SC.

The adapter/multiplexer sits in front of SC. Its purpose is to route messages to correct SC internal queues and to shield the rest of the platform from the internal structure of SC. Behind the adapter/multiplexer SC can safely be broken apart into small components (as shown here). Individual component can be scaled or be shared between multiple adapter/multiplexers. The end goal is that SC components would not share any state nor communicate via messaging. 

From this point of view, the wire-level communication compatibility between the endpoints and the SC core can be solved in two places:
 * The control channel
 * The adapter/multiplexer

It seems to me we have not enough information at this stage which solution is better and I suspect there can be pros and cons to each approach. Here are some (random) thoughts:
 * When using MSMQ, there is no strict need for the control channel. A null implementation might be a good way to make the plugins unaware of that fact.
 * Using control channel implies there is one additional queue per endpoint. I think this is a reasonable requirement
 * Control channel should require zero configuration (other than connection string)
 * When using competing consumers, should the control channel have queue per instance or a shared queue for all instances?

**Comment by SzymonPobiega** [comment]
@Particular/servicecontrol-maintainers what are your thoughts? Did I capture the essence of the challenge?

**Comment by SzymonPobiega** [comment]
@Particular/servicecontrol-maintainers ping?

**Comment by mikeminutillo** [comment]
Awesome. You've drawn the solution containing both pieces. Do we need to decide between them then or can/should we implement both?

I suspect we need to have two conversations here. One is about scaling SC and one is about Platform-Level compatability. I think both solutions will have an impact on these problems and we should decide which we are tackling first before trying to decide which of these abstractions to build first.

**Comment by mikeminutillo** [comment]
You've drawn each of the pieces on the right in separate boxes. Is it intended that those would be separate processes?

**Comment by SzymonPobiega** [comment]
@mikeminutillo I drawn separate boxes to not imply they are a single process. But I expect that they will be bundled in a single process initially (as they are currently).

Regarding which solution to implement first, as I mentioned in https://github.com/Particular/PlatformDevelopment/issues/1106, I think the adapter approach is less risky in the way it would be easier to move from adapters (should we decide it does not address the issues) to control channel than to retract from the control channel.
