### ISSUE TITLE
Mgmt util not catching "The service cannot accept control messages at this time"

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#908]
When starting and stopping instances the underlying Windows Service Controller can refuse the request with "The service cannot accept control messages at this time".  The mgmt utility is not handling this state and  instead the error is bubbling up to the unhandled exception management

**Comment by TraGicCode** [comment]
This is a really frustrating bug.  Any expectation on when this will be worked on?

**Comment by SzymonPobiega** [comment]
@TraGicCode the fix has been merged. I will be released in the next SC release.
