### ISSUE TITLE
Update Release Notes Generator

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#918]
Currently we have a specialized version of the Particular Release Notes Compiler on [a branch].

The GitTools teams have a generic and configurable version of the same tool and we should switch to using it. It's available at https://github.com/GitTools/GitReleaseManager

To implement this we need to add a yaml configuration file to our repo and update our Octopus build. 

Luckily the SI team has already done this and we can leverage their hard work. Their yaml file is available https://github.com/Particular/ServiceInsight/blob/master/GitReleaseManager.yaml

The steps to be updated in the build are 
- `Add Assets to Release V2`, 
- `Create release notes V2` and 
- `Publish release notes V2`

There are templates for each of these already up on the deployment server.

**Comment by SzymonPobiega** [comment]
Pretty sure this has been implemented already.
