### ISSUE TITLE
ServiceControl installation or Mgmt util should call out that Silverlight is required to manage  RavenDB

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#923]
## Problem

During a support call a customer called us out on the fact that the embedded Raven Management requires Silverlight and this is not  handled by our installation

## Background

The customer wanted to check the index states but because Silverlight was not installed he could not, 
His IT department locks down the server so he'd need to wade through his internal change control processes to get the change in.  In the meantime he's blocked.  This could have been prevented by either handling the Silverlight install or calling it out in the installation that this is a required component

**Comment by gbiellem** [comment]
Just to be clear I'm not advocating we include Silverlight in the installation, Since it's a browser plugin I think this should be handled by the user with their browser of choice.  What I would like though is some sort of notification that it is required.  Maybe in  the Adv Installer install? Or a one off dismissable dialog in the management UI.  

In the mean time docs have been updated to reflect the dependency

**Comment by gbiellem** [comment]
Bring forth the UI guru!  @sergioc  thoughts ☝️

**Comment by sergioc** [comment]
> What I would like though is some sort of notification that it is required.

How about adding a notification disguised ad option at the end of the SC installation:

> [ ] Download Silverlight (only required for accessing RavenDB management)

Could do the same in the PI. Otherwise it will require more work to expose sub-options for each component. But then mentioning beforehand Silverlight as required to use some part of SC can also scare...

**Comment by janovesk** [comment]
Just wanted to add that Internet Explorer is now the only current browser  that supports loading Silverlight anymore. Chrome ditched it long ago and Firefox recently dropped support.

**Comment by gbiellem** [comment]
Impeding lack of silverlight support was one of the reasons for the Raven 3 update that was attempted but didn't pan out due to perf issues.

**Comment by SzymonPobiega** [comment]
RavenDB we use no longer depends Silverlight 🎉
