### ISSUE TITLE
Integration events not working after Service Control restart

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceControl#927]
## Who's Affected
Users subscribing to Service Control [integration events](https://docs.particular.net/servicecontrol/contracts).

## Symptoms
Integration events are no longer received after restarting Service Control.

## Workaround
Restart endpoints subscribed to these integration event, so they send their subscription message again.

**Comment by janovesk** [comment]
I'll have a look @dvdstelt.

**Comment by janovesk** [comment]
I can repro with latest SC and SC integration sample :(

**Comment by janovesk** [comment]
Thinking backm, I realize I saw this in a customer support case earlier this week BTW.
