### ISSUE TITLE
ServiceControl instance upgrade stuck cleaning expired documents

### ISSUE THREAD

**Issue by harumph** [Particular/ServiceControl#941]
I was doing an upgrade of ServiceControl from 1.22.0 to 1.38.0.
The instance upgrade got stuck trying to clean expired documents for about 20 hours before I finally stopped it.

Here's the log: https://gist.github.com/harumph/d2e095aa7dc24b46cc3429a57098baba

Looking into the source code of the cleaners, eg. [EventLogItemsCleaner](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/RavenDB/Expiration/EventLogItemsCleaner.cs), it looks like they are using indexes. I am guessing these got corrupted - most issues that I've run into with ServiceControl so far were related to that.

I am thinking of removing all indexes and letting them repopulate before attempting an upgrade again.
Any other ideas what should I try?

**Comment by mikeminutillo** [comment]
@harumph have you seen any evidence that the indexes are corrupt. I worry that deleting them will just slow the overall process down. If they are corrupt, then deleting them will fix it but it means that SC must rebuild indexes before it can do anything else.

**Comment by harumph** [comment]
Thanks @mikeminutillo I don't have proof of indexes being to blame, we decided against doing an in place upgrade so I stopped looking into it.

I couldn't replicate this upgrade issue in my later testing so we've had a nasty uncertainty in the upgrade plan.
We don't really use auditing and getting errors out of ServiceControl is easy enough so we're just going to redirect traffic to a new instance and retry any failed messages on the old instance after failover.

I still have the instance that the upgrade failed on, so I could provide full logs if you're interested.

**Comment by WilliamBZA** [comment]
@harumph Those logs would be great, and if the data in the db isn't too sensitive, we'd love to take a look at it too. If you want a more private way of providing the db you can email support@particular.net and one of us will reply and we can coordinate how to get the db to us.

**Comment by mikeminutillo** [comment]
@harumph if you aren't using the audit data in ServiceControl, I would recommend turning it off. Ingesting audits puts a fair bit of pressure on SC and expands the size of the database significantly. The upgrade process you described (configure a new SC, redirect traffic to it, retry all errors) should work. The only thing you will lose is the historical retry data about failed messages (although realistically we only surface that as a number of retry attempts).

If you're happy with this upgrade process and we can't do anything to try and recreate/resolve the original error, would you be happy to close this issue?

**Comment by WilliamBZA** [comment]
@harumph thanks for the log files, I'll work through them now but I suspect @mikeminutillo's suggestion above may be the best approach - especially for an environment that has such an intentionally high volume. You could also spread the heartbeat time a bit more to reduce the volume of messages even more.

**Comment by harumph** [comment]
@mikeminutillo, @WilliamBZA Yep, thank you for your comments.

We already have heartbeats spread out and auditing turned off in production but thanks for the tips. :)
