### ISSUE TITLE
Easy way to edit servicecontrol.exe.config

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#953]
You cannot easily open `servicecontrol.exe.config` for editing. First you need to open notepad in admin mode, open a file and navigate to the folder that contains `servicecontrol.exe.config`

It would help if the ServiceControl Management utility has a way to quickly do this.

Reasons for doing this are moving folders to another disk or tweaking ravendb settings.

**Comment by fourpastmidnight** [comment]
Or use PowerShell? That's what we do when deploying ServiceControl. It's relatively easy:

```powershell
Import-Module "${env:ProgramFiles(x86)}\Particular Software\ServiceControl Management\ServiceControlMgmt.psd1" | Out-Null
$Instance = Get-ServiceControlInstances | Select-Object -First 1
$ConfigurationManager = [System.Configuration.ConfigurationManager]::OpenExeConfiguration($(Join-Path $Instance.InstallPath -ChildPath 'ServiceControl.exe'))
Write-Host "The heartbeat grace period is $($ConfigurationManager.AppSettings.Settings.Item('ServiceControl/HeartbeatGracePeriod').Value"
```

You could also try using the PowerShell XML provider:

```powershell
Import-Module "${env:ProgramFiles(x86)}\Particular Software\ServiceControl Management\ServiceControlMgmt.psd1" | Out-Null
$Instance = Get-ServiceControlInstances | Select-Object -First 1
[xml]$config = Get-Content (Join-Path $Instance.InstallPath -ChildPath 'ServiceControl.exe.config) -Encoding UTF8 -Raw
# Do stuff with $config here
```

The downside being, obviously, you have no strong-type support that you're not saving a botched config.

**Comment by ramonsmits** [comment]
Closing this in favor of https://github.com/Particular/ServiceControl/issues/955
