### ISSUE TITLE
Time to retry small groups is too long (and random)

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#961]
Feedback received from customer:

> Time to reprocess messages. If we had a collection of, say 40, messages which needed reprocessing we'd click the button to reenqueue them. Then we'd go for lunch. Sometimes we'd also go for supper and breakfast too before they actually hit the queue. I have no idea why it would take more than a couple of seconds to take a message from ravendb and insert it in SQL Server. It was very frustrating for us and our client to have to wait some impossible to guess period of time for messages to make it back into the queue. We found that when it was under heavy load the service control server would seem to lose the desire to reprocess messages. We'd have to restart the service to unstick it, risking the dreaded reindex.

I have witnessed this myself too, when a group of failed messages is retried for the first time it seems to take an incredibly long time to retry even a small number of messages. We should identify the reason for this, and either fix or surface that information to the users so that they are aware of what the system is doing at that time.

**Comment by justinSelf** [comment]
I've seen this too. On one project, we actually had the steps documented (don't remember exactly what they were) for when we needed to retry messages. They included restarting SC one or two times.

**Comment by WilliamBZA** [comment]
Github needs better reaction emojis 😞 

As much as I'd like to blame the db for this again, I can confirm that I've ruled out the database as the prime suspect. Well, for the scenario I have in mind at least. There appears to be some negotiation problem happening at the first enqueue operation, but I need more time to confirm.

**Comment by marcselis** [comment]
We just had to restart a SC that had retries for 35 messages queued for 10 days!  The restart of SC took more than 5 minutes, but after that they were finally processed...
![capture](https://cloud.githubusercontent.com/assets/3587795/26670312/792b33b0-46b1-11e7-9844-868a94ac96dd.PNG)

**Comment by WilliamBZA** [comment]
@marcselis What versions of SP/SC are you running?

**Comment by marcselis** [comment]
@WilliamBZA ServicePuls v1.9.1, ServiceControl v1.40.  SqlServerTransport.

**Comment by WilliamBZA** [comment]
Thanks @marcselis. Any chance you can email the SC and RavenDB logs through to support@particular.net so we can see if there's anything useful in them that may help with this issue?

**Comment by marcselis** [comment]
@WillamBZA I'll forward your request to our devops team...

**Comment by marcselis** [comment]
@WilliamBZA I just mailed our logfiles to support@particular.net.

**Comment by WilliamBZA** [comment]
@marcselis We have a fix!! https://github.com/Particular/ServiceControl/releases/tag/1.47.3

This should prevent the problem you're experiencing completely.

**Comment by WilliamBZA** [comment]
Closing as the retry pipeline has changed considerably and previous data around this problem likely won't be applicable anymore.
