### ISSUE TITLE
ServiceControl Manager doesn't reflect new port when it is changed

### ISSUE THREAD

**Issue by kbaley** [Particular/ServiceControl#964]
## Steps to reproduce

1. Install an SC instance
1. Edit the instance and change the port

After saving the changes, the port displayed in the manager remains as the old one. Restarting the manager will show the new (correct) port.

**Comment by adamralph** [comment]
It's not just the port. I see the same behaviour with other fields such as the name of the error queue.

It's probably worth checking through all the fields to see if it's a general problem across all of them.

**Comment by WilliamBZA** [comment]
This has been resolved, and will reflect in the next release of ServiceControl (1.4.1)

**Comment by DavidBoike** [comment]
@WilliamBZA You mean 1.41.0 (now patched up to 1.41.2) right?

**Comment by WilliamBZA** [comment]
@DavidBoike Correct, I do

**Comment by adamralph** [comment]
Or, rather, 1.41.1?
