### ISSUE TITLE
Error Forwarding Queue not created on initial instance creation

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#970]
When specifying both the error and audit forwarding queues when creating a new instance the audit forwarding queue gets created perfectly but the error forwarding queue does not.

**Comment by WilliamBZA** [comment]
Thanks @TraGicCode. Let me dig into this a bit and get back to you. Sounds like a bug though.

**Comment by TraGicCode** [comment]
FYI this was happening when using the rabbitmq transport.

**Comment by WilliamBZA** [comment]
Definitely doesn't create the queue, exactly as you said @TraGicCode.

I have a question for the @Particular/servicecontrol-maintainers relating to this: _Should_ these queues be created by ServiceControl at all? These are essentially external queues for integration points and by relying on ServiceControl to create those queues, the settings for those queues (DLQ, journalling, permissions, etc) will be based on what ServiceControl thinks is appropriate. These defaults may not be appropriate for the required integration scenario. Perhaps the creation of the audit forwarding queues should actually be removed and replaced with a check in the configuration tool to notify the user if the queues don't exist?

The documentation also refers to these queues as [externally controlled](https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior):
> The queues are not directly managed by ServiceControl and are meant as points of external integration

**Comment by mikeminutillo** [comment]
Do endpoints create the Error/Audit queues if they don't exist? We should behave the same way because we're basically usurping that function. i.e. You had an audit queue before and now we're draining it so we give you an Audit Forwarding Queue so that we act more like a wire-tap.

**Comment by SzymonPobiega** [comment]
I verified it and it works on 3.4.1
