### ISSUE TITLE
Management app doesn't populate error/audit queue names from config file

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServiceControl#976]
If you modify a ServiceControl instance and change the error queue, the Servicecontrol.exe.config will be updated correctly.

However, if you edit the same instance again, the field value will be "error" again, which means if you do nothing and click Save, the default value will be restored (incorrectly) in the config file.

Same goes for audit queue.

**Comment by WilliamBZA** [comment]
Already logged here: https://github.com/Particular/ServiceControl/issues/964

Closing this as it will be handled there. Thanks @DavidBoike
