### ISSUE TITLE
Implement first set of metrics for Launchwave

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#979]
Local issue for https://github.com/Particular/launchWave.DevOpsAdvancedMonitoring/issues/52 so that we can link PRs in waffle correctle

**Comment by Scooletz** [comment]
Is it done?

**Comment by Scooletz** [comment]
Is it done?

**Comment by WilliamBZA** [comment]
I mean, I guess. This was to track the PRs from other repos on our waffle board, but that's not really being used here.
