### ISSUE TITLE
WaitOne on ManualResetEvents can cause the shutdown to hang indefinitely

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#980]
## Who's affected

Customers having a large number of audit messages to clean up

## Symptoms

Audit message cleaning can take a really long time and is currently not implemented with cancellation tokens to indicate to the chunker and cleaner that SC wants to shut down. In combination with the ManualResetEvent usage for example in [ExpiredDocumentsCleanerBundle](https://github.com/Particular/ServiceControl/blob/d681bfe2f3611ce0c9123e5a1e7641bb122452f8/src/ServiceControl/Infrastructure/RavenDB/Expiration/ExpiredDocumentsCleanerBundle.cs#L56) it can lead to issues where the shutdown takes hours or never occurs.

This also affects the setup phase of ServiceControl. RavenDB Embeddable Document Store will automatically load the expired documents cleaner bundle and execute it even during the setup phase. In this case, it is possible that the setup phase hangs indefinitely.

![image](https://user-images.githubusercontent.com/174258/27425362-79688d4a-5738-11e7-9bd7-ca8527beec40.png)

## Things to consider

- [ ] Use ManualResetEvents with timeout on the wait operation
- [ ] Make document expiration cancellable
- [ ] Figure out how to disable the expiration bundle when SC is executed in context of the management util.

**Comment by SzymonPobiega** [comment]
@danielmarbach I'd suggest adding another item to the PoA: figure out how to disable the expiration bundle when SC is executed in context of the management util.

**Comment by danielmarbach** [comment]
@SzymonPobiega updated
