### ISSUE TITLE
No error log when invalid audit/error queue names used with RabbitMQ

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServiceControl#985]
On a support case, it was discovered that RabbitMQ is case-sensitive about queue names. SC was configured to use the default `audit` and `error` and the customer's queue names were `Audit` and `Errors`. This may have been caused by https://github.com/Particular/ServiceControl/issues/964 in an outdated SCMU overwriting the previously correct values.

The problematic thing was the log file was silent on this, and the app ran along in silent failure mode.

This was the entirety of the log file which, while the customer has updated SCMU, SC is still on 1.33 here. Is this something that has potentially been fixed since? I have not had time to verify it myself.

```
-------------------------------------------------------------
ServiceControl Version:				1.33.0.0
Selected Transport:					NServiceBus.RabbitMQTransport, NServiceBus.Transports.RabbitMQ
Audit Retention Period:				7.10:54:43.7060000
Error Retention Period:				30.00:00:00
Forwarding Error Messages:		False
Forwarding Audit Messages:		False
Database Size:							0bytes
-------------------------------------------------------------
2017-07-12 11:43:06.4000|6|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
2017-07-12 11:54:31.3649|6|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
2017-07-12 11:56:37.4926|6|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
```

**Comment by WilliamBZA** [comment]
@DavidBoike I'll dig into it and see. There were fixes to the logging in 1.41.2 which could have given a better log file, but I don't think that would resolve this issue.

**Comment by WilliamBZA** [comment]
@DavidBoike quick update: I haven't managed to get around to this yet, and it's unlikely that I will in the near future. I'm going to backlog, but leave it assigned to myself.

**Comment by SzymonPobiega** [comment]
The latest version of SC spams the logs with exceptions. I guess we need to live with this approach as there is no transport-agnostic way of checking if queue exists.

The only thing we can do is, when starting, send a dummy message to the `audit` and `error` queues and fail starting if it cannot be sent. @Particular/servicecontrol-maintainers what do you think? Is it worth the effort?

**Comment by WilliamBZA** [comment]
Don't we already do that somewhere?

**Comment by SzymonPobiega** [comment]
@WilliamBZA we have a startup task for `.log` queues e.g. `EnsureCanWriteToForwardingAddress` that sends an empty message there.

**Comment by SzymonPobiega** [comment]
So @WilliamBZA & @boblangley , can we call it `good enough` that we get the exception or do we think there is value in having the same kind of check as with `.log` queues?

**Comment by WilliamBZA** [comment]
:+1:

**Comment by boblangley** [comment]
Agreed
